Repository kubeedge/kubeedge, pull requests merged in 2019-07, with the labels that each got.

#833 run gofmt on the project
  edgemesh/pkg/common/utils.go
  edgemesh/pkg/module.go
  edgemesh/pkg/panel/fake.go
  edgemesh/pkg/registry/registry.go
  edgemesh/pkg/resolver/resolver.go
  edgemesh/pkg/resolver/resolver_chain_test.go
  edgemesh/pkg/server/dns.go
  edgemesh/pkg/server/server.go
  edgemesh/pkg/server/tcp.go
  edgemesh/pkg/server/tcp_test.go
  tests/e2e/constants/constants.go
  tests/e2e/deployment/deployment_test.go
  tests/e2e/device_crd/device_crd_test.go
  tests/e2e/edgesite/edgesite_test.go
  tests/e2e/testsuite/testsuite.go
  tests/e2e/utils/common.go
  tests/e2e/utils/config.go
  tests/e2e/utils/device.go
  tests/e2e/utils/node.go
  tests/e2e/utils/pod.go
  tests/performance/common/common.go
  tests/performance/hubtest/hubtest_test.go
  tests/performance/loadtest/loadtest_test.go
  tests/performance/nodedensity/nodedensity_suite_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#837 Remove a replicate case in a select statement
  edge/pkg/devicetwin/dtcontroller.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/XS

#838 Use switch instead of if-else
  cloud/pkg/cloudhub/servers/factory.go
Labels: approved, kind/cleanup, lgtm, size/S

#840 Improve the poor code
  edge/pkg/edgehub/controller.go
Labels: approved, kind/cleanup, lgtm, size/S

#841 Clean up code
  cloud/pkg/cloudhub/wsserver/server.go
Labels: approved, lgtm, size/L

#842 Move some var to const because they are const
  edge/pkg/edgehub/controller.go
Labels: approved, kind/cleanup, lgtm, size/S

#704 fix md/html mismatch
  docs/conf.py
  docs/getting-started/contribute.md
  docs/getting-started/getting-started.md
  docs/getting-started/support.md
  docs/guides/message_topics.md
  docs/modules/kubeedge.md
  docs/setup/setup.md
  docs/troubleshooting/troubleshooting.md
Labels: approved, kind/documentation, lgtm, size/M

#829 Add New Feature: support CRI Interface docking docker
  Gopkg.lock
  edge/conf/edge.yaml
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/remote/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/remote/docker_server.go
  vendor/k8s.io/kubernetes/pkg/kubelet/network/dns/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/network/dns/OWNERS
  vendor/k8s.io/kubernetes/pkg/kubelet/network/dns/dns.go
  vendor/k8s.io/kubernetes/pkg/util/interrupt/BUILD
  vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go
Labels: approved, kind/feature, lgtm, size/XL

#849 Avoid hard code in codebase
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/handler/quichandler.go
  cloud/pkg/cloudhub/handler/websockethandler.go
  cloud/pkg/cloudhub/servers/wsserver/server.go
Labels: approved, lgtm, size/S

#853 Add a specific method for generating cni-plugin from source code in e…
  docs/guides/edgemesh_test_env_guide.md
Labels: approved, lgtm, size/S

#848 fix WHAT string edgesite
  Makefile
Labels: approved, kind/bug, lgtm, size/XS

#551 Use Viaduct for Websocket server and client
  cloud/pkg/cloudhub/common/io/hubio.go
  cloud/pkg/cloudhub/handler/eventhandler.go
  cloud/pkg/cloudhub/handler/quichandler.go
  cloud/pkg/cloudhub/handler/websockethandler.go
  cloud/pkg/cloudhub/servers/factory.go
  cloud/pkg/cloudhub/servers/quicserver/server.go
  cloud/pkg/cloudhub/servers/wsserver/server.go
  edge/pkg/edgehub/clients/factory.go
  edge/pkg/edgehub/clients/factory_test.go
  edge/pkg/edgehub/clients/wsclient/websocket.go
  edge/pkg/edgehub/clients/wsclient/websocket_test.go
  edge/pkg/edgehub/config/config.go
  edge/pkg/edgehub/config/config_test.go
Labels: kind/bug, lgtm, size/XL

#854 Add stop channel to controller&cloudhub
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/controller/controller.go
  cloud/pkg/devicecontroller/module.go
Labels: approved, lgtm, size/M

#850 initialize feature lifecycle doc
  docs/getting-started/feature-lifecycle.md
Labels: approved, kind/documentation, lgtm, size/M

#863 Remove all the getkeep file
  docs/proposals/.gitkeep
  edge/cmd/.gitkeep
  edge/hack/.gitkeep
  edge/pkg/devicetwin/.gitkeep
  edge/pkg/edged/.gitkeep
  edge/pkg/edgehub/.gitkeep
  edge/pkg/eventbus/.gitkeep
  edge/pkg/metamanager/.gitkeep
  edgesite/cmd/.gitkeep
Labels: approved, lgtm, size/XS

#865 Fix the expired slack invite link
  README.md
  README_zh.md
Labels: approved, lgtm, size/XS

#858 initialize OWNERS file for device management
  cloud/pkg/devicecontroller/OWNERS
  edge/pkg/devicetwin/OWNERS
Labels: approved, kind/documentation, lgtm, size/S

#859 Add feature : Pass through the DNS request if the client does not access the services inside the cluster
  edge/pkg/metamanager/msg_processor.go
  edgemesh/pkg/server/dns.go
Labels: approved, lgtm, size/M

#869 Remove hard code times
  edge/pkg/edgehub/controller.go
Labels: approved, lgtm, size/XS

#876 Add dockerfile for edgesite
  .gitignore
  Makefile
  build/edgesite/Dockerfile
Labels: approved, lgtm, size/M

#873 initialize OWNERS file for application deployment modules
  cloud/pkg/controller/OWNERS
  edge/pkg/edged/OWNERS
  edge/pkg/metamanager/OWNERS
Labels: approved, kind/documentation, lgtm, size/S

#878 Small refactor
  edge/pkg/devicetwin/dtmanager/device.go
  edge/pkg/devicetwin/dtmodule/dtmodule.go
Labels: approved, lgtm, size/M

#877 Update Community meeting time
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#871 Improve contributing guide
  CONTRIBUTING.md
Labels: approved, lgtm, size/L

#836 implement docker runtime as a remote container runtime
  Gopkg.lock
  edge/conf/edge.yaml
  edge/pkg/edged/apis/runtime/cri/services.go
  edge/pkg/edged/apis/types.go
  edge/pkg/edged/cadvisor/cadvisor_linux.go
  edge/pkg/edged/containers/container_manager.go
  edge/pkg/edged/dockertools/docker_manager.go
  edge/pkg/edged/dockertools/docker_manager_test.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_status.go
  edge/test/integration/appdeployment/application_test.go
  edge/test/integration/utils/helpers/helpers.go
  edgesite/conf/edgeSite.yaml
Labels: approved, lgtm, size/XXL

#895 update the doc for cross-compilation
  docs/setup/cross-compilation.md
Labels: approved, kind/documentation, lgtm, size/XS

#879 fix travis run
  .travis.yml
Labels: approved, kind/bug, lgtm, size/XS

#893 modify the cni-plugin version , recommend using version 0.2.0
  docs/guides/edgemesh_test_env_guide.md
Labels: approved, lgtm, size/S

#885 Fix the bug #884
  edgemesh/pkg/server/dns.go
Labels: approved, lgtm, size/S

#894 Make changes to contribution guide for website docs
  docs/getting-started/contribute.md
Labels: approved, kind/documentation, lgtm, size/L

#905 Update device_controller.md
  docs/modules/cloud/device_controller.md
Labels: approved, kind/documentation, lgtm, size/XS

#902 update latest dependencies of async, chokidar and log4js
  device/modbus_mapper/src/package-lock.json
  device/modbus_mapper/src/package.json
Labels: approved, lgtm, size/XXL

#899 Remove unused fields placement/refresh-ak-sk-interval/auth-info-files-path/placement-url
  docs/modules/edge/edgehub.md
  edge/conf/edge.yaml
  edge/hack/setup_for_IEF.sh
  edge/pkg/edgehub/config/config.go
  edge/pkg/edgehub/config/config_test.go
  edge/pkg/edgehub/controller.go
  edge/pkg/edgehub/controller_test.go
  keadm/app/cmd/common/config.go
  keadm/app/cmd/common/types.go
Labels: approved, lgtm, size/L

#844 Keadm error handling improvements
  keadm/app/cmd/cloud/init.go
  keadm/app/cmd/edge/join.go
  keadm/app/cmd/util/common.go
  keadm/app/cmd/util/dockerinstaller.go
  keadm/app/cmd/util/k8sinstaller.go
  keadm/app/cmd/util/ubuntuinstaller.go
Labels: approved, kind/bug, lgtm, size/L

#912 initialize OWNERS file for KubeEdge installer
  keadm/OWNERS
  keadm/app/cmd/util/k8sinstaller.go
Labels: approved, kind/documentation, lgtm, size/S

#916 removed dockertools dependency
  Gopkg.lock
  edge/pkg/edged/dockertools/docker_manager.go
  edge/pkg/edged/dockertools/docker_manager_test.go
  edge/pkg/edged/dockertools/fake_docker_client.go
  edge/pkg/edged/dockertools/runtime_interface.go
  edge/pkg/edged/dockertools/secret.go
  edge/pkg/edged/edged.go
Labels: approved, kind/cleanup, lgtm, size/XXL

#921 update viaduct to lastest verson
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go
  vendor/github.com/kubeedge/viaduct/pkg/lane/lane.go
  vendor/github.com/kubeedge/viaduct/pkg/lane/wsnopack.go
Labels: approved, lgtm, size/M

#919 Modify the issue template to allow modifications as enhancements
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: approved, kind/documentation, lgtm, size/XS

#870 fix bug #866
  cloud/pkg/cloudhub/handler/eventhandler.go
Labels: approved, kind/bug, lgtm, size/XS

#896 bug fix: cpumanager state file not written error
  edge/pkg/edged/edged.go
Labels: approved, lgtm, size/S

#925 remove getURL func
  edge/pkg/edgehub/controller.go
  edge/pkg/edgehub/controller_test.go
Labels: approved, lgtm, size/M

#910 Removing code to update device state from edge to cloud in bluetooth mapper
  device/bluetooth_mapper/helper/helper.go
  device/bluetooth_mapper/watcher/watcher.go
Labels: approved, lgtm, size/S

#924 remove gpu codes
  Gopkg.lock
  edge/pkg/edged/containers/container_manager.go
  edge/pkg/edged/edged.go
  vendor/k8s.io/kubernetes/pkg/kubelet/gpu/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/gpu/OWNERS
  vendor/k8s.io/kubernetes/pkg/kubelet/gpu/gpu_manager_stub.go
  vendor/k8s.io/kubernetes/pkg/kubelet/gpu/nvidia/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/gpu/nvidia/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/gpu/types.go
Labels: approved, kind/cleanup, lgtm, size/XL

#929 add error message for `pleg/generic.go:121`
  edge/pkg/edged/pleg/generic.go
Labels: approved, lgtm, size/XS

#936 bugfix: deviceTwin membership msg unmarshal failed.
  edge/pkg/devicetwin/dtcontroller.go
Labels: approved, lgtm, size/S

#814 Add integration tests for device CRD validation
  cloud/Makefile
  cloud/hack/test-integration.sh
  cloud/hack/test.sh
  cloud/pkg/cloudhub/common/model/types_test.go
  cloud/test/integration/crds/validation_test.go
  cloud/test/integration/fixtures/constants.go
  cloud/test/integration/fixtures/device.go
  cloud/test/integration/fixtures/devicemodel.go
Labels: approved, kind/test, lgtm, size/XXL

#946 remove hard code
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, lgtm, size/L

#965 Fix a crash of keadm
  keadm/app/cmd/util/common.go
Labels: approved, lgtm, size/XS

#955 Fix bug introduced by #946
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, lgtm, size/XS

#935 Adding wait group for schedules created at runtime
  device/bluetooth_mapper/controller/controller.go
Labels: approved, lgtm, size/XS

#960 Fix #887: Update roadmap
  README.md
  docs/getting-started/roadmap.md
Labels: approved, kind/documentation, lgtm, size/M

#964 Update modules info in readme
  README.md
  README_zh.md
Labels: approved, lgtm, size/S

#962 Add --image-repository && --pod-network-cidr for keadm init.
  keadm/app/cmd/cloud/init.go
  keadm/app/cmd/common/constant.go
  keadm/app/cmd/common/types.go
  keadm/app/cmd/util/centosinstaller.go
  keadm/app/cmd/util/cloudinstaller.go
  keadm/app/cmd/util/ubuntuinstaller.go
Labels: approved, lgtm, size/M

#969 added reviewers in main OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#974 Fixed bug in performance test update_configmap script
  tests/performance/assets/02-edgeconfigmap.yaml
  tests/performance/scripts/update_configmap.sh
Labels: approved, lgtm, size/XS

#979 Move cloud/pkg/devicecontroller/apis to cloud/pkg/apis
  cloud/hack/update-codegen.sh
  cloud/pkg/apis/devices/v1alpha1/device_instance_types.go
  cloud/pkg/apis/devices/v1alpha1/device_model_types.go
  cloud/pkg/apis/devices/v1alpha1/doc.go
  cloud/pkg/apis/devices/v1alpha1/register.go
  cloud/pkg/apis/devices/v1alpha1/zz_generated.deepcopy.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/manager/device.go
  cloud/pkg/devicecontroller/manager/devicemodel.go
  cloud/pkg/devicecontroller/utils/crdclient.go
  cloud/test/integration/crds/validation_test.go
  cloud/test/integration/fixtures/device.go
  cloud/test/integration/fixtures/devicemodel.go
  tests/e2e/device_crd/device_crd_test.go
  tests/e2e/utils/common.go
  tests/e2e/utils/device.go
Labels: approved, kind/cleanup, lgtm, size/S

#968 Fix items in edge conf
  edge/conf/edge.yaml
  tests/performance/assets/02-edgeconfigmap.yaml
Labels: approved, kind/test, lgtm, size/S

#972 Enable devicecontroller in 05-configmap.yaml
  build/cloud/05-configmap.yaml
Labels: approved, lgtm, size/XS

#966 Rename device dir which place mapper to mappers
  Makefile
  mappers/bluetooth_mapper/Dockerfile
  mappers/bluetooth_mapper/Makefile
  mappers/bluetooth_mapper/README.md
  mappers/bluetooth_mapper/action_manager/action_manager.go
  mappers/bluetooth_mapper/configuration/config.go
  mappers/bluetooth_mapper/configuration/config.yaml
  mappers/bluetooth_mapper/configuration/config_map_types.go
  mappers/bluetooth_mapper/controller/controller.go
  mappers/bluetooth_mapper/data_converter/data_converter.go
  mappers/bluetooth_mapper/deployment.yaml
  mappers/bluetooth_mapper/helper/helper.go
  mappers/bluetooth_mapper/main.go
  mappers/bluetooth_mapper/scheduler/scheduler.go
  mappers/bluetooth_mapper/watcher/watcher.go
  mappers/modbus_mapper/Dockerfile
  mappers/modbus_mapper/Makefile
  mappers/modbus_mapper/README.md
  mappers/modbus_mapper/conf/conf.json
  mappers/modbus_mapper/deployment.yaml
  mappers/modbus_mapper/dpl/deviceProfile.json
  mappers/modbus_mapper/sample/sample_server.js
  mappers/modbus_mapper/scripts/start_modbusmapper.sh
  mappers/modbus_mapper/src/common.js
  mappers/modbus_mapper/src/constant.js
  mappers/modbus_mapper/src/devicetwin.js
  mappers/modbus_mapper/src/index.js
  mappers/modbus_mapper/src/modbus.js
  mappers/modbus_mapper/src/package-lock.json
  mappers/modbus_mapper/src/package.json
  mappers/modbus_mapper/src/watchfile.js
Labels: approved, lgtm, size/M

#983 clean useless log
  cloud/pkg/controller/controller.go
  cloud/pkg/controller/controller/downstream.go
  cloud/pkg/controller/controller/upstream.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/module.go
Labels: approved, kind/cleanup, lgtm, size/S

#982 change go version from go 1.11 to go 1.12
  docs/setup/setup.md
Labels: approved, kind/documentation, lgtm, size/XS

#985 Add the access role to device/devicemodel
  build/cloud/03-clusterrole.yaml
Labels: approved, lgtm, size/S

#977 K8S: Fix edgecontroller ClusterRole definition
  build/cloud/03-clusterrole.yaml
  build/cloud/07-deployment.yaml
Labels: approved, kind/bug, lgtm, size/XS

#952 Travis stages
  .travis.yml
Labels: approved, kind/feature, kind/test, lgtm, size/M
