Repository kubeedge/kubeedge, pull requests merged in 2019-06, with the labels that each got.

#635 fix build under macOS
  edge/Makefile
  edge/pkg/edged/containers/container_manager.go
Labels: approved, kind/bug, lgtm

#632 docs:[Fix:#608]: Open ports to cloud component for edge nodes in the …
  keadm/README.md
Labels: approved, kind/documentation, lgtm

#629 Edgesite code refactored - removed duplicated code
  cloud/pkg/controller/config/kube.go
  cloud/pkg/controller/constants/service.go
  cloud/pkg/controller/controller/downstream.go
  cloud/pkg/controller/controller/upstream.go
  cloud/pkg/controller/manager/pod.go
  cloud/pkg/controller/messagelayer/context.go
  cloud/pkg/controller/messagelayer/util.go
  edgesite/cmd/edgesite.go
  edgesite/conf/edgeSite.yaml
  edgesite/pkg/controller/config/buffer.go
  edgesite/pkg/controller/config/context.go
  edgesite/pkg/controller/config/kube.go
  edgesite/pkg/controller/config/load.go
  edgesite/pkg/controller/config/messagelayer.go
  edgesite/pkg/controller/constants/service.go
  edgesite/pkg/controller/controller.go
  edgesite/pkg/controller/controller/downstream.go
  edgesite/pkg/controller/controller/upstream.go
  edgesite/pkg/controller/manager/common.go
  edgesite/pkg/controller/manager/configmap.go
  edgesite/pkg/controller/manager/location.go
  edgesite/pkg/controller/manager/pod.go
  edgesite/pkg/controller/manager/secret.go
  edgesite/pkg/controller/messagelayer/context.go
  edgesite/pkg/controller/messagelayer/layer.go
  edgesite/pkg/controller/messagelayer/util.go
  edgesite/pkg/controller/types/nvidia.go
  edgesite/pkg/controller/utils/kubeclient.go
  edgesite/pkg/controller/utils/kubeconfig.go
Labels: kind/cleanup, lgtm

#621 Update crd design with validation
  docs/proposals/device-crd.md
Labels: approved, kind/design, lgtm

#649 Added initial OWNERS file
  OWNERS
Labels: approved, kind/documentation, lgtm, size/XS

#641 Readme.md for kubeedge env setup using release package issue #495
  README.md
  docs/getting-started/release_package.md
Labels: approved, kind/documentation, lgtm

#658 adding lint checking in keadm
  .travis.yml
  Makefile
  keadm/Makefile
Labels: approved, kind/test, lgtm, size/S

#659 move code only used by cloud to cloud project
  cloud/pkg/controller/config/kube.go
  cloud/pkg/controller/config/types.go
  common/types/types.go
Labels: approved, kind/cleanup, size/M

#647 set projectid e632aba927ea4ac2b575ec1603d56f10 as constant
  edge/pkg/edgehub/config/config_test.go
  keadm/app/cmd/common/config.go
  keadm/app/cmd/common/constant.go
  keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, size/M

#689 Cosmetics improvements in docs
  docs/modules/cloud/controller.md
  docs/modules/edge/edged.md
  docs/modules/edge/metamanager.md
  docs/modules/kubeedge.md
  docs/proposals/EdgeSite.md
  docs/proposals/quic-design.md
Labels: needs-ok-to-test, size/M

#603 initialize CHANGELOG.md
  CHANGELOG.md
Labels: approved, kind/documentation, lgtm, size/L

#684 Added conversion operations for read action of action manager
  device/bluetooth_mapper/controller/controller.go
Labels: approved, lgtm

#674 Support to watch on service and endpoints and send to edge for EdgeMesh Cloud Side Impl
  cloud/pkg/controller/config/buffer.go
  cloud/pkg/controller/controller/downstream.go
  cloud/pkg/controller/manager/endpoint.go
  cloud/pkg/controller/manager/location.go
  cloud/pkg/controller/manager/service.go
  common/constants/default.go
Labels: approved, kind/feature, lgtm, size/L

#669 Issue #631: Add validation of required fields for device model and device instance
  build/crds/devices/devices_v1alpha1_device.yaml
  build/crds/devices/devices_v1alpha1_devicemodel.yaml
Labels: approved, lgtm

#697 fix build change with workaround
  .travis.yml
Labels: approved, kind/test, lgtm, size/XS

#682 Delete redundant status field in CRD
  build/crds/devices/devices_v1alpha1_device.yaml
  build/crds/devices/devices_v1alpha1_devicemodel.yaml
Labels: approved, kind/cleanup, ok-to-test, size/S

#680 Renaming KubeEdge installer name to keadm
  docs/proposals/keadm-scope.md
  keadm/Makefile
  keadm/README.md
  keadm/app/cmd/cloud/init.go
  keadm/app/cmd/cmd.go
  keadm/app/cmd/edge/join.go
  keadm/app/cmd/reset.go
  keadm/app/cmd/util/edgeconfig.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#706 add dep check ci test
  .travis.yml
  Gopkg.lock
  Makefile
Labels: approved, kind/feature, lgtm, size/S

#644 added edge node role label while running installer
  keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, kind/bug, lgtm

#707 operator kubeconfig error
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, kind/cleanup, lgtm, size/XS

#701 Make device/bluetooth_mapper
  .travis.yml
  Makefile
  device/bluetooth_mapper/Makefile
  device/bluetooth_mapper/configuration/config.go
  device/bluetooth_mapper/configuration/config_map_types.go
  device/bluetooth_mapper/controller/controller.go
  device/bluetooth_mapper/data_converter/data_converter.go
  device/bluetooth_mapper/helper/helper.go
  device/bluetooth_mapper/main.go
  device/bluetooth_mapper/scheduler/scheduler.go
  device/bluetooth_mapper/watcher/watcher.go
Labels: approved, kind/test, lgtm, size/L

#667 expected value twins
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, lgtm, size/M

#712 Retaining metadata type value given by user for device
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, lgtm, size/S

#653 removing race condition in dtcontext
  edge/pkg/devicetwin/dtcontext/dtcontext.go
  edge/pkg/devicetwin/dtcontext/dtcontext_test.go
  edge/pkg/devicetwin/dtmanager/membership_test.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
Labels: approved, lgtm

#699 xeadm improvements including bionic support
  keadm/app/cmd/cloud/init.go
  keadm/app/cmd/cmd.go
  keadm/app/cmd/util/ubuntuinstaller.go
Labels: kind/bug, lgtm, needs-ok-to-test, size/M

#702 added support in metaManager for services and endpoints CRUD and query support in controller
  cloud/pkg/controller/config/buffer.go
  cloud/pkg/controller/config/load.go
  cloud/pkg/controller/controller/downstream.go
  cloud/pkg/controller/controller/upstream.go
  cloud/pkg/controller/manager/location.go
  common/constants/default.go
  edge/pkg/common/modules/names.go
  edge/pkg/metamanager/msg_processor.go
  edge/pkg/metamanager/msg_processor_test.go
Labels: approved, kind/feature, lgtm, size/XL

#654 CRI Support
  Gopkg.lock
  edge/conf/edge.yaml
  edge/pkg/edged/clcm/clcm.go
  edge/pkg/edged/clcm/clcm_policy_none.go
  edge/pkg/edged/clcm/internal_life_cycle.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_getters.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/edged_status.go
  edge/pkg/edged/pleg/generic.go
  edgesite/conf/edgeSite.yaml
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/OWNERS
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/doc.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/utils.go
Labels: approved, kind/feature, lgtm, size/XXL

#723 Added User Guide for device CRD
  docs/guides/device_crd_guide.md
Labels: approved, lgtm, size/M

#730 Updated documentation of Bluetooth Mapper
  Makefile
  device/bluetooth_mapper/README.md
Labels: approved, lgtm, size/XS

#720 Add multicontainer start(but can not support pause container yet)
  edge/pkg/edged/apis/runtime/cri/services.go
  edge/pkg/edged/apis/types.go
  edge/pkg/edged/containers/container_manager.go
  edge/pkg/edged/containers/reason_cache.go
  edge/pkg/edged/dockertools/docker_manager.go
  edge/pkg/edged/dockertools/docker_manager_test.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/pleg/generic.go
  edge/pkg/edged/rainerruntime/runtime.go
Labels: approved, kind/feature, lgtm, size/L

#732 Add tools catalog, submits script tools for edgemesh traffic hijackin…
  edgemesh/tools/initContainer/createImg.sh
  edgemesh/tools/initContainer/deb/Dockerfile
  edgemesh/tools/initContainer/rpm/Dockerfile
  edgemesh/tools/initContainer/script/edgemesh-iptables.sh
Labels: approved, lgtm, size/L

#735 Handled case in bluetooth mapper with no converter information while reading
  device/bluetooth_mapper/configuration/config.go
Labels: approved, kind/bug, lgtm, size/XS

#736 Add new feature: Dns cheat
  edgemesh/cmd/edgemesh.go
  edgemesh/pkg/server/dns.go
Labels: approved, lgtm, size/L

#695 add modbus mapper
  device/modbus_mapper/Dockerfile
  device/modbus_mapper/Makefile
  device/modbus_mapper/README.md
  device/modbus_mapper/conf/conf.json
  device/modbus_mapper/deployment.yaml
  device/modbus_mapper/dpl/deviceProfile.json
  device/modbus_mapper/sample/sample_server.js
  device/modbus_mapper/scripts/start_modbusmapper.sh
  device/modbus_mapper/src/common.js
  device/modbus_mapper/src/constant.js
  device/modbus_mapper/src/devicetwin.js
  device/modbus_mapper/src/index.js
  device/modbus_mapper/src/modbus.js
  device/modbus_mapper/src/package-lock.json
  device/modbus_mapper/src/package.json
  device/modbus_mapper/src/watchfile.js
Labels: approved, lgtm, size/XXL

#741 Revert "Add multicontainer start(but can not support pause container yet)"
  edge/pkg/edged/apis/runtime/cri/services.go
  edge/pkg/edged/apis/types.go
  edge/pkg/edged/containers/container_manager.go
  edge/pkg/edged/containers/reason_cache.go
  edge/pkg/edged/dockertools/docker_manager.go
  edge/pkg/edged/dockertools/docker_manager_test.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/pleg/generic.go
  edge/pkg/edged/rainerruntime/runtime.go
Labels: approved, lgtm, size/L

#749 Add new feature: hijacking and dns cheat
  edge/conf/modules.yaml
  edge/test/integration/scripts/execute.sh
  edgemesh/pkg/server/dns.go
  edgemesh/pkg/server/server.go
  edgemesh/tools/initContainer/createImg.sh
  edgemesh/tools/initContainer/deb/Dockerfile
  edgemesh/tools/initContainer/rpm/Dockerfile
  edgemesh/tools/initContainer/script/edgemesh-iptables.sh
Labels: approved, lgtm, size/XL

#751 edgemesh listen on all ip default and fix go-chassis panic bug
  edgemesh/pkg/server/server.go
  edgemesh/pkg/server/tcp.go
Labels: approved, lgtm, size/XS

#752 edgemesh listen on all ip default and fix go-chassis panic bug
  edgemesh/pkg/server/server.go
  edgemesh/pkg/server/tcp.go
Labels: approved, lgtm, size/XS

#737 Edgesite documentation
  docs/images/edgesite/EdgeSite_Setup.PNG
  docs/images/edgesite/EdgeSite_arch.PNG
  docs/proposals/EdgeSite.md
  edgesite/README.md
Labels: approved, kind/documentation, lgtm, size/L

#745 Moving keadm installer readme.md to Docs folder
  README.md
  docs/setup/installer_setup.md
Labels: approved, kind/cleanup, lgtm, size/XS

#744 Moving mappers README to docs folder
  docs/mappers/bluetooth_mapper.md
  docs/mappers/modbus_mapper.md
Labels: approved, lgtm, size/XS

#755 Fix issue #754: Pods created using CRI on deletion remain in terminat…
  edge/pkg/edged/pleg/generic.go
Labels: approved, kind/bug, lgtm, size/M

#759 fix bug: replace value in [key, value] by expected[1]
  device/modbus_mapper/src/index.js
Labels: approved, lgtm, size/XS

#757 Add Changelog for 1.0
  CHANGELOG-1.0.md
Labels: approved, kind/documentation, lgtm, size/M

#747 Document for Cri in docs/edged
  docs/images/edged/edged-cri.png
  docs/modules/edge/edged.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/M

#746 Adding CRI documentation in Docs/release_package.md folder
  docs/getting-started/release_package.md
Labels: approved, lgtm, size/M

#761 update edge_core version to reflect the vendor k8s and kubeedge version
  edge/conf/edge.yaml
Labels: approved, kind/bug, lgtm, size/XS

#763 Automated cherry pick of #757: Add Changelog for 1.0
  CHANGELOG-1.0.md
Labels: approved, lgtm, size/M

#743 Added documentation for device controller
  docs/modules/cloud/device_controller.md
Labels: approved, lgtm, size/M

#764 Automated cherry pick of #759: fix bug: replace value in [key, value] by expected[1]
  device/modbus_mapper/src/index.js
Labels: approved, lgtm, size/XS

#765 Automated cherry pick of #747: Document for cri in docs/edged
  docs/images/edged/edged-cri.png
  docs/modules/edge/edged.md
Labels: approved, lgtm, size/M

#766 Automated cherry pick of #746: Adding CRI documentation in Docs/release_package.md
  docs/getting-started/release_package.md
Labels: approved, lgtm, size/M

#762 Automated cherry pick of #755: Fix issue #754: Pods created using CRI on deletion remain in terminating status
  edge/pkg/edged/pleg/generic.go
Labels: approved, lgtm, size/M

#767 Automated cherry pick of #761: update edge_core version to reflect the vendor k8s and kubeedge version
  edge/conf/edge.yaml
Labels: approved, lgtm, size/XS

#768 Fix issue #754
  edge/pkg/edged/pleg/generic.go
Labels: approved, lgtm, size/M

#758 add edgemesh end to end test guide
  docs/guides/edgemesh_test_env_guide.md
  docs/images/edgemesh/endtoend-test-flow.jpg
  docs/images/edgemesh/model.jpg
Labels: approved, lgtm, size/L

#771 Automated cherry pick of #737: Edgesite documentation
  docs/images/edgesite/EdgeSite_Setup.PNG
  docs/images/edgesite/EdgeSite_arch.PNG
  docs/proposals/EdgeSite.md
  edgesite/README.md
Labels: approved, lgtm, size/L

#772 Automated cherry pick of #745: moving keadm installer readme.md to Docs folder
  README.md
  docs/setup/installer_setup.md
Labels: approved, lgtm, size/XS

#773 Automated cherry pick of #758: add edgemesh end to end test guide
  docs/guides/edgemesh_test_env_guide.md
  docs/images/edgemesh/endtoend-test-flow.jpg
  docs/images/edgemesh/model.jpg
Labels: approved, lgtm, size/L

#774 Automated cherry pick of #743: Added documentation for device controller
  docs/modules/cloud/device_controller.md
Labels: approved, lgtm, size/M

#775 Automated cherry pick of #744: Moving mappers README to docs folder
  docs/mappers/bluetooth_mapper.md
  docs/mappers/modbus_mapper.md
Labels: approved, lgtm, size/XS

#760 Changing Keadm Default version to 0.3.0
  keadm/app/cmd/common/constant.go
Labels: approved, kind/cleanup, lgtm, size/XS

#776 Automated cherry pick of #768: Solved Pods created using CRI on deletion remain in
  edge/pkg/edged/pleg/generic.go
Labels: approved, lgtm, size/M

#777 Automated cherry pick of #760: Changing Keadm Default version to 0.3.0
  keadm/app/cmd/common/constant.go
Labels: approved, lgtm, size/XS

#778 Adding hyperlinks in README to the docs and moving edgesite documentation to docs
  device/bluetooth_mapper/README.md
  device/modbus_mapper/README.md
  docs/modules/edgesite.md
  edgesite/README.md
Labels: approved, lgtm, size/L

#780 Automated cherry pick of #778: Adding hyperlinks in README to the docs in docs folder and
  device/bluetooth_mapper/README.md
  device/modbus_mapper/README.md
  docs/modules/edgesite.md
  edgesite/README.md
Labels: approved, lgtm, size/L

#781 Update CHANGELOG-1.0.md
  CHANGELOG-1.0.md
Labels: approved, lgtm, size/XS

#782 Automated cherry pick of #781: Update CHANGELOG-1.0.md
  CHANGELOG-1.0.md
Labels: approved, lgtm, size/XS

#783 Update documentation for docs.kubeedge.io
  docs/index.rst
  docs/modules/cloud/cloudhub.md
  docs/modules/edge/edgehub.md
  docs/modules/edgesite.md
  docs/setup/installer_setup.md
  keadm/README.md
Labels: approved, lgtm, size/M

#785 Add user guide：edgemesh_test_env_guide.md
  docs/guides/edgemesh_test_env_guide.md
  docs/images/edgemesh/edgemesh-test-env-example.png
Labels: approved, lgtm, size/M

#786 Automated cherry pick of #783: Update documentation for docs.kubeedge.io
  docs/index.rst
  docs/modules/cloud/cloudhub.md
  docs/modules/edge/edgehub.md
  docs/modules/edgesite.md
  docs/setup/installer_setup.md
  keadm/README.md
Labels: approved, lgtm, size/M

#787 Automated cherry pick of #785: Add user guide：edgemesh_test_env_guide.md
  docs/guides/edgemesh_test_env_guide.md
  docs/images/edgemesh/edgemesh-test-env-example.png
Labels: approved, lgtm, size/M

#714 minor fixes message build / parsing
  cloud/pkg/devicecontroller/apis/devices/v1alpha1/device_instance_types.go
  edge/pkg/devicetwin/dttype/types.go
  edge/pkg/devicetwin/dttype/types_helper.go
Labels: approved, kind/bug, lgtm, size/S

#788 Fixed image link for edgesite doc to format supported by docs.kubeedge.io
  docs/modules/edgesite.md
Labels: approved, lgtm, size/XS

#790 Automated cherry pick of #788: Changing image link for edgesite doc to format supported by
  docs/modules/edgesite.md
Labels: approved, lgtm, size/XS

#791 device controller: Fix broken image links
  docs/modules/cloud/device_controller.md
Labels: approved, kind/documentation, lgtm, size/S

#789 Automated cherry pick of #714: fix minor problems with message parsing / building
  cloud/pkg/devicecontroller/apis/devices/v1alpha1/device_instance_types.go
  edge/pkg/devicetwin/dttype/types.go
  edge/pkg/devicetwin/dttype/types_helper.go
Labels: approved, lgtm, size/S

#792 Automated cherry pick of #791: device controller: Fix broken image links
  docs/modules/cloud/device_controller.md
Labels: approved, lgtm, size/S

#793 Correcting minor mistakes in docs for edgemesh and release_package.md
  docs/getting-started/release_package.md
  docs/guides/edgemesh_test_env_guide.md
Labels: approved, lgtm, size/S

#794 Automated cherry pick of #793: Correcting minor mistakes in docs for edgemesh and
  docs/getting-started/release_package.md
  docs/guides/edgemesh_test_env_guide.md
Labels: approved, lgtm, size/S

#795 changes made to Intsaller to support CRI
  keadm/app/cmd/common/config.go
  keadm/app/cmd/common/constant.go
  keadm/app/cmd/common/types.go
  keadm/app/cmd/edge/join.go
  keadm/app/cmd/util/common.go
  keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, lgtm, size/M

#796 Automated cherry pick of #795: changes made to Intsaller to support CRI
  keadm/app/cmd/common/config.go
  keadm/app/cmd/common/constant.go
  keadm/app/cmd/common/types.go
  keadm/app/cmd/edge/join.go
  keadm/app/cmd/util/common.go
  keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, lgtm, size/M

#797 Adding edgemesh in modules to support keadm installer
  keadm/app/cmd/common/config.go
  keadm/app/cmd/common/constant.go
  keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, lgtm, size/XS

#800 Modify guide edgemesh_test_env_guide.md
  docs/guides/edgemesh_test_env_guide.md
Labels: size/M

#799 Automated cherry pick of #797: Adding edgemesh in modules to support keadm installer
  keadm/app/cmd/common/config.go
  keadm/app/cmd/common/constant.go
  keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, lgtm, size/XS

#801 Automated cherry pick of #800: Modify guide edgemesh_test_env_guide.md
  docs/guides/edgemesh_test_env_guide.md
Labels: size/M

#717 adding unit tests cloud
  .travis.yml
  Makefile
  cloud/Makefile
Labels: approved, kind/test, lgtm, size/S

#813 Update CHANGELOG to include 1.0 release details
  CHANGELOG-1.0.md
Labels: approved, kind/documentation, lgtm, size/M

#812 updating error message with keadm
  Makefile
Labels: approved, kind/bug, lgtm, size/XS

#802 add GetLatency func
  tests/performance/assets/02-edgeconfigmap.yaml
  tests/performance/common/common.go
  tests/performance/hubtest/hubtest_suite_test.go
  tests/performance/scripts/runperf.sh
Labels: approved, kind/test, lgtm, size/M

#809 Refactor bluetooth mapper to discover characteristics only once
  device/bluetooth_mapper/action_manager/action_manager.go
  device/bluetooth_mapper/watcher/watcher.go
Labels: approved, lgtm, size/M

#821 update: update release_package.md
  docs/getting-started/release_package.md
Labels: approved, kind/documentation, lgtm, size/XS

#687 Adding visio file for KubeEdge architecture diagram
  docs/images/KubeEdge_arch.vsdx
Labels: approved, lgtm

#818 Remove ServiceComb dependency
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/ServiceComb/paas-lager/.gitignore
  vendor/github.com/ServiceComb/paas-lager/.travis.yml
  vendor/github.com/ServiceComb/paas-lager/LICENSE
  vendor/github.com/ServiceComb/paas-lager/NOTICE
  vendor/github.com/ServiceComb/paas-lager/README.md
  vendor/github.com/ServiceComb/paas-lager/lager.go
  vendor/github.com/ServiceComb/paas-lager/third_party/forked/cloudfoundry/lager/LICENSE
  vendor/github.com/ServiceComb/paas-lager/third_party/forked/cloudfoundry/lager/NOTICE
  vendor/github.com/go-chassis/paas-lager/rotate/logrotate.go
  vendor/github.com/kubeedge/beehive/pkg/common/log/logger.go
Labels: approved, lgtm, size/XL

#820 update edgemesh end to end test guide
  docs/guides/edgemesh_test_env_guide.md
  docs/images/edgemesh/model.jpg
Labels: approved, kind/documentation, lgtm, size/M

#828 Update install doc to main repo
  keadm/README.md
Labels: approved, lgtm, size/XS

#831 Small refactor to cloud part
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/cloudhub.go
Labels: approved, lgtm, size/M

#834 Improve a warn message
  cloud/pkg/controller/controller.go
Labels: approved, kind/cleanup, lgtm, size/XS

#835 Return nil instead the err as it must be nil
  cloud/pkg/controller/utils/kubeconfig.go
Labels: approved, kind/cleanup, lgtm, size/XS
