Repository kubeedge/kubeedge, pull requests merged in 2019-09, with the labels that each got.

#1066 clarify priority between master flag and kubeconfig
  cloud/conf/controller.yaml
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
  docs/setup/setup.md
  tests/e2e/scripts/setup.sh
Labels: approved, kind/documentation, lgtm, size/S

#1084 update email address
  MAINTAINERS
Labels: approved, kind/documentation, lgtm, size/XS

#1087 dynamic create node version info
  common/constants/default.go
  edge/conf/edge.yaml
  edge/pkg/edged/edged.go
  keadm/app/cmd/common/config.go
  keadm/app/cmd/common/types.go
  keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, kind/feature, lgtm, size/S

#1090 Separate cloudcore&admission in makefile
  Makefile
Labels: approved, lgtm, size/S

#1085 Add local up kubeedge script
  .gitignore
  Makefile
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
Labels: approved, lgtm, size/L

#1047 add in-tree csi plugin implementations
  edge/pkg/edged/edged.go
  edge/pkg/edged/volume/csi/csi_attacher.go
  edge/pkg/edged/volume/csi/csi_client.go
  edge/pkg/edged/volume/csi/csi_controller.go
  edge/pkg/edged/volume/csi/csi_drivers_store.go
  edge/pkg/edged/volume/csi/csi_mounter.go
  edge/pkg/edged/volume/csi/csi_plugin.go
  edge/pkg/edged/volume/csi/csi_util.go
  edge/pkg/edged/volume/csi/nodeinfomanager/nodeinfomanager.go
  go.mod
  vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
  vendor/github.com/golang/protobuf/ptypes/struct/struct.pb.go
  vendor/github.com/golang/protobuf/ptypes/struct/struct.proto
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XXL

#1091 Add volume downwardAPI and projected
  edge/pkg/edged/edged.go
  vendor/k8s.io/kubernetes/pkg/volume/downwardapi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/downwardapi/OWNERS
  vendor/k8s.io/kubernetes/pkg/volume/downwardapi/downwardapi.go
  vendor/k8s.io/kubernetes/pkg/volume/projected/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/projected/projected.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XL

#1094 Create the manifest for namespace
  build/admission/namespace.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#1100 fix bug #1097
  edgemesh/pkg/proxy/proxy.go
Labels: approved, kind/bug, lgtm, size/S

#1098 change setup.md document to Improve the installation process
  docs/setup/setup.md
Labels: approved, kind/documentation, lgtm, size/L

#1104 support env in edge pods
  edge/pkg/edged/edged_pods.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/L

#1099 Device value not updated
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/devicecontroller/constants/service.go
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/bug, lgtm, size/S

#1103 using upstream volumesattached
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/feature, lgtm, size/XS

#1109 fix unistall_kubeedge undifined error
  hack/local-up-kubeedge.sh
Labels: approved, kind/bug, lgtm, size/XS

#1110 add comment about edged.podsandbox-image
  docs/setup/setup.md
  edge/conf/edge.yaml
Labels: approved, kind/documentation, lgtm, size/S

#1112 Fix panic: concurrent write to websocket
  edge/pkg/edgehub/controller.go
Labels: approved, lgtm, size/XS

#1111 fix local up failure: ca and certs not generated
  hack/local-up-kubeedge.sh
Labels: approved, kind/bug, lgtm, size/XS

#1059 add csi driver from kubeedge
  Makefile
  build/csidriver/Dockerfile
  build/csisamples/hostpath/deploy/csicontroller.yaml
  build/csisamples/hostpath/deploy/csinode.yaml
  build/csisamples/hostpath/example/app.yaml
  build/csisamples/hostpath/example/pvc.yaml
  build/csisamples/hostpath/example/sc.yaml
  cloud/cmd/csidriver/app/options/options.go
  cloud/cmd/csidriver/app/server.go
  cloud/cmd/csidriver/csidriver.go
  cloud/pkg/csidriver/controllerserver.go
  cloud/pkg/csidriver/identityserver.go
  cloud/pkg/csidriver/server.go
  cloud/pkg/csidriver/uds.go
  cloud/pkg/csidriver/utils.go
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/descriptor/descriptor.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/pborman/uuid/.travis.yml
  vendor/github.com/pborman/uuid/CONTRIBUTING.md
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/README.md
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/go.mod
  vendor/github.com/pborman/uuid/go.sum
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XXL

#933 proposal for admission webhook
  docs/proposals/web-hook.md
Labels: approved, kind/design, kind/documentation, kind/feature, lgtm, size/L

#1116 Add CHANGELOG-1.1
  CHANGELOG-1.1.md
Labels: kind/documentation, size/M

#1123 delete useless PubMQTTMsg function
  edge/pkg/eventbus/mqtt/client.go
Labels: approved, kind/cleanup, lgtm, size/S

#1129 Fix CHANGELOG for v1.1
  CHANGELOG-1.1.md
Labels: approved, size/XS

#1130 add CHANGELOG for v1.1
  CHANGELOG-1.1.md
Labels: size/M

#1135 bluetooth_mapper: use strings.EqualFold to compare string
  mappers/bluetooth_mapper/action_manager/action_manager.go
  mappers/bluetooth_mapper/configuration/config.go
  mappers/bluetooth_mapper/controller/controller.go
  mappers/bluetooth_mapper/scheduler/scheduler.go
  mappers/bluetooth_mapper/watcher/watcher.go
Labels: approved, kind/cleanup, lgtm, size/S

#1128 change cd ~/cmd/config -> cd ~/cmd/conf
  docs/setup/setup.md
Labels: approved, kind/documentation, size/XS

#1137 Update ubuntuinstaller.go
  keadm/app/cmd/util/ubuntuinstaller.go
Labels: approved, lgtm, size/XS

#1089 change cloudcore loginfo level
  cloud/pkg/edgecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: kind/feature, size/M

#616 add csi proposal
  docs/images/csi/csi-architecture.png
  docs/images/csi/csi-attach-volume.png
  docs/images/csi/csi-create-volume.png
  docs/images/csi/csi-delete-volume.png
  docs/images/csi/csi-detach-volume.png
  docs/images/csi/csi-mount-volume.png
  docs/images/csi/csi-umount-volume.png
  docs/proposals/csi.md
Labels: kind/design, lgtm, size/XL

#1146 add devicemodel update valid check
  cloud/pkg/admissioncontroller/admit_devicemodel.go
Labels: lgtm

#1148 cleanup: remove or simplification code pieces
  cloud/pkg/edgecontroller/controller/downstream.go
  edge/pkg/devicetwin/dtcontext/dtcontext.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
  edge/pkg/devicetwin/dttype/types.go
  edge/pkg/edged/util/source_ready.go
  edgemesh/pkg/proxy/proxy.go
  edgemesh/pkg/server/dns.go
Labels: approved, lgtm, size/M

#1155 delete useless version config for edgeSite
  edgesite/conf/edgeSite.yaml
Labels: approved, kind/documentation, lgtm, size/XS

#1163 change fb4ebb70-2783-42b8-b3ef-63e2fd6d242e to edge-node
  build/csisamples/hostpath/deploy/csicontroller.yaml
  build/node.json
  docs/getting-started/release_package.md
  docs/getting-started/usage.md
  docs/modules/edgesite.md
  docs/proposals/csi.md
  docs/proposals/quic-design.md
  docs/setup/setup.md
  edge/conf/edge.yaml
  edge/pkg/edgehub/config/config_test.go
  edge/test/README.md
  edge/test/integration/scripts/fast_test
  edgesite/conf/edgeSite.yaml
  keadm/app/cmd/common/config.go
Labels: lgtm, size/M

#1156 add scripts for syncing standalone subprojects code into tree
  hack/sync-subproject-code.sh
Labels: approved, kind/cleanup, lgtm, size/L
