Repository kubeedge/kubeedge, pull requests merged in 2019-02, with the labels that each got.

#139 Update README
  README.md
  docs/guides/try_kubeedge_with_ief.md
Labels: kind/documentation

#134 docs: Added documentation for device twin module
  docs/modules/devicetwin.md
Labels: kind/documentation

#132 edged integration test support
  Makefile
  test/integration/appdeployment/application_suite_test.go
  test/integration/appdeployment/application_test.go
  test/integration/device/device_suite_test.go
  test/integration/device/device_test.go
  test/integration/scripts/compile.sh
  test/integration/scripts/execute.sh
  test/integration/scripts/fast_test
  test/integration/utils/edge/config.go
  test/integration/utils/helpers/helpers.go
  test/test.go
Labels: kind/test

#140 Remove IEF-related information in ReadME.md
  README.md
Labels: kind/documentation

#146 edged: added correct return for configmaps
  pkg/edged/volume_host.go
Labels: kind/bug

#138 DeviceTwin:Adding error handling in dtcontoller.go
  pkg/devicetwin/dtcontroller.go
  pkg/devicetwin/dtcontroller_test.go
Labels: kind/bug

#148 kubeedge: moved mocks inside t.Run
  pkg/devicetwin/dtclient/device_db_test.go
  pkg/devicetwin/dtclient/deviceattr_db_test.go
  pkg/devicetwin/dtclient/devicetwin_db_test.go
  pkg/devicetwin/dtclient/sqlite_test.go
  pkg/metamanager/dao/meta_test.go
Labels: kind/cleanup

#150 DeviceTwin:Added Error Handling and assertion in twin.go
  pkg/devicetwin/dtmanager/twin.go
Labels: kind/bug

#164 docs: Improved the documentation of the device module of device twin
  docs/images/devicetwin/device-state-update.png
  docs/images/devicetwin/device-update.png
  docs/modules/devicetwin.md
Labels: kind/documentation

#163 docs: Improved the documentation of the twin module of device twin by…
  docs/images/devicetwin/devicetwin-get.png
  docs/images/devicetwin/devicetwin-update.png
  docs/images/devicetwin/sync-to-cloud.png
  docs/modules/devicetwin.md
Labels: kind/documentation

#165 kubeedge: added cross build job for edge
  .travis.yml
  Makefile
  edge/Makefile
Labels: kind/feature

#171 docs: Improved language in main README.md
  README.md
Labels: kind/documentation

#175 docs: Improved the documentation of devicetwin module
  docs/images/devicetwin/device-state-update.png
  docs/images/devicetwin/device-update.png
  docs/images/devicetwin/devicetwin-get.png
  docs/images/devicetwin/devicetwin-update.png
  docs/images/devicetwin/membership-detail.png
  docs/images/devicetwin/membership-get.png
  docs/images/devicetwin/membership-update.png
  docs/images/devicetwin/sync-to-cloud.png
  docs/modules/devicetwin.md
Labels: kind/documentation

#173 DeviceTwin: Adding unit tests for types_helper.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
Labels: kind/test

#153 Added ReadTheDocs support. Formatted documentation. Added docs.
  README.md
  README_zh.md
  docs/Makefile
  docs/conf.py
  docs/contribute-website.md
  docs/contribute.md
  docs/getting-started.md
  docs/guides/message_topics.md
  docs/guides/unit_test_guide.md
  docs/images/favicon.png
  docs/images/kubeedge-logo-only.png
  docs/index.rst
  docs/kubeedge.md
  docs/make.bat
  docs/modules/beehive.md
  docs/modules/devicetwin.md
  docs/modules/edgehub.md
  docs/modules/eventbus.md
  docs/modules/metamanager.md
  docs/requirements.md
  docs/roadmap.md
  docs/setup.md
  docs/support.md
  docs/troubleshooting.md
Labels: kind/documentation

#180 Fixed the display of documentation site. Increased to full width.
  docs/_static/css/custom.css
  docs/conf.py
Labels: kind/documentation
