Repository kubeedge/kubeedge, pull requests merged in 2019-12, with the labels that each got.

#1286 add a judgement before decoding the message in edgemesh
  edgemesh/pkg/proxy/proxy.go
Labels: approved, kind/bug, lgtm

#1300 Add compatibility matrix
  README.md
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/M

#1301 Fix the UT failure and open the CI test on ARM64
  .travis.yml
  edge/pkg/devicetwin/devicetwin_test.go
  edge/pkg/devicetwin/dtmanager/communicate_test.go
Labels: approved, kind/bug, lgtm, size/M

#1276 Optimize the initialization of the edgecore modules global variable
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/devicecontroller/config/config.go
  cloud/pkg/edgecontroller/config/config.go
  edge/pkg/common/config/config.go
  edge/pkg/common/dbm/db.go
  edge/pkg/common/util/config.go
  edge/pkg/devicetwin/config/config.go
  edge/pkg/devicetwin/devicetwin.go
  edge/pkg/devicetwin/dtcontext/dtcontext.go
  edge/pkg/edged/config/config.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edgehub/clients/factory.go
  edge/pkg/edgehub/clients/factory_test.go
  edge/pkg/edgehub/config/config.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgehub/process.go
  edge/pkg/edgehub/process_test.go
  edge/pkg/eventbus/config/config.go
  edge/pkg/eventbus/eventbus.go
  edge/pkg/eventbus/mqtt/client.go
  edge/pkg/metamanager/config/config.go
  edge/pkg/metamanager/metamanager.go
  edge/pkg/metamanager/process.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1312 Remove limitation of insecure port
  docs/getting-started/release_package.md
  docs/getting-started/usage.md
  docs/getting-started/usage_zh.md
  docs/modules/edgesite.md
Labels: approved, kind/documentation, lgtm, size/L

#1315 Fix cleanup scripts
  tests/e2e/scripts/cleanup.sh
Labels: approved, kind/bug, lgtm, size/M

#1324 Close file after invoking os.open()
  edge/test/integration/utils/edge/config.go
Labels: approved, kind/bug, lgtm, size/XS

#1323 Cleanup a unused file
  edge/pkg/common/util/yamlconfigurationsource.go
  go.mod
  vendor/modules.txt
Labels: approved, kind/bug, kind/cleanup, lgtm, size/XL

#1325 Return error returned by CSINode Get if initialization failed
  edge/pkg/edged/volume/csi/nodeinfomanager/nodeinfomanager.go
Labels: approved, kind/bug, lgtm, size/XS

#1314 update setup guide
  README.md
  README_zh.md
  docs/getting-started/usage.md
  docs/getting-started/usage_zh.md
  docs/setup/setup.md
Labels: approved, kind/cleanup, lgtm, size/L

#1327 Run local verifications before submitting
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#1339 update docs of kubeedge install prerequisites
  docs/setup/setup.md
Labels: approved, kind/documentation, lgtm, size/S

#1328 Refactor KubeEdge architecture diagram
  docs/images/KubeEdge_arch.vsdx
  docs/images/kubeedge_arch.png
Labels: approved, kind/documentation, lgtm, size/XS

#1344 catch unknow message source
  edge/pkg/metamanager/process.go
Labels: approved, lgtm, size/XS

#1336 Remove unused files
  edge/pkg/devicetwin/dtclient/sqlite.go
  edge/pkg/devicetwin/dtclient/sqlite_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#1342 change /usr/bin/bash to /bin/bash in the edgemesh_init image
  edgemesh/tools/initContainer/script/edgemesh-iptables.sh
Labels: approved, kind/bug, lgtm, size/XS

#1341 Check the running environment before start edge core
  edge/cmd/edgecore/app/server.go
  go.mod
  go.sum
  vendor/github.com/mitchellh/go-ps/.gitignore
  vendor/github.com/mitchellh/go-ps/.travis.yml
  vendor/github.com/mitchellh/go-ps/LICENSE.md
  vendor/github.com/mitchellh/go-ps/README.md
  vendor/github.com/mitchellh/go-ps/Vagrantfile
  vendor/github.com/mitchellh/go-ps/process.go
  vendor/github.com/mitchellh/go-ps/process_darwin.go
  vendor/github.com/mitchellh/go-ps/process_freebsd.go
  vendor/github.com/mitchellh/go-ps/process_linux.go
  vendor/github.com/mitchellh/go-ps/process_solaris.go
  vendor/github.com/mitchellh/go-ps/process_unix.go
  vendor/github.com/mitchellh/go-ps/process_windows.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XL

#1346 clear useless config node-id
  cloud/pkg/edgecontroller/config/config.go
Labels: approved, lgtm, size/XS

#1347 Bugfix: wrong defaut kube burst config for edgecontroller
  cloud/pkg/edgecontroller/config/config.go
Labels: approved, lgtm, size/XS

#1337 Remove unused const in devicetwin module
  edge/pkg/devicetwin/dtcommon/common.go
Labels: approved, kind/cleanup, lgtm, size/L

#1354 Refactor the travis ci
  .travis.yml
Labels: approved, kind/test, lgtm, size/L

#1355 fix Code of conduct dead link in document
  docs/getting-started/contribute.md
Labels: approved, kind/bug, kind/documentation, lgtm, size/XS
