Repository kubeedge/kubeedge, pull requests merged in 2019-04, with the labels that each got.

#181 design: Device CRD design proposal
  docs/images/device-crd/device-crd-model.png
  docs/images/device-crd/device-crd.png
  docs/images/device-crd/device-downstream-controller.png
  docs/images/device-crd/device-model-crd.png
  docs/images/device-crd/device-updates-cloud-edge.png
  docs/images/device-crd/device-updates-edge-cloud.png
  docs/images/device-crd/device-upstream-controller.png
  docs/proposals/device-crd.md
Labels: kind/design

#328 Fixed flaky unit test in edgehub/config
  edge/pkg/common/util/config.go
Labels: kind/failing-test

#326 Migrating E2E tests to Travis-CI & Added Few Tests to E2E framework
  .travis.yml
  tests/e2e/deployment/deployment_suite_test.go
  tests/e2e/deployment/deployment_test.go
  tests/e2e/scripts/execute.sh
  tests/e2e/scripts/fast_test.sh
  tests/e2e/utils/common.go
  tests/e2e/utils/config.go
  tests/e2e/utils/context.go
  tests/e2e/utils/node.go
  tests/e2e/utils/pod.go
Labels: kind/test

#329 PR to add documentation to setup kube edge load performance test setup
  docs/images/memfootprint-img/perftestsetup_diagram.PNG
  docs/setup/memfootprint-test-setup.md
  edge/hack/memfootprint-test/Dockerfile
  edge/hack/memfootprint-test/perftestimg.yaml
Labels: kind/feature

#335 Increase the deployment of docker-compose and modify the README
  README.md
  README_zh.md
  build/cloud/README.md
  build/cloud/README_zh.md
  build/edge/.env
  build/edge/Dockerfile
  build/edge/README.md
  build/edge/README_zh.md
  build/edge/docker-compose.yaml
  build/edge/run_daemon.sh
  edge/hack/install_docker_for_raspbian.sh
Labels: kind/documentation

#333 Adding UT for common/dbm/db.go
  edge/pkg/common/dbm/db_test.go
Labels: kind/test

#340 Makefile changes to make both cloud and edge_core binaries
  .travis.yml
  Makefile
  README.md
  tests/e2e/scripts/execute.sh
Labels: kind/test

#349 Update kubeedge arch pic in README
  docs/images/kubeedge_arch.png
Labels: kind/documentation

#354 Modifying device.go for code fix
  edge/pkg/devicetwin/dtmanager/device.go
Labels: kind/bug

#355 Update readme to add commnunity meeting link
  README.md
  README_zh.md
Labels: kind/documentation

#314 design: Added router design in edgemesh design
  docs/images/proposals/router-design.png
  docs/images/proposals/router-flow.png
  docs/proposals/edgemesh-design.md
Labels: kind/design

#342 Adding kubeEdge installtion procedures scope document for Issue 324
  docs/proposals/kubeedgeadm-scope.md
Labels: kind/feature

#356 Update kubeedge roadmap
  README.md
Labels: kind/documentation

#366 fix the wrong port for nginx
  build/deployment.yaml
Labels: kind/bug, lgtm

#358 Device CRD: Add types for devices
  build/crd-samples/devices/create-device-instance.yaml
  build/crd-samples/devices/create-device-model.yaml
  build/crds/devices/devices_v1alpha1_device.yaml
  build/crds/devices/devices_v1alpha1_devicemodel.yaml
  cloud/edgecontroller/pkg/devicecontroller/apis/devices/v1alpha1/device_instance_types.go
  cloud/edgecontroller/pkg/devicecontroller/apis/devices/v1alpha1/device_model_types.go
  cloud/edgecontroller/pkg/devicecontroller/apis/devices/v1alpha1/register.go
  cloud/edgecontroller/pkg/devicecontroller/apis/devices/v1alpha1/zz_generated.deepcopy.go
Labels: kind/api-change

#364 clean files after e2e test
  tests/e2e/scripts/cleanup.sh
Labels: kind/cleanup

#362 Added device model type definition for Bluetooth protocol in device CRD design
  docs/proposals/device-crd.md
Labels: kind/api-change

#374 Add meeting record link(youtube)
  README.md
  README_zh.md
Labels: kind/documentation

#382 scripts: Improvement on the scripts for deploying wiht containers
  build/edge/.env
  build/edge/run_daemon.sh
Labels: kind/cleanup

#381 doc: run script in the right dir
  build/edge/README.md
Labels: kind/bug, kind/documentation

#378 Skipping e2e tests when the change only docs(*.md) #371
  .travis.yml
Labels: kind/test

#391 Adjust getting-started documents
  README.md
  README_zh.md
  docs/getting-started/roadmap.md
  docs/getting-started/roadmap_zh.md
  docs/getting-started/usage.md
  docs/getting-started/usage_zh.md
Labels: kind/cleanup

#392 Add modules links
  README.md
  README_zh.md
Labels: kind/documentation

#397 output time duration per test case
  tests/e2e/deployment/deployment_test.go
  tests/e2e/utils/timer.go
Labels: kind/test

#402 Device CRD: Fix #384, make device property and visitor config pointer types
  cloud/edgecontroller/pkg/devicecontroller/apis/devices/v1alpha1/device_model_types.go
  cloud/edgecontroller/pkg/devicecontroller/apis/devices/v1alpha1/zz_generated.deepcopy.go
Labels: kind/bug

#363 Add device controller implementation
  cloud/edgecontroller/cmd/edgecontroller.go
  cloud/edgecontroller/conf/controller.yaml
  cloud/edgecontroller/conf/modules.yaml
  cloud/edgecontroller/pkg/cloudhub/channelq/channelq.go
  cloud/edgecontroller/pkg/devicecontroller/config/buffer.go
  cloud/edgecontroller/pkg/devicecontroller/config/context.go
  cloud/edgecontroller/pkg/devicecontroller/config/kube.go
  cloud/edgecontroller/pkg/devicecontroller/config/load.go
  cloud/edgecontroller/pkg/devicecontroller/config/messagelayer.go
  cloud/edgecontroller/pkg/devicecontroller/constants/default.go
  cloud/edgecontroller/pkg/devicecontroller/constants/service.go
  cloud/edgecontroller/pkg/devicecontroller/controller/downstream.go
  cloud/edgecontroller/pkg/devicecontroller/controller/upstream.go
  cloud/edgecontroller/pkg/devicecontroller/manager/common.go
  cloud/edgecontroller/pkg/devicecontroller/manager/configmap.go
  cloud/edgecontroller/pkg/devicecontroller/manager/device.go
  cloud/edgecontroller/pkg/devicecontroller/manager/devicemodel.go
  cloud/edgecontroller/pkg/devicecontroller/messagelayer/context.go
  cloud/edgecontroller/pkg/devicecontroller/messagelayer/layer.go
  cloud/edgecontroller/pkg/devicecontroller/messagelayer/util.go
  cloud/edgecontroller/pkg/devicecontroller/module.go
  cloud/edgecontroller/pkg/devicecontroller/types/device.go
  cloud/edgecontroller/pkg/devicecontroller/types/deviceprofile.go
  cloud/edgecontroller/pkg/devicecontroller/utils/crdclient.go
  cloud/edgecontroller/pkg/devicecontroller/utils/kubeclient.go
  edge/pkg/devicetwin/dtcontroller.go
Labels: kind/feature

#407 use the `nginx` image which supports `ARM` as well
  build/deployment.yaml
Labels: kind/cleanup

#408 change poll into watch
  tests/e2e/deployment/deployment_test.go
  tests/e2e/utils/pod.go
Labels: kind/cleanup

#410 fix cloudpart cannot run in container
  build/cloud/05-configmap.yaml
  build/cloud/07-deployment.yaml
  build/cloud/Dockerfile
  cloud/edgecontroller/pkg/devicecontroller/types/device.go
Labels: kind/bug

#412 remove keepalive
  edge/pkg/edgehub/controller.go
  edge/pkg/edgehub/controller_test.go
Labels: kind/cleanup

#418 setup script changes for IEF
  edge/hack/keepalivefunction.txt
  edge/hack/setup_for_IEF.sh
Labels: kind/cleanup

#422 Add protocol config for bluetooth
  cloud/edgecontroller/pkg/devicecontroller/controller/downstream.go
Labels: kind/feature

#429 Stop keepalive message from sending to controller group
  cloud/edgecontroller/pkg/cloudhub/wsserver/server.go
Labels: kind/bug

#308 Performance Test Proposal
  docs/images/perf/perf-app-deploy.png
  docs/images/perf/perf-cloudhub-edgehub.png
  docs/images/perf/perf-create-device.png
  docs/images/perf/perf-deploy-type.png
  docs/images/perf/perf-edgenodes-join-cluster.png
  docs/images/perf/perf-multi-devices.png
  docs/images/perf/perf-multi-edgenodes.png
  docs/images/perf/perf-report-devicestatus.png
  docs/images/perf/perf-test-framework.png
  docs/images/perf/perf-update-devicetwin.png
  docs/proposals/perf.md
Labels: kind/design

#432 [Issue#319] Fix the nil pointer exception for missing config string
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/config/default.go
  cloud/pkg/cloudhub/wsserver/server.go
  cloud/pkg/controller/controller.go
  cloud/pkg/devicecontroller/module.go
  edge/pkg/edged/edged.go
  edge/pkg/eventbus/event_bus.go
Labels: kind/bug
