Repository kubeedge/kubeedge, pull requests merged in 2019-03, with the labels that each got.

#187 Fixed formatting. Fixed broken image links. Fixed section links.
  docs/conf.py
  docs/guides/unit_test_guide.md
  docs/index.rst
  docs/kubeedge.md
  docs/modules/beehive.md
  docs/modules/devicetwin.md
  docs/requirements.txt
Labels: kind/documentation

#188 docs: Improved readability of device twin documentation for docs.kubeedge.io
  docs/modules/devicetwin.md
Labels: kind/documentation

#192 Added link to the KubeEdge website in the TOC.
  docs/index.rst
Labels: kind/documentation

#174 docs: Mapper Design Proposal
  docs/images/proposals/mapper-design.png
  docs/proposals/mapper-design.md
Labels: kind/design

#197 script changes to replace Placement flag to true
  edge/hack/setup_for_IEF.sh
Labels: kind/test

#199 Fixed error in README
  README.md
Labels: kind/documentation

#185 Documentation for CloudHub module
  docs/modules/cloudhub/CloudHub.md
Labels: kind/documentation

#184 Document for the Edgecontroller module cloud part
  docs/images/edgecontroller/DownstreamController.png
  docs/images/edgecontroller/UpstreamController.png
  docs/modules/cloud/controller.md
Labels: kind/documentation

#204 Added Cloud documentation to the RTD site. Fixed formatting and typos
  README.md
  docs/getting-started.md
  docs/index.rst
  docs/kubeedge.md
  docs/setup.md
  docs/setup/cross-compilation.md
  docs/setup/setup.md
Labels: kind/documentation

#200 Improvement of test file util/common_test.go
  edge/pkg/eventbus/common/util/common_test.go
Labels: kind/test

#206 Restructured the docs folder. Updated contents. Fixed broken links.
  docs/README.md
  docs/_static/css/custom.css
  docs/contribute-website.md
  docs/getting-started/contribute.md
  docs/getting-started/getting-started.md
  docs/getting-started/reporting_bugs.md
  docs/getting-started/roadmap.md
  docs/getting-started/support.md
  docs/guides/message_topics.md
  docs/guides/try_kubeedge_with_ief.md
  docs/guides/unit_test_guide.md
  docs/index.rst
  docs/modules/beehive.md
  docs/modules/kubeedge.md
  docs/setup/requirements.md
  docs/setup/setup.md
  docs/troubleshooting.md
  docs/troubleshooting/troubleshooting.md
Labels: kind/documentation

#210 fix typos
  common/beehive/pkg/core/context/context_channel.go
  common/beehive/pkg/core/core.go
  common/beehive/pkg/core/module.go
  edge/pkg/common/util/config.go
  edge/pkg/edged/dockertools/fake_docker_client.go
Labels: kind/documentation

#213 check pem.Encode's return err before return
  edge/pkg/common/util/config.go
Labels: kind/feature

#212 Added the proposals folder to the exclude list in readthedocs config
  docs/conf.py
Labels: kind/documentation

#215 Added maintainers file
  MAINTAINERS
Labels: kind/documentation

#209 DeviceTwin: Modifying testcases of dttype
  edge/pkg/devicetwin/dttype/types_helper_test.go
  edge/pkg/devicetwin/dttype/types_test.go
  edge/pkg/edgehub/common/http/http_test.go
Labels: kind/test

#218 Adds test cases for edged integration test
  edge/test/integration/appdeployment/application_test.go
  edge/test/integration/utils/helpers/helpers.go
Labels: kind/test

#222 sync readme into cn
  README.md
  README_zh.md
Labels: kind/documentation

#221 Fixed broken links. Fixed formatting.
  docs/getting-started/getting-started.md
  docs/guides/unit_test_guide.md
Labels: kind/documentation

#223 Updated the sections in the TOC. Added Next and Prev buttons on top.
  docs/conf.py
  docs/index.rst
Labels: kind/documentation

#226 wrap the server io to support different encoding
  cloud/edgecontroller/pkg/cloudhub/common/io/hubio.go
  cloud/edgecontroller/pkg/cloudhub/wsserver/server.go
Labels: kind/feature

#227 Document pod spec limitation on edge node
  docs/setup/setup.md
Labels: kind/documentation

#219 re-organize documents
  docs/index.rst
  docs/modules/cloud/cloudhub.md
  docs/modules/cloud/controller.md
  docs/modules/edge/devicetwin.md
  docs/modules/edge/edgehub.md
  docs/modules/edge/eventbus.md
  docs/modules/edge/metamanager.md
  docs/modules/kubeedge.md
Labels: kind/cleanup, kind/documentation

#240 Fixed a broken link to the cloudhub documentation.
  README.md
  README_zh.md
  docs/modules/kubeedge.md
Labels: bug, kind/documentation

#217 Adding Integration Test Cases for Edge_Core (Issue #151)
  edge/test/integration/device/device_suite_test.go
  edge/test/integration/device/device_test.go
  edge/test/integration/utils/helpers/helpers.go
Labels: kind/test

#233 Adding edged document
  docs/images/edged/PLEG-Flow.PNG
  docs/images/edged/configmap-handling.PNG
  docs/images/edged/edged-overall.PNG
  docs/images/edged/pod-addition-flow.PNG
  docs/images/edged/pod-deletion-flow.PNG
  docs/images/edged/pod-status-manger-flow.PNG
  docs/images/edged/pod-update-flow.PNG
  docs/images/edged/query-configmap-from-edged.PNG
  docs/images/edged/query-secret-from-edged.PNG
  docs/images/edged/secret-handling.PNG
  docs/modules/edged.md
Labels: kind/documentation

#239 E2E Automation framework changes
  Makefile
  tests/e2e/deployment/deployment_suite_test.go
  tests/e2e/deployment/deployment_test.go
  tests/e2e/scripts/cleanup.sh
  tests/e2e/scripts/compile.sh
  tests/e2e/scripts/execute.sh
  tests/e2e/scripts/fast_test.sh
  tests/e2e/scripts/generate_cert.sh
  tests/e2e/scripts/setup.sh
  tests/e2e/utils/common.go
  tests/e2e/utils/config.go
  tests/e2e/utils/context.go
  tests/e2e/utils/log.go
  tests/e2e/utils/node.go
  tests/e2e/utils/pod.go
Labels: kind/test

#237 It test to fix the issue related to random failures
  edge/test/integration/device/device_test.go
  edge/test/integration/scripts/fast_test
  edge/test/integration/utils/edge/config.go
  edge/test/integration/utils/helpers/helpers.go
Labels: kind/test

#189 DeviceTwin: Adding test cases for communicate.go
  edge/pkg/devicetwin/dtmanager/communicate_test.go
Labels: kind/test
