Repository kubeedge/kubeedge, pull requests merged in 2019-10, with the labels that each got.

#1165 create a symlink in vendor directory pointing to the staging components
  .travis.yml
  Makefile
  hack/update-vendor.sh
  hack/verify-vendor.sh
Labels: kind/cleanup, lgtm, size/M

#1160 Improve the environment information for bug report
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: kind/documentation, lgtm, size/S

#1164 Unifying logging library to klog for beehive
  staging/src/github.com/kubeedge/beehive/pkg/common/config/config.go
  staging/src/github.com/kubeedge/beehive/pkg/common/log/logger.go
  staging/src/github.com/kubeedge/beehive/pkg/common/log/logger_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_channel.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_factory.go
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
  staging/src/github.com/kubeedge/beehive/pkg/core/module.go
  vendor/github.com/go-chassis/paas-lager/.gitignore
  vendor/github.com/go-chassis/paas-lager/.travis.yml
  vendor/github.com/go-chassis/paas-lager/LICENSE
  vendor/github.com/go-chassis/paas-lager/NOTICE
  vendor/github.com/go-chassis/paas-lager/README.md
  vendor/github.com/go-chassis/paas-lager/lager.go
  vendor/github.com/go-chassis/paas-lager/rotate/logrotate.go
  vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/LICENSE
  vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/NOTICE
  vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/README.md
  vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/color/color.go
  vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go
  vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/models.go
  vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/reconfigurable_sink.go
  vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/writer_sink.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, size/XXL

#1177 travis fix
  .travis.yml
Labels: approved, lgtm, size/XS

#1176 update some comments
  cloud/cmd/admission/app/options/options.go
  cloud/pkg/admissioncontroller/admission.go
Labels: approved, kind/cleanup, lgtm, size/S

#1180 remove the duplicated travis task
  .travis.yml
Labels: approved, kind/cleanup, lgtm, size/XS

#1179 remove unnecessary select clause, replace it with simple chan sending
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1151 delete useless sync group module
  edge/pkg/edgehub/controller.go
Labels: approved, kind/bug, lgtm, size/XS

#1174 Remove namespace config in cloudcore
  cloud/conf/controller.yaml
  cloud/pkg/devicecontroller/config/kube.go
  cloud/pkg/edgecontroller/config/kube.go
  cloud/pkg/edgecontroller/config/types.go
Labels: approved, kind/cleanup, lgtm, size/S

#1173 Remove logging.yaml
  build/cloud/05-configmap.yaml
  build/edge/kubernetes/03-configmap-edgenodeconf.yaml
  cloud/conf/logging.yaml
  edge/conf/logging.yaml
  edgesite/conf/logging.yaml
  keadm/app/cmd/common/config.go
  keadm/app/cmd/common/types.go
  keadm/app/cmd/util/cloudinstaller.go
  keadm/app/cmd/util/common.go
  keadm/app/cmd/util/edgecoreinstaller.go
  tests/performance/assets/01-configmap.yaml
  tests/performance/assets/02-edgeconfigmap.yaml
Labels: approved, lgtm, size/M

#1188 bump golangci-lint from 1.16 to 1.20
  .travis.yml
Labels: approved, kind/failing-test, lgtm, size/XS

#1190 fix: immediate return when dns server start err
  edgemesh/pkg/server/dns.go
Labels: lgtm, size/XS

#1196 Update roadmap for 2019 Q4
  docs/getting-started/roadmap.md
Labels: approved, lgtm, size/S

#1198 Fix go mod verify failure: servicecomb-kie checksum mismatch
  go.mod
  go.sum
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/beehive/go.sum
  staging/src/github.com/kubeedge/viaduct/go.mod
  staging/src/github.com/kubeedge/viaduct/go.sum
Labels: approved, kind/bug, lgtm, size/S

#1199 Fix update vendors
  go.mod
  hack/update-vendor.sh
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/beehive/go.sum
  staging/src/github.com/kubeedge/viaduct/go.mod
  staging/src/github.com/kubeedge/viaduct/go.sum
  vendor/modules.txt
Labels: approved, kind/cleanup, lgtm, size/M

#1204 refer to PR1141, update the download path of the kubeedge checksum file
  keadm/app/cmd/util/ubuntuinstaller.go
Labels: approved, lgtm, size/XS

#1208 purge external dependency to stand-alone beehive and viaduct repos
  .gitignore
  go.mod
  hack/update-vendor.sh
  hack/verify-vendor.sh
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/beehive/go.sum
  staging/src/github.com/kubeedge/viaduct/go.mod
  staging/src/github.com/kubeedge/viaduct/go.sum
  vendor/modules.txt
Labels: approved, kind/cleanup, lgtm, size/M

#1206 Fix roadmap link in readme and add chinese roadmap
  README.md
  README_zh.md
  docs/getting-started/roadmap.md
  docs/getting-started/roadmap_zh.md
Labels: approved, lgtm, size/M

#1211 remove vendor/ in staging repo after update-vendor.sh execution
  .gitignore
  hack/update-vendor.sh
Labels: approved, kind/cleanup, lgtm, size/XS

#1201 fix setup.md
  build/tools/cloudcore.service
  build/tools/edgecore.service
  docs/setup/setup.md
Labels: approved, lgtm, size/M

#1194 Enable travis CI on arm64
  .travis.yml
  build/edge/Dockerfile
Labels: approved, kind/feature, lgtm, size/M

#1195 Small improvement for codebase
  edge/pkg/edged/edged.go
Labels: approved, kind/cleanup, lgtm, size/L

#1216 Update docs for edge application
  docs/getting-started/usage.md
  docs/setup/setup.md
Labels: approved, kind/documentation, lgtm, size/XS

#1225 Exit local-up immediately if there's an error
  hack/local-up-kubeedge.sh
Labels: approved, lgtm, size/XS

#1222 make webhook service port configurable
  build/admission/deployment.yaml
  cloud/cmd/admission/app/options/options.go
  cloud/pkg/admissioncontroller/admission.go
Labels: approved, kind/bug, lgtm, size/XS

#1229 Comments failed buildimages tests for arm
  .travis.yml
Labels: approved, lgtm, size/S

#1228 Fix local-up script
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
Labels: approved, kind/bug, lgtm, size/M

#1232 Make sure the bluetoothdevice image is built in Travis CI
  .travis.yml
  Makefile
Labels: approved, kind/bug, lgtm, size/M

#1230 docs: Fix obeserve typo
  docs/setup/installer_setup.md
Labels: approved, lgtm, size/XS
