Repository kubeedge/kubeedge, pull requests merged in 2020-12, with the labels that each got.

#2382 modify log level
  edge/pkg/edged/edged.go
Labels: approved, lgtm, size/XS

#2390 hack: check and use GOBIN environment variable first
  cloud/hack/generate-groups.sh
Labels: approved, lgtm, size/XS

#2387 fix msg in nodestore compare error
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: approved, kind/bug, lgtm, size/XS

#2395 Allow container logs to grow bigger than 1 byte before rotation
  edge/pkg/edged/edged.go
Labels: approved, kind/bug, lgtm, size/XS

#2397 modify log format
  edge/pkg/edged/edged_status.go
Labels: approved, kind/feature, lgtm, size/XS

#2394 Automated cherry pick of #2387: fix msg in nodestore compare error
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: approved, lgtm, size/XS

#2392 fix message send problem
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: approved, kind/bug, lgtm, size/S

#2396 fix the invalid memory address panic of common_test in eventbus
  edge/pkg/eventbus/common/util/common_test.go
Labels: approved, kind/feature, lgtm, size/XS

#2377 Automated cherry pick of #2334: CI: switch amd64 tests to Github Action
  .github/workflows/main.yaml
  .travis.yml
  Makefile
  edge/hack/clean.sh
  edge/hack/install_docker_for_raspbian.sh
  edge/hack/setup_for_IEF.sh
  hack/lib/golang.sh
  hack/lib/init.sh
  hack/lib/install.sh
  hack/lib/lint.sh
  hack/lib/mapper.sh
  hack/lib/util.sh
  hack/setup-vmruntime.sh
  mappers/modbus_mapper/scripts/start_modbusmapper.sh
  tests/e2e/scripts/bluetoothconfig.sh
Labels: approved, lgtm, size/L

#2389 Get EdgeNode ip before registerModules to fix stream module problem
  edge/cmd/edgecore/app/server.go
  edge/pkg/edged/edged_status.go
Labels: approved, kind/feature, lgtm, size/S

#2402 Fixed spelling mistake
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
Labels: approved, lgtm, size/S

#2399 Automated cherry pick of #2392: fix message send problem
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: approved, lgtm, size/S

#2391 add _tmp to gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#2403 CI: fix panic warning
  .golangci.yml
  cloud/cmd/admission/app/server.go
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/devicecontroller/constants/default.go
  cloud/pkg/devicecontroller/utils/crdclient.go
  cloud/pkg/edgecontroller/manager/configmap.go
  cloud/pkg/edgecontroller/manager/endpoint.go
  cloud/pkg/edgecontroller/manager/location.go
  cloud/pkg/edgecontroller/manager/location_test.go
  cloud/pkg/edgecontroller/manager/node.go
  cloud/pkg/edgecontroller/manager/pod.go
  cloud/pkg/edgecontroller/manager/secret.go
  cloud/pkg/edgecontroller/manager/service.go
  cloud/pkg/leaderelection/leaderelection.go
  cloud/test/integration/fixtures/device.go
  common/types/types.go
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/edged/clcm/internal_life_cycle.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edgedtypes/types.go
  edge/pkg/edged/securitycontext/provider.go
  edge/pkg/edged/securitycontext/types.go
  edge/pkg/edged/status/status_manager.go
  edge/pkg/metamanager/process.go
  edge/test/cloudhub/stub.go
  edge/test/integration/appdeployment/application_test.go
  edge/test/integration/utils/helpers/helpers.go
  edge/test/test.go
  edgemesh/pkg/cache/cache.go
  edgemesh/pkg/listener/listener_test.go
  edgemesh/pkg/plugin/plugin.go
  edgemesh/pkg/plugin/registry/registry.go
  keadm/cmd/keadm/app/cmd/debug/check.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
  keadm/cmd/keadm/app/cmd/debug/diagnose.go
  keadm/cmd/keadm/app/cmd/debug/get.go
  keadm/cmd/keadm/app/cmd/reset.go
  mappers/bluetooth_mapper/action_manager/action_manager.go
  mappers/bluetooth_mapper/configuration/config.go
  mappers/bluetooth_mapper/controller/controller.go
  mappers/bluetooth_mapper/watcher/watcher.go
  mappers/common/event_test.go
  mappers/modbus-go/configmap/parse.go
  mappers/modbus-go/configmap/parse_test.go
  mappers/modbus-go/device/device.go
  mappers/modbus-go/device/devstatus.go
  mappers/modbus-go/device/twindata.go
  mappers/modbus-go/main.go
  tests/e2e/utils/node.go
  tests/performance/loadtest/loadtest_test.go
Labels: approved, kind/bug, kind/test, lgtm, size/L

#2405 Added unit tests for keadm/cmd/keadm/app/cmd/debug/get.go
  keadm/cmd/keadm/app/cmd/debug/get_test.go
Labels: approved, lgtm, size/M

#2410 fix typo.
  edgemesh/pkg/plugin/plugin.go
Labels: approved, lgtm, size/XS

#2393 fix synccontroller manage same name object error
  cloud/pkg/synccontroller/objectsync.go
Labels: approved, kind/bug, lgtm, size/M

#2422 CI: fix lint issue
  cloud/pkg/synccontroller/objectsync.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2430 semantic error in comments
  edge/pkg/eventbus/mqtt/server.go
Labels: approved, lgtm, size/XS

#2426 Fix an issue that misuse the name of the modbus register.
  mappers/modbus-go/driver/client.go
Labels: approved, kind/bug, lgtm, size/XS

#2431 edge: fix typo in comment.
  edge/pkg/metamanager/client/metaclient.go
Labels: approved, lgtm, size/XS

#2435 add InitConfigure of ServiceBus
  edge/pkg/servicebus/config/config.go
  edge/pkg/servicebus/servicebus.go
Labels: approved, kind/feature, lgtm, size/S

#2414 Fix edgehub synckeeper use unbuffer channel error
  edge/pkg/edgehub/process.go
  edge/pkg/edgehub/process_test.go
Labels: approved, kind/bug, lgtm, size/S

#2421 Install golangci-lint for local test
  .github/workflows/main.yaml
  hack/lib/install.sh
  hack/make-rules/lint.sh
Labels: approved, kind/test, lgtm, size/S

#2446 Fix bug: keadm doesn't delete file directly when checkSum is failed
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/bug, lgtm, size/XS

#2419 fix typing and grammar errors
  docs/proposals/EdgeSite.md
  docs/proposals/cloudcore-ha-design.md
  docs/proposals/configuration.md
  docs/proposals/cri.md
  docs/proposals/csi.md
  docs/proposals/device-crd.md
  docs/proposals/device-management-enhance.md
  docs/proposals/edgemesh-design.md
  docs/proposals/keadm-scope.md
  docs/proposals/mapper-design.md
  docs/proposals/quic-design.md
  docs/proposals/reliable-message-delivery.md
  docs/proposals/web-hook.md
Labels: approved, kind/documentation, lgtm, size/M

#2447 Comment minial support version and cleanup related codes
  README.md
  README_zh.md
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, kind/cleanup, lgtm, size/L

#2440 recognize message operation into one file
  edge/pkg/common/message/message.go
  edge/pkg/devicetwin/dtmanager/device.go
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/devicetwin/dtmanager/twin.go
  edge/pkg/edgehub/process.go
  edge/pkg/eventbus/eventbus.go
  edge/pkg/eventbus/mqtt/client.go
  edge/pkg/eventbus/mqtt/server.go
Labels: approved, kind/feature, lgtm, size/M

#2438 modify unit test of process.go in metamanager
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
Labels: approved, kind/test, lgtm, size/L

#2444 bluetooth mapper updates
  cloud/pkg/apis/devices/v1alpha2/device_instance_types.go
  mappers/bluetooth_mapper/configuration/config.go
  mappers/bluetooth_mapper/configuration/config_map_types.go
  mappers/bluetooth_mapper/data_converter/data_converter.go
  tests/e2e/mapper/bluetooth/crds/deviceinstance.yaml
  tests/e2e/mapper/bluetooth/crds/devicemodel.yaml
Labels: approved, lgtm, size/L

#2454 cloudstream: fix panic of concurrent map read and map write.
  cloud/pkg/cloudstream/session.go
  cloud/pkg/cloudstream/tunnelserver.go
Labels: approved, kind/bug, lgtm, size/XS

#2345 Add unsubscribe case in eventbus
  edge/pkg/common/message/message.go
  edge/pkg/eventbus/eventbus.go
Labels: approved, kind/feature, lgtm, size/XS

#2388 Keadm: optimize OS detect
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/debinstaller.go
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
Labels: approved, kind/feature, lgtm, size/M

#2460 edgecontroller: improve test coverage for edgecontroller/manager/location.go
  cloud/pkg/edgecontroller/manager/location_test.go
Labels: approved, lgtm, size/XL

#2254 Use pidof install ps to check process existence
  edge/test/integration/scripts/execute.sh
  keadm/cmd/keadm/app/cmd/util/common.go
  tests/e2e/scripts/keadm_e2e.sh
Labels: approved, lgtm, size/S

#2465 Keadm: remove useless files
  keadm/cmd/keadm/app/cmd/util/cloudconfig.go
Labels: approved, kind/cleanup, lgtm, size/M

#2469 keadm: optimize keadm_e2e.sh cleanup function
  tests/e2e/scripts/keadm_e2e.sh
Labels: approved, kind/bug, lgtm, size/XS

#2468 keadm: clean useless file after keadm_e2e test
  keadm/cmd/keadm/app/cmd/util/common.go
  tests/e2e/scripts/keadm_e2e.sh
Labels: approved, kind/feature, lgtm, size/XS

#2463 edgecore: support customize node labels、taints and annotations
  edge/pkg/edged/edged_status.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: approved, kind/feature, lgtm, size/S

#2480 keadm: fix spell issue
  keadm/cmd/keadm/app/cmd/debug/check.go
  keadm/cmd/keadm/app/cmd/debug/diagnose.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, lgtm, size/XS

#2415 keadm: support init kubeedge with package manager `pacman`
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/debinstaller.go
  keadm/cmd/keadm/app/cmd/util/pacmaninstaller.go
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
Labels: approved, lgtm, size/L

#2471 Fix bug: the websocket connection timeout setting doesn't take effect
  edge/pkg/edgehub/clients/wsclient/websocket.go
Labels: approved, lgtm, size/XS

#2479 Remove useless env settings
  build/edge/Dockerfile
  build/edgesite/Dockerfile
  docs/setup/kubeedge_precheck.md
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/debinstaller.go
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
Labels: approved, lgtm, size/S

#2478 Keadm: fix install issue
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/bug, lgtm, size/XS

#2482 support more metric path in cloud
  cloud/pkg/cloudstream/streamserver.go
Labels: approved, kind/bug, lgtm, size/XS

#2481 keadm: Generate default configuration support edgeStream.TunnelServer modification
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, kind/feature, lgtm, size/XS

#2457 add func that make subscribed topics persistence
  edge/pkg/eventbus/dao/subtopics.go
  edge/pkg/eventbus/dao/subtopics_test.go
  edge/pkg/eventbus/eventbus.go
  edge/pkg/eventbus/mqtt/client.go
  edge/pkg/eventbus/mqtt/server.go
Labels: approved, kind/feature, lgtm, size/L

#2474 Keadm: ensure /usr/local/bin exist
  build/tools/cloudcore.service
  build/tools/edgecore.service
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/bug, lgtm, size/S
