Repository kubeedge/kubeedge, pull requests merged in 2020-04, with the labels that each got.

#1380 refactor edgemesh
  common/constants/default.go
  docs/guides/edgemesh_test_env_guide.md
  edge/pkg/metamanager/client/listener.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/service.go
  edge/pkg/metamanager/process.go
  edgemesh/cmd/edgemesh.go
  edgemesh/pkg/cache/cache.go
  edgemesh/pkg/common/utils.go
  edgemesh/pkg/common/utils_test.go
  edgemesh/pkg/config/config.go
  edgemesh/pkg/dns/dns.go
  edgemesh/pkg/listener/listener.go
  edgemesh/pkg/module.go
  edgemesh/pkg/plugin/panel/panel.go
  edgemesh/pkg/plugin/plugin.go
  edgemesh/pkg/plugin/registry/registry.go
  edgemesh/pkg/protocol/http/http.go
  edgemesh/pkg/protocol/protocol.go
  edgemesh/pkg/proxy/poll/poll.go
  edgemesh/pkg/proxy/proxy.go
  edgemesh/pkg/proxy/virtualdevice/virtualdevice.go
  edgemesh/pkg/registry/registry.go
  edgemesh/pkg/resolver/resolver.go
  edgemesh/pkg/resolver/resolver_chain.go
  edgemesh/pkg/resolver/resolver_chain_test.go
  edgemesh/pkg/server/dns.go
  edgemesh/pkg/server/ip.go
  edgemesh/pkg/server/server.go
  edgemesh/pkg/server/tcp.go
  edgemesh/pkg/server/tcp_test.go
  go.mod
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: approved, lgtm, size/XXL

#1581 Modify a small error in 'edgemesh_test_env_guide.md'
  docs/guides/edgemesh_test_env_guide.md
Labels: approved, kind/documentation, lgtm, size/XS

#1580 endpoint of `ImageService` is not alway equal to `RuntimeService`
  edge/pkg/edged/edged.go
Labels: approved, kind/bug, lgtm, size/XS

#1587 update daemonEndpoints of node status when sync node status
  edge/pkg/edged/config/config.go
  edge/pkg/edged/edged_status.go
Labels: approved, lgtm, size/S

#1572 Update the guide for the installation from source
  docs/setup/kubeedge_configure.md
  docs/setup/kubeedge_install_source.md
Labels: approved, kind/documentation, lgtm, size/L

#1588 modify test case; remove conf/modules.yaml
  staging/src/github.com/kubeedge/beehive/pkg/common/util/file_util.go
  staging/src/github.com/kubeedge/beehive/test/cmd/conf/modules.yaml
  staging/src/github.com/kubeedge/beehive/test/conf/modules.yaml
  staging/src/github.com/kubeedge/beehive/test/modules/test_destination.go
  staging/src/github.com/kubeedge/beehive/test/modules/test_destination_group.go
  staging/src/github.com/kubeedge/beehive/test/modules/test_source.go
Labels: approved, kind/test, lgtm, size/M

#1563 Adding a page for the KubeEdge Troubleshooting
  docs/troubleshooting/troubleshooting.md
Labels: approved, kind/documentation, lgtm, size/M

#1590 set node.status.Address use hostnameoverride
  edge/pkg/edged/edged_status.go
Labels: approved, lgtm, size/XS

#1594 fix GroupName for devices apis register
  cloud/pkg/apis/devices/v1alpha1/register.go
Labels: approved, kind/bug, lgtm, size/XS

#1589 Enable `systemd` as the `cgroup` driver
  common/constants/default.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: approved, kind/feature, lgtm, size/S

#1596 Add adopters for KubeEdge
  ADOPTERS.md
  docs/adopters/china-unicom-wocloud.png
  docs/adopters/huawei-cloud.png
Labels: approved, kind/documentation, lgtm, size/XS

#1598 Fix outtaded docs
  docs/setup/cross-compilation.md
  docs/setup/kubeedge_install_source.md
Labels: approved, kind/documentation, lgtm, size/XS

#1407 Fix pod stay in terminating state and can't be deleted
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/status/status_manager.go
  edge/pkg/edged/util/pod/pod_deletion.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/pod.go
  edge/pkg/metamanager/process.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
Labels: approved, kind/bug, lgtm, size/L

#1601 Add built-in labels when auto registering node
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/edged/edged_status.go
Labels: approved, kind/feature, lgtm, size/S

#1607 change some logs level to 4 to reduce debug log output by too much
  cloud/pkg/edgecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/messagelayer/util.go
  cloud/pkg/synccontroller/objectsync.go
Labels: approved, kind/cleanup, lgtm, size/S

#1610 Guide on the lightweight runtime works with kubeedge
  docs/setup/kubeedge_configure.md
  docs/setup/kubeedge_cri_configure.md
Labels: approved, kind/documentation, lgtm, size/L

#1614 update example yaml to reflect built-in labels
  build/deployment-armv7.yaml
Labels: approved, lgtm, size/XS

#1616 fix component config field capitalization and descriptions
  build/cloud/05-configmap.yaml
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/manager/configmap.go
  docs/proposals/configuration.md
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  pkg/apis/componentconfig/edgesite/v1alpha1/types.go
Labels: approved, kind/cleanup, lgtm, size/L

#1618 Add feature to provision VM workload
  docs/setup/kubeedge_install_keadm.md
  hack/setup-vmruntime.sh
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, lgtm, size/L

#1600 Implement HA in hot standby mode
  build/cloud/ha/ha-clusterrole.yaml
  build/cloud/ha/ha-deployment.yaml
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/leaderelection/leaderelection.go
  cloud/pkg/leaderelection/readyzadaptor.go
  go.sum
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_factory.go
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go
  vendor/k8s.io/component-base/config/OWNERS
  vendor/k8s.io/component-base/config/doc.go
  vendor/k8s.io/component-base/config/types.go
  vendor/k8s.io/component-base/config/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1625 hack/local-up-kubeedge.sh: fix clean up issue
  hack/local-up-kubeedge.sh
Labels: approved, kind/bug, lgtm, size/XS

#1606 support kubectl logs feature in edge computing scenario
  build/tools/certgen.sh
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudstream/cloudstream.go
  cloud/pkg/cloudstream/config/config.go
  cloud/pkg/cloudstream/connection.go
  cloud/pkg/cloudstream/session.go
  cloud/pkg/cloudstream/streamserver.go
  cloud/pkg/cloudstream/tunnelserver.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/messagelayer/util.go
  common/constants/default.go
  docs/setup/kubeedge_install_source.md
  edge/cmd/edgecore/app/server.go
  edge/pkg/edged/config/config.go
  edge/pkg/edged/edged_status.go
  edge/pkg/edged/server/server.go
  edge/pkg/edgestream/config/config.go
  edge/pkg/edgestream/edgestream.go
  edge/pkg/edgestream/tunnel.go
  edge/test/integration/utils/test_setup.go
  go.mod
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation.go
  pkg/stream/connection.go
  pkg/stream/constants.go
  pkg/stream/flushwriter/writer.go
  pkg/stream/message.go
  pkg/stream/tunnel.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
  staging/src/github.com/kubeedge/viaduct/pkg/protos/message/message.pb.go
  tests/e2e/utils/test_setup.go
Labels: approved, kind/feature, lgtm, size/XXL

#1605 Add edge-node certs bootstrap
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  cloud/pkg/cloudhub/servers/httpserver/updateconfig.go
  cloud/pkg/cloudhub/servers/server.go
  common/constants/default.go
  edge/cmd/edgecore/app/options/options.go
  edge/pkg/edgehub/clients/wsclient/websocket.go
  edge/pkg/edgehub/clients/wsclient/websocket_test.go
  edge/pkg/edgehub/common/certutil/certfile.go
  edge/pkg/edgehub/common/certutil/certutil.go
  edge/pkg/edgehub/common/http/http.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgehub/process.go
  go.mod
  hack/local-up-kubeedge.sh
  keadm/cmd/keadm/app/cmd/util/cloudconfig.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation.go
  pkg/util/validation/check.go
  tests/e2e/deployment/deployment_suite_test.go
  tests/e2e/mapper/bluetooth/bluetooth_suite_test.go
  tests/e2e/scripts/execute.sh
  tests/e2e/utils/config.go
  tests/e2e/utils/test_setup.go
  vendor/github.com/dgrijalva/jwt-go/.gitignore
  vendor/github.com/dgrijalva/jwt-go/.travis.yml
  vendor/github.com/dgrijalva/jwt-go/LICENSE
  vendor/github.com/dgrijalva/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/dgrijalva/jwt-go/README.md
  vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md
  vendor/github.com/dgrijalva/jwt-go/claims.go
  vendor/github.com/dgrijalva/jwt-go/doc.go
  vendor/github.com/dgrijalva/jwt-go/ecdsa.go
  vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
  vendor/github.com/dgrijalva/jwt-go/errors.go
  vendor/github.com/dgrijalva/jwt-go/hmac.go
  vendor/github.com/dgrijalva/jwt-go/map_claims.go
  vendor/github.com/dgrijalva/jwt-go/none.go
  vendor/github.com/dgrijalva/jwt-go/parser.go
  vendor/github.com/dgrijalva/jwt-go/rsa.go
  vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
  vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
  vendor/github.com/dgrijalva/jwt-go/signing_method.go
  vendor/github.com/dgrijalva/jwt-go/token.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XXL
