Repository kubeedge/kubeedge, pull requests merged in 2020-06, with the labels that each got.

#1763 fix spell check
  edgemesh/tools/initContainer/script/edgemesh-iptables.sh
Labels: approved, lgtm, size/XS

#1761 Add v1.3.1 changelog
  CHANGELOG-1.3.md
Labels: approved, kind/documentation, lgtm, size/M

#1765 fix wrong use of e.namespace when get imagePullSecret
  edge/pkg/edged/edged.go
Labels: approved, lgtm, size/XS

#1770 edgemesh: unit deploy yaml
  build/README_zh.md
  build/deployment-armv7.yaml
  build/deployment.yaml
Labels: approved, lgtm, size/M

#1746 Clean all cache before do test
  Makefile
  hack/lib/golang.sh
  hack/make-rules/clean.sh
Labels: approved, lgtm, size/XS

#1775 fix wrong parse operation when service url is short
  edgemesh/pkg/plugin/registry/registry.go
Labels: approved, kind/bug, lgtm, size/S

#1778 add xh-iot to adopters
  ADOPTERS.md
  docs/adopters/xh-iot.png
Labels: approved, kind/documentation, lgtm, size/S

#1782 Use v1.3.1 as default in keadm
  keadm/cmd/keadm/app/cmd/common/constant.go
Labels: approved, lgtm, size/XS

#1784 Automated cherry pick of #1782: use v1.3.1 as default
  keadm/cmd/keadm/app/cmd/common/constant.go
Labels: approved, lgtm, size/XS

#1668 fix logs when node disconnected
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: approved, kind/bug, lgtm, size/XS

#1792 hack/lib/lint.sh: skip deleted files
  hack/lib/lint.sh
Labels: approved, kind/bug, lgtm, size/XS

#1793 Optimize docs
  docs/components/beehive.md
  docs/components/cloud/cloudhub.md
  docs/components/cloud/controller.md
  docs/components/cloud/device_controller.md
  docs/components/edge/devicetwin.md
  docs/components/edge/edged.md
  docs/components/edge/edgehub.md
  docs/components/edge/eventbus.md
  docs/components/edge/metamanager.md
  docs/components/edgesite.md
  docs/components/kubeedge.md
  docs/components/mappers/bluetooth_mapper.md
  docs/components/mappers/modbus_mapper.md
  docs/configuration/cri.md
  docs/configuration/kubeedge.md
  docs/contributing/bluetooth_mapper_e2e_guide.md
  docs/contributing/build.md
  docs/contributing/community.md
  docs/contributing/contribute.md
  docs/contributing/device_crd_guide.md
  docs/contributing/edgemesh_test_env_guide.md
  docs/contributing/feature-lifecycle.md
  docs/contributing/memfootprint-test-setup.md
  docs/contributing/message_topics.md
  docs/contributing/unit_test_guide.md
  docs/getting-started.md
  docs/getting-started/getting-started.md
  docs/getting-started/release_package.md
  docs/getting-started/reporting_bugs.md
  docs/getting-started/support.md
  docs/governance.md
  docs/index.rst
  docs/requirements.txt
  docs/roadmap.md
  docs/roadmap_zh.md
  docs/setup/build.md
  docs/setup/deploy-edge-node.md
  docs/setup/develop_kubeedge.md
  docs/setup/ief.md
  docs/setup/index.md
  docs/setup/keadm.md
  docs/setup/kubeedge_install_keadm.md
  docs/setup/kubeedge_install_source.md
  docs/setup/kubeedge_run.md
  docs/setup/local.md
  docs/troubleshooting.md
Labels: approved, kind/documentation, lgtm, size/XXL

#1774 build: update deploy docs
  build/cloud/07-deployment.yaml
  build/cloud/README.md
  build/cloud/README_zh.md
Labels: approved, kind/documentation, lgtm, size/M

#1804 fix Quick Start doc link not find
  README.md
Labels: approved, lgtm, size/XS

#1795 test/e2e: Optimize keadm e2e test script
  tests/e2e/scripts/keadm_e2e.sh
Labels: approved, lgtm, size/L

#1810 Docs: fix spell issue
  CHANGELOG-1.3.md
  docs/contributing/contribute.md
  docs/governance.md
  docs/proposals/cloudcore-ha-design.md
Labels: approved, lgtm, size/S

#1802 Optimize integration test scripts
  edge/test/integration/scripts/execute.sh
  edge/test/integration/scripts/fast_test.sh
  edge/test/integration/utils/test_setup.go
Labels: approved, kind/failing-test, lgtm, size/L

#1779 Keadm: support raspbian
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/feature, lgtm, size/S

#1787 keadm: fix get version issue
  keadm/cmd/keadm/app/cmd/edge/join.go
Labels: approved, kind/bug, lgtm, size/XS

#1812 Use const namespace value
  common/constants/default.go
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  tests/e2e/utils/common.go
Labels: approved, kind/cleanup, lgtm, size/S

#1813 update project maintainers
  MAINTAINERS
  OWNERS
Labels: approved, kind/documentation, lgtm, size/S

#1823 CI: Skip OWNERS/MAINTAINERS
  .travis.yml
Labels: approved, lgtm, size/XS

#1822 hack/lib/lint.sh: fix lint error when running on master
  hack/lib/lint.sh
Labels: approved, kind/bug, lgtm, size/XS

#1809 delay the volume mount until the pods are retrieved from metaManger and added to managers when edgecore starts
  edge/pkg/edged/edged.go
  edge/pkg/edged/util/source_ready.go
Labels: approved, lgtm, size/S

#1801 edge/test/integration/scripts/generate_cert.sh: fix no rnd file issue
  edge/test/integration/scripts/generate_cert.sh
Labels: approved, kind/bug, lgtm, size/XS

#1829 Edge: Ignore some log to users
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/process.go
Labels: approved, lgtm, size/XS

#1841 lint: ignore image files
  hack/lib/lint.sh
Labels: approved, kind/cleanup, lgtm, size/XS

#1833 Cloud: update cluster role
  build/cloud/03-clusterrole.yaml
Labels: approved, lgtm, size/XS

#1670 Fix the edge node takes too long time to get ready when reconnect
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/common/model/types_test.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/edgecontroller/controller/downstream.go
  edge/pkg/edged/edged_status.go
Labels: approved, kind/bug, lgtm, size/L

#1853 fix wrong use of e.namespace when get imagePullSecret
  edge/pkg/edged/edged.go
Labels: approved, lgtm, size/XS

#1858 Doc: document advertise-address clearer
  docs/setup/keadm.md
Labels: approved, lgtm, size/XS

#1852 delay the volume mount until the pods are retrieved from metaManger a…
  edge/pkg/edged/edged.go
  edge/pkg/edged/util/source_ready.go
Labels: approved, lgtm, size/S

#1844 dtmanager/communicate: optimize log level
  edge/pkg/devicetwin/dtmanager/communicate.go
Labels: approved, lgtm, size/S

#1860 Automated cherry pick of #1670: fix too long time to get node ready when reconnect
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/common/model/types_test.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/edgecontroller/controller/downstream.go
  edge/pkg/edged/edged_status.go
Labels: approved, lgtm, size/L

#1839 Fix the broken pic files
  docs/images/KubeEdge_arch.vsdx
  docs/images/reliable-message-delivery/reliablemessage-workflow.PNG
Labels: approved, kind/documentation, lgtm, size/XS

#1862 add clean namespace in keadm reset
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/cmd.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/centosinstaller.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/kubeclient.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/L

#1864 bugfix: deployment document index error
  docs/setup/index.md
Labels: approved, lgtm, size/XS

#1866 fix cpu limit does not take effect issue
  edge/pkg/edged/edged.go
Labels: approved, kind/bug, lgtm, size/XS

#1867 fix print information error of keadm version
  keadm/cmd/keadm/app/cmd/version.go
Labels: approved, lgtm, size/XS

#1869 Lint: verify vendor licenses
  .travis.yml
  Makefile
Labels: approved, lgtm, size/XS

#1865 update keadm docs
  docs/setup/keadm.md
Labels: approved, kind/documentation, lgtm, size/S

#1873 CloudCoreConfig: 'DeletePodWorkers' is wrong
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
Labels: approved, lgtm, size/XS

#1874 Auto detect sandbox image
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
Labels: approved, lgtm, size/XS

#1842 Lint: add transfer sign for hint
  hack/lib/lint.sh
Labels: approved, kind/cleanup, lgtm, size/XS
