Repository kubeedge/kubeedge, pull requests merged in 2020-09, with the labels that each got.

#2120 fix resource version compare
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: approved, kind/api-change, kind/cleanup, kind/design, kind/documentation, kind/failing-test, kind/feature, kind/test, lgtm, size/XS

#2114 BluetoothMapper: fix logic error
  mappers/bluetooth_mapper/controller/controller.go
Labels: approved, kind/api-change, kind/bug, kind/cleanup, kind/design, kind/documentation, kind/failing-test, kind/feature, kind/test, lgtm, size/XS

#2122 Remove redundant code in edgecontroller upstream process.
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/cleanup, lgtm, size/L

#2132 README: add troubleshooting link
  README.md
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/S

#2134 Fix bot add irrelevant labels
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/cleanup, lgtm, size/S

#2116 edgehub dispatch message by type
  edge/pkg/common/message/message.go
  edge/pkg/edgehub/process.go
Labels: approved, kind/feature, lgtm, size/S

#2126 Support config domain URL for cloudcore
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
Labels: approved, kind/feature, lgtm, size/S

#2136 Docs: update troubleshooting doc
  docs/troubleshooting.md
Labels: approved, lgtm, size/XS

#2032 Minor optimization for edgecontroller.
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2125 add metrics api support in streamserver
  cloud/pkg/cloudstream/containermetrics_connection.go
  cloud/pkg/cloudstream/streamserver.go
  pkg/stream/edgedmetricsconnection.go
Labels: approved, kind/feature, lgtm, size/S

#1989 Document how to handle network issue with keadm
  docs/troubleshooting.md
Labels: approved, kind/documentation, lgtm, size/M

#2011 Do not send SIGKILL to stop process
  edge/hack/clean.sh
  edge/test/integration/scripts/execute.sh
  edge/test/integration/utils/test_setup.go
  keadm/cmd/keadm/app/cmd/util/common.go
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
  tests/e2e/scripts/keadm_e2e.sh
Labels: approved, kind/bug, lgtm, size/S

#2143 fix deviceProfile json bug
  mappers/modbus_mapper/src/modbus.js
Labels: approved, kind/bug, lgtm, size/XS

#1877 Docs: add upgrade document
  docs/index.rst
  docs/setup/upgrade.md
Labels: approved, kind/documentation, lgtm, size/M

#2112 Add kubectl logs feature and metrics-server deployment complete guide
  docs/setup/keadm.md
Labels: approved, kind/documentation, lgtm, size/L

#2135 fix/keadm: checksum validation of the downloaded file every time
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/bug, lgtm, size/L

#2033 cloudhub: put all module name and module group in one place
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudstream/cloudstream.go
  cloud/pkg/common/modules/modules.go
  cloud/pkg/devicecontroller/constants/default.go
  cloud/pkg/devicecontroller/constants/service.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/devicecontroller.go
  cloud/pkg/edgecontroller/constants/service.go
  cloud/pkg/edgecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/edgecontroller.go
  cloud/pkg/synccontroller/const.go
  cloud/pkg/synccontroller/objectsync.go
  cloud/pkg/synccontroller/synccontroller.go
Labels: approved, kind/cleanup, lgtm, size/L

#2149 Keadm: support arm/arm64 for CentOS
  keadm/cmd/keadm/app/cmd/util/centosinstaller.go
Labels: approved, kind/feature, lgtm, size/XS

#2093 Add the build option to make the binaries debuggable
  Makefile
  hack/lib/golang.sh
Labels: approved, kind/feature, lgtm, size/S

#2151 Edge: add metamanager test
  edge/pkg/metamanager/metamanager_test.go
Labels: approved, lgtm, size/M

#1721 Lint: enable errcheck linter
  .golangci.yml
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/apis/devices/v1alpha2/device_instance_types.go
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  cloud/pkg/cloudhub/servers/udsserver/server.go
  cloud/pkg/cloudstream/tunnelserver.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/devicecontroller.go
  cloud/pkg/edgecontroller/edgecontroller.go
  edgemesh/pkg/dns/dns.go
  edgemesh/pkg/listener/listener.go
  edgemesh/pkg/plugin/plugin.go
  edgemesh/pkg/protocol/http/http.go
  edgemesh/pkg/proxy/proxy.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
  keadm/cmd/keadm/app/keadm.go
  mappers/bluetooth_mapper/watcher/watcher.go
  tests/e2e/mapper/bluetooth/bluetooth_suite_test.go
  tests/e2e/utils/common.go
  tests/performance/common/common.go
  tests/stubs/cloud/controllerstub/module.go
  tests/stubs/cloud/controllerstub/podmanager.go
  tests/stubs/devices/mockserver.go
  tests/stubs/edge/handlerstub/module.go
Labels: approved, lgtm, size/L

#2158 Docs: update the way to aviod kube-proxy
  docs/setup/keadm.md
Labels: approved, lgtm

#2166 fix change log links
  CHANGELOG.md
Labels: approved, kind/bug, lgtm, size/S

#2165 add CNCF incubation announcement in README
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#2173 docs/troubleshooting.md: update release version
  docs/troubleshooting.md
Labels: approved, kind/documentation, lgtm, size/S

#2169 Stop to output the detail of licenses diff
  hack/verify-vendor-licenses.sh
Labels: approved, lgtm, size/XS

#2174 documentation：Solve modubs_mapper configuration error
  mappers/modbus_mapper/dpl/deviceProfile.json
Labels: approved, lgtm, size/S

#2178 Docs: add OWNERS file
  docs/OWNERS
Labels: approved, lgtm, size/XS

#2187 Replace `Kubeedge` with `KubeEdge`
  CHANGELOG/CHANGELOG-before-1.0.md
  docs/components/kubeedge.md
  docs/proposals/cloudcore-ha-design.md
  docs/proposals/keadm-scope.md
  edge/test/README.md
  edge/test/integration/docs/README.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/S

#1954 enable logs feature in hack/local-up-kubeedge script
  hack/local-up-kubeedge.sh
Labels: approved, kind/feature, lgtm, size/M

#2192 Docs: fix typos
  docs/index.rst
  docs/setup/local.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#2189 Update CI job description
  .travis.yml
Labels: approved, kind/test, lgtm, size/XS

#2197 Update build.md - Path for make
  docs/setup/build.md
Labels: approved, lgtm, size/XS

#2200 Fix no rnd error
  hack/local-up-kubeedge.sh
Labels: approved, lgtm, size/XS

#2194 CI: use `install: skip` instead of `install: true`
  .travis.yml
Labels: approved, kind/test, lgtm, size/XS

#2203 README: add getting start link
  README.md
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/XS

#2164 Add question issue template
  .github/ISSUE_TEMPLATE/question.md
Labels: approved, lgtm, size/M

#2209 documentation: typo issue.
  docs/components/mappers/modbus_mapper.md
Labels: approved, lgtm, size/XS

#2020 edgecore support not specifying ip address
  cloud/pkg/cloudstream/tunnelserver.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation.go
Labels: approved, kind/feature, lgtm, size/XS

#2204 Docs: fix dead link
  docs/setup/keadm.md
Labels: approved, kind/documentation, lgtm, size/XS

#2205 Docs: fix typos
  docs/components/cloud/device_controller.md
  docs/proposals/device-crd.md
Labels: approved, kind/documentation, lgtm, size/XS

#2199 Docs: fix grammar issues
  docs/components/edge/edged.md
  docs/components/kubeedge.md
  docs/contributing/memfootprint-test-setup.md
  docs/governance.md
  docs/setup/upgrade.md
Labels: approved, do-not-merge/hold, kind/documentation, lgtm, size/M

#2202 Keadm: add command line option crgoupdriver for subcommand join
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, kind/feature, lgtm, size/S

#2163 Update github bug issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, lgtm, size/L

#2193 CI: enable go module cache
  .travis.yml
Labels: approved, kind/test, lgtm, size/XS

#2212 Fix gosimple issue
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: approved, lgtm, size/S

#1890 Docs: simplify build doc
  docs/setup/build.md
Labels: approved, kind/documentation, lgtm, size/M

#2218 cleanup dup codes
  edge/pkg/edged/edged_status.go
Labels: approved, kind/cleanup, lgtm, size/S

#2219 edge/pkg/edged: fix dropped error
  edge/pkg/edged/edged.go
Labels: approved, lgtm, size/XS
