Repository kubeedge/kubeedge, pull requests merged in 2020-05, with the labels that each got.

#1626 enforce repo-wide gofmt and go vet checking
  edgemesh/pkg/plugin/registry/registry.go
  edgemesh/pkg/proxy/proxy.go
  hack/lib/lint.sh
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  tests/e2e/mapper/bluetooth/bluetooth_test.go
  tests/stubs/cloud/controllerstub/module.go
  tests/stubs/cloud/controllerstub/upstream.go
  tests/stubs/edge/handlerstub/message.go
  tests/stubs/edge/handlerstub/module.go
Labels: approved, kind/cleanup, lgtm, size/M

#1633 documentation: improved readability
  docs/setup/kubeedge_install_keadm.md
Labels: approved, kind/documentation, lgtm, size/S

#1604 Intialize community governance model.
  governance.md
Labels: approved, kind/documentation, lgtm, size/M

#1640 change the token separator space to dot
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  edge/pkg/edgehub/process.go
Labels: approved, kind/bug, lgtm, size/S

#1628 keadm: fix get version issue
  keadm/cmd/keadm/app/cmd/cloud/init.go
Labels: approved, lgtm, size/XS

#1645 log errors in function NewCloudCoreCertDERandKey
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  common/constants/default.go
Labels: approved, kind/bug, lgtm, size/M

#1636 lint: add spell check
  .golangci.yml
  CHANGELOG-1.1.md
  CONTRIBUTING.md
  Makefile
  cloud/pkg/admissioncontroller/admit_devicemodel.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/cloudstream/connection.go
  docs/mappers/modbus_mapper.md
  docs/modules/cloud/controller.md
  docs/modules/edge/edged.md
  docs/modules/edgesite.md
  docs/proposals/EdgeSite.md
  docs/proposals/cri.md
  docs/proposals/csi.md
  docs/proposals/edgemesh-design.md
  docs/proposals/keadm-scope.md
  docs/proposals/perf.md
  docs/setup/kubeedge_precheck.md
  docs/setup/kubeedge_run.md
  docs/troubleshooting/troubleshooting.md
  edgemesh/tools/initContainer/script/edgemesh-iptables.sh
  hack/lib/lint.sh
  keadm/cmd/keadm/app/cmd/edge/join.go
  mappers/modbus_mapper/src/index.js
  staging/src/github.com/kubeedge/viaduct/pkg/server/server.go
  tests/e2e/deployment/deployment_suite_test.go
  tests/e2e/deployment/deployment_test.go
  tests/e2e/deployment/device_crd_test.go
  tests/e2e/edgesite/edgesite_suite_test.go
  tests/e2e/edgesite/edgesite_test.go
  tests/e2e/keadm/keadm_test.go
  tests/e2e/mapper/bluetooth/bluetooth_suite_test.go
  tests/e2e/mapper/bluetooth/bluetooth_test.go
  tests/e2e/utils/pod.go
  tests/performance/common/common.go
  tests/performance/hubtest/hubtest_test.go
  tests/performance/loadtest/loadtest_suite_test.go
  tests/performance/loadtest/loadtest_test.go
  tests/performance/nodedensity/nodedensity_suite_test.go
  tests/performance/scripts/build_upload_image.sh
Labels: approved, kind/api-change, kind/cleanup, lgtm, size/L

#1443 add edgenode authentication proposal
  docs/images/edgeAuthentication/authentication-flow.png
  docs/images/edgeAuthentication/token.png
  docs/proposals/edge-authentication.md
Labels: approved, kind/design, lgtm, size/L

#1649 Polish the guide on the lightweight runtime configuration
  docs/setup/kubeedge_cri_configure.md
Labels: approved, kind/documentation, lgtm, size/S

#1652 update generate certificates docs
  docs/setup/kubeedge_install_source.md
Labels: approved, kind/documentation, lgtm, size/XS

#1651 fix bug that load cert from local dir
  cloud/pkg/cloudhub/config/config.go
Labels: approved, kind/bug, lgtm, size/M

#1643 add advitise address in cloudcore
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
Labels: approved, kind/feature, lgtm, size/M

#1646 Remove gen-certs in local-up script
  hack/local-up-kubeedge.sh
Labels: approved, kind/cleanup, lgtm, size/XS

#1655 add env status.hostIP for pods
  edge/pkg/edged/edged_pods.go
Labels: approved, lgtm, size/XS

#1650 Improve retransmission logic in leaderelection
  cloud/pkg/leaderelection/leaderelection.go
Labels: approved, lgtm, size/S

#1656 update the doc kubeedge_configure
  docs/setup/kubeedge_configure.md
Labels: approved, kind/documentation, lgtm, size/M

#1667 Run fmt on all files
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_factory.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/factory_test.go
  staging/src/github.com/kubeedge/viaduct/pkg/lane/lane_test.go
  staging/src/github.com/kubeedge/viaduct/pkg/lane/quic_test.go
  staging/src/github.com/kubeedge/viaduct/pkg/packer/package_test.go
  staging/src/github.com/kubeedge/viaduct/pkg/packer/packer_test.go
  staging/src/github.com/kubeedge/viaduct/pkg/packer/reader_test.go
  staging/src/github.com/kubeedge/viaduct/pkg/packer/version_test.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1661 Modify logs for node reconnect
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1666 Add tips to clean up certificates in secret
  docs/setup/kubeedge_install_source.md
Labels: approved, kind/documentation, lgtm, size/XS

#1569 Add proposal For CloudCore HA
  docs/images/cloudcore-ha-design/HotStandby.png
  docs/proposals/cloudcore-ha-design.md
Labels: approved, kind/design, lgtm, size/L

#1672 Automated cherry pick of #1640: change the token separator space to dot
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  edge/pkg/edgehub/process.go
Labels: approved, lgtm, size/S

#1673 Automated cherry pick of #1643: add advitise address in cloudcore
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
Labels: approved, lgtm, size/M

#1674 Automated cherry pick of #1645: log errors in function NewCloudCoreCertDERandKey
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  common/constants/default.go
Labels: approved, lgtm, size/M

#1675 Automated cherry pick of #1651: fix a bug about loading certificates from local dir
  cloud/pkg/cloudhub/config/config.go
Labels: approved, lgtm, size/M

#1676 Automated cherry pick of #1652: update generate certificates docs
  docs/setup/kubeedge_install_source.md
Labels: approved, lgtm, size/XS

#1677 Automated cherry pick of #1655: add env status.hostIP for pods
  edge/pkg/edged/edged_pods.go
Labels: approved, lgtm, size/XS

#1671 Automated cherry pick of #1628: keadm: fix get version issue
  keadm/cmd/keadm/app/cmd/cloud/init.go
Labels: approved, lgtm, size/XS

#1678 Automated cherry pick of #1656: update the doc kubeedge_configure
  docs/setup/kubeedge_configure.md
Labels: approved, lgtm, size/M

#1679 Automated cherry pick of #1661: modify logs for node reconnect
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: approved, lgtm, size/XS

#1680 Automated cherry pick of #1666: Add tips to clean up certificates in secret
  docs/setup/kubeedge_install_source.md
Labels: approved, lgtm, size/XS

#1682 change tunnel port from 10002 to 10004
  common/constants/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
Labels: approved, kind/feature, lgtm, size/XS

#1684 Automated cherry pick of #1682: change tunnel port from 10002 to 10004
  common/constants/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
Labels: approved, lgtm, size/XS

#1685 Add KubeEdge v1.3 Release note
  CHANGELOG-1.0.md
  CHANGELOG-1.1.md
  CHANGELOG-1.2.md
  CHANGELOG-1.3.md
Labels: approved, kind/documentation, lgtm, size/L

#1686 update v1.3 changelog, add download links
  CHANGELOG-1.3.md
Labels: approved, kind/documentation, lgtm, size/S

#1683 use net.JoinHostPort to assemble URL
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  tests/performance/loadtest/loadtest_suite_test.go
  tests/performance/nodedensity/nodedensity_suite_test.go
Labels: approved, kind/cleanup, lgtm, size/M

#1695 Update authors list
  CHANGELOG-1.3.md
Labels: approved, kind/documentation, lgtm, size/XS

#1710 Update : misspell change to 'namespace'
  docs/proposals/reliable-message-delivery.md
Labels: approved, kind/documentation, lgtm, size/XS

#1701 update keadm to support KubeEdge 1.3
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cmd.go
  keadm/cmd/keadm/app/cmd/common/config.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  tests/e2e/scripts/keadm_e2e.sh
Labels: approved, lgtm, size/L

#1702 support both RSA and DSA certificates
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/server.go
Labels: approved, kind/bug, lgtm, size/XS

#1705 Improved automatic certificate generation log and fix bugs
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  edge/pkg/edgehub/common/certutil/certutil.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgehub/process.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/L

#1703 Update roadmap for 2020 Q2
  README.md
  README_zh.md
  docs/getting-started/roadmap.md
  docs/getting-started/roadmap_zh.md
Labels: approved, kind/documentation, lgtm, size/M

#1713 Automated cherry pick of #1701: update keadm
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cmd.go
  keadm/cmd/keadm/app/cmd/common/config.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  tests/e2e/scripts/keadm_e2e.sh
Labels: approved, lgtm, size/L

#1715 Add 1.3 to compatibility chart
  README.md
  docs/setup/develop_kubeedge.md
Labels: approved, kind/documentation, lgtm, size/XS

#1719 Update docs for keadm 1.3
  CHANGELOG-1.3.md
  docs/setup/kubeedge_install_keadm.md
Labels: approved, kind/documentation, lgtm, size/M

#1709 fix E2E_UPDATE_DEVICE_3 failure
  tests/e2e/deployment/device_crd_test.go
Labels: approved, kind/bug, lgtm, size/S

#1724 Lint: enable govet linter
  .golangci.yml
  hack/lib/lint.sh
Labels: approved, lgtm, size/XS

#1708 fix using same namespace while syncPodStatus
  edge/pkg/metamanager/process.go
Labels: approved, lgtm, size/S

#1723 Lint: enable gosimple linter
  .golangci.yml
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/leaderelection/leaderelection.go
  edge/cmd/edgecore/app/server.go
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/devicetwin/process.go
  edge/pkg/edged/edged_status.go
  edge/pkg/edged/status/status_manager.go
  edge/pkg/edged/volume/csi/csi_mounter.go
  edge/pkg/edged/volume/csi/nodeinfomanager/nodeinfomanager.go
  edge/test/integration/utils/common/log.go
  edge/test/integration/utils/helpers/helpers.go
  edge/test/test.go
  edgemesh/pkg/dns/dns.go
  edgemesh/pkg/listener/listener.go
  edgemesh/pkg/protocol/http/http.go
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/common.go
  tests/e2e/mapper/bluetooth/bluetooth_suite_test.go
  tests/e2e/utils/common.go
  tests/e2e/utils/context.go
  tests/e2e/utils/log.go
  tests/e2e/utils/node.go
  tests/performance/common/common.go
  tests/stubs/cloud/controllerstub/podmanager.go
  tests/stubs/devices/mockserver.go
  tests/stubs/example/main.go
Labels: approved, lgtm, size/L

#1730 Lint: remove useless val
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/volume/csi/csi_controller.go
  edge/pkg/edged/volume/csi/csi_plugin.go
  edge/pkg/edged/volume/csi/csi_util.go
  edge/pkg/edgehub/common/certutil/certutil.go
  edge/pkg/edgehub/config/config.go
  edge/pkg/eventbus/config/config.go
  edge/pkg/metamanager/config/config.go
  edge/test/cloudhub/stub.go
  edge/test/test.go
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  tests/e2e/utils/config.go
Labels: approved, kind/cleanup, lgtm, size/M

#1720 Lint: enable goconst linter
  .golangci.yml
  edge/pkg/devicetwin/dtmanager/twin.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/eventbus/mqtt/client.go
  edge/test/test.go
  tests/e2e/deployment/device_crd_test.go
  tests/e2e/mapper/bluetooth/bluetooth_test.go
  tests/e2e/utils/common.go
Labels: approved, kind/cleanup, lgtm, size/L

#1734 add raisecom technology and China telecom research institute to adopters
  ADOPTERS.md
  docs/adopters/raisecom-technology.png
Labels: approved, kind/documentation, lgtm, size/S

#1739 Auto detect pause image
  common/constants/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  pkg/util/util.go
Labels: approved, lgtm, size/M

#1647 optimize e2e test
  .travis.yml
  hack/local-up-kubeedge.sh
  tests/e2e/deployment/deployment_suite_test.go
  tests/e2e/scripts/cleanup.sh
  tests/e2e/scripts/execute.sh
Labels: approved, lgtm, size/L

#1663 Expose electionChecker to a http server
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: approved, kind/feature, lgtm, size/S

#1747 Automated cherry pick of #1663: expose checker
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: approved, lgtm, size/S

#1753 add kubesphere in ADOPTER.md
  ADOPTERS.md
  docs/adopters/kubesphere-logo.png
Labels: approved, kind/documentation, lgtm, size/S

#1755 Automated cherry pick of #1709: fix E2E_UPDATE_DEVICE_3 failure
  tests/e2e/deployment/device_crd_test.go
Labels: approved, lgtm, size/S

#1748 Automated cherry pick of #1702: configure tls use ECDSA cipher
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/server.go
Labels: approved, lgtm, size/XS

#1749 Automated cherry pick of #1705: Improve certsfunction
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  edge/pkg/edgehub/common/certutil/certutil.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgehub/process.go
Labels: approved, lgtm, size/L

#1750 Automated cherry pick of #1708: fix using same namespace while sync podstatus to cloud
  edge/pkg/metamanager/process.go
Labels: approved, lgtm, size/S

#1751 docs/mappers: update docs path
  docs/mappers/bluetooth_mapper.md
  docs/mappers/modbus_mapper.md
Labels: approved, kind/documentation, lgtm, size/L

#1754 Update adopter for adding space between logo
  ADOPTERS.md
Labels: approved, kind/documentation, lgtm, size/XS

#1757 fix edgemesh caching serviceList bug
  edgemesh/pkg/listener/listener.go
  edgemesh/pkg/listener/listener_test.go
Labels: approved, lgtm, size/M

#1725 Fix TC_TEST_EBUS_6 failed to run in arm machine issue
  edge/test/integration/device/device_test.go
Labels: approved, kind/bug, lgtm, size/XS

#1681 add stale bot
  .github/stale.yml
Labels: approved, kind/cleanup, lgtm, size/M

#1697 fix kubectl logs cert after V1.3
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudstream/cloudstream.go
  cloud/pkg/cloudstream/tunnelserver.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgestream/edgestream.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation.go
Labels: approved, kind/bug, lgtm, size/L

#1759 Automated cherry pick of #1757: fix edgemesh caching serviceList bug
  edgemesh/pkg/listener/listener.go
  edgemesh/pkg/listener/listener_test.go
Labels: approved, lgtm, size/M

#1760 Automated cherry pick of #1697: fix kubectl logs certs
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudstream/cloudstream.go
  cloud/pkg/cloudstream/tunnelserver.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgestream/edgestream.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation.go
Labels: approved, lgtm, size/L
