Repository kubeedge/kubeedge, pull requests merged in 2020-03, with the labels that each got.

#1521 Sort documents by users and developers
  README.md
  docs/index.rst
  docs/setup/develop_kubeedge.md
  docs/setup/kubeedge_install_keadm.md
  docs/setup/kubeedge_precheck.md
  docs/setup/requirements.md
  keadm/README.md
Labels: approved, kind/documentation, lgtm, size/M

#1518 edgecore: support configmap environment variable
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/fake/typed/core/v1/fake_configmap.go
  edge/pkg/edged/fake/typed/core/v1/fake_core_client.go
Labels: approved, lgtm, size/M

#1526 Move golang dependency to developer guide
  README.md
  docs/setup/develop_kubeedge.md
  docs/setup/kubeedge_install_keadm.md
Labels: approved, lgtm, size/S

#1524 updated yamls for cloudcore incluster deployment
  build/cloud/03-clusterrole.yaml
  build/cloud/05-configmap.yaml
  build/cloud/07-deployment.yaml
  build/cloud/08-service.yaml.example
  build/cloud/Dockerfile
Labels: approved, kind/cleanup, lgtm, size/L

#1527 Refactor the readme
  README.md
Labels: approved, kind/documentation, lgtm, size/M

#1519 add util func can print by line.
  cloud/cmd/cloudcore/app/server.go
  edge/cmd/edgecore/app/server.go
  edgesite/cmd/edgesite/app/server.go
  keadm/cmd/keadm/keadm.go
  pkg/util/uitl_test.go
  pkg/util/util.go
Labels: approved, lgtm, size/M

#1523 Fix sourcecode install guide for new version of kubeedge
  docs/getting-started/contribute.md
  docs/getting-started/getting-started.md
  docs/setup/deploy-edge-node.md
  docs/setup/develop_kubeedge.md
  docs/setup/installer_setup.md
  docs/setup/kubeedge_configure.md
  docs/setup/kubeedge_install_source.md
  docs/setup/kubeedge_run.md
  docs/setup/setup.md
Labels: approved, kind/documentation, lgtm, size/XXL

#1532 Small change to the pic in readme
  README.md
  docs/images/KubeEdge_arch.svg
  docs/images/KubeEdge_arch.vsdx
  docs/images/kubeedge_arch.png
Labels: approved, kind/documentation, lgtm, size/XXL

#1533 Fix --version issue in compoment container images
  Makefile
  build/admission/Dockerfile
  build/cloud/Dockerfile
  build/csidriver/Dockerfile
  build/edge/Dockerfile
  build/edgesite/Dockerfile
  hack/make-rules/version.sh
Labels: approved, kind/bug, lgtm, size/M

#1537 removed unnecessary space character
  docs/setup/kubeedge_install_keadm.md
Labels: approved, lgtm, size/XS

#1540 Use bionic in travis CI
  .travis.yml
Labels: approved, kind/test, lgtm, size/XS

#1535 Move componentconfig related apis to componentconfig dir
  cloud/cmd/cloudcore/app/options/options.go
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/devicecontroller/config/config.go
  cloud/pkg/devicecontroller/devicecontroller.go
  cloud/pkg/edgecontroller/config/config.go
  cloud/pkg/edgecontroller/edgecontroller.go
  cloud/pkg/synccontroller/config/config.go
  cloud/pkg/synccontroller/synccontroller.go
  docs/proposals/configuration.md
  edge/cmd/edgecore/app/options/options.go
  edge/cmd/edgecore/app/server.go
  edge/pkg/devicetwin/config/config.go
  edge/pkg/devicetwin/devicetwin.go
  edge/pkg/edged/config/config.go
  edge/pkg/edged/edged.go
  edge/pkg/edgehub/config/config.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/eventbus/config/config.go
  edge/pkg/eventbus/eventbus.go
  edge/pkg/metamanager/config/config.go
  edge/pkg/metamanager/metamanager.go
  edge/pkg/servicebus/servicebus.go
  edge/test/integration/utils/test_setup.go
  edge/test/test.go
  edgemesh/pkg/config/config.go
  edgemesh/pkg/module.go
  edgesite/cmd/edgesite/app/options/options.go
  edgesite/cmd/edgesite/app/server.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/helper.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/register.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/helper.go
  pkg/apis/componentconfig/edgecore/v1alpha1/register.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  pkg/apis/componentconfig/edgesite/v1alpha1/helper.go
  pkg/apis/componentconfig/edgesite/v1alpha1/register.go
  pkg/apis/componentconfig/edgesite/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/validation/validation.go
  pkg/apis/componentconfig/meta/v1alpha1/types.go
  tests/e2e/utils/test_setup.go
Labels: approved, kind/cleanup, lgtm, size/L

#1536 keadm Support centos
  keadm/cmd/keadm/app/cmd/util/centosinstaller.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  keadm/cmd/keadm/app/cmd/util/ubuntuinstaller.go
Labels: approved, lgtm, size/XL

#1542 Avoiding panic in keadm
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/edge/join.go
Labels: approved, kind/bug, lgtm, size/XS

#1548 Fix typo of the topic suffix for device updated event
  edge/pkg/devicetwin/process.go
Labels: approved, lgtm, size/XS

#1547 fix issue minor version of full managed k8s instances
  hack/lib/golang.sh
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: approved, kind/bug, lgtm, size/M

#1550 Update docs in keadm installation for centos support
  docs/setup/kubeedge_install_keadm.md
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation.go
Labels: approved, kind/documentation, lgtm, size/S

#1552 Fix panic in cloudcore
  cloud/pkg/synccontroller/objectsync.go
Labels: approved, kind/bug, lgtm, size/M

#1555 [keadm/cmd] change 'The Kubeedge Authors' to 'The KubeEdge Authors'
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cmd.go
  keadm/cmd/keadm/app/cmd/common/config.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/centosinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  keadm/cmd/keadm/app/cmd/util/mqttinstaller.go
  keadm/cmd/keadm/app/cmd/util/ubuntuinstaller.go
  keadm/cmd/keadm/app/keadm.go
  keadm/cmd/keadm/keadm.go
Labels: approved, lgtm, size/M

#1538 clarifies location of keadm compiled binary
  docs/setup/kubeedge_install_keadm.md
Labels: approved, kind/documentation, lgtm, size/XS

#1558 Add retry times in keadm for get latest release, if it's still failed, use default version
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, lgtm, size/M

#1557 fix message handleserver close channel panic
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: approved, kind/bug, lgtm, size/XS

#1567 Fix the broken link
  docs/setup/develop_kubeedge.md
Labels: approved, kind/cleanup, lgtm, size/XS
