Repository kubeedge/kubeedge, pull requests merged in 2020-11, with the labels that each got.

#2292 Bump the kind to latest version
  .travis.yml
  hack/lib/install.sh
Labels: approved, kind/test, lgtm, size/XS

#2182 fix bug: cloud send twin_update confirm message to edge
  cloud/pkg/devicecontroller/constants/service.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/messagelayer/util.go
Labels: approved, kind/bug, lgtm, size/M

#2296 Docs: fix typo
  docs/contributing/edgemesh_guide.md
Labels: approved, lgtm, size/XS

#2294 edge/cmd/edgecore/app/server.go: fix a typo
  edge/cmd/edgecore/app/server.go
Labels: approved, lgtm, size/XS

#2147 Mapper proposal
  docs/images/mapper/components.PNG
  docs/images/mapper/message.PNG
  docs/images/mapper/routine.PNG
  docs/proposals/mapper-design-v2.md
Labels: approved, size/L

#2293 Update K8s version in node status and related docs
  README.md
  README_zh.md
  common/constants/default.go
Labels: approved, kind/documentation, lgtm, size/S

#2304 fix cloudhub api /readyz panic
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: approved, lgtm, size/XS

#2305 Automated cherry pick of #2304: cloudhub: fix /readyz panic
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: approved, lgtm, size/XS

#2298 Add type param annotation for cloudcore and edgecore
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: approved, kind/feature, lgtm, size/S

#2170 fix reDownload serviceFile
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: approved, kind/bug, lgtm, size/L

#2302 modify one log of eventbus
  edge/pkg/eventbus/mqtt/client.go
Labels: approved, kind/feature, lgtm, size/XS

#2311 Automated cherry pick of #2170: fix re-dowload bug when use keadm
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: approved, lgtm, size/L

#2310 remove some unused code of edge part
  edge/pkg/devicetwin/dtcommon/util.go
  edge/pkg/devicetwin/dtcontext/dtcontext.go
  edge/pkg/edged/apis/types.go
  edge/pkg/edged/config/config.go
  edge/pkg/edgehub/clients/factory.go
  edge/pkg/metamanager/dao/meta.go
Labels: approved, kind/cleanup, lgtm, size/M

#2303 Docs: fix grammar issues
  build/cloud/README.md
  docs/components/beehive.md
  docs/components/cloud/cloudhub.md
  docs/components/edge/devicetwin.md
  docs/components/edge/edged.md
  docs/components/edge/edgehub.md
  docs/components/edgesite.md
  docs/components/mappers/bluetooth_mapper.md
  docs/components/mappers/modbus_mapper.md
  docs/configuration/cri.md
  docs/configuration/kubeedge.md
  tests/stubs/edge/handlerstub/podmanager.go
Labels: kind/documentation, size/M

#2312 Change `/isCloudcoreReady` to `/readyz`
  docs/proposals/cloudcore-ha-design.md
Labels: approved, kind/documentation, lgtm, size/XS

#2313 reorganize constant file
  common/constants/default.go
Labels: approved, kind/cleanup, lgtm, size/M

#1998 Keadm: add prompting for confirmation
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/reset.go
Labels: approved, kind/feature, lgtm, size/S

#2318 Bugfix:less verbose edge message output
  edge/pkg/edgehub/process.go
Labels: approved, kind/bug, lgtm, size/XS

#2320 Print less verbose message received from cloud-hub
  edge/pkg/edgehub/process.go
Labels: approved, kind/bug, lgtm, size/XS

#1939 Add keadm-debug proposal
  docs/proposals/keadm-debug.md
Labels: approved, kind/design, kind/feature, lgtm, size/XL

#2325 Update cloudhub.md
  docs/components/cloud/cloudhub.md
Labels: approved, lgtm, size/XS

#2322 Add changelog for v1.5
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/README.md
Labels: approved, kind/documentation, lgtm, size/M

#2326 Update device_controller.md
  docs/components/cloud/device_controller.md
Labels: approved, lgtm, size/XS

#2329 change the EventId of GetDetailNode struct in deviectwin to uuid
  edge/pkg/devicetwin/dtmanager/communicate.go
Labels: approved, kind/feature, lgtm, size/XS

#2317 support devices, mounts and env fields for extented resources requeired by container
  edge/pkg/edged/edged_pods.go
Labels: approved, kind/bug, lgtm, size/XS

#2332 edgehub.md: adding links to beehive
  docs/components/edge/edgehub.md
Labels: approved, lgtm, size/XS

#2335 reorganize edge module name into one file
  common/constants/default.go
  edge/pkg/common/modules/group.go
  edge/pkg/common/modules/names.go
  edge/pkg/devicetwin/devicetwin.go
  edge/pkg/edgestream/edgestream.go
  edge/pkg/eventbus/eventbus.go
  edge/pkg/servicebus/servicebus.go
Labels: approved, kind/feature, lgtm, size/M

#2336 metamanager remote query timeout configurable
  common/constants/default.go
  edge/pkg/metamanager/process.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
Labels: approved, kind/feature, lgtm, size/XS

#2338 move func addDeviceCrds to apis/devices/v1alpha2/register.go
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/apis/devices/v1alpha2/register.go
Labels: approved, kind/feature, lgtm, size/S

#2340 Quic client capture error information
  edge/pkg/edgehub/clients/quicclient/quicclient.go
Labels: approved, kind/feature, lgtm, size/XS

#2341 fix err information of certutil
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
Labels: approved, kind/feature, lgtm, size/XS

#2334 CI: switch amd64 tests to Github Action
  .github/workflows/main.yaml
  .travis.yml
  Makefile
  edge/hack/clean.sh
  edge/hack/install_docker_for_raspbian.sh
  edge/hack/setup_for_IEF.sh
  hack/lib/golang.sh
  hack/lib/init.sh
  hack/lib/install.sh
  hack/lib/lint.sh
  hack/lib/mapper.sh
  hack/lib/util.sh
  hack/setup-vmruntime.sh
  mappers/modbus_mapper/scripts/start_modbusmapper.sh
  tests/e2e/scripts/bluetoothconfig.sh
Labels: approved, kind/test, lgtm, size/L

#2354 test: cleanup temp dir for TestPrivateDownloadServiceFile
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: approved, lgtm, size/XS

#2348 CI: enable gci linter
  .github/workflows/main.yaml
  .golangci.yml
  cloud/pkg/cloudstream/apiserverconnection.go
  cloud/pkg/cloudstream/containerexec_connection.go
  cloud/pkg/cloudstream/containerlog_connection.go
  cloud/pkg/cloudstream/containermetrics_connection.go
  cloud/pkg/cloudstream/session.go
  cloud/pkg/cloudstream/tunnelserver.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/leaderelection/leaderelection.go
  cloud/test/integration/fixtures/devicemodel.go
  edge/cmd/edgecore/app/server.go
  edge/mocks/beego/fake_rawseter.go
  edge/mocks/edgehub/fake_adapter.go
  edge/pkg/devicetwin/dtclient/devicetwin_db_test.go
  edge/pkg/edged/edged_getters.go
  edge/pkg/edged/fake/typed/core/v1/fake_configmap.go
  edge/pkg/edged/fake/typed/core/v1/fake_persistentvolume.go
  edge/pkg/edged/fake/typed/core/v1/fake_persistentvolumeclaim.go
  edge/pkg/edged/fake/typed/storage/v1/fake_volumeattachment.go
  edge/pkg/edgehub/common/certutil/certfile.go
  edge/pkg/metamanager/client/listener.go
  edge/pkg/metamanager/client/nodestatus.go
  edge/pkg/metamanager/client/podstatus.go
  edge/pkg/metamanager/client/service.go
  edge/pkg/metamanager/metamanager_test.go
  edge/test/integration/appdeployment/application_suite_test.go
  edgemesh/cmd/edgemesh.go
  edgemesh/pkg/listener/listener.go
  edgemesh/pkg/module.go
  pkg/stream/edgedexecconnection.go
  pkg/version/verflag/verflag.go
Labels: approved, lgtm, size/L

#2352 fix the wrong TestStart in metamanager_test.go
  edge/pkg/metamanager/metamanager_test.go
Labels: approved, kind/feature, lgtm, size/XS

#2343 edge/pkg/edgehub: fix grammar issues
  edge/mocks/edgehub/fake_adapter.go
  edge/pkg/edgehub/certificate/certmanager.go
  edge/pkg/edgehub/clients/adapter.go
  edge/pkg/edgehub/clients/quicclient/quicclient.go
  edge/pkg/edgehub/clients/wsclient/websocket.go
  edge/pkg/edgehub/common/http/http.go
  edge/pkg/edgehub/common/http/http_test.go
  edge/pkg/edgehub/edgehub.go
Labels: approved, kind/feature, lgtm, size/M

#2347 cloud/pkg/cloudhub: optimize IsFromEdge method
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/common/model/types_test.go
Labels: approved, kind/feature, lgtm, size/M

#2355 Unify use google uuid library
  LICENSES/vendor/github.com/pborman/uuid/LICENSE
  cloud/pkg/csidriver/controllerserver.go
  cloud/pkg/devicecontroller/controller/downstream.go
  edge/pkg/devicetwin/dttype/types.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
  edge/pkg/devicetwin/dttype/types_test.go
  external-dependency.md
  go.mod
  go.sum
  vendor/github.com/pborman/uuid/.travis.yml
  vendor/github.com/pborman/uuid/CONTRIBUTING.md
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/README.md
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/go.mod
  vendor/github.com/pborman/uuid/go.sum
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#2360 fix a bug of device update
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, lgtm, size/S

#2331 fix the wrong Servicebus group name
  edge/pkg/servicebus/servicebus.go
Labels: approved, kind/feature, lgtm, size/XS

#2366 Fixed bug during node creation in edgesite
  edge/pkg/edged/edged_status.go
Labels: approved, kind/bug, lgtm, size/XS

#1935 Keadm: optimize command exec logic
  keadm/cmd/keadm/app/cmd/util/centosinstaller.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/exec.go
  keadm/cmd/keadm/app/cmd/util/exec_test.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  keadm/cmd/keadm/app/cmd/util/ubuntuinstaller.go
  tests/e2e/scripts/keadm_e2e.sh
Labels: approved, kind/cleanup, lgtm, size/L

#2374 fixed bug: edgesite pods do not start
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
Labels: approved, kind/bug, lgtm, size/XS

#2373 fix resource version compare error
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: approved, kind/bug, lgtm, size/XS

#2376 Automated cherry pick of #2373: fix resource version compare error
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: approved, lgtm, size/XS
