Repository kubeedge/kubeedge, pull requests merged in 2021-08, with the labels that each got.

#2993 check the return value of dbm.DBAccess.Delete()
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go
Labels: approved, kind/bug, lgtm, size/XS

#2995 fix start local cluster cloudStream and edgeStream disabled
  hack/local-up-kubeedge.sh
Labels: approved, kind/bug, lgtm, size/XS

#2999 Add iptables manager for tunnel port
  cloud/cmd/cloudcore/app/options/options.go
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudstream/iptables/iptables.go
  hack/local-up-kubeedge.sh
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
Labels: kind/feature, lgtm, approved, size/L

#2997 edgecore: add the validation of nodename
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation.go
Labels: kind/feature, lgtm, approved, size/XS

#3021 support k8s v1.21.X
  .github/workflows/main.yaml
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edged/volume_host.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/serviceaccount.go
  edge/pkg/metamanager/process.go
  hack/lib/install.sh
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: kind/feature, lgtm, approved, size/L

#3027 Automated cherry pick of #3021: support k8s v1.21.X
  .github/workflows/main.yaml
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edged/volume_host.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/serviceaccount.go
  edge/pkg/metamanager/process.go
  edgesite/README.md
  hack/lib/install.sh
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: lgtm, approved, size/L

#3032 Add release note for 1.7.2
  CHANGELOG/CHANGELOG-1.7.md
Labels: kind/documentation, size/S

#3024 use UpdateDeviceStatusWorkers as updateDeviceStatus routines
  cloud/pkg/devicecontroller/controller/upstream.go
Labels: kind/bug, lgtm, approved, size/XS

#3028 simplify the way of getting message []byte format
  edge/pkg/metamanager/client/configmap.go
  edge/pkg/metamanager/client/node.go
  edge/pkg/metamanager/client/persistentvolume.go
  edge/pkg/metamanager/client/persistentvolumeclaim.go
  edge/pkg/metamanager/client/secret.go
  edge/pkg/metamanager/client/serviceaccount.go
  edge/pkg/metamanager/client/volumeattachment.go
Labels: kind/cleanup, lgtm, approved, size/M

#3037 add unit test for edgecontroller rule manager and ruleendpoint manager
  cloud/pkg/edgecontroller/manager/rule_test.go
  cloud/pkg/edgecontroller/manager/ruleendpoint_test.go
Labels: kind/test, lgtm, approved, size/L

#3036 simplify the way to get content []byte format
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
  tests/stubs/cloud/controllerstub/upstream.go
  tests/stubs/edge/handlerstub/message.go
Labels: kind/cleanup, lgtm, approved, size/L

#3025 Handling node/*/membership/detail
  cloud/pkg/devicecontroller/constants/service.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/messagelayer/util.go
  cloud/pkg/devicecontroller/messagelayer/util_test.go
Labels: kind/bug, lgtm, approved, size/M

#2955 Solve the concurrent map write for metaserver handler.go
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
  edge/pkg/metamanager/metaserver/server.go
Labels: lgtm, approved, size/S

#3038 edgecore: add the validation of edgeCoreConfig
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
Labels: kind/feature, lgtm, approved, size/S

#3039 fix not correct format verb: %++v
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/edgestream/tunnel.go
Labels: kind/bug, lgtm, approved, size/XS

#2897 make synccontroller manageObject more clear
  cloud/pkg/synccontroller/objectsync.go
Labels: kind/cleanup, lgtm, approved, size/M

#3014 sync the response message unconditionally
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: kind/bug, approved, size/XS

#3044 Feature/edgeSite
  cloud/cmd/cloudcore/app/server.go
  edge/cmd/edgecore/app/server.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  pkg/util/util.go
Labels: kind/feature, size/M

#3049 Fixed modbus config parameters null value invalid
  cloud/pkg/apis/devices/v1alpha2/device_instance_types.go
  cloud/pkg/apis/devices/v1alpha2/zz_generated.deepcopy.go
  cloud/test/integration/fixtures/device.go
  docs/proposals/device-crd.md
  tests/e2e/utils/device.go
Labels: lgtm, approved, size/M

#2848 admission: fix pod toleration replace
  cloud/pkg/admissioncontroller/mutate_offlinemigration.go
Labels: kind/bug, lgtm, approved, size/M

#3072 fixed: remove redundant code in handler/messagehandler.go
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: kind/bug, lgtm, approved, size/XS

#3068 Support sendToGroup printing module name
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_channel.go
Labels: kind/feature, lgtm, approved, size/XS

#3010 fix target kubeletendpoint port in metrics request,the edgecore kubel…
  cloud/pkg/cloudstream/containermetrics_connection.go
Labels: kind/bug, lgtm, approved, size/XS

#3075 Automated cherry pick of #3010: fix target kubeletendpoint port in metrics request,the
  cloud/pkg/cloudstream/containermetrics_connection.go
Labels: lgtm, approved, size/XS

#3073 add reviewer
  OWNERS
Labels: lgtm, approved, size/XS

#3069 fixed format content in beehive/pkg/core/context/context_channel.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_channel.go
Labels: kind/bug, lgtm, approved, size/XS

#3083 Add ictnj to kubeedge adopter
  ADOPTERS.md
  docs/adopters/ictnj.png
Labels: lgtm, approved, size/XS

#3088 Add release note for release 1.8
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/README.md
Labels: kind/documentation, size/M
