Repository kubeedge/kubeedge, pull requests merged in 2021-01, with the labels that each got.

#2470 Keadm: optimize reset detect logic
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, lgtm, size/M

#2462 Keadm: use util/exec pkg to exec shell commands
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/debug/check.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, lgtm, size/L

#2466 edge: update websocket test
  edge/pkg/common/util/config.go
  edge/pkg/edgehub/clients/wsclient/websocket_test.go
Labels: approved, lgtm, size/L

#2487 Remove YEAR field in copyright for all codegen files
  cloud/hack/boilerplate/boilerplate.txt
  cloud/pkg/apis/devices/v1alpha2/zz_generated.deepcopy.go
  cloud/pkg/apis/reliablesyncs/v1alpha1/zz_generated.deepcopy.go
  cloud/pkg/client/clientset/versioned/clientset.go
  cloud/pkg/client/clientset/versioned/doc.go
  cloud/pkg/client/clientset/versioned/fake/clientset_generated.go
  cloud/pkg/client/clientset/versioned/fake/doc.go
  cloud/pkg/client/clientset/versioned/fake/register.go
  cloud/pkg/client/clientset/versioned/scheme/doc.go
  cloud/pkg/client/clientset/versioned/scheme/register.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/device.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/devicemodel.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/devices_client.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/doc.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/fake/doc.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/fake/fake_device.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/fake/fake_devicemodel.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/fake/fake_devices_client.go
  cloud/pkg/client/clientset/versioned/typed/devices/v1alpha2/generated_expansion.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/clusterobjectsync.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/doc.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/fake/doc.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/fake/fake_clusterobjectsync.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/fake/fake_objectsync.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/fake/fake_reliablesyncs_client.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/generated_expansion.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/objectsync.go
  cloud/pkg/client/clientset/versioned/typed/reliablesyncs/v1alpha1/reliablesyncs_client.go
  cloud/pkg/client/informers/externalversions/devices/interface.go
  cloud/pkg/client/informers/externalversions/devices/v1alpha2/device.go
  cloud/pkg/client/informers/externalversions/devices/v1alpha2/devicemodel.go
  cloud/pkg/client/informers/externalversions/devices/v1alpha2/interface.go
  cloud/pkg/client/informers/externalversions/factory.go
  cloud/pkg/client/informers/externalversions/generic.go
  cloud/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  cloud/pkg/client/informers/externalversions/reliablesyncs/interface.go
  cloud/pkg/client/informers/externalversions/reliablesyncs/v1alpha1/clusterobjectsync.go
  cloud/pkg/client/informers/externalversions/reliablesyncs/v1alpha1/interface.go
  cloud/pkg/client/informers/externalversions/reliablesyncs/v1alpha1/objectsync.go
  cloud/pkg/client/listers/devices/v1alpha2/device.go
  cloud/pkg/client/listers/devices/v1alpha2/devicemodel.go
  cloud/pkg/client/listers/devices/v1alpha2/expansion_generated.go
  cloud/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go
  cloud/pkg/client/listers/reliablesyncs/v1alpha1/expansion_generated.go
  cloud/pkg/client/listers/reliablesyncs/v1alpha1/objectsync.go
Labels: approved, kind/cleanup, lgtm, size/L

#2486 edgecontroller: improve test coverage
  cloud/pkg/edgecontroller/config/config_test.go
  cloud/pkg/edgecontroller/manager/common_test.go
  cloud/pkg/edgecontroller/manager/configmap_test.go
  cloud/pkg/edgecontroller/manager/endpoint_test.go
  cloud/pkg/edgecontroller/manager/node_test.go
  cloud/pkg/edgecontroller/manager/pod_test.go
  cloud/pkg/edgecontroller/manager/secret_test.go
  cloud/pkg/edgecontroller/manager/service_test.go
  cloud/pkg/edgecontroller/messagelayer/context_test.go
  cloud/pkg/edgecontroller/messagelayer/util_test.go
Labels: approved, kind/test, lgtm, size/XXL

#2488 Deps: unify all k8s packages
  go.mod
  go.sum
  vendor/k8s.io/kube-proxy/config/v1alpha1/types.go
  vendor/k8s.io/kube-proxy/config/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, kind/cleanup, lgtm, size/L

#2437 support kubectl get --raw /api/v1/nodes/{node}/proxy/metrics
  cloud/pkg/cloudstream/streamserver.go
  cloud/pkg/cloudstream/tunnelserver.go
Labels: approved, lgtm, size/S

#2491 keadm: when the service file does not exist, the rm file command is not executed
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/bug, lgtm, size/XS

#2472 Refactor informer and client used in cloudcore
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/common/client/client.go
  cloud/pkg/common/informers/informers.go
  cloud/pkg/edgecontroller/config/config.go
  cloud/pkg/edgecontroller/config/config_test.go
  cloud/pkg/edgecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/edgecontroller.go
  cloud/pkg/edgecontroller/manager/configmap.go
  cloud/pkg/edgecontroller/manager/configmap_test.go
  cloud/pkg/edgecontroller/manager/const_test.go
  cloud/pkg/edgecontroller/manager/endpoint.go
  cloud/pkg/edgecontroller/manager/endpoint_test.go
  cloud/pkg/edgecontroller/manager/node.go
  cloud/pkg/edgecontroller/manager/node_test.go
  cloud/pkg/edgecontroller/manager/pod.go
  cloud/pkg/edgecontroller/manager/pod_test.go
  cloud/pkg/edgecontroller/manager/secret.go
  cloud/pkg/edgecontroller/manager/secret_test.go
  cloud/pkg/edgecontroller/manager/service.go
  cloud/pkg/edgecontroller/manager/service_test.go
  cloud/pkg/edgecontroller/utils/kubeclient.go
  cloud/pkg/edgecontroller/utils/kubeconfig.go
  cloud/pkg/leaderelection/leaderelection.go
  cloud/pkg/synccontroller/config/config.go
  cloud/pkg/synccontroller/synccontroller.go
  edgesite/cmd/edgesite/app/server.go
Labels: approved, lgtm, size/XXL

#2153 Generate coverprofile when test
  Makefile
  hack/lib/golang.sh
  hack/make-rules/clean.sh
Labels: approved, lgtm, size/S

#2496 Fix issue in error-handler of WSClient
  staging/src/github.com/kubeedge/viaduct/pkg/client/ws.go
Labels: approved, kind/bug, lgtm, size/XS

#2497 Makefile: fix OUT_DIR does not work
  Makefile
Labels: approved, kind/bug, lgtm, size/XS

#2290 update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/S

#2493 add threestoneliu to reviewer
  cloud/pkg/cloudhub/OWNERS
  cloud/pkg/edgecontroller/OWNERS
  cloud/pkg/synccontroller/OWNERS
Labels: approved, lgtm, size/XS

#2507 ISSUE_TEMPLATE: update label
  .github/ISSUE_TEMPLATE/question.md
Labels: approved, lgtm, size/XS

#2500 cloud/pkg/cloudhub/common/model: add unit test
  cloud/pkg/cloudhub/common/model/types_test.go
Labels: approved, kind/test, lgtm, size/M

#2495 Optimize hack/local-up-kubeedge.sh
  hack/local-up-kubeedge.sh
Labels: approved, kind/bug, lgtm, size/XS

#2511 hack/lib/golang.sh: fix a hardcode
  hack/lib/golang.sh
Labels: approved, kind/cleanup, lgtm, size/XS

#2502 Refactor k8s and crd client in devicecontroller
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/devicecontroller/config/config.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/devicecontroller.go
  cloud/pkg/devicecontroller/manager/device.go
  cloud/pkg/devicecontroller/manager/devicemodel.go
  cloud/pkg/devicecontroller/utils/crdclient.go
  cloud/pkg/devicecontroller/utils/kubeclient.go
  cloud/pkg/leaderelection/leaderelection.go
  cloud/test/integration/crds/validation_test.go
Labels: approved, lgtm, size/L

#2504 Move e2e cluster cleanup work from e2e binary to script
  tests/e2e/deployment/deployment_suite_test.go
  tests/e2e/scripts/execute.sh
Labels: approved, kind/cleanup, lgtm, size/S

#2516 Remove unused topic
  edge/pkg/eventbus/mqtt/server.go
Labels: approved, kind/bug, lgtm, size/XS

#2517 hack/local-up-kubeedge.sh: ensure cleanup successfully
  hack/local-up-kubeedge.sh
Labels: approved, lgtm, size/XS

#2518 edgecontroller: optimize locationcache
  cloud/pkg/edgecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/manager/location.go
  cloud/pkg/edgecontroller/manager/location_test.go
Labels: approved, kind/cleanup, lgtm, size/XL

#2519 Remove edgesite config from cloudcore
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/edgecontroller/config/config.go
  cloud/pkg/edgecontroller/config/config_test.go
  cloud/pkg/edgecontroller/constants/service.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/edgecontroller.go
  cloud/pkg/edgecontroller/messagelayer/context.go
  cloud/pkg/edgecontroller/messagelayer/context_test.go
  cloud/pkg/edgecontroller/messagelayer/util.go
  cloud/pkg/edgecontroller/messagelayer/util_test.go
  edgesite/cmd/edgesite/app/server.go
Labels: approved, kind/cleanup, lgtm, size/L

#2520 Remove the duplicated context struct
  cloud/pkg/edgecontroller/messagelayer/context_test.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
Labels: approved, kind/cleanup, lgtm, size/S

#2505 stalebot: add exempt label
  .github/stale.yml
Labels: approved, lgtm, size/XS

#2527 keadm: fix crd error tip
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
Labels: approved, kind/bug, lgtm, size/S

#2531 Fix flake ut in devicetwin
  edge/pkg/devicetwin/dtmanager/communicate.go
Labels: approved, kind/failing-test, lgtm, size/XS

#2529 edgecore: add nfs localpath support
  .gitignore
  edge/pkg/edged/edged.go
  vendor/k8s.io/kubernetes/pkg/volume/local/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/local/OWNERS
  vendor/k8s.io/kubernetes/pkg/volume/local/doc.go
  vendor/k8s.io/kubernetes/pkg/volume/local/local.go
  vendor/k8s.io/kubernetes/pkg/volume/nfs/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/nfs/OWNERS
  vendor/k8s.io/kubernetes/pkg/volume/nfs/doc.go
  vendor/k8s.io/kubernetes/pkg/volume/nfs/nfs.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XXL

#2538 Update roadmap for 2021
  README.md
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/L

#2537 delete useless code
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2535 Remove unused file in devicecontroller
  cloud/pkg/devicecontroller/constants/default.go
Labels: approved, kind/cleanup, lgtm, size/S

#2541 hack/lib/golang.sh: fix typos
  hack/lib/golang.sh
Labels: approved, kind/cleanup, lgtm, size/S

#2542 fix: broken link about cri-o
  docs/configuration/cri.md
Labels: approved, kind/documentation, lgtm, size/XS
