Repository kubeedge/kubeedge, pull requests merged in 2021-06, with the labels that each got.

#2870 Update version in readme to 1.7
  README.md
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/S

#2871 Add changelog for 1.7 release
  CHANGELOG/CHANGELOG-1.7.md
Labels: approved, kind/documentation, lgtm, size/L

#2874 fix document
  edgesite/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#2873 add release log
  CHANGELOG/CHANGELOG-1.7.md
Labels: approved, kind/documentation, lgtm, size/XS

#2876 modify the value of tunnel port
  cloud/cmd/cloudcore/app/server.go
Labels: approved, kind/bug, lgtm, size/M

#2882 Update CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.7.md
Labels: approved, kind/documentation, lgtm, size/XS

#2885 Automated cherry pick of #2876: modify the value of tunnel port
  cloud/cmd/cloudcore/app/server.go
Labels: approved, lgtm, size/M

#2890 Add v1.7.1 changelog
  CHANGELOG/CHANGELOG-1.7.md
Labels: kind/documentation, size/M

#2895 remove function getPodCondition not-used return value: index
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/cleanup, lgtm, size/S

#2883 Fix message to apiserver
  cloud/pkg/cloudstream/containerexec_connection.go
  cloud/pkg/cloudstream/containerlog_connection.go
  cloud/pkg/cloudstream/containermetrics_connection.go
  cloud/pkg/cloudstream/streamserver.go
Labels: approved, kind/bug, lgtm, size/M

#2898 handle processing msg errors more gracefully
  edge/pkg/metamanager/metaserver/config/config.go
  edge/pkg/metamanager/process.go
Labels: approved, kind/cleanup, lgtm, size/S

#2893 refine edgesite
  edgesite/cmd/edgesite-agent/main.go
  edgesite/cmd/edgesite-server/app/server.go
  edgesite/cmd/edgesite-server/main.go
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/cmd/agent/app/options/options.go
  vendor/sigs.k8s.io/apiserver-network-proxy/cmd/agent/app/server.go
  vendor/sigs.k8s.io/apiserver-network-proxy/cmd/server/app/options/options.go
  vendor/sigs.k8s.io/apiserver-network-proxy/pkg/agent/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/pkg/server/backend_manager.go
  vendor/sigs.k8s.io/apiserver-network-proxy/pkg/server/default_route_backend_manager.go
  vendor/sigs.k8s.io/apiserver-network-proxy/pkg/server/metrics/metrics.go
  vendor/sigs.k8s.io/apiserver-network-proxy/pkg/server/server.go
Labels: approved, kind/feature, lgtm, size/XXL

#2879 fix msg log print use correct msg
  cloud/pkg/edgecontroller/controller/downstream.go
Labels: approved, kind/bug, lgtm, size/S

#2878 instead of string type by rule-endpoint-type
  cloud/pkg/admissioncontroller/admit_rule.go
  cloud/pkg/admissioncontroller/admit_ruleendpoint.go
  cloud/pkg/apis/rules/v1/types.go
  cloud/pkg/router/constants/constants.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/rest/rest.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  cloud/pkg/router/provider/source.go
  cloud/pkg/router/provider/target.go
  tests/e2e/deployment/rule_crd_test.go
  tests/e2e/utils/rule.go
Labels: approved, kind/feature, lgtm, size/L

#2907 fix incorrect use of TrimLeft or TrimRight
  cloud/pkg/router/provider/rest/rest.go
  cloud/pkg/router/utils/path_test.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/S

#2894 normalize edgecontroller upstream codes
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/cleanup, lgtm, size/M

#2913 to avoid update cm after created a new cm
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, lgtm, size/XS

#2904 extract contructors of new edged module to make codes cleaner
  edge/pkg/edged/edged.go
Labels: approved, kind/cleanup, lgtm, size/L

#2909 Solved the checksum file download problem when ke was installed offline
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/feature, lgtm, size/M

#2914 use function to get content as []byte
  cloud/pkg/dynamiccontroller/application/application.go
  edge/pkg/edgehub/common/http/http_test.go
Labels: approved, lgtm

#2926 delete check arch description which is not supported
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/debug/check.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2927 fix ci failed issue
  .github/workflows/main.yaml
Labels: approved, kind/failing-test, lgtm, size/XS

#2413 add cloud-edge-custom-message-design.md
  docs/images/proposals/router.PNG
  docs/proposals/cloud-edge-custom-message-design.md
Labels: approved, lgtm, size/L

#2935 cloudhub: fix signEdgeCert nil pointer
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: approved, kind/bug, lgtm, size/XS
