Repository kubeedge/kubeedge, pull requests merged in 2021-05, with the labels that each got.

#2821 CloudCore HA can be configured to use modules such as DeviceController
  build/cloud/ha/02-ha-configmap.yaml.example
Labels: approved, kind/bug, lgtm, size/M

#2831 devicetwin: ValidateValue supports checking integer
  edge/pkg/devicetwin/dtcommon/util.go
  edge/pkg/devicetwin/dtcommon/util_test.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
Labels: approved, lgtm, size/S

#2840 modify some codes in csidriver
  cloud/pkg/csidriver/controllerserver.go
  cloud/pkg/csidriver/utils.go
Labels: approved, kind/bug, lgtm, size/M

#2842 remove not used function GetContent
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/common/model/types_test.go
Labels: approved, kind/cleanup, lgtm, size/M

#2835 DeviceTwin: optimize device state's judgement code
  edge/pkg/devicetwin/dtmanager/device.go
Labels: approved, lgtm, size/XS

#2843 modify some codes in cloudhub
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/udsserver/server.go
Labels: approved, kind/cleanup, lgtm, size/S

#2841 modify interface name to KubeEdgeCustomInformer
  cloud/pkg/common/informers/informers.go
  cloud/pkg/edgecontroller/controller/downstream.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2839 fix/edged and edge controller: make customsiz labels available when restart …
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_status.go
Labels: approved, kind/feature, lgtm, size/S

#2851 solve unregular default config item-- dynamicController
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2857 Add v1.6.2 release note
  CHANGELOG/CHANGELOG-1.6.md
Labels: approved, kind/documentation, lgtm, size/M

#2594 Implement update rule status
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/router/constants/constants.go
  cloud/pkg/router/messagelayer/util.go
  cloud/pkg/router/rule/statushandler.go
  common/constants/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: approved, kind/api-change, lgtm, size/L

#2860 add reviewer ttlv to devicetwin and devicecontroller
  cloud/pkg/devicecontroller/OWNERS
  edge/pkg/devicetwin/OWNERS
Labels: approved, lgtm, size/XS

#2852 Add basic metaserver integration test(at local) and delete all omitempty tag in enable
  edge/test/integration/metaserver/metaserver_suite_test.go
  edge/test/integration/metaserver/metaserver_test.go
  edge/test/integration/scripts/fast_test.sh
  edge/test/integration/utils/test_setup.go
  hack/local-up-kubeedge.sh
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  tests/integration/framework/cloud.go
  tests/integration/framework/edge.go
  tests/integration/framework/util.go
Labels: approved, kind/test, lgtm, size/L

#2639 Master limitsize
  cloud/pkg/router/constants/constants.go
  cloud/pkg/router/listener/http.go
Labels: approved, kind/failing-test, kind/feature, lgtm, size/XS

#2866 Fix e2e and keadm e2e ci issue
  .github/workflows/main.yaml
Labels: approved, kind/test, lgtm, size/XS

#2588 add router servicebus
  cloud/pkg/admissioncontroller/admit_rule.go
  cloud/pkg/admissioncontroller/admit_ruleendpoint.go
  cloud/pkg/router/constants/constants.go
  cloud/pkg/router/listener/http.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/rest/rest.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  cloud/pkg/router/router.go
  common/types/http.go
  edge/pkg/edgehub/process.go
  edge/pkg/servicebus/servicebus.go
  hack/local-up-kubeedge.sh
  tests/e2e/deployment/rule_crd_test.go
  tests/e2e/utils/common.go
  tests/e2e/utils/rule.go
Labels: approved, kind/feature, lgtm, size/XL

#2867 Cloudcore support ha
  cloud/cmd/cloudcore/app/options/options.go
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/common/modules/modules.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/edgecontroller.go
  cloud/pkg/leaderelection/leaderelection.go
  cloud/pkg/leaderelection/readyzadaptor.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  tests/integration/framework/util.go
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XXL
