Repository kubeedge/kubeedge, pull requests merged in 2021-04, with the labels that each got.

#2744 Fix header SessionHostNameOverride
  cloud/pkg/cloudstream/tunnelserver.go
  edge/pkg/edgestream/edgestream.go
  pkg/stream/constants.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/M

#2758 Disable image gc while ImageGCHighThreshold == 100
  edge/pkg/edged/edged.go
Labels: approved, kind/feature, lgtm, size/S

#2767 skip check env if enable ake feature
  edge/cmd/edgecore/app/server.go
Labels: approved, kind/bug, lgtm, size/XS

#2705 cloud/dynamiccontroller: add ProcessApplication
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/dynamiccontroller/dynamiccontroller.go
Labels: approved, kind/feature, lgtm, size/L

#2771 Skip init device controller if disable
  cloud/pkg/devicecontroller/devicecontroller.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2768 skip init edged if disable
  edge/pkg/edged/edged.go
Labels: approved, kind/bug, lgtm, size/XS

#2783 cloudcore: fix bug. should reassign the result of selector.Add() to s…
  cloud/pkg/edgecontroller/controller/downstream.go
Labels: approved, kind/bug, lgtm, size/XS

#2781 Stop to create listener when application center serve list request
  cloud/pkg/dynamiccontroller/application/application.go
Labels: approved, kind/bug, lgtm, size/XS

#2738 Close response body when request done
  cloud/pkg/router/listener/message.go
Labels: approved, kind/bug, lgtm, size/XS

#2745 Fix RemoveConnect cannot cancel directly
  pkg/stream/edgedexecconnection.go
  pkg/stream/edgedlogconnection.go
  pkg/stream/edgedmetricsconnection.go
Labels: approved, kind/bug, lgtm, size/L

#2790 add Iceber to reviewer
  cloud/pkg/cloudhub/OWNERS
  cloud/pkg/devicecontroller/OWNERS
  cloud/pkg/dynamiccontroller/OWNERS
  cloud/pkg/edgecontroller/OWNERS
  edge/pkg/devicetwin/OWNERS
  staging/src/github.com/kubeedge/beehive/OWNERS
Labels: approved, lgtm, size/XS

#2784 upgrade crds api version to a stable version
  build/crds/devices/devices_v1alpha2_device.yaml
  build/crds/devices/devices_v1alpha2_devicemodel.yaml
  build/crds/reliablesyncs/cluster_objectsync_v1alpha1.yaml
  build/crds/reliablesyncs/objectsync_v1alpha1.yaml
Labels: approved, kind/feature, lgtm, size/XXL

#2803 keadm: install CRDs corresponding to specific version
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
Labels: approved, kind/feature, lgtm, size/L

#2799 Revert "upgrade crds api version to a stable version"
  build/crds/devices/devices_v1alpha2_device.yaml
  build/crds/devices/devices_v1alpha2_devicemodel.yaml
  build/crds/reliablesyncs/cluster_objectsync_v1alpha1.yaml
  build/crds/reliablesyncs/objectsync_v1alpha1.yaml
Labels: approved, lgtm, size/XXL

#2806 Fix: The server could not find the requested resource
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go
Labels: approved, kind/bug, lgtm, size/XS

#2793 add unit test for edge/pkg/devicetwin/dtmodule
  edge/pkg/devicetwin/dtmodule/dtmodule_suite_test.go
  edge/pkg/devicetwin/dtmodule/dtmodule_test.go
Labels: approved, kind/test, lgtm, size/L

#2805 Automated cherry pick of #2803: keadm: install CRDs corresponding to the version
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
Labels: approved, lgtm, size/L

#2796 Add config of cloudcore token refresh frequence
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
Labels: approved, kind/feature, lgtm, size/S
