Repository kubeedge/kubeedge, pull requests merged in 2021-07, with the labels that each got.

#2937 Fix some minor errors
  keadm/cmd/keadm/app/cmd/debug/check.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
Labels: approved, kind/bug, lgtm, size/S

#2931 cloudcore support configmap dynamic update when the env of container …
  cloud/pkg/edgecontroller/manager/location.go
Labels: approved, kind/bug, lgtm, size/S

#2938 Fix kind create cluster failed issue
  .github/workflows/main.yaml
Labels: approved, lgtm, size/S

#2939 only when toremove devices exist, remove device
  edge/pkg/devicetwin/dtmanager/membership.go
Labels: approved, kind/bug, lgtm, size/XS

#2854 add Gabage-Collection for application
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/dynamiccontroller/application/application_test.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
Labels: approved, kind/feature, lgtm, size/M

#2943 move upstream chan assign from controller start to controller create
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/cleanup, lgtm, size/S

#2951 fix bug: dynamiccontroller use edgecontroller config
  cloud/pkg/dynamiccontroller/messagelayer/context_test.go
Labels: approved, kind/bug, lgtm, size/XS

#2958 modify comments of keadm
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/debug/check.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
  keadm/cmd/keadm/app/cmd/debug/diagnose.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/debinstaller.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  keadm/cmd/keadm/app/cmd/util/mqttinstaller.go
  keadm/cmd/keadm/app/cmd/util/pacmaninstaller.go
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
Labels: approved, kind/cleanup, lgtm, size/M

#2964 remove not-used callback func return value: interface{}
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/devicetwin/dtmanager/communicate_test.go
  edge/pkg/devicetwin/dtmanager/device.go
  edge/pkg/devicetwin/dtmanager/device_test.go
  edge/pkg/devicetwin/dtmanager/dtworker.go
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/devicetwin/dtmanager/membership_test.go
  edge/pkg/devicetwin/dtmanager/twin.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#2972 Use stable ubuntu release in fossa test
  .github/workflows/fossa.yml
Labels: approved, kind/test, lgtm, size/XS

#2952 move edgecontroller config into EdgeController struct
  cloud/pkg/edgecontroller/config/config.go
  cloud/pkg/edgecontroller/config/config_test.go
  cloud/pkg/edgecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/edgecontroller.go
  cloud/pkg/edgecontroller/manager/configmap.go
  cloud/pkg/edgecontroller/manager/configmap_test.go
  cloud/pkg/edgecontroller/manager/endpoint.go
  cloud/pkg/edgecontroller/manager/endpoint_test.go
  cloud/pkg/edgecontroller/manager/node_test.go
  cloud/pkg/edgecontroller/manager/pod.go
  cloud/pkg/edgecontroller/manager/pod_test.go
  cloud/pkg/edgecontroller/manager/rule.go
  cloud/pkg/edgecontroller/manager/ruleendpoint.go
  cloud/pkg/edgecontroller/manager/secret.go
  cloud/pkg/edgecontroller/manager/secret_test.go
  cloud/pkg/edgecontroller/manager/service.go
  cloud/pkg/edgecontroller/manager/service_test.go
  cloud/pkg/edgecontroller/messagelayer/context.go
  cloud/pkg/edgecontroller/messagelayer/context_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#2978 using http methods defined in net/http to replace string literals
  cloud/pkg/cloudhub/servers/httpserver/server.go
  edge/pkg/edgehub/certificate/certmanager.go
  pkg/stream/edgedlogconnection.go
  pkg/stream/edgedmetricsconnection.go
Labels: approved, kind/cleanup, lgtm, size/S

#2827 feat/keadm: support customsized labels when use join command
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
Labels: approved, kind/feature, lgtm, size/S

#2984 forward http headers on service bus
  cloud/pkg/router/listener/http.go
Labels: approved, kind/bug, lgtm, size/XS
