Repository kubeedge/kubeedge, pull requests merged in 2021-12, with the labels that each got.

#3403 change a string to a local variable
  edge/pkg/edged/edged_status.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3304 Support helm repo for cloudcore
  build/helm/cloudcore/Chart.yaml
  build/helm/cloudcore/README.md
  build/helm/cloudcore/crds/cluster_objectsync_v1alpha1.yaml
  build/helm/cloudcore/crds/devices_v1alpha2_device.yaml
  build/helm/cloudcore/crds/devices_v1alpha2_devicemodel.yaml
  build/helm/cloudcore/crds/objectsync_v1alpha1.yaml
  build/helm/cloudcore/crds/router_v1_rule.yaml
  build/helm/cloudcore/crds/router_v1_ruleEndpoint.yaml
  build/helm/cloudcore/templates/_helpers.tpl
  build/helm/cloudcore/templates/configmap_cloudcore.yaml
  build/helm/cloudcore/templates/daemonset_iptablesmanager.yaml
  build/helm/cloudcore/templates/deployment_cloudcore.yaml
  build/helm/cloudcore/templates/rbac_cloudcore.yaml
  build/helm/cloudcore/templates/rbac_iptablesmanager.yaml
  build/helm/cloudcore/templates/secret_cloudcore.yaml
  build/helm/cloudcore/templates/service_cloudcore.yaml
  build/helm/cloudcore/values.yaml
  build/helm/edgemesh/README.md
  hack/generate-crds.sh
Labels: kind/feature, lgtm, approved, size/XXL

#3421 fix misspellings
  keadm/cmd/keadm/app/cmd/debug/diagnose.go
Labels: lgtm, approved, size/XS

#3378 fix spelling errors
  edge/pkg/devicetwin/dtmanager/twin.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
Labels: kind/bug, lgtm, approved, size/M

#3301 feat/servicebus: issue3254 enhance router module and servicebus
  cloud/pkg/router/constants/constants.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/rest/rest.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  edge/pkg/servicebus/dao/targeturls.go
  edge/pkg/servicebus/dao/targeturls_test.go
  edge/pkg/servicebus/servicebus.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  tests/e2e/deployment/rule_crd_test.go
  tests/e2e/utils/common.go
  tests/e2e/utils/rule.go
Labels: size/XL

#3399 remove unused value and fix spelling error
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/dynamiccontroller/application/application_test.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/status/status_manager.go
Labels: kind/cleanup, lgtm, approved, size/S

#3354 Grammar fixed in edged module
  edge/pkg/edged/volume/csi/csi_attacher.go
  edge/pkg/edged/volume/csi/csi_drivers_store.go
  edge/pkg/edged/volume/csi/csi_mounter.go
Labels: kind/feature, lgtm, approved, size/XS

#3293 Fix: resType does not match
  cloud/pkg/dynamiccontroller/application/listener.go
  pkg/metaserver/util/util.go
Labels: kind/bug, lgtm, approved, size/S

#3426 Update keadm-scope.md
  docs/proposals/keadm-scope.md
Labels: kind/documentation, lgtm, approved, size/XS

#3415 fix deviceTwin device update fields
  edge/pkg/devicetwin/dtmanager/device.go
  edge/pkg/devicetwin/dtmanager/device_test.go
Labels: kind/bug, lgtm, approved, size/S

#3414 Reveal the details on the failure of namespace creation
  cloud/cmd/cloudcore/app/server.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3422 fixed error message capitalization
  edge/pkg/devicetwin/process.go
  edge/pkg/devicetwin/process_test.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3406 remove unused constant
  edge/pkg/edged/apis/types.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3428 add device state update topic constant
  edge/pkg/devicetwin/dtcommon/common.go
  edge/pkg/devicetwin/dtmanager/device.go
  edge/test/integration/device/device_test.go
Labels: kind/feature, lgtm, approved, size/S

#3430 Add changelog for 1.9.0
  CHANGELOG/CHANGELOG-1.9.md
Labels: kind/documentation, size/L

#3432 update kubeedge default version to 1.9.0
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/common/constant.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3436 cleanup not used codes of keadm
  keadm/cmd/keadm/app/cmd/common/config.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
Labels: kind/cleanup, lgtm, approved, size/L

#3437 add rules to 01-ha-prepare.yaml for cloudcore ha deployment
  build/cloud/03-clusterrole.yaml
  build/cloud/ha/01-ha-prepare.yaml
  build/helm/cloudcore/templates/rbac_cloudcore.yaml
Labels: kind/bug, lgtm, approved, size/XS

#3434 fix white noise issue
  CHANGELOG/CHANGELOG-1.9.md
Labels: kind/documentation, lgtm, approved, size/S

#3427 add README.md
  edge/README.md
Labels: kind/documentation, lgtm, approved, size/S

#3417 fix pod exec is not close conn when edgecore is closed
  cloud/pkg/cloudstream/containerexec_connection.go
Labels: kind/bug, lgtm, approved, size/XS

#3444 fix crd create failed
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, size/XXL

#3452 Automated cherry pick of #3444: fix crd version error
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#3431 update k8s compatibility
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/S

#3376 support device message attr error return
  edge/pkg/devicetwin/dtmanager/device.go
Labels: kind/feature, lgtm, approved, size/XS

#3373 add log if remove device MarshalMembershipUpdate error
  edge/pkg/devicetwin/dtmanager/membership.go
Labels: kind/feature, lgtm, approved, size/S

#3372 DealDeviceTwin cleanup
  edge/pkg/devicetwin/dtmanager/twin.go
Labels: kind/cleanup, lgtm, approved, size/S

#3359 fix keadm check mqtt install bug
  keadm/cmd/keadm/app/cmd/util/debinstaller.go
  keadm/cmd/keadm/app/cmd/util/pacmaninstaller.go
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
Labels: kind/bug, lgtm, approved, size/XS

#3412 Optimize script when create stream cert
  build/tools/certgen.sh
Labels: lgtm, approved, size/XS

#3456 modify the log view command after edgecore is running
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: kind/feature, lgtm, approved, size/S

#3222 replace deprecated package io/ioutil with packages io and os
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudstream/config/config.go
  cloud/pkg/cloudstream/streamserver.go
  cloud/pkg/edgecontroller/manager/configmap_test.go
  cloud/pkg/edgecontroller/manager/endpoint_test.go
  cloud/pkg/edgecontroller/manager/node_test.go
  cloud/pkg/edgecontroller/manager/pod_test.go
  cloud/pkg/edgecontroller/manager/rule_test.go
  cloud/pkg/edgecontroller/manager/ruleendpoint_test.go
  cloud/pkg/edgecontroller/manager/secret_test.go
  cloud/pkg/edgecontroller/manager/service_test.go
  cloud/pkg/router/listener/http.go
  cloud/pkg/router/provider/rest/rest.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  edge/pkg/edged/edged_getters.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/edged_status.go
  edge/pkg/edgehub/certificate/certmanager.go
  edge/pkg/edgehub/clients/quicclient/quicclient.go
  edge/pkg/edgehub/clients/wsclient/websocket.go
  edge/pkg/edgehub/common/http/http_test.go
  edge/pkg/eventbus/common/util/common.go
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
  edge/pkg/servicebus/servicebus.go
  edge/test/cloudhub/stub.go
  edge/test/integration/utils/helpers/helpers.go
  edge/test/integration/utils/test_setup.go
  edge/test/test.go
  edgesite/cmd/edgesite-server/app/server.go
  hack/verify-golang.sh
  keadm/cmd/keadm/app/cmd/common/config.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/helper.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation_test.go
  pkg/apis/componentconfig/edgecore/v1alpha1/helper.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation_test.go
  pkg/apis/componentconfig/edgesite/v1alpha1/helper.go
  pkg/stream/message.go
  pkg/util/validation/check_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/config/config.go
  staging/src/github.com/kubeedge/viaduct/examples/chat/common.go
  staging/src/github.com/kubeedge/viaduct/pkg/client/ws.go
  tests/e2e/utils/common.go
  tests/e2e/utils/node.go
  tests/e2e/utils/pod.go
  tests/e2e/utils/rule.go
  tests/e2e/utils/test_setup.go
  tests/performance/common/common.go
  tests/stubs/cloud/controllerstub/podmanager.go
  tests/stubs/example/main.go
Labels: kind/cleanup, lgtm, approved, size/L

#3464 remove github.com/apache/servicecomb-kie unstable release
  go.mod
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/viaduct/go.mod
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/XS

#3463 replace github.com/satori/go.uuid with github.com/google/uuid
  LICENSES/vendor/github.com/satori/go.uuid/LICENSE
  go.sum
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/beehive/go.sum
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
  staging/src/github.com/kubeedge/viaduct/go.mod
  staging/src/github.com/kubeedge/viaduct/go.sum
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/codec.go
  vendor/github.com/satori/go.uuid/generator.go
  vendor/github.com/satori/go.uuid/sql.go
  vendor/github.com/satori/go.uuid/uuid.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/XL

#3459 drop import of github.com/stretchr/testify
  edge/pkg/devicetwin/dtmanager/membership_test.go
  edge/pkg/devicetwin/dtmodule/dtmodule_test.go
  edge/pkg/eventbus/common/util/common_test.go
  go.mod
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/L

#3443 fixes imagePullSecrets in cloudcore deployment and in iptablesManager daemonset
  build/helm/cloudcore/templates/daemonset_iptablesmanager.yaml
  build/helm/cloudcore/templates/deployment_cloudcore.yaml
Labels: kind/bug, lgtm, approved, size/XS

#3457 cloudhub: prevent dropping volume messages
  cloud/pkg/cloudhub/channelq/channelq.go
Labels: kind/bug, lgtm, approved, size/S

#3461 optimize the iptables manager
  cloud/cmd/cloudcore/app/server.go
  cloud/cmd/iptablesmanager/app/options/options.go
  cloud/cmd/iptablesmanager/app/server.go
  cloud/pkg/cloudstream/iptables/iptables.go
Labels: kind/cleanup, kind/feature, lgtm, approved, size/M

#3468 bump up staging package vendor
  go.sum
  staging/src/github.com/kubeedge/viaduct/go.mod
  staging/src/github.com/kubeedge/viaduct/go.sum
Labels: kind/cleanup, lgtm, approved, size/M

#3476 add release note for v1.9
  CHANGELOG.md
Labels: kind/documentation, lgtm, approved, size/XS

#3478 Add release note for v1.9.1
  CHANGELOG/CHANGELOG-1.9.md
Labels: kind/documentation, size/S

#3479 Modify the wrong function name
  cloud/pkg/cloudhub/handler/messagehandler.go
  pkg/metaserver/util/util.go
  pkg/metaserver/util/util_test.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3474 replace string with const
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  common/constants/default.go
  keadm/cmd/keadm/app/cmd/edge/join.go
Labels: lgtm, approved, size/S

#3481 remove not used edgesite
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  pkg/apis/componentconfig/edgesite/v1alpha1/helper.go
  pkg/apis/componentconfig/edgesite/v1alpha1/register.go
  pkg/apis/componentconfig/edgesite/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/validation/validation.go
  tests/e2e/edgesite/edgesite_suite_test.go
  tests/e2e/utils/test_setup.go
Labels: kind/cleanup, lgtm, approved, size/L

#3480 clean not used mesh
  edge/pkg/common/modules/group.go
  pkg/apis/componentconfig/meta/v1alpha1/types.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3486 update k8s version to v1.21.8
  .github/workflows/main.yaml
  common/constants/default.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3441 enable golangci-lint for codes under staging
  .golangci.yml
  hack/lib/lint.sh
  staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
  staging/src/github.com/kubeedge/beehive/pkg/core/module.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/broker/broker.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/broker/broker_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/context_socket.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/helper.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/modules/socket/server.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/modules/socket/socket.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/synckeeper/keeper_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/wrapper.go
  staging/src/github.com/kubeedge/viaduct/pkg/client/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/client/ws.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/factory_test.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go
  staging/src/github.com/kubeedge/viaduct/pkg/filter/filter.go
  staging/src/github.com/kubeedge/viaduct/pkg/keeper/synckeeper.go
  staging/src/github.com/kubeedge/viaduct/pkg/lane/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/lane/ws.go
  staging/src/github.com/kubeedge/viaduct/pkg/lane/wsnopack.go
  staging/src/github.com/kubeedge/viaduct/pkg/mux/expr.go
  staging/src/github.com/kubeedge/viaduct/pkg/mux/mux.go
  staging/src/github.com/kubeedge/viaduct/pkg/server/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/server/ws.go
  staging/src/github.com/kubeedge/viaduct/pkg/smgr/session.go
  staging/src/github.com/kubeedge/viaduct/pkg/smgr/smgr.go
  staging/src/github.com/kubeedge/viaduct/pkg/translator/message.go
Labels: kind/cleanup, lgtm, approved, size/L

#3488 Automated cherry pick of #3486: update k8s version to v1.21.8
  .github/workflows/main.yaml
  common/constants/default.go
Labels: lgtm, approved, size/XS

#3466 Add missing resource permissions to cloudcore ClusterRole
  build/cloud/03-clusterrole.yaml
  build/cloud/ha/01-ha-prepare.yaml
  build/helm/cloudcore/templates/rbac_cloudcore.yaml
Labels: kind/bug, lgtm, approved, size/S

#3490 update helm_keadm_e2e_test kubelet to v1.21.4
  .github/workflows/main.yaml
Labels: kind/cleanup, lgtm, approved, size/XS

#3487 in keadm_e2e no need to download kubeedge release
  .github/workflows/main.yaml
Labels: kind/cleanup, lgtm, approved, size/XS

#3491 fixed error message capitalization
  edge/pkg/servicebus/util/httpclient.go
Labels: kind/bug, lgtm, approved, size/XS

#3492 add v1.9 changelog link
  CHANGELOG/README.md
Labels: kind/documentation, lgtm, approved, size/XS

#3493 Modify the doc
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/XS

#3495 cleanup command util log
  pkg/util/util.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3496 fix: change the resourceType of msg issued by synccontroller
  cloud/pkg/synccontroller/objectsync.go
  pkg/metaserver/util/util.go
  pkg/metaserver/util/util_test.go
Labels: kind/bug, lgtm, approved, size/S

#3413 beehive: fixes SendSync channel allocation behaviour
  staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go
Labels: kind/bug, lgtm, approved, size/S

#3386 add valueType constant for deviceTwin
  edge/pkg/devicetwin/dtcommon/common.go
  edge/pkg/devicetwin/dtcommon/util.go
  edge/pkg/devicetwin/dtcommon/util_test.go
  edge/pkg/devicetwin/dtmanager/twin.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
  edge/pkg/devicetwin/dttype/types.go
  edge/pkg/devicetwin/dttype/types_helper.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
  edge/pkg/devicetwin/dttype/types_test.go
Labels: kind/feature, lgtm, approved, size/L

#3371 use constant for pod condition
  edge/pkg/edged/status/status_manager.go
Labels: kind/bug, lgtm, approved, size/XS

#3344 Optimization of csinode.yaml
  build/csisamples/hostpath/deploy/csinode.yaml
Labels: kind/feature, lgtm, approved, size/XS

#3502 add stream/tunnel port and nodeport for cloudcore
  build/cloud/07-deployment.yaml
  build/cloud/08-service.yaml.example
  build/cloud/ha/03-ha-deployment.yaml.example
Labels: lgtm, approved, size/M

#3505 Extend the stale timeout for prs and issues
  .github/stale.yml
Labels: lgtm, approved, size/S

#3520 Automated cherry pick of #3496: changeResType
  cloud/pkg/synccontroller/objectsync.go
  pkg/metaserver/util/util.go
  pkg/metaserver/util/util_test.go
Labels: lgtm, approved, size/S

#3522 Fix the issue when cross-building for ARMv8
  Makefile
  hack/lib/golang.sh
Labels: kind/bug, lgtm, approved, size/XS

#3515 supporting crossbuild all components
  Makefile
  hack/lib/golang.sh
Labels: lgtm, approved, size/S

#3519 simplify edgecore image build
  Makefile
  build/edge/Dockerfile
Labels: kind/cleanup, lgtm, approved, size/S

#3524 unify image build
  .github/workflows/main.yaml
  Makefile
  hack/make-rules/image.sh
  tests/e2e/scripts/helm_keadm_e2e.sh
Labels: kind/cleanup, lgtm, approved, size/L

#3512 add iptablesmanager to make all
  Makefile
  hack/lib/golang.sh
Labels: lgtm, approved, size/XS

#3529 add detail log when failed to upgrade the websocket protocol
  cloud/pkg/cloudstream/tunnelserver.go
Labels: kind/feature, lgtm, approved, size/XS
