Repository kubeedge/kubeedge, pull requests merged in 2021-09, with the labels that each got.

#3065 devicecontroller: fix dataProperty misplaced
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/types/deviceprofile.go
  tests/e2e/utils/device.go
Labels: kind/bug, lgtm, approved, size/M

#3097 update k8s compatibility
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/S

#3099 fix help message when white noise issue occurs
  hack/lib/lint.sh
Labels: kind/cleanup, lgtm, approved, size/XS

#3096 Add README jump hyperlink
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/XS

#3085 move edgehub moduleName to common module package
  cloud/pkg/dynamiccontroller/application/application.go
  edge/pkg/common/modules/names.go
  edge/pkg/edged/edged_status.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgehub/process.go
  edge/pkg/edgehub/process_test.go
Labels: kind/cleanup, lgtm, approved, size/M

#3102 fix changelog white noise
  CHANGELOG/CHANGELOG-1.8.md
Labels: kind/bug, lgtm, approved, size/S

#3089 rpminstaller:add support for openEuler
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
Labels: lgtm, approved, size/M

#3111 fix lowercase
  keadm/cmd/keadm/app/cmd/debug/diagnose.go
Labels: kind/bug, lgtm, approved, size/XS

#3109 修改 ictnj to supporters
  docs/adopters/ictnj.png
Labels: lgtm, approved, size/XS

#3115 fixed: the first letter of fmt.ErrorF is not lowercase
  cloud/pkg/admissioncontroller/admit_rule.go
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  cloud/pkg/cloudstream/session.go
  cloud/pkg/cloudstream/streamserver.go
  cloud/pkg/dynamiccontroller/application/application.go
  edge/cmd/edgecore/app/server.go
  edge/pkg/edged/edged_getters.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/edged_volumes.go
Labels: kind/bug, lgtm, approved, size/M

#3120 fixed: the first letter of the fmt.ErrorF is not lowercase
  edge/pkg/edged/edged.go
  edge/pkg/edged/volume/csi/csi_plugin.go
  keadm/cmd/keadm/app/cmd/debug/get.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  pkg/util/util.go
  staging/src/github.com/kubeedge/beehive/pkg/common/util/parse_resource.go
  tests/stubs/common/utils/utils.go
Labels: kind/bug, lgtm, approved, size/M

#3116 Delete unnecessary logs
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: kind/bug, lgtm, approved, size/XS

#3123 set the validity period for the admission certificate
  build/admission/gen-admission-secret.sh
Labels: kind/feature, lgtm, approved, size/XS

#3121 change ictnj format svg
  ADOPTERS.md
  docs/adopters/ictnj.png
  docs/adopters/ictnj.svg
Labels: lgtm, approved, size/XXL

#3117 fix modbus slaveID cannot be 0
  cloud/pkg/apis/devices/v1alpha2/device_instance_types.go
  cloud/pkg/apis/devices/v1alpha2/zz_generated.deepcopy.go
  cloud/test/integration/fixtures/device.go
  docs/proposals/device-management-enhance.md
  tests/e2e/utils/device.go
Labels: kind/bug, lgtm, approved, size/S

#3129 added iptables to Dockerfile and made cloudcore privileged
  build/cloud/07-deployment.yaml
  build/cloud/Dockerfile
  build/cloud/ha/03-ha-deployment.yaml.example
Labels: kind/bug, lgtm, approved, size/M

#3130 Added CustomInterfaceEnabled and CustomInterfaceName for edgecore
  edge/cmd/edgecore/app/server.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_channel.go
Labels: kind/feature, lgtm, approved, size/M

#3133 Enabled install debug handlers to enable the logs feature
  edge/pkg/edged/server/server.go
Labels: kind/bug, lgtm, approved, size/XS

#3132 simply return an error
  cloud/pkg/cloudstream/containermetrics_connection.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3134 Enabled install debug handlers to enable the logs feature
  edge/pkg/edged/server/server.go
Labels: lgtm, approved, size/XS

#3137 Automated cherry pick of #3129 origin release 1.8
  build/cloud/07-deployment.yaml
  build/cloud/Dockerfile
  build/cloud/ha/03-ha-deployment.yaml.example
Labels: lgtm, approved, size/M

#3139 fix message format
  pkg/stream/message.go
Labels: kind/bug, lgtm, approved, size/XS

#3135 add unit test for package validation
  pkg/util/validation/validation_test.go
Labels: kind/test, lgtm, approved, size/M

#3141 use constants.MessageSuccessfulContent replace magic number 'OK'
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/manager/location_test.go
  common/constants/default.go
  edge/pkg/edged/edged_status.go
Labels: kind/cleanup, lgtm, approved, size/M

#3146 update golangci-lint version to v1.42.0
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/router/provider/rest/rest.go
  hack/lib/install.sh
Labels: kind/feature, lgtm, approved, size/M

#3140 improve test coverage
  keadm/cmd/keadm/app/cmd/util/exec.go
  keadm/cmd/keadm/app/cmd/util/exec_test.go
  pkg/metaserver/key_test.go
  pkg/util/uitl_test.go
  pkg/util/util_test.go
Labels: kind/test, lgtm, approved, size/L

#3154 make:build csidriver binary in makefile
  Makefile
  hack/lib/golang.sh
Labels: lgtm, approved, size/XS

#3149 add release note for v1.7 and v1.8
  CHANGELOG.md
Labels: kind/documentation, lgtm, approved, size/XS, ok-to-test

#3150 fix parameter verification of func GoToTarget
  cloud/pkg/router/provider/eventbus/eventbus.go
Labels: kind/bug, lgtm, approved, size/S

#3162 cherry pick of #3117: fix modbus slaveID cannot be 0
  cloud/pkg/apis/devices/v1alpha2/device_instance_types.go
  cloud/pkg/apis/devices/v1alpha2/zz_generated.deepcopy.go
  cloud/test/integration/fixtures/device.go
  docs/proposals/device-management-enhance.md
  tests/e2e/utils/device.go
Labels: lgtm, approved, size/S

#3147 clean not used service and endpoint meta
  edge/pkg/metamanager/client/endpoint.go
  edge/pkg/metamanager/client/service.go
Labels: kind/cleanup, lgtm, approved, size/L

#3084 unified namespace reference
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudstream/iptables/iptables.go
  cloud/pkg/common/modules/modules.go
  common/constants/default.go
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  tests/e2e/utils/common.go
Labels: kind/feature, lgtm, approved, size/M

#3148 fix some code smells
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: kind/bug, lgtm, approved, size/XS

#3168 remove not used beehive common package
  edge/pkg/common/util/resource.go
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/process.go
  keadm/cmd/keadm/app/cmd/debug/get.go
  staging/src/github.com/kubeedge/beehive/pkg/common/util/conn.go
  staging/src/github.com/kubeedge/beehive/pkg/common/util/conn_test.go
  staging/src/github.com/kubeedge/beehive/pkg/common/util/parse_resource.go
  tests/stubs/edge/handlerstub/message.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/L

#3163 fix: use `path.Join` replace `fmt.Sprintf` to set the path value
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/eventbus/eventbus_test.go
Labels: kind/bug, lgtm, approved, size/M

#3160 simplify yaml related import package
  LICENSES/vendor/github.com/ghodss/yaml/LICENSE
  go.mod
  go.sum
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  keadm/cmd/keadm/app/cmd/version.go
  tests/e2e/utils/node.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/XXL, ok-to-test

#3159 rpm:add kubeedge.spec for rpm build
  build/README_zh.md
  build/rpm/README_zh.md
  build/rpm/kubeedge.spec
Labels: lgtm, approved, size/L

#3157 feat(edge): node ephemeral storage info
  edge/pkg/edged/edged_status.go
Labels: kind/feature, lgtm, approved, size/M

#3167 add some unit test cases
  cloud/pkg/dynamiccontroller/messagelayer/util_test.go
  cloud/pkg/edgecontroller/messagelayer/util_test.go
  cloud/pkg/router/utils/path_test.go
  edge/pkg/devicetwin/dtmanager/communicate_test.go
Labels: kind/test, lgtm, approved, size/L

#3060 add message handler for edgehub
  edge/pkg/edgehub/common/msghandler/handler.go
  edge/pkg/edgehub/process.go
  edge/pkg/edgehub/process_test.go
Labels: kind/feature, lgtm, approved, size/M

#3119 meta server addr configurable
  common/constants/default.go
  edge/pkg/metamanager/metaserver/config/config.go
  edge/pkg/metamanager/metaserver/server.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  tests/integration/metaserver/access_test.go
Labels: kind/feature, lgtm, approved, size/S

#3173 Add release note for 1.8.1
  CHANGELOG/CHANGELOG-1.8.md
Labels: kind/documentation, lgtm, approved, size/S

#3171 docs for rpm build
  build/rpm/README.md
  build/rpm/README_zh.md
Labels: lgtm, approved, size/L

#3066 Override spell error
  pkg/stream/constants.go
Labels: lgtm, approved, size/XS

#3174 replaces a string with a defined constant
  cloud/pkg/cloudhub/handler/messagehandler.go
  edge/pkg/eventbus/mqtt/client.go
  edge/pkg/eventbus/mqtt/server.go
  edge/pkg/servicebus/servicebus.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: kind/bug, lgtm, approved, size/M

#3170 add unit test
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation_test.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation_test.go
  pkg/util/validation/check_test.go
Labels: kind/test, lgtm, approved, size/XL

#3179 Fixed: broken links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind/documentation, lgtm, approved, size/XS

#3175 Grant access to cloudcore for PV and PVC
  build/cloud/03-clusterrole.yaml
  build/cloud/ha/01-ha-prepare.yaml
Labels: kind/bug, lgtm, approved, size/XS

#3052 add socket way for module inter communicate
  build/rpm/README_zh.md
  cloud/pkg/dynamiccontroller/messagelayer/context_test.go
  cloud/pkg/edgecontroller/messagelayer/context_test.go
  edge/pkg/devicetwin/devicetwin_test.go
  edge/pkg/devicetwin/dtmanager/communicate_test.go
  edge/pkg/devicetwin/dtmanager/device_test.go
  edge/pkg/devicetwin/process_test.go
  edge/pkg/edgehub/process_test.go
  edge/pkg/metamanager/metamanager_test.go
  edge/pkg/metamanager/process_test.go
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/beehive/go.sum
  staging/src/github.com/kubeedge/beehive/pkg/common/type.go
  staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_channel_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_factory.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_unixsocket.go
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
  staging/src/github.com/kubeedge/beehive/pkg/core/module.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/broker/broker.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/broker/broker_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/config/config.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/context_socket.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/helper.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/modules/socket/server.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/modules/socket/socket.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/store/pipe.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/store/pipeinfo.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/synckeeper/keeper.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/synckeeper/keeper_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/packer/packer.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/reader/package.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/reader/raw.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/reader/reader.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/wrapper.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/writer/package.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/writer/raw.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/writer/writer.go
  staging/src/github.com/kubeedge/viaduct/go.sum
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, size/XXL

#3176 support envFrom configmap in edge pods
  edge/pkg/edged/edged_pods.go
Labels: kind/feature, lgtm, approved, size/M

#3136 Idenfifying session not by IP of node
  cloud/pkg/cloudstream/streamserver.go
Labels: kind/bug, lgtm, approved, size/S

#3186 Bump gorilla websocket to v1.4.2 in viaduct
  pkg/util/util_test.go
  staging/src/github.com/kubeedge/viaduct/go.mod
  staging/src/github.com/kubeedge/viaduct/go.sum
Labels: kind/bug, lgtm, approved, size/S

#3187 fix some problems of socket context
  build/rpm/README.md
  staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_factory.go
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
  staging/src/github.com/kubeedge/beehive/pkg/core/module.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/config/config.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/modules/socket/server.go
  staging/src/github.com/kubeedge/beehive/pkg/core/socket/wrapper/wrapper.go
Labels: kind/bug, lgtm, approved, size/M

#3192 Automated cherry pick of #3136 origin release 1.8
  cloud/pkg/cloudstream/streamserver.go
Labels: kind/bug, lgtm, approved, size/S

#3191 Automated cherry pick of #3114 origin release 1.8
  common/constants/default.go
  docs/proposals/configuration.md
  docs/proposals/cri.md
  keadm/cmd/keadm/app/cmd/common/config.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/edgesite/v1alpha1/default.go
  pkg/util/util.go
  tests/performance/assets/02-edgeconfigmap.yaml
Labels: kind/feature, lgtm, approved, size/M

#3193 fix beehive context send to group
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_factory.go
Labels: kind/bug, lgtm, approved, size/S

#3144 fix kubeedge license
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: kind/bug, lgtm, approved, size/XS

#3183 Include Yin Ding in maintainers list
  MAINTAINERS.md
Labels: kind/cleanup, lgtm, approved, size/XS

#3190 update golang to 1.16
  .github/workflows/fossa.yml
  .github/workflows/main.yaml
  .travis.yml
  Makefile
  build/admission/Dockerfile
  build/cloud/Dockerfile
  build/csidriver/Dockerfile
  build/edge/Dockerfile
  build/edgesite/agent-build.Dockerfile
  build/edgesite/server-build.Dockerfile
  edge/pkg/edgehub/common/http/http_test.go
  go.mod
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/viaduct/go.mod
  staging/src/github.com/kubeedge/viaduct/go.sum
Labels: kind/feature, lgtm, approved, size/M

#3199 Add myself to cloudhub/admission/keadm modules OWNERS approvers
  cloud/pkg/admissioncontroller/OWNERS
  cloud/pkg/cloudhub/OWNERS
  keadm/OWNERS
Labels: lgtm, approved, size/XS

#3201 replace archived golint with revive
  .golangci.yml
  MAINTAINERS.md
  cloud/pkg/edgecontroller/controller/upstream.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_factory.go
  tests/e2e/utils/config.go
Labels: kind/cleanup, lgtm, approved, size/S

#3177 perf: cloudcore certificate application restful api supports certificate usages
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: lgtm, approved, size/S

#3203 add .vscode directory to gitignore
  .gitignore
Labels: kind/cleanup, lgtm, approved, size/XS

#3205 Automated cherry pick of #3177: perf: cloudcore ecertificate application restful api supports
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: lgtm, approved, size/S

#3131 add experimental feature
  cloud/cmd/cloudcore/app/server.go
  edge/cmd/edgecore/app/server.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/features/features.go
Labels: kind/feature, lgtm, approved, size/M

#3200 Nominate new maintainer zc2638
  MAINTAINERS.md
Labels: lgtm, approved, size/XS

#3209 fix: break the pointless loop
  cloud/pkg/admissioncontroller/admit_rule.go
Labels: kind/bug, lgtm, approved, size/XS
