Repository kubeedge/kubeedge, pull requests merged in 2021-03, with the labels that each got.

#2595 fix keadm issue
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, lgtm, size/XS

#2603 Automated cherry pick of #2595: fix keadm install edgecore
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, lgtm, size/XS

#2593 fix the bug of script fast_test.sh
  tests/e2e/scripts/fast_test.sh
Labels: approved, kind/bug, lgtm, size/XS

#2604 Add timeout for github actions
  .github/workflows/main.yaml
Labels: approved, kind/test, lgtm, size/XS

#2607 Don't omitempty for enable field for all modules
  hack/local-up-kubeedge.sh
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: approved, kind/cleanup, lgtm, size/M

#2609 Revert "Don't omitempty for enable field for all modules"
  hack/local-up-kubeedge.sh
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: size/M

#2615 modify some code in devicetwin module
  edge/pkg/devicetwin/dtcommon/common.go
  edge/pkg/devicetwin/dtmanager/membership.go
Labels: approved, kind/bug, lgtm, size/XS

#2613 fix cloudcore crash when nodekeepalivechannel is nil
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: approved, kind/bug, lgtm, size/XS

#2617 fix watch issue
  cloud/pkg/dynamiccontroller/application/listener.go
Labels: approved, kind/bug, lgtm, size/XS

#2621 fix how to build from source code
  docs/setup/build.md
Labels: approved, kind/bug, lgtm, size/XS

#2624 update roadmap_zh.md
  docs/roadmap_zh.md
Labels: approved, kind/documentation, lgtm, size/L

#2623 trans troubleshooting.md
  docs/troubleshooting_zh.md
Labels: approved, kind/documentation, lgtm, size/M

#2622 Automated cherry pick of #2617: fix watch issue
  cloud/pkg/dynamiccontroller/application/listener.go
Labels: approved, lgtm, size/XS

#2608 Install crd for router in keadm
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
Labels: approved, kind/bug, lgtm, size/M

#2614 Remove synckeeper in edgehub
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgehub/process.go
  edge/pkg/edgehub/process_test.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/L

#2636 Automated cherry pick of #2608: install crd for router in keadm
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
Labels: approved, lgtm, size/M

#2635 Automated cherry pick of #2614: remove syncKeeper in edgehub
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgehub/process.go
  edge/pkg/edgehub/process_test.go
Labels: approved, lgtm, size/L

#2641 Shorten the reconnect wait time when connect failed
  edge/pkg/edgehub/edgehub.go
Labels: approved, kind/cleanup, lgtm, size/S

#2599 Fix the warning log when edgemesh is disabled
  edge/pkg/metamanager/process.go
Labels: approved, kind/bug, lgtm, size/XS

#2653 keadm: fix file mode
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
Labels: approved, lgtm, size/XS

#2649 beehive/util: fix the NewUnixSocket
  staging/src/github.com/kubeedge/beehive/pkg/common/util/conn.go
Labels: approved, kind/bug, lgtm, size/S

#2643 beehive/pkg/core: optimize the GracefulShutdown
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
Labels: approved, lgtm, size/S

#2656 synccontroller: fix the comment of the GetObjectResourceVersion
  cloud/pkg/synccontroller/objectsync.go
Labels: approved, lgtm, size/XS

#2657 Automated cherry pick of #2599: Fix the warning log when edgemesh is disabled
  edge/pkg/metamanager/process.go
Labels: approved, lgtm, size/XS

#2645 beehive/context: fix the unlocking of the ctx.chsLock in the delChannel
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_channel.go
Labels: approved, kind/bug, lgtm, size/XS

#2654 cloudhub: fix the return error
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: approved, kind/bug, lgtm, size/XS

#2663 Insert empty line betwen funcs
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
Labels: approved, lgtm, size/XS

#2664 beehive/context: fix recovery when sending message
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_channel.go
Labels: approved, kind/bug, lgtm, size/M

#2655 cloudstream: fix defer cleanup
  cloud/pkg/cloudstream/streamserver.go
Labels: approved, kind/bug, lgtm, size/XS

#2642 Fix image gc issue
  edge/pkg/edged/edged.go
  edge/pkg/edged/images/image_gc_manager.go
Labels: approved, kind/bug, lgtm, size/M

#2646 Automated cherry pick of #2641: Shorten the reconnect wait time when connect failed
  edge/pkg/edgehub/edgehub.go
Labels: approved, lgtm, size/S

#2659 Fix container gc issue
  edge/pkg/edged/containers/helpers.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
Labels: approved, kind/bug, lgtm, size/L

#2666 Automated cherry pick of #2659: fix container gc issue
  edge/pkg/edged/containers/helpers.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/edged_pods.go
Labels: approved, lgtm, size/L

#2667 Automated cherry pick of #2642: fix image gc issue
  edge/pkg/edged/edged.go
  edge/pkg/edged/images/image_gc_manager.go
Labels: approved, lgtm, size/M

#2668 Add changelog for v1.6.1
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
Labels: approved, kind/documentation, lgtm, size/M

#2676 add GetContentData to get content data of []byte type
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: approved, lgtm, size/L

#2675 add unit test for edgemesh common utils.go
  edgemesh/pkg/common/utils_test.go
Labels: approved, kind/test, lgtm, size/M

#2674 add unit test for metaserver util.go
  pkg/metaserver/util/util_test.go
Labels: approved, kind/test, lgtm, size/L

#2670 cloud: fix the warning log for printing object type
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/downstream.go
Labels: approved, kind/bug, lgtm, size/S

#2672 cloud/edgecontroller: fix the syncPod in the downstream controller
  cloud/pkg/edgecontroller/controller/downstream.go
Labels: approved, kind/bug, lgtm, size/XS

#2678 edgecore: optimize environmentCheck code
  edge/cmd/edgecore/app/server.go
Labels: approved, lgtm, size/M

#2683 optimize code
  pkg/metaserver/util/util.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2684 modify devicetwin module configuration package visibility
  edge/pkg/devicetwin/config/config.go
  edge/pkg/devicetwin/dtcontext/dtcontext.go
Labels: approved, kind/bug, lgtm, size/XS

#2685 cloudhub/udsserver: fix NewUnixDomainSocket
  cloud/pkg/cloudhub/servers/udsserver/uds.go
Labels: approved, kind/bug, lgtm, size/XS

#2687 add unit test for edge certutil certfile.go
  edge/pkg/edgehub/common/certutil/certfile_test.go
Labels: approved, kind/test, lgtm, size/M

#2673 cloud/edgecontroller: fix log when operation is not supported
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/bug, lgtm, size/XS

#2681 add unit test for cloud devicecontroller util.go
  cloud/pkg/devicecontroller/messagelayer/util_test.go
Labels: approved, kind/test, lgtm, size/L

#2692 edgecontroller: fix newEdgeController simple
  cloud/pkg/edgecontroller/edgecontroller.go
Labels: approved, kind/cleanup, lgtm, size/S

#2694 upstream: refactor kubeClientGet
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/feature, lgtm, size/M

#2689 fix GetLocalIP IP lookup error
  pkg/util/util.go
Labels: approved, kind/bug, lgtm, size/M

#2691 optimize code and log, fix an error of verifyAuthorization
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: approved, kind/bug, lgtm, size/S

#2693 edgesite: optimize code for edgeSiteCommand
  edgesite/cmd/edgesite/app/server.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2697 cloudhub: fix exit server chan size
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: approved, lgtm, size/XS

#2695 edgecontroller: fix downstream easier to read
  cloud/pkg/edgecontroller/controller/downstream.go
Labels: approved, kind/feature, lgtm, size/L

#2698 Remove excess memory allocation
  pkg/stream/edgedexecconnection.go
  pkg/stream/edgedlogconnection.go
Labels: approved, kind/cleanup, lgtm, size/S

#2696 use CertificateBlockType constants for cloud and edge
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/server.go
  cloud/pkg/cloudstream/tunnelserver.go
  edge/pkg/common/util/config.go
  edge/pkg/edgehub/certificate/certmanager.go
  edge/pkg/edgehub/common/certutil/certfile.go
Labels: approved, kind/cleanup, lgtm, size/M

#2701 Fix if/else statement have exactly the same implementation
  edgemesh/pkg/dns/dns.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/XS

#2706 cloud/dynamiccontroller: fix close application
  cloud/pkg/dynamiccontroller/application/application.go
Labels: approved, kind/bug, lgtm, size/XS

#2700 Fix Invalid if statement
  edge/pkg/edged/volume/csi/csi_client.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2703 Remove Msg WriteTo
  cloud/pkg/cloudstream/session.go
  pkg/stream/edgedexecconnection.go
  pkg/stream/edgedlogconnection.go
  pkg/stream/edgedmetricsconnection.go
  pkg/stream/message.go
Labels: approved, kind/cleanup, lgtm, size/S

#2710 cleanup code for http.go
  cloud/pkg/router/listener/http.go
Labels: approved, kind/cleanup, lgtm, size/S

#2707 cloud/dynamiccontroller: fix toBytes
  cloud/pkg/dynamiccontroller/application/application.go
Labels: approved, kind/bug, lgtm, size/S

#2716 Fix wrong field used for calculating length
  edgemesh/pkg/dns/dns.go
Labels: approved, kind/bug, lgtm, size/XS

#2704 Cleanup manager.Start
  edge/pkg/edged/status/status_manager.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2723 Fix failing-test
  pkg/metaserver/key_test.go
Labels: approved, kind/failing-test, lgtm, size/M

#2709 cloud/dynamiccontroller: fix the sendObj of the SelectorListener
  cloud/pkg/dynamiccontroller/application/listener.go
Labels: approved, kind/bug, lgtm, size/S

#2679 cloud/router: fix and optimize rule code
  cloud/pkg/router/rule/rule.go
  cloud/pkg/router/rule/statushandler.go
Labels: approved, kind/bug, lgtm, size/L

#2722 Add test ci for pkg
  hack/lib/golang.sh
Labels: approved, kind/bug, kind/test, lgtm, size/S

#2733 Add rules crd to clusterrole.
  build/cloud/03-clusterrole.yaml
  build/cloud/ha/01-ha-prepare.yaml
Labels: approved, kind/bug, lgtm, size/XS

#2739 pkg/util/util.go: fix get local ip issue
  pkg/util/util.go
Labels: approved, kind/bug, lgtm, size/S

#2727 cloud/leaderelection: fix and optimize leaderelection
  cloud/pkg/common/client/client.go
  cloud/pkg/leaderelection/leaderelection.go
Labels: approved, kind/feature, lgtm, size/L

#2715 Remove excess memory allocation for cloudstream
  cloud/pkg/cloudstream/containerexec_connection.go
Labels: approved, lgtm, size/XS

#2720 pkg/metaserver: optimize key.go
  pkg/metaserver/key.go
Labels: approved, kind/cleanup, lgtm, size/M

#2726 edge/eventbus: fix pubCloudMsgToEdge
  edge/pkg/eventbus/eventbus.go
Labels: approved, kind/bug, lgtm, size/S

#2690 cloudhub: optimize message handler by removing range
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: approved, lgtm, size/S

#2734 has systemd double check
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/bug, lgtm, size/S

#2728 cloud/leaderelection: fix recorder
  cloud/pkg/leaderelection/leaderelection.go
Labels: approved, kind/bug, kind/feature, lgtm, size/XS

#2743 add back the MAINTAINERS file placeholder to avoid dead link issue
  MAINTAINERS
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS
