Repository kubeedge/kubeedge, pull requests merged in 2021-02, with the labels that each got.

#2539 Keadm: delete extra residual files
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/feature, lgtm, size/S

#2236 Keadm: update OWNERS
  keadm/OWNERS
Labels: approved, lgtm, size/XS

#2552 cloudcore: fix panic in cloudcore
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: approved, kind/bug, lgtm, size/M

#2560 FOSSA scan enabled
  .github/workflows/fossa.yml
Labels: approved, lgtm, size/S

#2499 Admission: support edge apps autonomy when offline
  build/admission/deployment.yaml
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/admissioncontroller/admit_devicemodel.go
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/admissioncontroller/mutate_offlinemigration.go
Labels: approved, kind/feature, lgtm, size/L

#2563 fix: missing invoke StartGarbageCollection func bug
  edge/pkg/edged/edged.go
Labels: approved, kind/bug, lgtm, size/XS

#2559 keadm: refactoring retryDownload
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: approved, kind/feature, lgtm, size/M

#2568 improve issue template format, collapse optional info
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question.md
Labels: approved, lgtm, size/L

#2570 Ut coverage in edge/pkg/edgehyb/common/http/
  edge/pkg/edgehub/common/http/http_test.go
Labels: approved, kind/test, lgtm, size/L

#2582 remove cache when configmap not found from k8s
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, kind/bug, lgtm, size/XS

#2583 Automated cherry pick of #2582: remove cache when configmap not found from k8s
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: approved, lgtm, size/XS

#2573 Use default config for local up testing
  hack/local-up-kubeedge.sh
Labels: approved, kind/test, lgtm, size/XS

#2572 Remove unused hard code map in synccontroller
  cloud/pkg/synccontroller/objectsync.go
Labels: approved, kind/cleanup, lgtm, size/S

#2587 Fix kubelet accessing through edge-side meta server
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/router/provider/source.go
  cloud/pkg/router/provider/target.go
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
  edge/pkg/metamanager/metaserver/handlerfactory/helpers.go
  edge/pkg/metamanager/metaserver/handlerfactory/response.go
  edge/pkg/metamanager/metaserver/handlerfactory/rest.go
  edge/pkg/metamanager/metaserver/handlerfactory/update.go
  edge/pkg/metamanager/metaserver/kubernetes/fakers/admission.go
  edge/pkg/metamanager/metaserver/kubernetes/fakers/authorizer.go
  edge/pkg/metamanager/metaserver/kubernetes/fakers/convertor.go
  edge/pkg/metamanager/metaserver/kubernetes/fakers/defaulter.go
  edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/cacher/cacher.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
  edge/pkg/metamanager/metaserver/server.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  pkg/metaserver/key.go
  tests/integration/framework/cloud.go
  tests/integration/framework/edge.go
  tests/integration/framework/util.go
  tests/integration/metaserver/access_test.go
  tests/integration/metaserver/main_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/crdserverscheme/unstructured.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/admit/BUILD
  vendor/k8s.io/kubernetes/plugin/pkg/admission/admit/admission.go
  vendor/modules.txt
Labels: approved, kind/bug, kind/feature, lgtm, size/XXL

#2589 Automated cherry pick of #2587: support "create update patch" at edge
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/router/provider/source.go
  cloud/pkg/router/provider/target.go
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
  edge/pkg/metamanager/metaserver/handlerfactory/helpers.go
  edge/pkg/metamanager/metaserver/handlerfactory/response.go
  edge/pkg/metamanager/metaserver/handlerfactory/rest.go
  edge/pkg/metamanager/metaserver/handlerfactory/update.go
  edge/pkg/metamanager/metaserver/kubernetes/fakers/admission.go
  edge/pkg/metamanager/metaserver/kubernetes/fakers/authorizer.go
  edge/pkg/metamanager/metaserver/kubernetes/fakers/convertor.go
  edge/pkg/metamanager/metaserver/kubernetes/fakers/defaulter.go
  edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/cacher/cacher.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
  edge/pkg/metamanager/metaserver/server.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  pkg/metaserver/key.go
  tests/integration/framework/cloud.go
  tests/integration/framework/edge.go
  tests/integration/framework/util.go
  tests/integration/metaserver/access_test.go
  tests/integration/metaserver/main_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/crdserverscheme/unstructured.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/admit/BUILD
  vendor/k8s.io/kubernetes/plugin/pkg/admission/admit/admission.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2590 Automated cherry pick of #2572: remove unused hardcode map
  cloud/pkg/synccontroller/objectsync.go
Labels: approved, lgtm, size/S

#2591 add release note for v1.6
  CHANGELOG.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/README.md
Labels: approved, kind/documentation, lgtm, size/L
