Repository kubeedge/kubeedge, pull requests merged in 2021-11, with the labels that each got.

#3256 avoid print goroutine stack trace when component start failed
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  cloud/pkg/cloudhub/servers/server.go
  cloud/pkg/cloudhub/servers/udsserver/server.go
  cloud/pkg/cloudstream/config/config.go
  cloud/pkg/cloudstream/streamserver.go
  cloud/pkg/cloudstream/tunnelserver.go
  cloud/pkg/devicecontroller/devicecontroller.go
  cloud/pkg/dynamiccontroller/application/eventhandler.go
  cloud/pkg/dynamiccontroller/dynamiccontroller.go
  cloud/pkg/edgecontroller/edgecontroller.go
  edge/cmd/edgecore/app/server.go
  edge/pkg/common/dbm/db.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/server/server.go
  edge/pkg/edgehub/certificate/certmanager.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgestream/edgestream.go
  keadm/cmd/keadm/app/cmd/debug/get.go
  keadm/cmd/keadm/app/cmd/version.go
  keadm/cmd/keadm/keadm.go
  staging/src/github.com/kubeedge/beehive/pkg/core/context/context_factory.go
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
Labels: kind/cleanup, lgtm, approved, size/L

#3257 Fix device does not exist in the downstream controller after it is added
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: kind/bug, lgtm, approved, size/XS

#3260 modify some codes of admission controller
  cloud/pkg/admissioncontroller/admit_devicemodel.go
  cloud/pkg/admissioncontroller/admit_rule.go
  cloud/pkg/admissioncontroller/admit_ruleendpoint.go
  cloud/pkg/admissioncontroller/common.go
Labels: kind/cleanup, lgtm, approved, size/M

#3271 cleanup: kubernetes client instance
  cloud/pkg/common/client/client.go
Labels: kind/cleanup, lgtm, approved, size/M

#3272 replace go get with go install
  .github/workflows/main.yaml
  edge/test/integration/scripts/execute.sh
  hack/lib/install.sh
  tests/e2e/scripts/execute.sh
  tests/performance/scripts/jenkins.sh
Labels: kind/cleanup, lgtm, approved, size/S

#3267 cleanup and simplify keadm code
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cmd.go
  keadm/cmd/keadm/app/cmd/debug/check.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
  keadm/cmd/keadm/app/cmd/debug/debug.go
  keadm/cmd/keadm/app/cmd/debug/diagnose.go
  keadm/cmd/keadm/app/cmd/debug/get.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/kubeclient.go
  keadm/cmd/keadm/app/cmd/version.go
  keadm/cmd/keadm/app/keadm.go
  keadm/cmd/keadm/keadm.go
Labels: kind/cleanup, lgtm, approved, size/L

#3278 devicetwin code cleanup
  edge/pkg/devicetwin/dtmanager/communicate.go
Labels: kind/cleanup, lgtm, approved, size/S

#3262 support labelselector for metaserver
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/store.go
Labels: kind/bug, lgtm, approved, size/S

#3285 fixed error message capitalization
  edge/pkg/devicetwin/process.go
  edge/pkg/devicetwin/process_test.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3289 fix spelling errors in comments
  edge/pkg/devicetwin/dttype/message.go
Labels: lgtm, approved, size/XS

#3290 fix log type
  edge/pkg/edged/status/status_manager.go
Labels: kind/bug, lgtm, approved, size/XS

#3291 clean unuseful variables
  edge/pkg/metamanager/dao/v2/metav2.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3297 Add type check for each implementation of Module interface
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudstream/cloudstream.go
  cloud/pkg/devicecontroller/devicecontroller.go
  cloud/pkg/dynamiccontroller/dynamiccontroller.go
  cloud/pkg/edgecontroller/edgecontroller.go
  cloud/pkg/router/router.go
  cloud/pkg/synccontroller/synccontroller.go
  edge/pkg/devicetwin/devicetwin.go
  edge/pkg/edged/edged.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgestream/edgestream.go
  edge/pkg/eventbus/eventbus.go
  edge/pkg/metamanager/metamanager.go
  edge/pkg/servicebus/servicebus.go
  edge/test/cloudhub/stub.go
  edge/test/test.go
  tests/stubs/cloud/controllerstub/module.go
  tests/stubs/edge/handlerstub/module.go
Labels: lgtm, approved, size/M

#3292 Code improve: ticker should be stopped
  edge/cmd/edgecore/app/server.go
  edge/pkg/edgestream/edgestream.go
Labels: kind/cleanup, lgtm, approved, size/M

#3279 Still allowed delete rule when source not exist
  cloud/pkg/router/rule/rule.go
Labels: kind/feature, lgtm, approved, size/S

#3302 Fix the log's syntax problem in edged
  edge/pkg/edged/edged.go
Labels: kind/feature, lgtm, approved, size/XS

#3305 Remove useless []byte
  edge/pkg/metamanager/client/configmap.go
  edge/pkg/metamanager/client/serviceaccount.go
Labels: kind/feature, lgtm, approved, size/XS

#3307 Fix log spelling mistake in synccontroller
  cloud/pkg/synccontroller/synccontroller.go
Labels: kind/feature, lgtm, approved, size/XS

#3309 delete unwanted labels
  build/cloud/ha/03-ha-deployment.yaml.example
Labels: lgtm, approved, size/XS

#3306 Remove useless annotated code in metamanager
  edge/pkg/metamanager/client/secret.go
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
  edge/pkg/metamanager/process.go
Labels: kind/feature, lgtm, approved, size/XS

#3318 delete unwanted configmap label
  build/cloud/ha/02-ha-configmap.yaml.example
Labels: lgtm, approved, size/XS

#3315 fix some error log
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/dynamiccontroller/application/application_test.go
  edge/pkg/edgehub/certificate/certmanager.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3312 Fix import content
  cloud/cmd/admission/app/server.go
Labels: kind/feature, lgtm, approved, size/XS

#3313 remove unused member variable of device DownstreamController
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: kind/feature, lgtm, approved, size/XS

#3311 Remove meaningless code
  cloud/pkg/cloudhub/handler/messagehandler.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edgehub/process.go
Labels: kind/feature, lgtm, approved, size/S

#3330 delete useless device-v1alpha1 code while device is update to v1alpha2
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3334 declare a variable to instead the magic number
  edge/pkg/eventbus/common/util/common.go
Labels: lgtm, approved, size/XS

#3331 ensure unlock while function returns
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go
Labels: kind/bug, lgtm, approved, size/XS

#3333 fix assign grammar of application agent
  cloud/pkg/dynamiccontroller/application/application.go
Labels: kind/bug, lgtm, approved, size/S

#3339 need to return when error occurs
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3338 fix spelling error and remove redundant code
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3341 fix dynamiccontroller grammar errors
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/dynamiccontroller/application/listener.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3340 fix spelling error and remove redundant code
  cloud/pkg/csidriver/controllerserver.go
  cloud/pkg/devicecontroller/messagelayer/util.go
  cloud/pkg/edgecontroller/manager/pod_test.go
Labels: kind/cleanup, lgtm, approved, size/S

#3350 fix keadm info print format
  keadm/cmd/keadm/app/cmd/cmd.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3265 Optional loosely-coupled iptables manager for containerized deployment
  .github/workflows/main.yaml
  Makefile
  build/iptablesmanager/Dockerfile
  build/iptablesmanager/iptablesmanager-ds.yaml
  cloud/cmd/cloudcore/app/server.go
  cloud/cmd/iptablesmanager/app/options/options.go
  cloud/cmd/iptablesmanager/app/server.go
  cloud/cmd/iptablesmanager/iptablesmanager.go
  cloud/pkg/cloudstream/iptables/iptables.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/helper.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
Labels: kind/feature, lgtm, approved, size/L

#3349 use existing constants instead of variables
  edge/pkg/devicetwin/dtmanager/twin.go
Labels: kind/bug, lgtm, approved, size/XS

#3351 use NeverStop chan
  edge/pkg/edged/edged.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3360 edged: get node status log level to 5
  edge/pkg/edged/edged_status.go
Labels: kind/feature, lgtm, approved, size/XS

#3296 fix edge node ip <nil>
  edge/cmd/edgecore/app/server.go
Labels: kind/bug, lgtm, approved, size/S

#3346 fix "keadm get nodes -A" printing namespaces while nodes without namespaces actually
  keadm/cmd/keadm/app/cmd/debug/get.go
Labels: kind/bug, lgtm, approved, size/XS

#3364 remove unused config
  edge/pkg/metamanager/metaserver/config/config.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3329 fix:Secret can't send to edge in SecretKeyRef #3328
  edge/pkg/edged/edged_pods.go
Labels: kind/bug, lgtm, approved, size/M

#3375 add deviceTwin membership log
  edge/pkg/devicetwin/dtmanager/membership.go
Labels: kind/feature, lgtm, approved, size/XS

#3381 fix spelling errors in comments
  edge/pkg/devicetwin/dttype/types_helper.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3366 Refactor computing the SHA512 checksum to go instead of bash
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: kind/cleanup, kind/test, lgtm, approved, size/L

#3387 add gy95 as sub directory reviewer
  cloud/pkg/devicecontroller/OWNERS
  cloud/pkg/edgecontroller/OWNERS
  edge/pkg/devicetwin/OWNERS
  edge/pkg/edged/OWNERS
  keadm/OWNERS
Labels: kind/documentation, lgtm, approved, size/XS

#3352 fix spelling error and remove redundant code
  edge/pkg/common/util/config.go
  edge/pkg/devicetwin/dtcontext/dtcontext.go
  edge/pkg/devicetwin/dtcontext/dtcontext_test.go
  edge/pkg/devicetwin/dtmanager/communicate.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3384 fix return
  edge/pkg/edged/edged.go
Labels: kind/cleanup, lgtm, approved, size/S

#3337 Fix grammar problem in componentconfig
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: kind/feature, lgtm, approved, size/XS

#3353 fix unlock in addDevice of membership
  edge/pkg/devicetwin/dtmanager/membership.go
Labels: kind/bug, lgtm, approved, size/XS

#3377 edged: change volume mounter from plugins log level
  edge/pkg/edged/edged_volumes.go
Labels: kind/feature, lgtm, approved, size/XS

#3409 Remove dependency on os/exec and curl in favor of net/http
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: kind/cleanup, lgtm, approved, size/S

#3407 fix deviceTwin distributeMsg err log
  edge/pkg/devicetwin/process.go
Labels: kind/bug, lgtm, approved, size/XS

#3277 change kubeletEndpoint port when cloudstream conneted
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudstream/cloudstream.go
  cloud/pkg/cloudstream/tunnelserver.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/edgecontroller.go
Labels: kind/bug, lgtm, approved, size/M

#3404 remove unreachable return
  edge/pkg/edged/edged.go
Labels: kind/cleanup, lgtm, approved, size/XS
