Repository kubeedge/kubeedge, pull requests merged in 2022-04, with the labels that each got.

#3762 optimize prepare certs function
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: kind/cleanup, lgtm, approved, size/M

#3747 first stage: refactor message layer
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/common/messagelayer/context.go
  cloud/pkg/common/messagelayer/context_test.go
  cloud/pkg/common/messagelayer/util.go
  cloud/pkg/common/messagelayer/util_test.go
  cloud/pkg/devicecontroller/constants/service.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/messagelayer/context.go
  cloud/pkg/devicecontroller/messagelayer/util.go
  cloud/pkg/devicecontroller/messagelayer/util_test.go
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/dynamiccontroller/application/eventhandler.go
  cloud/pkg/dynamiccontroller/application/listener.go
  cloud/pkg/dynamiccontroller/dynamiccontroller.go
  cloud/pkg/dynamiccontroller/messagelayer/context.go
  cloud/pkg/dynamiccontroller/messagelayer/context_test.go
  cloud/pkg/dynamiccontroller/messagelayer/util.go
  cloud/pkg/dynamiccontroller/messagelayer/util_test.go
  cloud/pkg/edgecontroller/constants/service.go
  cloud/pkg/edgecontroller/controller/downstream.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/messagelayer/context.go
  cloud/pkg/edgecontroller/messagelayer/util.go
  cloud/pkg/synccontroller/objectsync.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/meta/v1alpha1/types.go
Labels: lgtm, approved, size/XXL

#3742 add ErrStatus in api-server application
  cloud/pkg/dynamiccontroller/application/application.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
Labels: kind/feature, lgtm, approved, size/M

#3756 support compile binaries with golang images
  Makefile
  hack/make-rules/build_with_container.sh
Labels: lgtm, approved, size/M

#3769 remove redundant type conversion
  cloud/pkg/cloudstream/iptables/iptables.go
  edge/test/test.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3768 compile inside container by default
  Makefile
  build/docker/installation-package/installation-package.dockerfile
  hack/make-rules/build_with_container.sh
Labels: lgtm, approved, size/S

#3771 fix SyncDeviceFromSqlite log print
  edge/pkg/devicetwin/dtmanager/membership.go
Labels: kind/bug, lgtm, approved, size/XS

#3782 rebuild build-tools image totally
  build/docker/build-tools/make-build-tools.sh
Labels: lgtm, approved, size/XS

#3783 remove unused securitycontext pkg
  edge/pkg/edged/securitycontext/provider.go
  edge/pkg/edged/securitycontext/types.go
Labels: lgtm, approved, size/M

#3786 device twin cleanup
  edge/pkg/devicetwin/dttype/types_helper.go
Labels: kind/cleanup, lgtm, approved, size/M

#3779 add msg resource err log
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: kind/feature, lgtm, approved, size/XS

#3781 support crossbuild with container
  .github/workflows/main.yaml
  .travis.yml
  Makefile
  hack/make-rules/build_with_container.sh
Labels: lgtm, approved, size/M

#3785 support smallbuild inside container
  .github/workflows/main.yaml
  .travis.yml
  Makefile
Labels: lgtm, approved, size/S

#3791 cleanup not used setup-go action
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#3790 Fixed wrong format placeholder and nil warning on check
  edge/pkg/edgehub/common/http/http_test.go
Labels: kind/test, lgtm, approved, size/S

#3796 update k8s compatibility in readme
  README.md
  README_zh.md
Labels: lgtm, approved, size/S

#3792 fix endpointslices to kind EndpointSlice
  pkg/metaserver/util/util.go
Labels: kind/bug, lgtm, approved, size/XS

#3797 cleanup not exist path in golangci exclude-rules
  .golangci.yml
Labels: kind/cleanup, lgtm, approved, size/XS

#3795 move the constants into union file
  pkg/stream/constants.go
  pkg/stream/message.go
Labels: lgtm, approved, size/S

#3764 add min TLS version for stream server
  cloud/pkg/cloudstream/streamserver.go
Labels: kind/feature, lgtm, approved, size/XS

#3794 add README for build/docker
  build/docker/README.md
Labels: kind/documentation, lgtm, approved, size/M

#3788 support make release inside container
  Makefile
  hack/make-rules/release.sh
Labels: lgtm, approved, size/S

#3800 Embed openssf Best Practices badge on home page
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/XS

#3803 modify email
  MAINTAINERS.md
Labels: kind/documentation, lgtm, approved, size/XS

#3802 chart: add cert domain config in helm chart
  manifests/charts/cloudcore/README.md
  manifests/charts/cloudcore/templates/configmap_cloudcore.yaml
  manifests/charts/cloudcore/values.yaml
Labels: lgtm, approved, size/XS

#3784 fix propagating signals on docker build
  .github/workflows/main.yaml
  .travis.yml
  hack/make-rules/build_with_container.sh
Labels: lgtm, approved, size/S

#3770 fix actualValue meta not set
  edge/pkg/devicetwin/dttype/types_helper.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
Labels: kind/bug, lgtm, approved, size/XS

#3780 Remove gopath in makefile
  Makefile
  hack/lib/golang.sh
Labels: kind/test, size/XS

#3808 add domain support for certgen.sh
  build/tools/certgen.sh
Labels: kind/bug, lgtm, approved, size/S

#3814 fix unbound variable GOPATH
  hack/generate-crds.sh
  hack/update-codegen.sh
Labels: kind/cleanup, lgtm, approved, size/XS

#3815 Pods configure imagePullSecret but doesn't exist in kubernetes cluster
  edge/pkg/edged/edged.go
Labels: kind/bug, lgtm, approved, size/S

#3817 replace string with constant for router type
  cloud/pkg/common/modules/modules.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/servicebus/servicebus.go
Labels: kind/cleanup, lgtm, approved, size/S

#3820 Automated cherry pick of #3815: Pods configure imagePullSecret but doesn't exist in
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#3819 Automated cherry pick of #3815: Pods configure imagePullSecret but doesn't exist in
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#3818 fix bug: fields.Selector for watch
  cloud/pkg/dynamiccontroller/application/selector.go
Labels: lgtm, approved, size/XS
