Repository kubeedge/kubeedge, pull requests merged in 2022-07, with the labels that each got.

#3994 fix complex parameters
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/devicetwin/dtmanager/communicate_test.go
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/devicetwin/dtmanager/membership_test.go
  edge/pkg/devicetwin/dtmanager/twin.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/edged_status.go
  edge/pkg/edged/volume/csi/csi_attacher.go
  edge/pkg/edged/volume/csi/csi_plugin.go
  edgesite/cmd/edgesite-server/app/server.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/debinstaller.go
  keadm/cmd/keadm/app/cmd/util/pacmaninstaller.go
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go
Labels: kind/cleanup, lgtm, approved, size/L

#4002 fix release 1.11 k8s compatibility and default verison in keadm
  README.md
  README_zh.md
  keadm/cmd/keadm/app/cmd/common/constant.go
Labels: lgtm, approved, size/S

#4009 clean up: delete import alias
  edge/test/integration/device/device_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3972 update deprecate dependency
  cloud/pkg/cloudhub/servers/httpserver/server.go
  edge/test/cloudhub/stub.go
  external-dependency.md
  go.mod
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/M

#4000 fix possible nil pointer of message
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/router/listener/message.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/mux/pattern.go
Labels: kind/cleanup, lgtm, approved, size/M

#4029 Automated cherry pick of #4000: fix possible nil pointer of message
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/router/listener/message.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/mux/pattern.go
Labels: lgtm, approved, size/M

#4030 Automated cherry pick of #3976: Possible type confusions
  cloud/pkg/router/listener/http.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/eventbus/eventbus.go
Labels: lgtm, approved, size/M

#4032 Automated cherry pick of #3972: update deprecate dependency
  cloud/pkg/cloudhub/servers/httpserver/server.go
  edge/test/cloudhub/stub.go
  external-dependency.md
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, size/M

#4025 Automated cherry pick of #3976: Possible type confusions
  cloud/pkg/router/listener/http.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/eventbus/eventbus.go
Labels: lgtm, approved, size/M

#4035 Automated cherry pick of #3976: Possible type confusions
  cloud/pkg/router/listener/http.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/eventbus/eventbus.go
Labels: lgtm, approved, size/M

#4033 update go version in github actions
  .github/workflows/main.yaml
Labels: kind/cleanup, kind/test, lgtm, approved, size/S

#4039 Cherry-pick GHSA-vwm6-qc77-v2rh: fix invalid request
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/router/listener/http.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  common/constants/default.go
  edge/pkg/edgehub/certificate/certmanager.go
  edge/pkg/servicebus/servicebus.go
  keadm/cmd/keadm/app/cmd/util/common.go
  pkg/stream/message.go
  staging/src/github.com/kubeedge/viaduct/pkg/client/ws.go
  staging/src/github.com/kubeedge/viaduct/pkg/comm/comm.go
Labels: kind/bug, lgtm, approved, size/M

#4037 Automated cherry pick of #3994: fix complex parameters
  edge/pkg/devicetwin/dtcommon/common.go
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/devicetwin/dtmanager/communicate_test.go
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/devicetwin/dtmanager/membership_test.go
  edge/pkg/devicetwin/dtmanager/twin.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
  edge/pkg/edged/edged_pods.go
  edge/pkg/edged/edged_status.go
  edge/pkg/edged/volume/csi/csi_attacher.go
  edge/pkg/edged/volume/csi/csi_plugin.go
  edgesite/cmd/edgesite-server/app/server.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/debinstaller.go
  keadm/cmd/keadm/app/cmd/util/pacmaninstaller.go
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go
Labels: lgtm, approved, size/L

#4041 Add release note for 1.10.2
  CHANGELOG/CHANGELOG-1.10.md
Labels: kind/documentation, lgtm, approved, size/S

#4043 Add release note for 1.9.4
  CHANGELOG/CHANGELOG-1.9.md
Labels: kind/documentation, lgtm, approved, size/S

#4040 Add release note for 1.11.1
  CHANGELOG/CHANGELOG-1.11.md
Labels: kind/documentation, lgtm, approved, size/S

#4047 cleanup:fix lint issue
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/store.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
  keadm/cmd/keadm/app/cmd/debug/get.go
  keadm/cmd/keadm/app/cmd/helm/installer.go
  keadm/cmd/keadm/app/cmd/helm/render.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
Labels: lgtm, approved, size/M

#4011 cleanup: Error string fmt and handle error
  cloud/pkg/admissioncontroller/admit_rule.go
  cloud/pkg/admissioncontroller/admit_ruleendpoint.go
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/edgecontroller/constants/service.go
Labels: kind/cleanup, lgtm, approved, size/S

#3909 run fuzzers in CI
  .github/workflows/cifuzz.yml
Labels: kind/feature, lgtm, approved, size/S

#4057 code cleanup
  cloud/pkg/controllermanager/edgeapplication/constants/constants.go
  tests/e2e/deployment/deployment_test.go
  tests/e2e/deployment/device_crd_test.go
  tests/e2e/edgesite/edgesite_test.go
  tests/e2e/keadm/keadm_test.go
Labels: kind/cleanup, lgtm, approved, size/S

#4068 bump containerd to 1.5.13
  go.mod
  go.sum
  vendor/github.com/Microsoft/hcsshim/internal/winapi/utils.go
  vendor/github.com/containerd/containerd/content/local/store_bsd.go
  vendor/github.com/containerd/containerd/content/local/store_openbsd.go
  vendor/github.com/containerd/containerd/content/local/store_unix.go
  vendor/github.com/containerd/containerd/pkg/dialer/dialer_unix.go
  vendor/github.com/containerd/containerd/platforms/defaults_unix.go
  vendor/github.com/containerd/containerd/platforms/defaults_windows.go
  vendor/github.com/containerd/containerd/version/version.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/M

#4076 fix spelling mistakes
  cloud/pkg/common/informers/informers.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3992 add wackxu as reviewer
  cloud/pkg/cloudhub/OWNERS
  cloud/pkg/edgecontroller/OWNERS
  staging/src/github.com/kubeedge/beehive/OWNERS
  tests/e2e/OWNERS
Labels: lgtm, approved, size/XS
