Repository kubeedge/kubeedge, pull requests merged in 2022-01, with the labels that each got.

#3499 Identify session not by IP of node for exec
  cloud/pkg/cloudstream/streamserver.go
Labels: kind/bug, lgtm, approved, size/M

#3533 Patch cloudcore rbac
  build/cloud/03-clusterrole.yaml
  build/cloud/ha/01-ha-prepare.yaml
  build/helm/cloudcore/templates/rbac_cloudcore.yaml
Labels: kind/bug, lgtm, approved, size/XS

#3536 fix typos
  cloud/pkg/router/constants/constants.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/servicebus/servicebus.go
Labels: lgtm, approved, size/XS

#3513 add a basic image for building various components of KubeEdge
  build/docker/build-tools.dockerfile
Labels: kind/feature, lgtm, approved, size/S

#3542 add beta command
  keadm/cmd/keadm/app/cmd/beta/beta.go
  keadm/cmd/keadm/app/cmd/cmd.go
Labels: kind/feature, lgtm, approved, size/M

#3467 add script for build release
  Makefile
  hack/make-rules/release.sh
Labels: kind/feature, lgtm, approved, size/L

#3557 fix misspelled words in comments
  edge/pkg/edged/edged_pods.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3469 using lateset codes to do keadm_e2e
  Makefile
  tests/e2e/scripts/keadm_e2e.sh
Labels: kind/cleanup, lgtm, approved, size/M

#3553 Verify go version when running build script directly
  .github/workflows/main.yaml
  Makefile
  hack/lib/golang.sh
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
  hack/make-rules/build.sh
  hack/make-rules/clean.sh
  hack/make-rules/crossbuild.sh
  hack/make-rules/release.sh
  hack/make-rules/smallbuild.sh
  hack/verify-golang.sh
Labels: kind/cleanup, lgtm, approved, size/M

#3563 Fix no prompt while executing `make all` without sed
  hack/lib/lint.sh
Labels: kind/bug, lgtm, approved, size/M

#3573 change name error
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
Labels: lgtm, approved, size/S

#3570 fix lots of duplicate logs "Failed to get obj" in objectsync.go
  cloud/pkg/synccontroller/objectsync.go
Labels: kind/bug, lgtm, approved, size/S

#3577 Automated cherry pick of #3570: fix lots of duplicate logs "Failed to get obj" in
  cloud/pkg/synccontroller/objectsync.go
Labels: lgtm, approved, size/S

#3530 support multi architecture image build
  Makefile
  hack/make-rules/crossbuildimage.sh
Labels: kind/feature, lgtm, approved, size/L

#3104 log optimization modification: adjust log level, remove duplicate log
  edge/pkg/edged/edged.go
  edge/pkg/edged/status/status_manager.go
  edge/pkg/edgehub/process.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/process.go
  pkg/stream/edgedmetricsconnection.go
Labels: kind/cleanup, lgtm, approved, size/M

#3103 add usename and password to eventbus mqtt configuration
  edge/pkg/eventbus/eventbus.go
  edge/pkg/eventbus/mqtt/client.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
Labels: kind/bug, lgtm, approved, size/M

#3584 Update image tag of iptablesManager in helm to v1.9.1
  build/helm/cloudcore/Chart.yaml
  build/helm/cloudcore/README.md
  build/helm/cloudcore/values.yaml
Labels: lgtm, approved, size/S

#3576 fix wrong build image command for cloudclore
  build/cloud/README.md
  build/cloud/README_zh.md
  build/cloud/ha/README.md
Labels: lgtm, approved, size/XS

#3571 fix remove os.Exit in updateNodeKubeletEndpoint
  cloud/pkg/cloudstream/tunnelserver.go
  edge/pkg/edgestream/tunnel.go
  pkg/stream/message.go
Labels: kind/bug, lgtm, approved, size/S

#3591 use testing.TempDir to create temp directory
  keadm/cmd/keadm/app/cmd/util/common_test.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation_test.go
  pkg/apis/componentconfig/edgecore/v1alpha1/validation/validation_test.go
  pkg/util/validation/check_test.go
Labels: kind/cleanup, lgtm, approved, size/M
