Repository kubeedge/kubeedge, pull requests merged in 2022-03, with the labels that each got.

#3631 Update vendor to fix security alerts
  go.mod
  go.sum
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/registry/api/errcode/errors.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/hugetlb.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/dbus.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v2.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/message_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/modules.txt
Labels: kind/bug, size/L

#3629 add edgecore image build script
  build/docker/installation-package.dockerfile
  build/docker/installation-package.sh
Labels: kind/feature, lgtm, approved, size/M

#3641 keadm: fix wrong directory check
  keadm/cmd/keadm/app/cmd/edge/joinbeta.go
Labels: kind/bug, lgtm, approved, size/XS

#3626 Update build-tools to support arm arch
  build/docker/build-tools.dockerfile
  build/docker/build-tools/build-tools.dockerfile
  build/docker/build-tools/make-build-tools.sh
  build/docker/installation-package/installation-package.dockerfile
  build/docker/installation-package/installation-package.sh
Labels: kind/feature, size/M

#3517 add keadm propsals on the cloud
  docs/proposals/refactor-keadm-on-the-cloud.md
Labels: kind/documentation, kind/feature, lgtm, approved, size/L

#3534 keadm support config images cmd
  keadm/cmd/keadm/app/cmd/beta/beta.go
  keadm/cmd/keadm/app/cmd/beta/config.go
  keadm/cmd/keadm/app/cmd/common/constant.go
Labels: kind/feature, lgtm, approved, size/L

#3637 Add Edgemark for scalability test
  Makefile
  build/edgemark/Dockerfile
  build/edgemark/README.md
  build/edgemark/edgemark_setup_guide.md
  build/edgemark/hollow_edge_node_template.yaml
  build/edgemark/images/edgemark.jpg
  edge/cmd/edgemark/hollow_edgecore.go
  edge/pkg/edged/edged.go
  hack/lib/golang.sh
  hack/make-rules/crossbuildimage.sh
  hack/make-rules/image.sh
  vendor/k8s.io/cri-api/pkg/apis/testing/fake_image_service.go
  vendor/k8s.io/cri-api/pkg/apis/testing/fake_runtime_service.go
  vendor/k8s.io/cri-api/pkg/apis/testing/utils.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cri/remote/fake/doc.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cri/remote/fake/endpoint.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cri/remote/fake/endpoint_windows.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cri/remote/fake/fake_image_service.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cri/remote/fake/fake_runtime.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#3537 add keadm beta reset command
  keadm/cmd/keadm/app/cmd/beta/beta.go
  keadm/cmd/keadm/app/cmd/beta/reset.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/kubeclient.go
Labels: lgtm, approved, size/L

#3648 Automated cherry pick of #3537: add reset-beta command for keadm
  keadm/cmd/keadm/app/cmd/beta/beta.go
  keadm/cmd/keadm/app/cmd/beta/reset.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/kubeclient.go
Labels: lgtm, approved, size/L

#3645 Add release note for v1.10
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/README.md
Labels: kind/documentation, lgtm, approved, size/L

#3647 Update default version in keadm to v1.10
  keadm/cmd/keadm/app/cmd/common/constant.go
Labels: kind/cleanup, size/XS

#3651 Automated cherry pick of #3647: update default version in keadm to v1.10
  keadm/cmd/keadm/app/cmd/common/constant.go
Labels: lgtm, size/XS

#3649 modfiy v1.10 release note
  CHANGELOG/CHANGELOG-1.10.md
Labels: kind/documentation, lgtm, approved, size/XS

#3652 [fix] fix router log
  cloud/pkg/router/listener/http.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3656 clear invalid code in `common_test` file
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3664 make log level configurable for local up kubeedge
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS

#3667 update README_zh.md, syncing from README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/M

#3657 remove unnecessary type check
  build/helm/charts/charts.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3655 keadm: beta join support remote runtime
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/joinbeta.go
Labels: kind/feature, lgtm, approved, size/S

#3665 fix readinessProbe and startupProbe bug
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/M

#3685 Automated cherry pick of #3665: fix readinessProbe and startupProbe do not work after upgrade
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/M

#3684 Unnecessary fmt formatting in metaserver/util/util.go file
  pkg/metaserver/util/util.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3686 Automated cherry pick of #3467: add script for build release
  Makefile
  hack/make-rules/release.sh
Labels: lgtm, approved, size/L

#3673 remove unused constant
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3671 use dependency to pull images
  keadm/cmd/keadm/app/cmd/beta/config.go
Labels: kind/cleanup, lgtm, approved, size/M

#3689 Automated cherry pick of #3665: fix readinessProbe and startupProbe do not work after upgrade
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/M

#3698 Automated cherry pick of #3553: verify go version when call build.sh script
  .github/workflows/main.yaml
  Makefile
  hack/lib/golang.sh
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
  hack/make-rules/build.sh
  hack/make-rules/clean.sh
  hack/make-rules/crossbuild.sh
  hack/make-rules/release.sh
  hack/make-rules/smallbuild.sh
  hack/verify-golang.sh
Labels: lgtm, approved, size/L

#3696 add release note for v1.9.2
  CHANGELOG/CHANGELOG-1.9.md
Labels: kind/documentation, lgtm, approved, size/S

#3693 add subresource field in application
  cloud/pkg/dynamiccontroller/application/application.go
Labels: lgtm, approved, size/M

#3705 Automated cherry pick of #3605: fix memory leak in edgesite kube-api
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go
Labels: lgtm, approved, size/XS

#3703 Automated cherry pick of #3693: add subresource field in application
  cloud/pkg/dynamiccontroller/application/application.go
Labels: lgtm, approved, size/M

#3704 Automated cherry pick of #3693: add subresource field in application
  cloud/pkg/dynamiccontroller/application/application.go
Labels: lgtm, approved, size/M

#3663 Add myself to deviceTwin modules OWNERS approvers/edgehub modules OWNERS reviewers
  edge/pkg/devicetwin/OWNERS
  edge/pkg/edgehub/OWNERS
Labels: lgtm, approved, size/XS

#3707 keep viaduct/beehive dependency packages version the same with main repo
  go.sum
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/beehive/go.sum
  staging/src/github.com/kubeedge/viaduct/go.mod
  staging/src/github.com/kubeedge/viaduct/go.sum
Labels: kind/cleanup, lgtm, approved, size/M

#3710 Automated cherry pick of #3670: fix concurrent map iteration and map write bug
  cloud/pkg/dynamiccontroller/application/eventhandler.go
Labels: lgtm, approved, size/S

#3706 update CHANGELOG for v1.9.2
  CHANGELOG/CHANGELOG-1.9.md
Labels: kind/documentation, lgtm, approved, size/XS

#3709 Automated cherry pick of #3670: fix concurrent map iteration and map write bug
  cloud/pkg/dynamiccontroller/application/eventhandler.go
Labels: lgtm, approved, size/S

#3708 change log level for err info
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3712 use runtime.GOARCH get machine arch instead of running shell command directly
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/debinstaller.go
  keadm/cmd/keadm/app/cmd/util/pacmaninstaller.go
  keadm/cmd/keadm/app/cmd/util/rpminstaller.go
Labels: kind/cleanup, lgtm, approved, size/M

#3654 add custom image repo for keadm join beta
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/joinbeta.go
  pkg/image/image.go
  pkg/image/image_test.go
Labels: kind/feature, lgtm, approved, size/L

#3715 bump containerd to v1.5.10
  go.mod
  go.sum
  vendor/github.com/Microsoft/hcsshim/go.mod
  vendor/github.com/Microsoft/hcsshim/go.sum
  vendor/github.com/containerd/containerd/images/image.go
  vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
  vendor/github.com/containerd/containerd/remotes/docker/httpreadseeker.go
  vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/containerd/ttrpc/.gitignore
  vendor/github.com/containerd/ttrpc/.travis.yml
  vendor/github.com/containerd/ttrpc/README.md
  vendor/github.com/containerd/ttrpc/channel.go
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/codec.go
  vendor/github.com/containerd/ttrpc/config.go
  vendor/github.com/containerd/ttrpc/go.mod
  vendor/github.com/containerd/ttrpc/go.sum
  vendor/github.com/containerd/ttrpc/server.go
  vendor/github.com/containerd/ttrpc/services.go
  vendor/github.com/containerd/ttrpc/unixcreds_linux.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/XXL

#3700 keadm beta config images: support remote runtime
  keadm/cmd/keadm/app/cmd/beta/config.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/joinbeta.go
  keadm/cmd/keadm/app/cmd/util/image.go
  pkg/image/image.go
Labels: lgtm, approved, size/XL

#3692 Fix and move helm base dir
  hack/generate-crds.sh
  keadm/cmd/keadm/app/cmd/beta/beta.go
  keadm/cmd/keadm/app/cmd/beta/init-beta.go
  keadm/cmd/keadm/app/cmd/beta/init.go
  keadm/cmd/keadm/app/cmd/beta/manifest.go
  keadm/cmd/keadm/app/cmd/beta/reset.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/helm/installer.go
  keadm/cmd/keadm/app/cmd/helm/render.go
  keadm/cmd/keadm/app/cmd/util/cloudinstaller.go
  keadm/cmd/keadm/app/cmd/util/kubeclient.go
  manifests/addons/.gitkeep
  manifests/charts/cloudcore/Chart.yaml
  manifests/charts/cloudcore/README.md
  manifests/charts/cloudcore/crds/cluster_objectsync_v1alpha1.yaml
  manifests/charts/cloudcore/crds/devices_v1alpha2_device.yaml
  manifests/charts/cloudcore/crds/devices_v1alpha2_devicemodel.yaml
  manifests/charts/cloudcore/crds/objectsync_v1alpha1.yaml
  manifests/charts/cloudcore/crds/router_v1_rule.yaml
  manifests/charts/cloudcore/crds/router_v1_ruleEndpoint.yaml
  manifests/charts/cloudcore/templates/_helpers.tpl
  manifests/charts/cloudcore/templates/configmap_cloudcore.yaml
  manifests/charts/cloudcore/templates/daemonset_iptablesmanager.yaml
  manifests/charts/cloudcore/templates/deployment_cloudcore.yaml
  manifests/charts/cloudcore/templates/rbac_cloudcore.yaml
  manifests/charts/cloudcore/templates/rbac_iptablesmanager.yaml
  manifests/charts/cloudcore/templates/secret_cloudcore.yaml
  manifests/charts/cloudcore/templates/service_cloudcore.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/charts/edgemesh/README.md
  manifests/manifests.go
  manifests/profiles/version.yaml
  tests/e2e/scripts/helm_keadm_e2e.sh
Labels: lgtm, approved, size/XL, ok-to-test

#3679 fix unhanle error
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3720 use unified image management
  keadm/cmd/keadm/app/cmd/beta/config.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  pkg/image/image.go
Labels: kind/feature, lgtm, approved, size/L

#3721 Clean up unnecessary log output
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3723 Use armhf as default for armv7/v6
  .github/workflows/main.yaml
  build/docker/build-tools/build-tools.dockerfile
  hack/lib/golang.sh
Labels: kind/cleanup, lgtm, approved, size/XS

#3725 Automated cherry pick of #3723: support armhf
  .github/workflows/main.yaml
  hack/lib/golang.sh
Labels: size/XS

#3726 Automated cherry pick of #3723: support armhf
  .github/workflows/main.yaml
  build/docker/build-tools/build-tools.dockerfile
  hack/lib/golang.sh
Labels: size/XS

#3724 Add myself to manifests modules OWNERS approvers/reviewers
  keadm/OWNERS
  manifests/OWNERS
Labels: lgtm, approved, size/XS

#3730 set deleteResource func param allowsOptions true
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
Labels: kind/bug, lgtm, approved, size/XS

#3699 Add Keadm beta e2e
  .github/workflows/main.yaml
  Makefile
  hack/make-rules/crossbuildimage.sh
  hack/make-rules/image.sh
  keadm/cmd/keadm/app/cmd/beta/init.go
  keadm/cmd/keadm/app/cmd/beta/manifest.go
  tests/e2e/scripts/keadm_beta_e2e.sh
Labels: lgtm, approved, size/M

#3732 Clear unnecessary parameters
  keadm/cmd/keadm/app/cmd/beta/init.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3678 Fix local-up exit without error msg
  hack/lib/golang.sh
Labels: kind/test, lgtm, approved, size/XS

#3734 Add myself module keadm OWNERS approvers
  keadm/OWNERS
Labels: lgtm, approved, size/XS

#3733 remove redundant type conversion
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/XS

#3741 Automated cherry pick of #3730: set deleteResource func param allowsOptions true
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
Labels: lgtm, approved, size/XS

#3740 Automated cherry pick of #3730: set deleteResource func param allowsOptions true
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
Labels: lgtm, approved, size/XS

#3739 Update travis ci config for arm64
  .travis.yml
Labels: kind/test, lgtm, approved, size/S

#3745 PodConfigMapsAndSecrets should handle Projected volume
  cloud/pkg/edgecontroller/manager/location.go
Labels: lgtm, approved, size/S

#3748 remove unused shell
  edge/hack/setup_for_IEF.sh
Labels: lgtm, approved, size/L

#3750 optimize the redundant accessor in function sendObj
  cloud/pkg/dynamiccontroller/application/listener.go
Labels: kind/cleanup, lgtm, approved, size/S

#3746 Add e2e test for arm64
  .travis.yml
Labels: kind/test, lgtm, approved, size/S

#3738 admission: handle errors the right way
  cloud/cmd/admission/app/server.go
  cloud/pkg/admissioncontroller/admission.go
  pkg/util/flag/flags.go
Labels: kind/bug, lgtm, approved, size/S
