Repository kubeedge/kubeedge, pull requests merged in 2022-05, with the labels that each got.

#3717 rewrite eventbus subscribe: add message handler
  edge/pkg/eventbus/eventbus.go
  edge/pkg/eventbus/mqtt/client.go
  edge/pkg/eventbus/mqtt/filter.go
  edge/pkg/eventbus/mqtt/filter_test.go
  edge/pkg/eventbus/mqtt/handler.go
  edge/pkg/eventbus/mqtt/server.go
Labels: kind/design, lgtm, approved, size/L

#3821 bugfix: rule.Status variable update
  cloud/pkg/edgecontroller/controller/upstream.go
Labels: kind/bug, lgtm, approved, size/XS

#3827 replace deprecated function NewSerializer with NewSerializerWithOptions
  edge/pkg/metamanager/metaserver/kubernetes/serializer/serializer.go
Labels: kind/cleanup, lgtm, approved, size/XS

#3826 fix Remove container failed
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/S

#3643 keadm: unified access to version
  keadm/cmd/keadm/app/cmd/beta/config.go
  keadm/cmd/keadm/app/cmd/beta/manifest.go
  keadm/cmd/keadm/app/cmd/edge/joinbeta.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: kind/feature, lgtm, approved, size/L

#3831 Automated cherry pick of #3826: fix Remove container failed
  keadm/cmd/keadm/app/cmd/edge/image.go
Labels: lgtm, approved, size/S

#3836 remove default KubeConfig for cloudcore
  common/constants/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
Labels: lgtm, approved, size/XS

#3849 fix make lint error: GOPATH: unbound variable
  hack/lib/install.sh
Labels: lgtm, approved, size/XS

#3857 codegen update in repository
  Makefile
  hack/lib/util.sh
  hack/update-codegen.sh
Labels: lgtm, approved, size/S

#3863 update chart readme
  manifests/charts/cloudcore/README.md
Labels: kind/cleanup, lgtm, approved, size/XS

#3865 remove redundant type conversion
  cloud/test/integration/fixtures/devicemodel.go
Labels: kind/cleanup, lgtm, approved, size/S

#3875 refactor keadm beta join: return error if join failed
  keadm/cmd/keadm/app/cmd/edge/joinbeta.go
Labels: lgtm, approved, size/S

#3878 secretsutil cleanup
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
Labels: lgtm, approved, size/XS

#3658 use sync mode to update pod status
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edged/status/status_manager_test.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/metamanager.go
  edge/pkg/metamanager/metamanager_test.go
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/testing/fake_pod_deletion_safety.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/testing/mock_pod_status_provider.go
  vendor/modules.txt
Labels: lgtm, approved, size/L
