Repository kubeedge/kubeedge, pull requests merged in 2022-09, with the labels that each got.

#4097 remove nodeLocks from MessageHandle
  cloud/pkg/cloudhub/handler/messagehandler.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/quic.go
Labels: kind/cleanup, lgtm, approved, size/M

#4151 use module group name instead of src name as argument when `SendToGroup`
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/common/model/types.go
Labels: kind/cleanup, lgtm, approved, size/S

#4156 fix typo single to signal
  pkg/stream/edgedexecconnection.go
  pkg/stream/edgedlogconnection.go
  pkg/stream/edgedmetricsconnection.go
Labels: lgtm, approved, size/XS

#4150 optimize log in metamanager
  edge/pkg/metamanager/process.go
Labels: kind/cleanup, lgtm, approved, size/XS

#4162 Fix e2e bug
  edge/test/integration/scripts/execute.sh
  edge/test/integration/scripts/fast_test.sh
  tests/e2e/scripts/execute.sh
  tests/e2e/scripts/fast_test.sh
  tests/e2e/scripts/keadm_deprecated_e2e.sh
  tests/e2e/scripts/keadm_e2e.sh
  tests/e2e/utils/common.go
Labels: lgtm, approved, size/L

#4160 fix: Ignore the cache timestamp of the MachineInfo Metrics
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#4179 fix: Ignore the cache timestamp of the MachineInfo Metrics
  edge/pkg/edged/edged.go
Labels: kind/bug, lgtm, approved, size/S

#4178 fix: Ignore the cache timestamp of the MachineInfo Metrics
  edge/pkg/edged/edged.go
Labels: kind/bug, lgtm, approved, size/S

#4176 [cloudHub] move some helper function to package common
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/common/helper.go
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: kind/cleanup, lgtm, approved, size/L

#4104 Verify token when list/watch and add autonomy switch
  cloud/pkg/common/client/client.go
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/dynamiccontroller/application/application_test.go
  cloud/pkg/dynamiccontroller/application/eventhandler.go
  common/types/http.go
  edge/pkg/common/modules/names.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/status/status_manager_test.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgestream/edgestream.go
  edge/pkg/metamanager/client/configmap.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/node.go
  edge/pkg/metamanager/client/persistentvolume.go
  edge/pkg/metamanager/client/persistentvolumeclaim.go
  edge/pkg/metamanager/client/secret.go
  edge/pkg/metamanager/client/serviceaccount.go
  edge/pkg/metamanager/client/volumeattachment.go
  edge/pkg/metamanager/metamanager.go
  edge/pkg/metamanager/metamanager_test.go
  edge/pkg/metamanager/metaserver/config/config.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/watchhook/hooks.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
  edge/pkg/metamanager/metaserver/server.go
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
  edge/test/integration/metaserver/metaserver_suite_test.go
  edge/test/integration/metaserver/metaserver_test.go
  edge/test/test.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/meta/v1alpha1/types.go
Labels: kind/feature, lgtm, approved, size/L

#4056 Modify the process for err in metaserver
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/watchhook/hooks.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/watchhook/watchhook.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/watcher.go
Labels: kind/bug, lgtm, approved, size/M

#3743 fix residual terminating pods problem after edge node reconnected
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: kind/bug, size/XS

#4183 fix: mqtt broker was not deleted when it run failed
  keadm/cmd/keadm/app/cmd/reset.go
Labels: kind/bug, lgtm, approved, size/XS

#4186 Revert "fix residual terminating pods problem after edge node reconnected"
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: lgtm, approved, size/XS

#4112 [Feature-New-Edged]rename fake kubeclient with kubeclient bridge
  edge/pkg/edged/edged.go
  edge/pkg/edged/fake/fake_clientset.go
  edge/pkg/edged/fake/typed/core/v1/fake_configmap.go
  edge/pkg/edged/fake/typed/core/v1/fake_core_client.go
  edge/pkg/edged/fake/typed/core/v1/fake_node.go
  edge/pkg/edged/fake/typed/core/v1/fake_persistentvolume.go
  edge/pkg/edged/fake/typed/core/v1/fake_persistentvolumeclaim.go
  edge/pkg/edged/fake/typed/storage/v1/fake_storage_client.go
  edge/pkg/edged/fake/typed/storage/v1/fake_volumeattachment.go
  edge/pkg/edged/kubeclientbridge/clientset_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/configmap_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/core_client_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/node_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/persistentvolume_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/persistentvolumeclaim_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/storage/v1/storage_client_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/storage/v1/volumeattachment_bridge.go
Labels: kind/feature, lgtm, approved, size/XL

#4165 [Feature-New-Edged]add serviceaccount|secret client bridge
  edge/pkg/edged/kubeclientbridge/typed/core/v1/core_client_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/secret_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/serviceaccount_bridge.go
Labels: kind/feature, lgtm, approved, size/L

#4111 [Feature-New-Edged] add node-lease resource
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edged/kubeclientbridge/clientset_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/coordination/v1/coordination_client_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/coordination/v1/lease_bridge.go
  edge/pkg/metamanager/client/lease.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/node.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go
  edge/pkg/metamanager/process.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: kind/feature, lgtm, approved, size/L

#3859 refactor function: copy files from image to host
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/M

#4187 fix keadm_deprecated_e2e error
  tests/e2e/scripts/keadm_deprecated_e2e.sh
Labels: lgtm, approved, size/S

#4192 fix residual terminating pods problem after edge node reconnected
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: kind/bug, lgtm, approved, size/XS

#4119 bugfix sqlite 'transaction has already been committed or rolled back'
  edge/pkg/common/dbm/db.go
  edge/pkg/devicetwin/dtclient/device_db.go
  edge/pkg/devicetwin/dtclient/device_db_test.go
  edge/pkg/devicetwin/dtclient/deviceattr_db.go
  edge/pkg/devicetwin/dtclient/deviceattr_db_test.go
  edge/pkg/devicetwin/dtclient/devicetwin_db.go
  edge/pkg/devicetwin/dtclient/devicetwin_db_test.go
  edge/pkg/devicetwin/dtmanager/device_test.go
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/devicetwin/dtmanager/membership_test.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
Labels: kind/bug, lgtm, approved, size/L

#4193 Automated cherry pick of #4192: fix residual terminating pods problem after edge node
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: lgtm, approved, size/XS

#4194 Automated cherry pick of #4192: fix residual terminating pods problem after edge node
  cloud/pkg/cloudhub/handler/messagehandler.go
Labels: lgtm, approved, size/XS

#4022 Fix admission not work: bump admissionregistration.k8s.io/v1beta1 to admissionregistration.k8s.io/v1
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/admissioncontroller/admit_devicemodel.go
  cloud/pkg/admissioncontroller/admit_rule.go
  cloud/pkg/admissioncontroller/admit_ruleendpoint.go
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/admissioncontroller/mutate_offlinemigration.go
Labels: kind/bug, lgtm, approved, size/L

#3917 fix sendresp stuck occasionally when sendsync receive select exited
  staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go
Labels: kind/bug, lgtm, approved, size/XS

#3957 add controllerManager to manifest
  keadm/cmd/keadm/app/cmd/helm/installer.go
  manifests/charts/cloudcore/templates/deployment_controllermanager.yaml
  manifests/charts/cloudcore/templates/rbac_controllermanager.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/L

#4141 fix force delete pod when node is offline
  edge/pkg/edged/edged.go
Labels: kind/bug, lgtm, approved, size/S

#4152 [Feature-New-Edged] add register and patch node upstream operation
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/node_bridge.go
  edge/pkg/metamanager/client/node.go
  edge/pkg/metamanager/process.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: kind/feature, lgtm, approved, size/L

#4182 [Feature-New-Edged]add patch pod operation
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/core_client_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/pod_bridge.go
  edge/pkg/metamanager/client/pod.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: kind/feature, lgtm, approved, size/L

#3807 Pod running on edge node has invalid serviceaccount token
  edge/pkg/edged/volume_host.go
  edge/pkg/metamanager/client/serviceaccount.go
  edge/pkg/metamanager/process.go
Labels: kind/bug, lgtm, approved, size/L

#4199 Automated cherry pick of #3917: fix sendresp stuck occasionally when sendsync receive select
  staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go
Labels: lgtm, approved, size/XS

#4205 Automated cherry pick of #3807: Pod running on edge node has invalid serviceaccount token
  edge/pkg/edged/volume_host.go
  edge/pkg/metamanager/client/serviceaccount.go
  edge/pkg/metamanager/process.go
Labels: lgtm, approved, size/L

#4208 Automated cherry pick of #4187: fix keadm_deprecated_e2e error
  edge/test/integration/scripts/execute.sh
  edge/test/integration/scripts/fast_test.sh
  tests/e2e/scripts/execute.sh
  tests/e2e/scripts/fast_test.sh
  tests/e2e/scripts/helm_keadm_e2e.sh
  tests/e2e/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/L

#4207 Automated cherry pick of #4187: fix keadm_deprecated_e2e error
  edge/test/integration/scripts/execute.sh
  edge/test/integration/scripts/fast_test.sh
  tests/e2e/scripts/execute.sh
  tests/e2e/scripts/fast_test.sh
  tests/e2e/scripts/keadm_deprecated_e2e.sh
  tests/e2e/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/L

#4211 Automated cherry pick of #3917: fix sendresp stuck occasionally when sendsync receive select
  staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go
Labels: lgtm, approved, size/XS

#4204 Automated cherry pick of #3807: Pod running on edge node has invalid serviceaccount token
  edge/pkg/edged/volume_host.go
  edge/pkg/metamanager/client/serviceaccount.go
  edge/pkg/metamanager/process.go
Labels: lgtm, approved, size/L

#4196 fix delete and create same name pod failed occasionally
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/edged/edged.go
Labels: kind/bug, lgtm, approved, size/L

#4105 Cloudhub refactor implementation
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/common/helper.go
  cloud/pkg/cloudhub/common/io/hubio.go
  cloud/pkg/cloudhub/common/message_pool.go
  cloud/pkg/cloudhub/common/testing/test_framework.go
  cloud/pkg/cloudhub/dispatcher/message_dispatcher.go
  cloud/pkg/cloudhub/dispatcher/message_dispatcher_test.go
  cloud/pkg/cloudhub/handler/message_handler.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/cloudhub/servers/server.go
  cloud/pkg/cloudhub/session/node_session.go
  cloud/pkg/cloudhub/session/node_session_test.go
  cloud/pkg/cloudhub/session/session_manager.go
  cloud/pkg/cloudhub/session/session_manager_test.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/factory.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/testing/mock_conn.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go
  staging/src/github.com/kubeedge/viaduct/pkg/server/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/server/server.go
  staging/src/github.com/kubeedge/viaduct/pkg/server/ws.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#4217 Automated cherry pick of #3885: fix failed to rotate log for container for docker runtime
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#4215 Automated cherry pick of #4125: fix delete pod terminating stuck when pod is create and
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/edged/status/status_manager.go
  edge/pkg/edged/status/status_manager_test.go
  edge/pkg/metamanager/client/podstatus.go
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
Labels: lgtm, approved, size/L

#4214 [cherry-pick]fix delete and create same name pod failed occasionally
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/L

#4223 [cherry-pick]fix delete and create same name pod failed occasionally
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/L

#4222 Automated cherry pick of #4160: fix: Ignore the cache timestamp of the MachineInfo Metrics
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#4226 add featuregate for authorization
  cloud/pkg/dynamiccontroller/application/application.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
  edge/pkg/metamanager/metaserver/server.go
  edge/test/integration/metaserver/metaserver_suite_test.go
  pkg/apis/componentconfig/edgecore/v1alpha1/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/features/features.go
Labels: kind/feature, lgtm, approved, size/M

#4231 bugfix grep nodeReady in local-up shell
  hack/local-up-kubeedge.sh
Labels: kind/bug, lgtm, approved, size/XS

#4233 add change logs for v1.9.5 v1.10.3 v1.11.2
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: kind/documentation, lgtm, approved, size/M

#4238 Automated cherry pick of #4231: bugfix grep nodeReady in local-up shell
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS

#4240 fix application wrong cache ID
  cloud/pkg/dynamiccontroller/application/application.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/bug, lgtm, approved, size/M

#4242 Automated cherry pick of #4240: fix application wrong cache ID
  cloud/pkg/dynamiccontroller/application/application.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: lgtm, approved, size/M

#4241 Add release note for v1.12
  CHANGELOG/CHANGELOG-1.12.md
Labels: kind/documentation, lgtm, approved, size/M

#4247 update security audit reports link
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/S

#4232 fix cloudcore cluster role
  build/cloud/03-clusterrole.yaml
  manifests/charts/cloudcore/templates/rbac_cloudcore.yaml
Labels: kind/bug, lgtm, approved, size/XS

#4246 restore device integration test
  edge/test/integration/device/device_suite_test.go
  edge/test/integration/scripts/fast_test.sh
Labels: kind/test, lgtm, approved, size/S

#4249 start http server when featuregates requireAuthorization is false
  edge/pkg/metamanager/metaserver/server.go
  edge/test/integration/metaserver/metaserver_test.go
Labels: kind/feature, lgtm, approved, size/M

#4245 use kubelet default NodeStatusUpdateFrequency and NodeStatusReportFre…
  common/constants/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
Labels: lgtm, approved, size/XS

#4250 Automated cherry pick of #4232: fix cloudcore cluster role
  build/cloud/03-clusterrole.yaml
  manifests/charts/cloudcore/templates/rbac_cloudcore.yaml
Labels: lgtm, approved, size/XS

#4252 Automated cherry pick of #4246: restore device integration test
  edge/test/integration/device/device_suite_test.go
  edge/test/integration/scripts/fast_test.sh
Labels: lgtm, approved, size/S

#4253 Automated cherry pick of #4245: use kubelet default NodeStatusUpdateFrequency and
  common/constants/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
Labels: lgtm, approved, size/XS

#4234 add nodeupgradejob related rbac to cloudcore deployment
  build/cloud/03-clusterrole.yaml
  manifests/charts/cloudcore/templates/rbac_cloudcore.yaml
Labels: kind/feature, lgtm, approved, size/XS

#4254 Automated cherry pick of #4234: add nodeupgradejob related rbac to cloudcore deployment
  build/cloud/03-clusterrole.yaml
  manifests/charts/cloudcore/templates/rbac_cloudcore.yaml
Labels: lgtm, approved, size/XS

#4224 update NodeUpgradeJob Image description
  build/crds/operations/operations_v1alpha1_nodeupgradejob.yaml
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  cloud/pkg/nodeupgradejobcontroller/controller/util.go
  cloud/pkg/nodeupgradejobcontroller/controller/util_test.go
  edge/pkg/edgehub/upgrade/upgrade.go
  manifests/charts/cloudcore/crds/operations_v1alpha1_nodeupgradejob.yaml
  pkg/apis/operations/v1alpha1/type.go
Labels: kind/api-change, kind/cleanup, lgtm, approved, size/M

#4255 Automated cherry pick of #4249: start http server when featuregates requireAuthorization is
  edge/pkg/metamanager/metaserver/server.go
  edge/test/integration/metaserver/metaserver_test.go
Labels: lgtm, approved, size/M

#4244 bugfix delete statefulset pod
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
  tests/e2e/deployment/deployment_test.go
Labels: kind/bug, lgtm, approved, size/L

#4259 update changelog for 1.12.0, add Important Steps for new Edged
  CHANGELOG/CHANGELOG-1.12.md
Labels: kind/documentation, lgtm, approved, size/XS

#4257 Automated cherry pick of #4224: update NodeUpgradeJob Image description
  build/crds/operations/operations_v1alpha1_nodeupgradejob.yaml
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  cloud/pkg/nodeupgradejobcontroller/controller/util.go
  cloud/pkg/nodeupgradejobcontroller/controller/util_test.go
  edge/pkg/edgehub/upgrade/upgrade.go
  manifests/charts/cloudcore/crds/operations_v1alpha1_nodeupgradejob.yaml
  pkg/apis/operations/v1alpha1/type.go
Labels: lgtm, approved, size/M

#4258 Automated cherry pick of #4244: bugfix statefulset
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
  tests/e2e/deployment/deployment_test.go
Labels: lgtm, approved, size/L
