Repository kubeedge/kubeedge, pull requests merged in 2022-12, with the labels that each got.

#4367 integrate Codecov into CI
  .github/codecov.yml
  .github/workflows/main.yaml
  hack/lib/golang.sh
Labels: lgtm, approved, size/S

#4451 update edgeapplication yaml format
  docs/proposals/node-group-management.md
Labels: kind/cleanup, lgtm, approved, size/M

#4462 remove unreachable code and unused variable
  staging/src/github.com/kubeedge/viaduct/examples/chat/client.go
  staging/src/github.com/kubeedge/viaduct/examples/chat/server.go
Labels: kind/cleanup, lgtm, approved, size/XS

#4463 use new function instead deprecated function
  cloud/pkg/controllermanager/controllermanager.go
  edge/pkg/metamanager/metaserver/kubernetes/serializer/serializer.go
Labels: kind/cleanup, lgtm, approved, size/XS

#4467 [Course Task] test-devicemodel
  cloud/pkg/devicecontroller/manager/devicemodel_test.go
Labels: lgtm, approved, size/M

#4489 get-the-value-of-map-in-the-idiomatic-way
  staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go
Labels: lgtm, approved, size/XS

#4491 remove unused edge function
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
Labels: kind/cleanup, lgtm, approved, size/L

#4498 bump containerd to v1.5.16
  go.mod
  go.sum
  vendor/github.com/Microsoft/go-winio/README.md
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/Microsoft/go-winio/hvsock.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_nonwindows.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_windows.go
  vendor/github.com/Microsoft/go-winio/pkg/security/grantvmgroupaccess.go
  vendor/github.com/Microsoft/go-winio/pkg/security/syscall_windows.go
  vendor/github.com/Microsoft/go-winio/pkg/security/zsyscall_windows.go
  vendor/github.com/Microsoft/go-winio/privilege.go
  vendor/github.com/Microsoft/go-winio/vhd/vhd.go
  vendor/github.com/Microsoft/go-winio/vhd/zvhd_windows.go
  vendor/github.com/containerd/containerd/content/helpers.go
  vendor/github.com/containerd/containerd/content/local/store.go
  vendor/github.com/containerd/containerd/filters/filter.go
  vendor/github.com/containerd/containerd/filters/parser.go
  vendor/github.com/containerd/containerd/filters/quote.go
  vendor/github.com/containerd/containerd/namespaces/store.go
  vendor/github.com/containerd/containerd/platforms/platforms.go
  vendor/github.com/containerd/containerd/remotes/docker/auth/parse.go
  vendor/github.com/containerd/containerd/remotes/docker/pusher.go
  vendor/github.com/containerd/containerd/remotes/docker/status.go
  vendor/github.com/containerd/containerd/version/version.go
  vendor/golang.org/x/sys/AUTHORS
  vendor/golang.org/x/sys/CONTRIBUTORS
  vendor/golang.org/x/sys/cpu/cpu_other_riscv64.go
  vendor/golang.org/x/sys/unix/asm_bsd_riscv64.s
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/XXL
