Repository kubeedge/kubeedge, pull requests merged in 2022-02, with the labels that each got.

#3598 update README_zh
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/M

#3594 fix-3489 filter pod by nodeName
  edge/pkg/edged/edged.go
  edge/test/integration/utils/helpers/helpers.go
Labels: lgtm, approved, size/M

#3244 fix/reliable-message-delivery: ObjectSync must be created when the resource first sends to CloudHub
  cloud/pkg/cloudhub/channelq/channelq.go
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/synccontroller/createfailedobject.go
  cloud/pkg/synccontroller/synccontroller.go
Labels: kind/bug, lgtm, approved, size/L

#3599 Fix pv's objectsync spec.ObjectKind is empty
  build/helm/cloudcore/values.yaml
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/synccontroller/objectsync.go
Labels: lgtm, approved, size/M

#3606 Automated cherry pick of #3594: filter pod in edged modify the helper.go, add NodeName for
  edge/pkg/edged/edged.go
  edge/test/integration/utils/helpers/helpers.go
Labels: lgtm, approved, size/M

#3613 Fix-3585 pv's objectsync spec.ObjectKind is empty
  build/helm/cloudcore/values.yaml
  cloud/pkg/cloudhub/handler/messagehandler.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/synccontroller/objectsync.go
Labels: lgtm, approved, size/M

#3581 fix: add missing metrics func
  edge/pkg/edged/volume/csi/csi_metrics.go
  edge/pkg/edged/volume/csi/csi_plugin.go
Labels: kind/bug, lgtm, approved, size/L

#3625 buildx on x86
  hack/make-rules/crossbuildimage.sh
Labels: lgtm, approved, size/XS
