Repository kubeedge/kubeedge, pull requests merged in 2023-05, with the labels that each got.

#4762 Add the field 'nodeName' in the HTTP header of the rest Router
  cloud/pkg/router/provider/rest/rest.go
Labels: kind/feature, lgtm, approved, size/XS

#4784 Update the timeout to 40 mins for docker image ci test
  .github/workflows/main.yaml
Labels: kind/test, lgtm, approved, size/XS

#4785 wait for cache sync
  cloud/pkg/common/informers/informer_manager.go
Labels: kind/bug, lgtm, approved, size/XS

#4786 Automated cherry pick of #4785: wait for cache sync
  cloud/pkg/common/informers/informer_manager.go
Labels: lgtm, approved, size/XS

#4780 use os.ReadFile
  build/conformance/e2e-runner/run.go
Labels: kind/cleanup, lgtm, approved, size/XS

#4775 Change the webhook-configuration name
  cloud/pkg/admissioncontroller/admission.go
Labels: kind/bug, lgtm, approved, size/XS

#4753 simplified regexp and fix grammar error
  .golangci.yml
  build/cloud/ha/01-ha-prepare.yaml
  build/crds/devices/devices_v1alpha2_device.yaml
  cloud/pkg/devicecontroller/types/deviceprofile.go
  docs/proposals/device-management-enhance.md
  keadm/cmd/keadm/app/cmd/util/common.go
  manifests/charts/cloudcore/crds/devices_v1alpha2_device.yaml
  pkg/apis/devices/v1alpha2/device_instance_types.go
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
Labels: kind/cleanup, lgtm, approved, size/S
