Repository kubeedge/kubeedge, pull requests merged in 2023-08, with the labels that each got.

#4909 deprecated RegisterWithTaints parameter
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/bug, lgtm, approved, size/XS

#4915 Fixed the cloudcore panic caused by the ClusterObjectSyncList item error
  pkg/apis/reliablesyncs/v1alpha1/type.go
  pkg/apis/reliablesyncs/v1alpha1/zz_generated.deepcopy.go
Labels: kind/bug, lgtm, approved, size/XS

#4918 Automated cherry pick of #4915: Fixed the cloudcore panic caused by the ClusterObjectSyncList
  pkg/apis/reliablesyncs/v1alpha1/type.go
  pkg/apis/reliablesyncs/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, size/XS

#4911 Optimize functions to improve code readability
  cloud/pkg/controllermanager/edgeapplication/overridemanager/imageparser/imageparser.go
Labels: kind/cleanup, lgtm, approved, size/XS

#4834 Fixed the kubeedge-version flag does not take effect
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cloud/manifest.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/helm/installer.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: kind/bug, lgtm, approved, size/L

#4773 fix the problem of not being able to create multiple servicebus to rest's rules
  edge/pkg/servicebus/servicebus.go
Labels: kind/bug, lgtm, approved, size/XS

#4935 Automated cherry pick of #4834: Fixed the kubeedge-version flag does not take effect in the
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cloud/manifest.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/helm/installer.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
Labels: lgtm, approved, size/L

#4936 Automated cherry pick of #4834: Fixed the kubeedge-version flag does not take effect in the
  .github/workflows/main.yaml
  hack/local-up-kubeedge.sh
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cloud/manifest.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/helm/installer.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
  tests/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/L

#4937 Automated cherry pick of #4834: Fixed the kubeedge-version flag does not take effect in the
  .github/workflows/main.yaml
  hack/local-up-kubeedge.sh
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cloud/manifest.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/helm/installer.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_test.go
  tests/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/L

#4940 Fix keadm e2e test ci failure
  .github/workflows/main.yaml
  hack/local-up-kubeedge.sh
  tests/scripts/keadm_e2e.sh
Labels: kind/bug, lgtm, approved, size/XS

#4934 add cl2017 as reviewer
  cloud/pkg/devicecontroller/OWNERS
  edge/pkg/devicetwin/OWNERS
Labels: lgtm, approved, size/XS

#4947 update golang version 1.19.12 for build tool
  build/docker/build-tools/build-tools.dockerfile
  build/docker/build-tools/make-build-tools.sh
Labels: kind/feature, lgtm, approved, size/S

#4950 revert build tool ubuntu version to 18.04
  build/docker/build-tools/build-tools.dockerfile
  build/docker/build-tools/make-build-tools.sh
  build/docker/installation-package/installation-package.dockerfile
Labels: kind/bug, lgtm, approved, size/XS

#4951 Don't run docker prune in local-up cluster
  hack/local-up-kubeedge.sh
Labels: kind/test, lgtm, approved, size/XS

#4953 update kubeedge build tool image 1.19.12-ke2
  .github/workflows/main.yaml
  .github/workflows/release.yml
  build/docker/installation-package/installation-package.dockerfile
  hack/make-rules/build_with_container.sh
Labels: kind/bug, lgtm, approved, size/S

#4939 Add e2e compatibility test
  .github/workflows/main.yaml
  Makefile
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
  tests/scripts/execute.sh
Labels: kind/feature, lgtm, approved, size/M

#4698 fix typo and update comments
  build/crds/reliablesyncs/cluster_objectsync_v1alpha1.yaml
  build/crds/reliablesyncs/objectsync_v1alpha1.yaml
  build/rpm/README.md
  cloud/pkg/controllermanager/edgeapplication/edgeapplicationcontroller.go
  cloud/pkg/controllermanager/edgeapplication/statusmanager/reconciler.go
  cloud/pkg/controllermanager/edgeapplication/statusmanager/statusmanager.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  common/constants/default.go
  docs/proposals/refactor-keadm-on-the-cloud.md
  edge/pkg/common/modules/group.go
  edge/pkg/common/util/config.go
  edge/pkg/devicetwin/dttype/types_helper.go
  edge/test/integration/utils/edge/testcontext.go
  edge/test/integration/utils/helpers/helpers.go
  edge/test/test.go
  hack/generate-crds.sh
  hack/lib/install.sh
  hack/sync-subproject-code.sh
  hack/update-vendor-licenses.sh
  manifests/charts/cloudcore/crds/cluster_objectsync_v1alpha1.yaml
  manifests/charts/cloudcore/crds/objectsync_v1alpha1.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
  pkg/apis/apps/v1alpha1/nodegroup_types.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
  pkg/apis/devices/v1alpha2/device_instance_types.go
  pkg/apis/reliablesyncs/v1alpha1/type.go
  pkg/metaserver/key.go
Labels: kind/cleanup, lgtm, approved, size/L

#4960 fix ci with cri config
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#4963 Fix throws nil runtime error when decode AdmissionReview failed
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/admissioncontroller/common_test.go
  cloud/test/httpfake/http_fake.go
Labels: kind/bug, lgtm, approved, size/M
