Repository kubeedge/kubeedge, pull requests merged in 2023-03, with the labels that each got.

#4655 Add adopter logo
  ADOPTERS.md
  docs/adopters/daocloud.svg
Labels: kind/documentation, lgtm, approved, size/S

#3822 add edge node upgrade proposal
  docs/images/edge-node-upgrade/upgrade.png
  docs/proposals/edge-node-upgrade.md
Labels: kind/documentation, lgtm, approved, size/L

#4620 fix iptables-manager controller-manager image name
  .github/workflows/release.yml
  hack/make-rules/crossbuildimage.sh
  hack/make-rules/imageprocess.sh
Labels: kind/cleanup, lgtm, approved, size/S

#4677 bugfix property type not match the type in mappers
  edge/pkg/devicetwin/dmiserver/event_type.go
Labels: kind/bug, lgtm, approved, size/XS

#4686 fix the bug of report illegal devicetwin value for the first time
  edge/pkg/devicetwin/dtmanager/twin.go
Labels: kind/bug, lgtm, approved, size/XS, sig/device-iot

#4689 Standardization of prompt messages for keadm command parameters
  keadm/cmd/keadm/app/cmd/edge/join.go
Labels: kind/documentation, lgtm, approved, size/S
