Repository kubeedge/kubeedge, pull requests merged in 2023-12, with the labels that each got.

#5243 Add v1.12.6, v1.13.4, v1.14.4 changelog
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
Labels: kind/documentation, lgtm, approved, size/M

#5240 Automated cherry pick of #5239: bump slsaframworker to v1.9.0
  .github/workflows/release.yml
Labels: lgtm, approved, size/XS

#5245 update workflow to 1.27.7
  .github/workflows/schedule.yml
Labels: kind/feature, lgtm, approved, size/S

#5174 update mapper framework config file
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/resource/configmap.yaml
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/resource/deployment.yaml
Labels: kind/feature, lgtm, approved, size/M

#5225 endpoint should not created successfully if the port is invalid
  cloud/pkg/admissioncontroller/admit_ruleendpoint.go
  cloud/pkg/admissioncontroller/admit_ruleendpoint_test.go
Labels: kind/bug, lgtm, approved, size/L

#5267 Correct word spelling mistakes
  pkg/metaserver/application.go
Labels: lgtm, approved, size/XS

#5269 Deprecate the edgecore containerized deployment solution
  build/edge/.env
  build/edge/README.md
  build/edge/README_zh.md
  build/edge/docker-compose.yaml
  build/edge/run_daemon.sh
Labels: kind/cleanup, lgtm, approved, size/L

#5252 modification for edged config
  edge/pkg/edged/config/config.go
  edge/pkg/edged/edged.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default_kubelet_configuration.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
  pkg/apis/componentconfig/edgecore/v1alpha2/validation/validation.go
  pkg/apis/componentconfig/edgecore/v1alpha2/validation/validation_others.go
  pkg/apis/componentconfig/edgecore/v1alpha2/validation/validation_windows.go
Labels: kind/cleanup, kind/feature, lgtm, approved, size/L

#5271 Automated cherry pick of #5254: fix default staticPodPath in windows
  common/constants/default.go
  common/constants/default_others.go
  common/constants/default_windows.go
Labels: lgtm, approved, size/XS

#5270 fix featuregates didn't take effect in edged config
  edge/pkg/edged/edged.go
Labels: kind/bug, lgtm, approved, size/XS

#5278 Update slack invitation link
  CONTRIBUTING.md
  README.md
  README_zh.md
Labels: kind/cleanup, lgtm, approved, size/XS

#5244 Init owners for changelog
  CHANGELOG/OWNERS
Labels: kind/documentation, lgtm, approved, size/S

#5276 Replace deprecated `io/ioutil` function
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/publish/http/client.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/config/config.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/httpserver/server.go
Labels: kind/feature, lgtm, approved, size/S

#5298 Automated cherry pick of #5270: fix featuregates didn't take effect in edged config
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/XS

#5297 Automated cherry pick of #5270: fix featuregates didn't take effect in edged config
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/XS

#5296 Automated cherry pick of #5270: fix featuregates didn't take effect in edged config
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/XS

#5295 Automated cherry pick of #5270: fix featuregates didn't take effect in edged config
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/XS

#5230 update mapper framework const
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicetwin.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/const.go
Labels: kind/cleanup, lgtm, approved, size/S

#5279 fix mutex unlock
  edge/pkg/devicetwin/dmiserver/server.go
Labels: kind/bug, lgtm, approved, size/XS

#5250 Change dmi-api reference method
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicetwin.go
  staging/src/github.com/kubeedge/mapper-framework/go.mod
  staging/src/github.com/kubeedge/mapper-framework/go.sum
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/register.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/report.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcserver/device.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcserver/server.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/type.go
Labels: kind/feature, lgtm, approved, size/M

#5305 remove unused protocol field
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/global/global.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/parse.go
Labels: kind/cleanup, lgtm, approved, size/S

#5312 join node cancels pause images
  pkg/image/image.go
  pkg/image/image_test.go
Labels: kind/bug, lgtm, approved, size/M

#5320 eventbus constant optimization
  cloud/pkg/router/provider/eventbus/eventbus.go
Labels: kind/cleanup, lgtm, approved, size/XS

#5313 Fix Metaserver Panic when Handling POST 2.
  edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go
  go.mod
Labels: kind/bug, lgtm, approved, size/S

#5288 fix mapper framework generate.sh to build image successfully
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/tdengine/client.go
  staging/src/github.com/kubeedge/mapper-framework/hack/make-rules/generate.sh
Labels: kind/bug, lgtm, approved, size/S

#5281 Update parse/grpc.go in mapper-framework
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/const.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/feature, lgtm, approved, size/L, sig/device-iot

#5328 fix device status problem
  cloud/pkg/devicecontroller/controller/upstream.go
Labels: kind/bug, lgtm, approved, size/S
