Repository kubeedge/kubeedge, pull requests merged in 2023-11, with the labels that each got.

#5097 Delete the historical version of CRD in cloudcore/CRD.
  manifests/charts/cloudcore/crds/devices_v1alpha2_device.yaml
  manifests/charts/cloudcore/crds/devices_v1alpha2_devicemodel.yaml
Labels: lgtm, approved, size/XL

#5151 servicebus constant optimization
  edge/pkg/common/message/message.go
  edge/pkg/servicebus/servicebus.go
Labels: kind/cleanup, lgtm, approved, size/XS

#5150 Automated cherry pick of #5036: Solving the deployment order dependency of mapper and device
  edge/pkg/devicetwin/dtmanager/dmiworker.go
Labels: lgtm, approved, size/S

#5149 Automated cherry pick of #5036: Solving the deployment order dependency of mapper and device
  edge/pkg/devicetwin/dtmanager/dmiworker.go
Labels: lgtm, approved, size/S

#5148 Automated cherry pick of #5036: Solving the deployment order dependency of mapper and device
  edge/pkg/devicetwin/dtmanager/dmiworker.go
Labels: lgtm, approved, size/S

#5125 Automated cherry pick of #4881: fix the bug in local-up mode that causes cni to not launch
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/M

#5146 bump go version to 1.20
  .github/workflows/fossa.yml
  .github/workflows/main-doc.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yml
  .github/workflows/schedule.yml
  build/admission/Dockerfile
  build/cloud/Dockerfile
  build/conformance/Dockerfile
  build/conformance/nodeconformance.Dockerfile
  build/controllermanager/Dockerfile
  build/csidriver/Dockerfile
  build/docker/installation-package/installation-package.dockerfile
  build/edge/Dockerfile
  build/edgemark/Dockerfile
  build/edgesite/agent-build.Dockerfile
  build/edgesite/server-build.Dockerfile
  build/iptablesmanager/Dockerfile
  cloud/pkg/policycontroller/manager/reconcile_test.go
  go.mod
  hack/lib/golang.sh
  hack/make-rules/build_with_container.sh
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/mapper-framework/go.mod
  staging/src/github.com/kubeedge/mapper-framework/go.sum
  staging/src/github.com/kubeedge/viaduct/go.mod
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, size/L

#5155 Automated cherry pick of #5120: modify parameters for ginkgo v2
  build/conformance/e2e-runner/run.go
  build/conformance/kubernetes/edge_skip_case.yaml
  build/conformance/node-e2e-runner/run.go
  build/conformance/util/util.go
  edge/test/integration/utils/common/log.go
  tests/e2e/apps/deployment.go
  tests/e2e/device/device.go
  tests/e2e/rule/rule.go
  tests/e2e/utils/log.go
  tests/e2e_edgesite/edgesite_test.go
  tests/e2e_keadm/keadm_test.go
Labels: lgtm, approved, size/M

#5147 Automated cherry pick of #5097: Delete the historical version of CRD in cloudcore/CRD.
  manifests/charts/cloudcore/crds/devices_v1alpha2_device.yaml
  manifests/charts/cloudcore/crds/devices_v1alpha2_devicemodel.yaml
Labels: lgtm, approved, size/XL

#5161 Refactor the code for skip environment check
  edge/cmd/edgecore/app/server.go
Labels: lgtm, approved, size/S

#5169 fix go version verify
  hack/lib/golang.sh
Labels: kind/bug, lgtm, approved, size/XS

#5141 Fix Metaserver Panic when Handling POST.
  edge/pkg/metamanager/metaserver/kubernetes/serializer/serializer.go
Labels: kind/bug, lgtm, approved, size/XS

#5165 add 'push conformance image to dockerhub' in release.yaml
  .github/workflows/release.yml
  hack/make-rules/imageprocess.sh
Labels: kind/feature, lgtm, approved, size/XS

#5176 add go test for NegotiateTunnelPort function
  cloud/cmd/cloudcore/app/server_test.go
  hack/lib/golang.sh
Labels: kind/feature, lgtm, approved, size/M

#5179 [release-1.12]Fix copy resources from the image throws nil runtimg error
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: kind/bug, lgtm, approved, size/S

#5188 Automated cherry pick of #5179: Fix copy resources from the image throws nil runtimg error
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5144 remove pid namespace config in copy-resource
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: kind/bug, lgtm, approved, size/XS

#5183 Automated cherry pick of #5141: Fix edgecore's metaserver panic when handling create, update,
  edge/pkg/metamanager/metaserver/kubernetes/serializer/serializer.go
Labels: lgtm, approved, size/XS

#5184 Automated cherry pick of #5141: Fix edgecore's metaserver panic when handling create, update,
  edge/pkg/metamanager/metaserver/kubernetes/serializer/serializer.go
Labels: lgtm, approved, size/XS

#5192 Automated cherry pick of #5144: remove pid config in copy resource
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5191 Automated cherry pick of #5144: remove pid config in copy resource
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5187 Automated cherry pick of #5049: feat: update to support release windows/amd64
  .github/workflows/release.yml
  Makefile
  hack/lib/golang.sh
  hack/make-rules/release.sh
Labels: lgtm, approved, size/L

#5112 Fixed a null pointer error when PushMethod is not defined for device properties.
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/bug, lgtm, approved, size/M, sig/device-iot

#5156 Correct the server IP of quic on edge nodes.
  common/constants/default.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/deprecated/join.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
  manifests/charts/cloudcore/templates/configmap_cloudcore.yaml
  manifests/charts/cloudcore/values.yaml
Labels: kind/bug, lgtm, approved, size/M

#5137 Init owners for mapper-framework
  staging/src/github.com/kubeedge/mapper-framework/OWNERS
Labels: kind/documentation, lgtm, approved, size/XS

#5190 fix ginkgo version in schedule test
  .github/workflows/schedule.yml
Labels: kind/bug, kind/failing-test, lgtm, approved, size/XS

#5200 remove deprecated func of create v1alpha1 edgecoreconfig in keadm
  keadm/cmd/keadm/app/cmd/edge/join_others.go
Labels: kind/cleanup, lgtm, approved, size/M

#5201 [release-1.15] update version for kubernetes 1.26.10
  .github/workflows/main.yaml
  common/constants/default.go
Labels: kind/bug, kind/cleanup, lgtm, approved, size/XS

#5204 Automated cherry pick of #5112: Fixed a null pointer error when PushMethod is not defined for device properties
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: lgtm, approved, size/M

#5070 mapper framework fix
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/cmd/main.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicetwin.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/config.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/register.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/report.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/parse.go
Labels: kind/bug, lgtm, approved, size/S

#5208 Automated cherry pick of #5070: mapper framework fix
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/cmd/main.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicetwin.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/config.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/register.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/report.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/parse.go
Labels: lgtm, approved, size/S

#5213 Automated cherry pick of #5107: Fix error logs for nodegroupx
  cloud/pkg/controllermanager/nodegroup/nodegroupcontroller.go
Labels: lgtm, approved, size/XS

#5212 Automated cherry pick of #5107: Fix error logs for nodegroupx
  cloud/pkg/controllermanager/nodegroup/nodegroupcontroller.go
Labels: lgtm, approved, size/XS

#5211 Automated cherry pick of #5107: Fix error logs for nodegroupx
  cloud/pkg/controllermanager/nodegroup/nodegroupcontroller.go
Labels: lgtm, approved, size/XS

#5210 Automated cherry pick of #5107: Fix error logs for nodegroupx
  cloud/pkg/controllermanager/nodegroup/nodegroupcontroller.go
Labels: lgtm, approved, size/XS

#5206 fix issues caused by constants deleted during the Kubernetes upgrade
  keadm/cmd/keadm/app/cmd/reset_windows.go
Labels: kind/bug, lgtm, approved, size/XS

#5140 Resolve that users do not need to define the status module in device. yaml.
  cloud/pkg/devicecontroller/controller/upstream.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/bug, lgtm, approved, size/M

#5207 update go version in mapper Dockerfile
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#5065 bugfix: device model sync
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: kind/bug, lgtm, approved, size/M

#5217 Automated cherry pick of #5140: Define Twin based on properties in mapper.
  cloud/pkg/devicecontroller/controller/upstream.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: lgtm, approved, size/M

#5221 Automated cherry pick of #5065: bugfix: device model sync
  cloud/pkg/devicecontroller/controller/downstream.go
Labels: lgtm, approved, size/M

#5226 Add CHANGELOG for v1.15.1
  CHANGELOG/CHANGELOG-1.15.md
Labels: kind/documentation, lgtm, approved, size/S

#5222 optimize variable names
  cloud/pkg/controllermanager/controllermanager.go
Labels: kind/cleanup, lgtm, approved, size/XS

#5218 update Kubernetes compatibility
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/S

#5219 refactor mapper config
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/cmd/main.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/config.yaml
  staging/src/github.com/kubeedge/mapper-framework/pkg/config/config.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/config.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/register.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/report.go
Labels: kind/feature, lgtm, approved, size/M, sig/device-iot

#5239 bump `slsa-framework / slsa-github-generator` to v1.9.0
  .github/workflows/release.yml
Labels: kind/bug, lgtm, approved, size/XS

#5241 Automated cherry pick of #5239: bump slsaframworker to v1.9.0
  .github/workflows/release.yml
Labels: lgtm, approved, size/XS
