Repository kubeedge/kubeedge, pull requests merged in 2023-01, with the labels that each got.

#4525 fix log output format fails
  cloud/pkg/dynamiccontroller/filter/endpointresource/endpointresource.go
Labels: kind/bug, lgtm, approved, size/XS

#4537 Optimize the comparison mode of bool judgment
  edge/pkg/devicetwin/dtmanager/device_test.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
  edge/pkg/devicetwin/process_test.go
  edge/pkg/edgehub/common/http/http_test.go
  edge/pkg/metamanager/metaserver/agent/agent_test.go
  edge/pkg/metamanager/process_test.go
Labels: kind/cleanup, lgtm, approved, size/M

#4536 Use errors.Is to check for a specific error
  cloud/pkg/cloudstream/containerexec_connection.go
  pkg/stream/edgedexecconnection.go
  pkg/stream/edgedlogconnection.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/quic.go
  staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go
  staging/src/github.com/kubeedge/viaduct/pkg/lane/ws.go
  staging/src/github.com/kubeedge/viaduct/pkg/lane/wsnopack.go
  staging/src/github.com/kubeedge/viaduct/pkg/packer/reader.go
Labels: kind/cleanup, lgtm, approved, size/S

#4527 update sandboxImage to kubeedge/pause:3.6
  common/constants/default.go
  pkg/apis/componentconfig/edgecore/v1alpha1/types.go
  pkg/image/image_test.go
Labels: lgtm, approved, size/S

#4548 new keadm support v1alpha1 edge config
  keadm/cmd/keadm/app/cmd/edge/join.go
Labels: kind/feature, lgtm, approved, size/L

#4533 replace default runtime docker with containerd
  .github/workflows/main.yaml
  common/constants/default.go
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
  keadm/cmd/keadm/app/cmd/config.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/reset.go
  tests/e2e/scripts/keadm_deprecated_e2e.sh
  tests/e2e/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/M

#4529 k8s: Add node-role.kubernetes.io/control-plane taint
  build/controllermanager/controllermanager-deploy.yaml
  build/iptablesmanager/iptablesmanager-ds.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/S

#4526 Reused common default docker parm.
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/debug/check.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
  keadm/cmd/keadm/app/cmd/debug/diagnose.go
Labels: kind/cleanup, lgtm, approved, size/S

#4497 Added UT of syncController
  cloud/pkg/synccontroller/config/config_test.go
  cloud/pkg/synccontroller/objectsync_test.go
  cloud/pkg/synccontroller/synccontroller_test.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#4496 remove unnecessary get requests for objectsync
  cloud/pkg/cloudhub/session/node_session.go
Labels: kind/cleanup, lgtm, approved, size/S

#4494 increase codecov successful uploads
  .github/workflows/main.yaml
Labels: lgtm, approved, size/XS

#4493 ignore not found err when delete objectsync
  cloud/pkg/cloudhub/session/node_session.go
Labels: kind/cleanup, lgtm, approved, size/XS

#4285 [Sig-Security] Generation of SLSA3+ provenance for KubeEdge release artifacts
  .github/workflows/release.yml
  hack/make-rules/imageprocess.sh
Labels: kind/cleanup, lgtm, approved, size/L, sig/security

#4469 clean up handlerCenter and SelectorListener
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/dynamiccontroller/application/eventhandler.go
  cloud/pkg/dynamiccontroller/application/listener.go
Labels: kind/cleanup, lgtm, approved, size/M

#4282 make it easier to restart cloudcore in local-up-kubeedge.sh
  hack/local-up-kubeedge.sh
Labels: kind/cleanup, lgtm, approved, size/XS

#4488 do not save edgecore token on disk
  common/constants/default.go
  edge/cmd/edgecore/app/server.go
  edge/pkg/edgehub/certificate/certmanager.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: lgtm, approved, size/M, sig/security

#4520 fix keadm join using cri-o error: cannot generate pod name without namespace
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#3646 add metric for cloudcore monitoring
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/session/session_manager.go
  cloud/pkg/common/monitor/monitor.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation_test.go
Labels: lgtm, approved, size/L

#4377 remove pod cache
  cloud/pkg/edgecontroller/manager/common.go
  cloud/pkg/edgecontroller/manager/common_test.go
  cloud/pkg/edgecontroller/manager/configmap.go
  cloud/pkg/edgecontroller/manager/event_filter.go
  cloud/pkg/edgecontroller/manager/node.go
  cloud/pkg/edgecontroller/manager/pod.go
  cloud/pkg/edgecontroller/manager/pod_test.go
  cloud/pkg/edgecontroller/manager/rule.go
  cloud/pkg/edgecontroller/manager/ruleendpoint.go
  cloud/pkg/edgecontroller/manager/secret.go
Labels: kind/feature, lgtm, approved, size/L

#4360 Unit Tests for edge/pkg/edgehub
  edge/pkg/edgehub/certificate/certmanager_test.go
  edge/pkg/edgehub/clients/quicclient/quicclient_test.go
  edge/pkg/edgehub/config/config_test.go
  edge/pkg/edgehub/edgehub_test.go
  edge/pkg/edgehub/upgrade/upgrade_test.go
Labels: kind/test, lgtm, approved, size/XL

#4476 add concurrency to NodeUpgradeJob
  build/crds/operations/operations_v1alpha1_nodeupgradejob.yaml
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/admissioncontroller/admit_nodeupgradejob.go
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  manifests/charts/cloudcore/crds/operations_v1alpha1_nodeupgradejob.yaml
  pkg/apis/operations/v1alpha1/type.go
Labels: lgtm, approved, size/L

#4256 add integration test for edgeapplication and nodegroup controller
  Makefile
  cloud/cmd/controllermanager/app/controllermanager.go
  cloud/pkg/controllermanager/controllermanager.go
  cloud/pkg/controllermanager/edgeapplication/edgeapplicationcontroller.go
  cloud/pkg/controllermanager/edgeapplication/statusmanager/statusmanager.go
  cloud/pkg/controllermanager/nodegroup/nodegroupcontroller.go
  cloud/test/integration/controllermanager/controllermanager_suite_test.go
  cloud/test/integration/controllermanager/controllermanager_test.go
  cloud/test/integration/scripts/execute.sh
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/helper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/errors.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_other.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/certs/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/auth.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/kubectl.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/arguments.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/bin_path_finder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
Labels: kind/test, lgtm, approved, size/XXL

#4490 fix 10s delay for edge request when the node is offline
  edge/pkg/common/cloudconnection/cloud_connection.go
  edge/pkg/common/cloudconnection/cloudconstants.go
  edge/pkg/edgehub/process.go
  edge/pkg/metamanager/config/config.go
  edge/pkg/metamanager/metaserver/agent/agent.go
  edge/pkg/metamanager/metaserver/agent/agent_test.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
Labels: kind/bug, lgtm, approved, size/L

#4281 fix panic when edgehub retry connect to cloudhub
  edge/pkg/edgehub/clients/quicclient/quicclient.go
  edge/pkg/edgehub/clients/wsclient/websocket.go
Labels: kind/bug, lgtm, approved, size/S

#4375 add generic informer
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/common/client/client.go
  cloud/pkg/common/informers/fake_informer_manager.go
  cloud/pkg/common/informers/informer_manager.go
  cloud/pkg/common/informers/informers.go
  cloud/pkg/devicecontroller/devicecontroller.go
  cloud/pkg/dynamiccontroller/application/eventhandler.go
  cloud/pkg/dynamiccontroller/dynamiccontroller.go
  cloud/pkg/dynamiccontroller/filter/util.go
  cloud/pkg/edgecontroller/edgecontroller.go
  cloud/pkg/edgecontroller/manager/configmap_test.go
  cloud/pkg/edgecontroller/manager/node_test.go
  cloud/pkg/edgecontroller/manager/pod_test.go
  cloud/pkg/edgecontroller/manager/rule_test.go
  cloud/pkg/edgecontroller/manager/ruleendpoint_test.go
  cloud/pkg/edgecontroller/manager/secret_test.go
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  cloud/pkg/nodeupgradejobcontroller/controller/upstream.go
  cloud/pkg/nodeupgradejobcontroller/nodeupgradejobcontroller.go
  cloud/pkg/synccontroller/objectsync.go
  cloud/pkg/synccontroller/objectsync_test.go
  cloud/pkg/synccontroller/synccontroller.go
Labels: kind/feature, lgtm, approved, size/XL

#4382 set NodeStatusImage not to be reported
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
Labels: kind/feature, lgtm, approved, size/XS

#4415 optimize convert kubelet flag: support more parameter
  common/constants/default.go
  edge/pkg/edged/config/config.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/feature, lgtm, approved, size/M

#4376 auto adjust cloudcore config
  cloud/cmd/cloudcore/app/server.go
  common/constants/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
Labels: kind/feature, lgtm, approved, size/L

#4472 add listener manager to store listener
  cloud/pkg/dynamiccontroller/application/eventhandler.go
  cloud/pkg/dynamiccontroller/application/listener_manager.go
  cloud/pkg/dynamiccontroller/application/listener_manager_test.go
Labels: kind/feature, lgtm, approved, size/L

#4358 drop initial tls options in Kubelet
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/cleanup, lgtm, approved, size/XS

#4551 feat: cloudhub adds support for rsa certificates
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/server.go
Labels: kind/feature, lgtm, approved, size/S

#4485 migrate kubelet configuration to edged kubelet configuration
  edge/pkg/edged/config/config.go
  edge/pkg/edged/edged.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default_kubelet_configuration.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
  pkg/apis/componentconfig/edgecore/v1alpha2/validation/validation_test.go
Labels: lgtm, approved, size/XL

#4412 drop useless parameters in kubelet flags
  common/constants/default.go
  edge/pkg/edged/config/config.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/cleanup, lgtm, approved, size/M

#4530 fix comfigmap/secret optional error
  cloud/pkg/cloudhub/dispatcher/message_dispatcher.go
  cloud/pkg/cloudhub/dispatcher/message_dispatcher_test.go
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/metamanager/client/configmap.go
  edge/pkg/metamanager/client/secret.go
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
Labels: kind/bug, lgtm, approved, size/L

#4555 bump kind version to 1.12.0
  go.mod
  go.sum
  hack/lib/install.sh
  vendor/gopkg.in/square/go-jose.v2/.gitignore
  vendor/gopkg.in/square/go-jose.v2/.travis.yml
  vendor/gopkg.in/square/go-jose.v2/asymmetric.go
  vendor/gopkg.in/square/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/square/go-jose.v2/crypter.go
  vendor/gopkg.in/square/go-jose.v2/encoding.go
  vendor/gopkg.in/square/go-jose.v2/jwk.go
  vendor/gopkg.in/square/go-jose.v2/jws.go
  vendor/gopkg.in/square/go-jose.v2/jwt/claims.go
  vendor/gopkg.in/square/go-jose.v2/jwt/errors.go
  vendor/gopkg.in/square/go-jose.v2/jwt/jwt.go
  vendor/gopkg.in/square/go-jose.v2/jwt/validation.go
  vendor/gopkg.in/square/go-jose.v2/opaque.go
  vendor/gopkg.in/square/go-jose.v2/shared.go
  vendor/gopkg.in/square/go-jose.v2/signing.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#4557 Automated cherry pick of #4555: bump kind version to 1.12.0
  go.mod
  go.sum
  hack/lib/install.sh
  vendor/gopkg.in/square/go-jose.v2/.gitignore
  vendor/gopkg.in/square/go-jose.v2/.travis.yml
  vendor/gopkg.in/square/go-jose.v2/asymmetric.go
  vendor/gopkg.in/square/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/square/go-jose.v2/crypter.go
  vendor/gopkg.in/square/go-jose.v2/encoding.go
  vendor/gopkg.in/square/go-jose.v2/jwk.go
  vendor/gopkg.in/square/go-jose.v2/jws.go
  vendor/gopkg.in/square/go-jose.v2/jwt/claims.go
  vendor/gopkg.in/square/go-jose.v2/jwt/errors.go
  vendor/gopkg.in/square/go-jose.v2/jwt/jwt.go
  vendor/gopkg.in/square/go-jose.v2/jwt/validation.go
  vendor/gopkg.in/square/go-jose.v2/opaque.go
  vendor/gopkg.in/square/go-jose.v2/shared.go
  vendor/gopkg.in/square/go-jose.v2/signing.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#4430 stream server painc if close channel wrongly
  cloud/pkg/cloudstream/apiserverconnection.go
  cloud/pkg/cloudstream/containerexec_connection.go
  cloud/pkg/cloudstream/containerlog_connection.go
  cloud/pkg/cloudstream/containermetrics_connection.go
  cloud/pkg/cloudstream/session.go
  cloud/pkg/cloudstream/streamserver.go
  edge/pkg/edgestream/tunnel.go
  pkg/stream/edgedconnection.go
  pkg/stream/edgedexecconnection.go
  pkg/stream/edgedlogconnection.go
  pkg/stream/edgedmetricsconnection.go
Labels: kind/bug, lgtm, approved, size/L

#4560 Automated cherry pick of #4430: stream server painc if close channel wrongly
  cloud/pkg/cloudstream/apiserverconnection.go
  cloud/pkg/cloudstream/containerexec_connection.go
  cloud/pkg/cloudstream/containerlog_connection.go
  cloud/pkg/cloudstream/containermetrics_connection.go
  cloud/pkg/cloudstream/session.go
  cloud/pkg/cloudstream/streamserver.go
  edge/pkg/edgestream/tunnel.go
  pkg/stream/edgedconnection.go
  pkg/stream/edgedexecconnection.go
  pkg/stream/edgedlogconnection.go
  pkg/stream/edgedmetricsconnection.go
Labels: lgtm, approved, size/L

#4559 Automated cherry pick of #4530: fix comfigmap/secret optional error
  cloud/pkg/cloudhub/dispatcher/message_dispatcher.go
  cloud/pkg/cloudhub/dispatcher/message_dispatcher_test.go
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/metamanager/client/configmap.go
  edge/pkg/metamanager/client/secret.go
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
Labels: lgtm, approved, size/L

#4563 Add release note for v1.13.
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/README.md
Labels: kind/documentation, lgtm, approved, size/M

#4556 Optimize partial descriptions in the document
  ADOPTERS.md
  CONTRIBUTING.md
  README.md
  docs/proposals/EdgeSite.md
  docs/proposals/cloud-edge-custom-message-design.md
  docs/proposals/cloudcore-ha-design.md
  docs/proposals/configuration.md
  docs/proposals/cri.md
  docs/proposals/device-management-enhance.md
  docs/proposals/edgemesh-design.md
  docs/proposals/keadm-debug.md
  docs/proposals/keadm-scope.md
  docs/proposals/mapper-design-v2.md
  docs/proposals/mapper-design.md
  docs/proposals/node-group-management.md
  docs/proposals/reliable-message-delivery.md
  docs/proposals/web-hook.md
Labels: kind/documentation, lgtm, approved, size/M
