Repository kubeedge/kubeedge, pull requests merged in 2023-06, with the labels that each got.

#4813 [bugfix] add the right to deleting configmaps in rbac of cloudcore to support device-profile
  build/cloud/03-clusterrole.yaml
  manifests/charts/cloudcore/templates/rbac_cloudcore.yaml
Labels: kind/bug, lgtm, approved, size/XS

#4807 fix helm default values
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: kind/bug, lgtm, approved, size/M

#4809 Using 1.13 installation, but displaying 1.12 in many places
  keadm/cmd/keadm/app/cmd/common/constant.go
Labels: kind/bug, size/XS

#4769 Proposal: Enabling authentication and rbac authorization on the edge node
  docs/images/proposals/authorization.png
  docs/proposals/authentication-and-authorization-on-the-edge-node.md
Labels: kind/design, size/L, sig/security

#4752 fix grammar error and redundant type conversion
  cloud/pkg/controllermanager/nodegroup/nodegroupcontroller.go
Labels: kind/cleanup, lgtm, approved, size/S

#4758 add support for cluster scope resource reliable delivery
  cloud/pkg/cloudhub/dispatcher/message_dispatcher.go
  cloud/pkg/cloudhub/session/node_session.go
  cloud/pkg/synccontroller/clusterobjectsync.go
  cloud/pkg/synccontroller/objectsync.go
  cloud/pkg/synccontroller/objectsync_test.go
  cloud/pkg/synccontroller/synccontroller.go
  pkg/metaserver/key.go
  pkg/metaserver/key_test.go
  pkg/metaserver/util/util.go
Labels: size/XL

#4690 add kubectl logs/exec/attach proposal
  docs/images/proposals/k8s-exec.png
  docs/images/proposals/kubectl-exec-detail.png
  docs/images/proposals/kubeedge-exec-con2.png
  docs/images/proposals/kubeedge-exec-con3.png
  docs/images/proposals/kubeedge-exec-con4.png
  docs/proposals/exec-logs.md
Labels: kind/feature, kind/design, size/L, sig/node

#4734 support kubectl attach in KubeEdge
  cloud/pkg/cloudstream/containerattach_connection.go
  cloud/pkg/cloudstream/streamserver.go
  edge/pkg/edgestream/tunnel.go
  pkg/stream/constants.go
  pkg/stream/edgedattachconnection.go
  pkg/stream/message.go
Labels: size/L
