Repository kubeedge/kubeedge, pull requests merged in 2023-07, with the labels that each got.

#4727 update UT of devicetwin to reduce the duplication
  edge/pkg/devicetwin/dtclient/dbtest.go
  edge/pkg/devicetwin/dtclient/device_db_test.go
  edge/pkg/devicetwin/dtclient/deviceattr_db_test.go
  edge/pkg/devicetwin/dtclient/devicetwin_db_test.go
  edge/pkg/devicetwin/dtcommon/common.go
  edge/pkg/devicetwin/dtcontext/dtcontext_test.go
  edge/pkg/devicetwin/dtmanager/communicate_test.go
  edge/pkg/devicetwin/dtmanager/device_test.go
  edge/pkg/devicetwin/dtmanager/membership_test.go
  edge/pkg/devicetwin/dtmanager/twin_test.go
  edge/pkg/devicetwin/dtmanager/workertest.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
  edge/pkg/devicetwin/process_test.go
  edge/pkg/devicetwin/testutil/devicetest.go
  pkg/testtools/dbtest.go
Labels: kind/test, size/XXL

#4837 update gomod with new tag v1.24.14
  go.mod
  go.sum
  vendor/k8s.io/client-go/util/certificate/csr/csr.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/modules.txt
Labels: lgtm, approved

#4841 add runtime validation in keadm
  keadm/cmd/keadm/app/cmd/edge/join.go
Labels: lgtm, approved

#4842 Add PITS Globale Datenrettungsdienste as an adopter
  ADOPTERS.md
  docs/adopters/pits-logo.svg
Labels: lgtm, approved

#4853 Automated cherry pick of #4837: update gomod
  go.mod
  go.sum
  vendor/k8s.io/client-go/util/certificate/csr/csr.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#4854 update doc
  docs/proposals/node-group-management.md
Labels: kind/documentation, lgtm, approved, size/XS

#4855 Automated cherry pick of #4784: update the timeout to 40 mins for docker image ci test
  .github/workflows/main.yaml
Labels: lgtm, approved, size/XS

#4852 Automated cherry pick of #4620: fix iptables-manager controller-manager image name
  .github/workflows/release.yml
  hack/make-rules/crossbuildimage.sh
  hack/make-rules/imageprocess.sh
Labels: lgtm, approved, size/S

#4857 Add TwoWin logo as an adopter
  ADOPTERS.md
  docs/adopters/twowin-logo.png
Labels: kind/documentation, lgtm, approved, size/XS

#4859 update doc
  docs/proposals/node-group-management.md
Labels: kind/documentation, lgtm, approved, size/XS

#4797 fix format err in keadm/cmd/keadm/app/cmd/debug/diagnose.go
  keadm/cmd/keadm/app/cmd/debug/diagnose.go
Labels: kind/documentation, lgtm, approved, size/XS

#4578 bugfix container terminated when edgecore restart
  edge/pkg/edged/edged.go
Labels: kind/bug, lgtm, approved, size/S

#4631 fix delete statefulset pod error
  edge/mocks/beego/fake_sqlresult.go
  edge/pkg/metamanager/dao/meta.go
  edge/pkg/metamanager/dao/meta_test.go
  edge/pkg/metamanager/process.go
  edge/pkg/metamanager/process_test.go
Labels: kind/bug, lgtm, approved, size/L

#4612 deal with error in delete pod upstream msg
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/metamanager/client/pod.go
Labels: kind/bug, lgtm, approved, size/S

#4641 use nodeIP initialization in Kubelet
  edge/cmd/edgecore/app/server.go
  edge/pkg/edgestream/edgestream.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
Labels: kind/bug, lgtm, approved, size/M

#4696 update pod db when patch successfully
  edge/pkg/metamanager/client/pod.go
Labels: kind/bug, lgtm, approved, size/M, sig/node

#4814 fix mqtt container exited: save mqtt meta in sqlite
  common/constants/default.go
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/client/pod.go
  edge/pkg/metamanager/dao/meta.go
  keadm/cmd/keadm/app/cmd/common/content.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
Labels: kind/bug, lgtm, approved, size/L

#4863 add Shelley as reviewer
  cloud/pkg/dynamiccontroller/OWNERS
  cloud/pkg/edgecontroller/OWNERS
  edge/pkg/edged/OWNERS
  edge/pkg/edgehub/OWNERS
  edge/pkg/metamanager/OWNERS
  keadm/OWNERS
  tests/OWNERS
Labels: lgtm, approved, size/XS

#4884 fix keadm failed ci
  tests/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/XS

#4888 Update the ubuntu to 22.04 in release-1.12
  .github/workflows/fossa.yml
  .github/workflows/main.yaml
  .github/workflows/release.yml
Labels: kind/test, lgtm, approved, size/S

#4886 Automated cherry pick of #4884: fix keadm ci failed issue
  tests/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/XS

#4885 Automated cherry pick of #4884: fix keadm ci failed issue
  tests/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/XS

#4887 Automated cherry pick of #4884: fix keadm ci failed issue
  tests/e2e/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/XS

#4870 Automated cherry pick of #4578: bugfix container terminated when edgecore restart
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#4874 Automated cherry pick of #4814: fix mqtt: start mqtt container
  common/constants/default.go
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/client/pod.go
  edge/pkg/metamanager/dao/meta.go
  keadm/cmd/keadm/app/cmd/common/content.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
Labels: lgtm, approved, size/L

#4876 Automated cherry pick of #4814: fix mqtt: start mqtt container
  common/constants/default.go
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/client/pod.go
  edge/pkg/metamanager/dao/meta.go
  keadm/cmd/keadm/app/cmd/common/content.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
Labels: lgtm, approved, size/L

#4879 Automated cherry pick of #4612: fix error in delete pod
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/metamanager/client/pod.go
Labels: lgtm, approved, size/S

#4877 Automated cherry pick of #4612: fix error in delete pod
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/metamanager/client/pod.go
Labels: lgtm, approved, size/S

#4878 Automated cherry pick of #4612: fix error in delete pod
  cloud/pkg/edgecontroller/controller/upstream.go
  edge/pkg/metamanager/client/pod.go
Labels: lgtm, approved, size/S

#4890 Automated cherry pick of #4696: update pod db when patch successfully
  edge/pkg/metamanager/client/pod.go
Labels: lgtm, approved, size/S

#4891 Automated cherry pick of #4696: update pod db when patch successfully
  edge/pkg/metamanager/client/pod.go
Labels: lgtm, approved, size/M

#4892 Automated cherry pick of #4696: update pod db when patch successfully
  edge/pkg/metamanager/client/pod.go
Labels: lgtm, approved, size/S

#4893 Automated cherry pick of #4641: replace nodeIP initialization in edged
  edge/cmd/edgecore/app/server.go
  edge/pkg/edgestream/edgestream.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
Labels: lgtm, approved, size/M

#4894 Automated cherry pick of #4641: replace nodeIP initialization in edged
  edge/cmd/edgecore/app/server.go
  edge/pkg/edgestream/edgestream.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
Labels: lgtm, approved, size/M

#4895 Automated cherry pick of #4641: replace nodeIP initialization in edged
  edge/cmd/edgecore/app/server.go
  edge/pkg/edgestream/edgestream.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
Labels: lgtm, approved, size/M

#4882 fix parsing response message err in metamanager
  edge/pkg/metamanager/process.go
Labels: kind/bug, lgtm, approved, size/XS

#4875 Automated cherry pick of #4814: fix mqtt: start mqtt container
  common/constants/default.go
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/client/pod.go
  edge/pkg/metamanager/dao/meta.go
  keadm/cmd/keadm/app/cmd/common/content.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
Labels: lgtm, approved, size/L

#4898 Automated cherry pick of #4882: fix parsing response message err in metamanager
  edge/pkg/metamanager/process.go
Labels: lgtm, approved, size/XS

#4900 Cherry pick of #4814: fix start mqtt container failed
  common/constants/default.go
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/client/podstatus.go
  edge/pkg/metamanager/dao/meta.go
  keadm/cmd/keadm/app/cmd/common/content.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/join.go
Labels: lgtm, approved, size/L

#4903 Add Changelog for 1.14.0 release and several patch releases
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
Labels: kind/documentation, lgtm, approved, size/L

#4867 Fix EdgeApplication image path annotation error
  build/crds/apps/apps_v1alpha1_edgeapplication.yaml
  manifests/charts/cloudcore/crds/apps_v1alpha1_edgeapplication.yaml
  pkg/apis/apps/v1alpha1/edgeapplication_types.go
Labels: kind/bug, lgtm, approved, size/S

#4881 fix the bug in local-up mode that causes cni to not launch
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
Labels: kind/bug, lgtm, approved, size/M
