Repository kubeedge/kubeedge, pull requests merged in 2023-09, with the labels that each got.

#4970 Automated cherry pick of #4963: Fix throws nil runtime error when decode AdmissionReview
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/admissioncontroller/common_test.go
  cloud/test/httpfake/http_fake.go
Labels: lgtm, approved, size/M

#4975 Automated cherry pick of #4960: enable cri config in containerd
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#4973 Automated cherry pick of #4960: enable cri config in containerd
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#4974 Automated cherry pick of #4960: enable cri config in containerd
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#4702 [bugfix]edgehub process send device twin msg to twingroup directly
  edge/pkg/devicetwin/process.go
  edge/pkg/edgehub/process.go
Labels: kind/bug, lgtm, approved, size/S, sig/device-iot

#4979 Automated cherry pick of #4702: edgehub process send twin msg to twingroup directly to avoid
  edge/pkg/devicetwin/process.go
  edge/pkg/edgehub/process.go
Labels: lgtm, approved, size/S

#4971 Automated cherry pick of #4963: Fix throws nil runtime error when decode AdmissionReview
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/admissioncontroller/common_test.go
  cloud/test/httpfake/http_fake.go
Labels: lgtm, approved, size/M

#4972 Automated cherry pick of #4963: Fix throws nil runtime error when decode AdmissionReview
  cloud/pkg/admissioncontroller/common.go
  cloud/pkg/admissioncontroller/common_test.go
  cloud/test/httpfake/http_fake.go
Labels: lgtm, approved, size/M

#4978 Automated cherry pick of #4702: edgehub process send twin msg to twingroup directly to avoid
  edge/pkg/devicetwin/process.go
  edge/pkg/edgehub/process.go
Labels: lgtm, approved, size/S

#4977 Automated cherry pick of #4702: edgehub process send twin msg to twingroup directly to avoid
  edge/pkg/devicetwin/process.go
  edge/pkg/edgehub/process.go
Labels: lgtm, approved, size/S

#4981 Add CHANGELOG for 1.12.4, 1.13.2 and 1.14.2
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
Labels: kind/documentation, lgtm, approved, size/M

#4964 add myself for sig-node and sig-testing related stuff as approver
  OWNERS
  cloud/pkg/edgecontroller/OWNERS
  edge/pkg/edged/OWNERS
  tests/OWNERS
Labels: lgtm, approved, size/XS

#4976 fix e2e test when push doc related PR
  .github/workflows/main-doc.yaml
Labels: kind/bug, lgtm, approved, size/S

#4992 Support to config log level for edgemark
  edge/cmd/edgemark/hollow_edgecore.go
Labels: kind/bug, lgtm, approved, size/XS

#4998 Add a timeout option to the golangci-lint command
  hack/lib/lint.sh
  tests/scripts/keadm_e2e.sh
Labels: kind/bug, lgtm, approved, size/XS

#5001 Add tsc member to maintainers docs
  MAINTAINERS.md
Labels: kind/documentation, lgtm, approved, size/M

#5015 Update Roadmap
  docs/roadmap.md
Labels: kind/documentation, lgtm, approved, size/L

#5014 update go.mod for kubeedge/kubernetes v1.26.7
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pod/mirror_client.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pod/pod_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pod_workers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/runonce.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/XL

#5026 update go-restful package version
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, size/XL

#5022 add 2023 H1 roadmap
  README.md
  README_zh.md
  docs/roadmap.md
  docs/roadmap_zh.md
Labels: kind/documentation, lgtm, approved, size/L

#5027 update distribution package version
  go.mod
  go.sum
  vendor/github.com/docker/distribution/.dockerignore
  vendor/github.com/docker/distribution/.golangci.yml
  vendor/github.com/docker/distribution/.mailmap
  vendor/github.com/docker/distribution/Dockerfile
  vendor/github.com/docker/distribution/Makefile
  vendor/github.com/docker/distribution/docker-bake.hcl
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/registry/api/v2/descriptors.go
  vendor/github.com/docker/distribution/registry/api/v2/errors.go
  vendor/github.com/docker/distribution/registry/client/repository.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, size/L

#5030 fixed the "setup" link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind/documentation, lgtm, approved, size/XS

#5025 update docker package version
  go.mod
  go.sum
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/github.com/docker/docker/api/types/time/timestamp.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/config_inspect.go
  vendor/github.com/docker/docker/client/container_attach.go
  vendor/github.com/docker/docker/client/container_inspect.go
  vendor/github.com/docker/docker/client/container_logs.go
  vendor/github.com/docker/docker/client/image_inspect.go
  vendor/github.com/docker/docker/client/network_inspect.go
  vendor/github.com/docker/docker/client/node_inspect.go
  vendor/github.com/docker/docker/client/plugin_inspect.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/client/secret_inspect.go
  vendor/github.com/docker/docker/client/service_inspect.go
  vendor/github.com/docker/docker/client/task_inspect.go
  vendor/github.com/docker/docker/client/volume_inspect.go
  vendor/github.com/docker/docker/pkg/ioutils/fswriters.go
  vendor/github.com/docker/docker/pkg/ioutils/temp_unix.go
  vendor/github.com/docker/docker/pkg/ioutils/temp_windows.go
  vendor/github.com/docker/docker/registry/endpoint_v1.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, size/L

#4967 Feat/windows nodes edgecore
  common/constants/default.go
  common/constants/default_others.go
  common/constants/default_windows.go
  edge/cmd/edgecore/app/server.go
  edge/pkg/devicetwin/dmiserver/const_others.go
  edge/pkg/devicetwin/dmiserver/const_windows.go
  edge/pkg/devicetwin/dmiserver/server.go
  edge/pkg/devicetwin/dmiserver/server_others.go
  edge/pkg/devicetwin/dmiserver/server_windows.go
  edge/pkg/edged/config/config.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default_kubelet_configuration.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default_others.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default_windows.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
  pkg/apis/componentconfig/edgecore/v1alpha2/validation/validation.go
  pkg/apis/componentconfig/edgecore/v1alpha2/validation/validation_others.go
  pkg/apis/componentconfig/edgecore/v1alpha2/validation/validation_windows.go
Labels: kind/feature, lgtm, approved, size/L, sig/node

#5037 fix: the container of mqtt can't be deleted when exec keadm reset
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: kind/bug, lgtm, approved, size/XS

#5036 Solving the deployment order dependency of mapper and device
  edge/pkg/devicetwin/dtmanager/dmiworker.go
Labels: kind/bug, lgtm, approved, size/S, sig/device-iot

#5006 Add e2e is compatible with kubernetes schedule test
  .github/workflows/schedule.yml
Labels: kind/feature, lgtm, approved, size/L

#4983 device crd v1beta1 and API definition
  build/README.md
  build/README_zh.md
  build/crds/devices/devices_v1beta1_device.yaml
  build/crds/devices/devices_v1beta1_devicemodel.yaml
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/admissioncontroller/admit_devicemodel.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/manager/configmap.go
  cloud/pkg/devicecontroller/manager/device.go
  cloud/pkg/devicecontroller/types/deviceprofile.go
  cloud/test/integration/crds/validation_test.go
  cloud/test/integration/fixtures/constants.go
  cloud/test/integration/fixtures/device.go
  cloud/test/integration/fixtures/devicemodel.go
  edge/pkg/devicetwin/dmiclient/client.go
  edge/pkg/devicetwin/dmiserver/server.go
  edge/pkg/devicetwin/dtcommon/util.go
  edge/pkg/devicetwin/dtmanager/dmiworker.go
  hack/generate-crds.sh
  hack/generate-dmi-proto.sh
  hack/local-up-kubeedge.sh
  hack/update-codegen.sh
  keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_devicemodel.yaml
  pkg/apis/devices/v1beta1/device_instance_types.go
  pkg/apis/devices/v1beta1/device_model_types.go
  pkg/apis/devices/v1beta1/doc.go
  pkg/apis/devices/v1beta1/register.go
  pkg/apis/devices/v1beta1/zz_generated.deepcopy.go
  pkg/apis/dmi/services.go
  pkg/apis/dmi/v1beta1/api.pb.go
  pkg/apis/dmi/v1beta1/api.proto
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/device.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/devicemodel.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/devices_client.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/doc.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/fake/fake_device.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/fake/fake_devicemodel.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/fake/fake_devices_client.go
  pkg/client/clientset/versioned/typed/devices/v1beta1/generated_expansion.go
  pkg/client/informers/externalversions/devices/interface.go
  pkg/client/informers/externalversions/devices/v1beta1/device.go
  pkg/client/informers/externalversions/devices/v1beta1/devicemodel.go
  pkg/client/informers/externalversions/devices/v1beta1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/devices/v1beta1/device.go
  pkg/client/listers/devices/v1beta1/devicemodel.go
  pkg/client/listers/devices/v1beta1/expansion_generated.go
  tests/e2e/device/device.go
  tests/e2e/utils/common.go
  tests/e2e/utils/device.go
Labels: kind/feature, lgtm, approved, size/XXL, sig/device-iot

#5054 fix: typo
  docs/proposals/edge-node-upgrade.md
Labels: lgtm, approved, size/XS
