Repository kubeedge/kubeedge, pull requests merged in 2023-10, with the labels that each got.

#5045 fix remove pod failed
  edge/pkg/edged/edged.go
Labels: kind/bug, lgtm, approved, size/S

#5046 Add 2023 H2 Roadmap_zh
  docs/roadmap.md
  docs/roadmap_zh.md
Labels: kind/documentation, lgtm, approved, size/L

#5041 Make NodeUpgradeJob enable through the helm
  manifests/charts/cloudcore/templates/configmap_cloudcore.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: kind/bug, lgtm, approved, size/XS

#4904 metaserver support pass through API, open /version path
  LICENSES/vendor/github.com/agiledragon/gomonkey/LICENSE
  cloud/pkg/dynamiccontroller/application/application.go
  cloud/pkg/dynamiccontroller/application/application_test.go
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/client.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/fake/fake.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage_test.go
  edge/pkg/metamanager/metaserver/server.go
  go.mod
  go.sum
  pkg/metaserver/key.go
  pkg/metaserver/key_test.go
  pkg/util/pass-through/pass_through.go
  pkg/util/pass-through/pass_through_test.go
  vendor/github.com/agiledragon/gomonkey/LICENSE
  vendor/github.com/agiledragon/gomonkey/README.md
  vendor/github.com/agiledragon/gomonkey/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/patch.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, size/XL

#4825 Add the function of supporting static pod on edge nodes.
  cloud/pkg/cloudhub/dispatcher/message_dispatcher.go
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edged/config/config.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/pod_bridge.go
  edge/pkg/metamanager/client/pod.go
  keadm/cmd/keadm/app/cmd/reset.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default_kubelet_configuration.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/feature, lgtm, approved, size/L

#5058 Create a new, empty flag set for keadm
  keadm/cmd/keadm/app/keadm.go
Labels: kind/cleanup, lgtm, approved, size/XS

#5047 Fix upgrade time layout and lost time value issue
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  cloud/pkg/nodeupgradejobcontroller/controller/util.go
  cloud/pkg/nodeupgradejobcontroller/controller/util_test.go
Labels: kind/bug, lgtm, approved, size/S

#5063 fix start edgecore failed when using systemd cgroupdriver
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/config.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: kind/bug, lgtm, approved, size/S

#5071 fix ci disk space lack issue
  .github/workflows/main.yaml
  hack/make-rules/image.sh
Labels: lgtm, approved, size/S

#5080 Automated cherry pick of #5071: fix ci disk space lack issue
  .github/workflows/main.yaml
  hack/make-rules/image.sh
Labels: lgtm, approved, size/S

#5067 Add changelog for release-1.15
  CHANGELOG/CHANGELOG-1.15.md
  CHANGELOG/README.md
Labels: kind/documentation, lgtm, approved, size/M

#5075 Automated cherry pick of #5047: Fix upgrade time layout and lost time value issue
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  cloud/pkg/nodeupgradejobcontroller/controller/util.go
  cloud/pkg/nodeupgradejobcontroller/controller/util_test.go
Labels: lgtm, approved, size/S

#5078 Automated cherry pick of #5063: fix start edgecore failed when using systemd cgroupdriver
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/config.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/S

#5089 use golang.org/x/text/cases instead of strings.Title(Deprecated)
  go.mod
  pkg/metaserver/util/util.go
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/match.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#5091 fix ci: update dependency tool version and cleanup unused images
  .github/workflows/main.yaml
  cloud/test/integration/scripts/execute.sh
  tests/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/S

#5093 Automated cherry pick of #5091: update dependency tool version and cleanup unused images
  .github/workflows/main.yaml
  cloud/test/integration/scripts/execute.sh
  tests/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/S

#5096 Automated cherry pick of #5091: cleanup unused images
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#5074 Automated cherry pick of #5047: Fix upgrade time layout and lost time value issue
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  cloud/pkg/nodeupgradejobcontroller/controller/util.go
  cloud/pkg/nodeupgradejobcontroller/controller/util_test.go
Labels: lgtm, approved, size/S

#5073 Automated cherry pick of #5047: Fix upgrade time layout and lost time value issue
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  cloud/pkg/nodeupgradejobcontroller/controller/util.go
  cloud/pkg/nodeupgradejobcontroller/controller/util_test.go
Labels: lgtm, approved, size/S

#5072 Automated cherry pick of #5047: Fix upgrade time layout and lost time value issue
  cloud/pkg/nodeupgradejobcontroller/controller/downstream.go
  cloud/pkg/nodeupgradejobcontroller/controller/util.go
  cloud/pkg/nodeupgradejobcontroller/controller/util_test.go
Labels: lgtm, approved, size/S

#5099 Update Roadmap Link
  README.md
  README_zh.md
  docs/roadmap.md
  docs/roadmap_zh.md
Labels: kind/documentation, lgtm, approved, size/L

#5103 Automated cherry pick of #5063: fix start edgecore failed when using systemd cgroupdriver
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/config.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/S

#4999 [proposal] Device CRD v1beta1
  docs/images/device-crd/device-crd-v1beta1.png
  docs/proposals/device-crd-v1beta1.md
Labels: kind/design, lgtm, approved, size/L, sig/device-iot

#5102 Automated cherry pick of #5063: fix start edgecore failed when using systemd cgroupdriver
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/config.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/S

#5085 fix keadm upgrade If edgecore is stopped, the keadm process will stop
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/common/content.go
Labels: kind/bug, lgtm, approved, size/XS

#5086 Determine whether to push device data from mapper to edgeCore based on ReportToCloud.
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicetwin.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/feature, lgtm, approved, size/XS, sig/device-iot

#5104 Automated cherry pick of #5045: fix remove pod failed
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#5105 Automated cherry pick of #5045: fix remove pod failed
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#5101 [release-1.12]fixed mqtt would not start when using custom registry
  common/constants/default.go
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/dao/meta.go
  keadm/cmd/keadm/app/cmd/common/content.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
Labels: kind/bug, lgtm, approved, size/L

#5076 Automated cherry pick of #5063: fix start edgecore failed when using systemd cgroupdriver
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/config.go
  keadm/cmd/keadm/app/cmd/edge/image.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/reset.go
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/S

#5106 Automated cherry pick of #5045: fix remove pod failed
  edge/pkg/edged/edged.go
Labels: lgtm, approved, size/S

#5109 Automated cherry pick of #5085: fix keadm upgrade If edgecore is stopped, the keadm process
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/common/content.go
Labels: lgtm, approved, size/XS

#5110 Automated cherry pick of #5085: fix keadm upgrade If edgecore is stopped, the keadm process
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/common/content.go
Labels: lgtm, approved, size/XS

#5111 Automated cherry pick of #5085: fix keadm upgrade If edgecore is stopped, the keadm process
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/common/content.go
Labels: lgtm, approved, size/XS

#5107 Fix error logs for nodegroup
  cloud/pkg/controllermanager/nodegroup/nodegroupcontroller.go
Labels: kind/bug, lgtm, approved, size/XS

#5108 Automated cherry pick of #5085: fix keadm upgrade If edgecore is stopped, the keadm process
  edge/pkg/edgehub/upgrade/upgrade.go
  keadm/cmd/keadm/app/cmd/common/content.go
Labels: lgtm, approved, size/XS

#5113 Add Changelog for v1.12.5, v1.13.3 and v1.14.3
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
Labels: kind/documentation, lgtm, approved, size/M

#5114 cleanup unused images for ci
  .github/workflows/main.yaml
Labels: kind/failing-test, lgtm, approved, size/S

#5118 Automated cherry pick of #5114: cleanup unused images for ci
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#5116 Automated cherry pick of #5086: Determine whether to push device data from mapper to edgeCore
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicetwin.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: lgtm, approved, size/XS

#5120 modify parameters for ginkgo v2
  build/conformance/e2e-runner/run.go
  build/conformance/kubernetes/edge_skip_case.yaml
  build/conformance/node-e2e-runner/run.go
  build/conformance/util/util.go
  edge/test/integration/utils/common/log.go
  tests/e2e/apps/deployment.go
  tests/e2e/device/device.go
  tests/e2e/rule/rule.go
  tests/e2e/utils/log.go
  tests/e2e_edgesite/edgesite_test.go
  tests/e2e_keadm/keadm_test.go
Labels: kind/bug, kind/test, lgtm, approved, size/M

#5123 update go version to 1.20.10 for docker build tool
  build/docker/build-tools/build-tools.dockerfile
  build/docker/build-tools/make-build-tools.sh
Labels: kind/feature, lgtm, approved, size/XS

#5017 Mirgration solution for devices among multi-nodes
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
  build/crds/devices/devices_v1alpha2_device.yaml
  build/crds/devices/devices_v1beta1_device.yaml
  build/crds/devices/devices_v1beta1_devicemodel.yaml
  cloud/pkg/cloudhub/common/helper.go
  cloud/pkg/cloudhub/common/model/types.go
  cloud/pkg/cloudhub/handler/message_handler.go
  cloud/pkg/common/messagelayer/util.go
  cloud/pkg/devicecontroller/constants/device.go
  cloud/pkg/devicecontroller/constants/service.go
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/manager/device.go
  cloud/pkg/devicecontroller/manager/mapper.go
  cloud/pkg/devicecontroller/types/device.go
  common/constants/default.go
  edge/pkg/common/message/message.go
  edge/pkg/devicetwin/dmiclient/client.go
  edge/pkg/devicetwin/dmiserver/server.go
  edge/pkg/devicetwin/dtcommon/common.go
  edge/pkg/devicetwin/dtcommon/util.go
  edge/pkg/devicetwin/dtcontext/dtcontext.go
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/devicetwin/dtmanager/device.go
  edge/pkg/devicetwin/dtmanager/dmiworker.go
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/devicetwin/dttype/types.go
  edge/pkg/devicetwin/process.go
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_devicemodel.yaml
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/devices/v1beta1/device_instance_types.go
  pkg/apis/devices/v1beta1/device_model_types.go
  pkg/apis/devices/v1beta1/zz_generated.deepcopy.go
  pkg/apis/dmi/v1alpha1/api.pb.go
  pkg/apis/dmi/v1beta1/api.pb.go
Labels: lgtm, approved, size/XL

#5049 Feat/windows nodes release
  .github/workflows/release.yml
  Makefile
  hack/lib/golang.sh
  hack/make-rules/release.sh
Labels: kind/feature, lgtm, approved, size/L

#4845 [proposal] Migration Solution for Edge Devices among Multi-nodes
  docs/images/proposals/multi-node-device-migration1.jpg
  docs/images/proposals/multi-node-device-migration2.jpg
  docs/images/proposals/multi-node-device-migration3.jpg
  docs/images/proposals/multi-node-device-migration4.jpg
  docs/proposals/migration-solution-for-edge-devices-among-multi-nodes.md
Labels: kind/design, lgtm, approved, size/L, sig/device-iot

#4968 Feat/windows nodes keadm
  keadm/cmd/keadm/app/cmd/cmd_others.go
  keadm/cmd/keadm/app/cmd/cmd_windows.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/constant_others.go
  keadm/cmd/keadm/app/cmd/common/constant_windows.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
  keadm/cmd/keadm/app/cmd/reset_others.go
  keadm/cmd/keadm/app/cmd/reset_windows.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/common_others.go
  keadm/cmd/keadm/app/cmd/util/common_windows.go
  keadm/cmd/keadm/app/cmd/util/exec_others.go
  keadm/cmd/keadm/app/cmd/util/exec_windows.go
  keadm/cmd/keadm/app/cmd/util/nssm.go
  keadm/cmd/keadm/app/cmd/util/nssm_test.go
Labels: kind/feature, lgtm, approved, size/XXL
