Repository kubeedge/kubeedge, pull requests merged in 2024-10, with the labels that each got.

#5898 Add an action in the conformance CI to increase available disk space
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#5906 Fix kubeconfig flag in keadm
  keadm/cmd/keadm/app/cmd/reset_others.go
Labels: kind/bug, lgtm, approved, size/XS

#5897 Skip kube-proxy during restarting edgecore.
  edge/cmd/edgecore/app/server.go
Labels: kind/bug, lgtm, approved, size/XS

#5905 Test coverage for `edge/pkg/metamanager/client` module - `pod`, `podstatus` and `secret` files
  edge/pkg/metamanager/client/pod_test.go
  edge/pkg/metamanager/client/podstatus_test.go
  edge/pkg/metamanager/client/secret_test.go
Labels: kind/test, lgtm, approved, size/L

#5811 Support edge nodes report events
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/edgecontroller/controller/upstream_test.go
  common/types/types.go
  edge/pkg/edged/edged.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/core_client_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/core/v1/event_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/storage/v1/volumeattachment_bridge_test.go
  edge/pkg/metamanager/client/event.go
  edge/pkg/metamanager/client/event_test.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/process.go
  manifests/charts/cloudcore/templates/rbac_cloudcore.yaml
  staging/src/github.com/kubeedge/api/apis/common/constants/default.go
  staging/src/github.com/kubeedge/api/apis/componentconfig/cloudcore/v1alpha1/default.go
  staging/src/github.com/kubeedge/api/apis/componentconfig/cloudcore/v1alpha1/types.go
  staging/src/github.com/kubeedge/api/apis/componentconfig/edgecore/v1alpha2/default.go
  staging/src/github.com/kubeedge/api/apis/componentconfig/edgecore/v1alpha2/types.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: kind/feature, lgtm, approved, size/XL

#5722 Proposal: support edge nodes report events
  docs/images/proposals/support-edge-nodes-report-events.png
  docs/proposals/support-edge-nodes-report-events.md
Labels: kind/design, lgtm, approved, size/L

#5902 mapper supports device data writing
  build/crds/devices/devices_v1beta1_device.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  staging/src/github.com/kubeedge/api/apis/devices/v1beta1/device_instance_types.go
  staging/src/github.com/kubeedge/api/apis/devices/v1beta1/zz_generated.deepcopy.go
  staging/src/github.com/kubeedge/api/apis/dmi/v1beta1/api.pb.go
  staging/src/github.com/kubeedge/api/apis/dmi/v1beta1/api.proto
  staging/src/github.com/kubeedge/api/apis/dmi/v1beta1/api_grpc.pb.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/driver/driver.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/configmaptype.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/datamethod.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/global/global.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/httpserver/callback.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/httpserver/responsetype.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/httpserver/restapi.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/httpserver/router.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/feature, lgtm, approved, size/XXL

#5662 Add mapper support device data writing proposal
  docs/images/mapper/device-write.png
  docs/proposals/mapper-support-devicedata-writing.md
Labels: kind/design, lgtm, approved, size/L

#5915 Add release onboarding issue template
  .github/ISSUE_TEMPLATE/release-onboarding.md
Labels: kind/documentation, lgtm, approved, size/S

#5914 Add a note comment for default value modification of `edged.rootDirectory`
  staging/src/github.com/kubeedge/api/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/feature, lgtm, approved, size/XS

#5761 Proposal:OTA(Over-The-Air) Upgrades For Edge Node
  docs/images/proposals/over-the-air-upgrades-for-edge-node.png
  docs/proposals/OTA(over-the-air)-upgrades-for-edge-node.md
Labels: kind/design, lgtm, approved, size/L

#5913 Mapper support set device status reportcycle
  build/crds/devices/devices_v1beta1_device.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  staging/src/github.com/kubeedge/api/apis/devices/v1beta1/device_instance_types.go
  staging/src/github.com/kubeedge/api/apis/dmi/v1beta1/api.pb.go
  staging/src/github.com/kubeedge/api/apis/dmi/v1beta1/api.proto
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicestatus.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/configmaptype.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/feature, lgtm, approved, size/L

#5894 Fix errors due to singular and plural conversion in metaserver
  pkg/metaserver/util/util.go
Labels: kind/bug, lgtm, approved, size/XS

#5628 Add opentelemetry to mapper-framework for enhancing pushmethod.
  build/crds/devices/devices_v1beta1_device.yaml
  hack/generate-groups.sh
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  staging/src/github.com/kubeedge/api/apis/devices/v1beta1/device_instance_types.go
  staging/src/github.com/kubeedge/api/apis/devices/v1beta1/zz_generated.deepcopy.go
  staging/src/github.com/kubeedge/api/apis/dmi/v1beta1/api.pb.go
  staging/src/github.com/kubeedge/api/apis/dmi/v1beta1/api.proto
  staging/src/github.com/kubeedge/api/apis/dmi/v1beta1/api_grpc.pb.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/publish/otel/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/publish/otel/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/const.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/feature, lgtm, approved, size/XXL

#5920 Automated cherry pick of #5894: Fix errors due to singular and plural conversion
  pkg/metaserver/util/util.go
Labels: lgtm, approved, size/XS

#5918 Automated cherry pick of #5894: Fix errors due to singular and plural conversion
  pkg/metaserver/util/util.go
Labels: lgtm, approved, size/XS

#5919 Automated cherry pick of #5894: Fix errors due to singular and plural conversion
  pkg/metaserver/util/util.go
Labels: lgtm, approved, size/XS

#5917 Automated cherry pick of #5894: Fix errors due to singular and plural conversion
  pkg/metaserver/util/util.go
Labels: lgtm, approved, size/XS

#5924 Starting from v1.19, remove specifying kubeedge version through `profile version`
  keadm/cmd/keadm/app/cmd/helm/cloudcore.go
Labels: lgtm, approved, size/M

#5929 Update default version in manifest to v1.19.0
  manifests/charts/cloudcore/Chart.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: kind/documentation, lgtm, approved, size/S

#5930 Automated cherry pick of #5924: Starting from v1.19, remove specifying kubeedge version
  keadm/cmd/keadm/app/cmd/helm/cloudcore.go
Labels: lgtm, approved, size/M

#5932 Automated cherry pick of #5929: update default version to 1.19.0
  manifests/charts/cloudcore/Chart.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/S

#5933 Revert #5818: runc version upgraded
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/paths.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/validator.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/setns_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/rlimit_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/rlimit_linux_go122.go
  vendor/github.com/opencontainers/runc/libcontainer/system/rlimit_stub.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps.c
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, size/XL

#5935 Add windows crossbuild in CI
  .github/workflows/main.yaml
  Makefile
  hack/lib/golang.sh
Labels: kind/test, lgtm, approved, size/S

#5931 Add v1.19.0 release note
  CHANGELOG/CHANGELOG-1.19.md
Labels: kind/documentation, lgtm, approved, size/M

#5724 Proposal: sound-equipment-fault-detection #5591
  docs/images/sound-equipment-fault-detection/fig.png
  docs/images/sound-equipment-fault-detection/sound.png
  docs/images/sound-equipment-fault-detection/structure.png
  docs/images/sound-equipment-fault-detection/task.png
  docs/proposals/sound-equipment-fault-detection.md
Labels: lgtm, approved, size/L

#5746 Proposal: batch node access #5426
  docs/images/batch-node-access/Design-overview.png
  docs/proposals/batch-node-access.md
Labels: kind/feature, lgtm, approved, size/L

#5900 [OSPP] Mapper-framework-Java design and implementation
  hack/update-vendor.sh
  staging/src/github.com/kubeedge/mapper-framework-Java/.gitignore
  staging/src/github.com/kubeedge/mapper-framework-Java/Dockerfile
  staging/src/github.com/kubeedge/mapper-framework-Java/Makefile
  staging/src/github.com/kubeedge/mapper-framework-Java/README.md
  staging/src/github.com/kubeedge/mapper-framework-Java/hack/make-rules/build.sh
  staging/src/github.com/kubeedge/mapper-framework-Java/hack/make-rules/generate.sh
  staging/src/github.com/kubeedge/mapper-framework-Java/pom.xml
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/Main.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/config/ConfigParser.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/DataConverter.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/TwinData.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/dbmethod/Influxdb2.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/dbmethod/Mysql.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/dbmethod/Redis.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/dbmethod/Tdengine.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/publish/DataPanel.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/publish/Http.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/publish/Mqtt.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/data/stream/StreamHandler.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/devicepanel/DevPanel.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/devicepanel/Device.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/dmi/v1beta1/Api.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/dmi/v1beta1/DeviceManagerServiceGrpc.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/dmi/v1beta1/DeviceMapperServiceGrpc.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/dmi/v1beta1/api.proto
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/driver/CustomizedClient.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/driver/CustomizedProtocolConfig.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/driver/VisitorConfig.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/grpc/GrpcClient.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/grpc/GrpcServer.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/http/HTTPServer.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/CustomizedDev.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/CustomizedProtocolConfig.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/VisitorConfig.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/common/Config.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/common/Const.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/common/DataModel.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/common/DeviceInstance.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/common/DeviceModel.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/model/common/HttpResponse.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/service/CustomizedClient_I.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/java/service/DevPanel_I.java
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/resources/config.yaml
  staging/src/github.com/kubeedge/mapper-framework-Java/src/main/resources/logback.xml
  staging/src/github.com/kubeedge/mapper-framework/hack/update-vendor.sh
Labels: kind/feature, lgtm, approved, size/XXL

#5773 Proposal of multi-lingual programming mapper
  docs/images/proposals/multi-lingual programming mapper.png
  docs/proposals/multi-lingual programming mapper.md
Labels: kind/design, lgtm, approved, size/L

#5928 CSI Driver `version flag` is inconsistent
  cloud/cmd/csidriver/app/options/options.go
  cloud/cmd/csidriver/app/options/options_test.go
  cloud/cmd/csidriver/app/server_test.go
Labels: lgtm, approved, size/S

#5939 [OSPP]Design and Implementation of MANET Edge Computing Architecture Based on KubeEdge
  cloud/cmd/cloudcore/cloudcore.go
  cloud/pkg/cloudhub/level.go
  config.yaml
  docs/images/batch-node-access/Design-overview.png
  docs/images/proposals/edit-device.png
  docs/images/proposals/exec-pod.png
  docs/images/proposals/logs-pod.png
  docs/images/sound-equipment-fault-detection/fig.png
  docs/images/sound-equipment-fault-detection/sound.png
  docs/images/sound-equipment-fault-detection/structure.png
  docs/images/sound-equipment-fault-detection/task.png
  docs/proposals/batch-node-access.md
  docs/proposals/offline-data-surface-resources-controll.md
  docs/proposals/sound-equipment-fault-detection.md
  edge/cmd/edgenode/level_node.go
  edge/pkg/edgehub/level_edge.go
Labels: kind/design, size/XL

#5765 Proposal: Provide a Common MQTT Mapper
  docs/images/proposals/Provide-a-common-MQTT-mapper-algo.jpg
  docs/images/proposals/Provide-a-common-MQTT-mapper-architecture.jpg
  docs/proposals/provide-a-commom-mqtt-mapper.md
Labels: kind/design, lgtm, approved, size/L

#5889 [OSPP] Implement Batch Node Access Functionality
  keadm/cmd/keadm/app/cmd/cmd_others.go
  keadm/cmd/keadm/app/cmd/edge/batchjoin.go
Labels: kind/feature, size/L
