Repository kubeedge/kubeedge, pull requests merged in 2024-01, with the labels that each got.

#5326 fix import to upgrade mapper
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/cmd/main.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/influxdb2/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/tdengine/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/publish/http/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/publish/mqtt/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicetwin.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/driver/devicetype.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
  staging/src/github.com/kubeedge/mapper-framework/hack/make-rules/generate.sh
Labels: kind/feature, lgtm, approved, size/L

#5325 Allow configuration of dmi.sock path
  common/constants/default.go
  edge/pkg/devicetwin/dmiserver/server.go
  edge/test/integration/utils/test_setup.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/bug, lgtm, approved, size/S

#5336 Automated cherry pick of #5328: fix device status problem
  cloud/pkg/devicecontroller/controller/upstream.go
Labels: lgtm, approved, size/S

#5303 Add a retry mechanism to solve situations where the device is deployed before the devicemodel.
  LICENSES/vendor/github.com/avast/retry-go/LICENSE
  cloud/pkg/devicecontroller/controller/downstream.go
  go.mod
  go.sum
  vendor/github.com/avast/retry-go/.gitignore
  vendor/github.com/avast/retry-go/.godocdown.tmpl
  vendor/github.com/avast/retry-go/.travis.yml
  vendor/github.com/avast/retry-go/Gopkg.toml
  vendor/github.com/avast/retry-go/LICENSE
  vendor/github.com/avast/retry-go/Makefile
  vendor/github.com/avast/retry-go/README.md
  vendor/github.com/avast/retry-go/VERSION
  vendor/github.com/avast/retry-go/appveyor.yml
  vendor/github.com/avast/retry-go/options.go
  vendor/github.com/avast/retry-go/retry.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, size/XXL

#5238 update generate.sh in mapper-framework
  staging/src/github.com/kubeedge/mapper-framework/hack/make-rules/generate.sh
Labels: kind/feature, lgtm, approved, size/S

#5289 Add keadm compatible e2e test
  .github/workflows/keadm_compatibility.yaml
  Makefile
  tests/scripts/keadm_compatibility_e2e.sh
Labels: kind/test, lgtm, approved, size/L

#5247 update device init
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/cmd/main.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/global/global.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/parse.go
Labels: lgtm, approved, size/L, sig/device-iot

#5346 remove invalid device file
  build/crds/devices/devices_v1alpha1_device.yaml
  build/crds/devices/devices_v1alpha1_devicemodel.yaml
  build/crds/devices/devices_v1alpha2_device.yaml
  build/crds/devices/devices_v1alpha2_devicemodel.yaml
Labels: kind/cleanup, lgtm, approved, size/XXL

#5143 Add support of getting healthz, livez, readyz for metaserver.
  pkg/util/pass-through/pass_through.go
  pkg/util/pass-through/pass_through_test.go
Labels: kind/api-change, kind/feature, lgtm, approved, size/M

#5277 Add DB handler
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/influxdb2/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/tdengine/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
Labels: kind/feature, lgtm, approved, size/L, sig/device-iot

#5347 apply to be a top-level approver
  OWNERS
Labels: kind/documentation, lgtm, approved, size/XS

#5353 Apply WillardHu to be a top-level approver
  OWNERS
Labels: kind/documentation, lgtm, approved, size/XS

#5290 Add Device Admission
  cloud/pkg/admissioncontroller/admission.go
  cloud/pkg/admissioncontroller/admit_device.go
Labels: kind/feature, lgtm, approved, size/M, sig/device-iot

#5294 Add nodename in edge certificate
  cloud/pkg/cloudhub/servers/httpserver/server.go
  common/constants/default.go
  common/types/http.go
  edge/pkg/edgehub/certificate/certmanager.go
  edge/pkg/edgehub/common/http/http.go
Labels: kind/feature, lgtm, approved, size/M, sig/security

#5196 Supports installing edgecore without installing the CNI plugin.
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: kind/bug, lgtm, approved, size/XS

#5234 Resolve the issue of deploying edgecore failing when CR turns on selinux.
  go.mod
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/util/common.go
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: kind/bug, lgtm, approved, size/M

#5329 fix namespace problem in cloudcore
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/manager/common.go
  cloud/pkg/devicecontroller/manager/device.go
  cloud/pkg/devicecontroller/manager/devicemodel.go
Labels: kind/bug, lgtm, approved, size/M

#5321 add cri-ci
  .github/workflows/main.yaml
  .github/workflows/schedule.yml
  edge/test/integration/scripts/fast_test.sh
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
  tests/scripts/execute.sh
Labels: kind/feature, lgtm, approved, size/L

#5292 add lint check for mapper-framework
  hack/lib/lint.sh
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
  staging/src/github.com/kubeedge/mapper-framework/go.mod
  staging/src/github.com/kubeedge/mapper-framework/go.sum
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcserver/device.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcserver/server.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/httpserver/callback.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/httpserver/server.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/feature, lgtm, approved, size/L, sig/device-iot

#5262 Update the EdgeApplication API definition. EdgeApplication Differenti…
  build/crds/apps/apps_v1alpha1_edgeapplication.yaml
  cloud/pkg/controllermanager/controllermanager.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/argsoverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/commandoverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/constants.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/imageoverrider.go
  docs/proposals/node-group-management.md
  manifests/charts/cloudcore/crds/apps_v1alpha1_edgeapplication.yaml
  pkg/apis/apps/v1alpha1/edgeapplication_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, lgtm, approved, size/XXL

#5356 fix some bug in framework
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/bug, lgtm, approved, size/M

#5229 Construction of cloudcore upgrading capability
  edge/pkg/edgehub/task/taskexecutor/node_upgrade.go
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cloud/manifest.go
  keadm/cmd/keadm/app/cmd/cloud/upgrade.go
  keadm/cmd/keadm/app/cmd/cmd_others.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/common/types_test.go
  keadm/cmd/keadm/app/cmd/config.go
  keadm/cmd/keadm/app/cmd/deprecated/init.go
  keadm/cmd/keadm/app/cmd/deprecated/join.go
  keadm/cmd/keadm/app/cmd/deprecated/reset.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/helm/cloudcore.go
  keadm/cmd/keadm/app/cmd/helm/cloudcore_test.go
  keadm/cmd/keadm/app/cmd/helm/helm_helper.go
  keadm/cmd/keadm/app/cmd/helm/helm_helper_test.go
  keadm/cmd/keadm/app/cmd/helm/installer.go
  keadm/cmd/keadm/app/cmd/helm/values.go
  keadm/cmd/keadm/app/cmd/helm/values_test.go
  keadm/cmd/keadm/app/cmd/reset_others.go
  keadm/cmd/keadm/app/cmd/upgrade.go
  manifests/charts/cloudcore/Chart.yaml
  manifests/charts/cloudcore/templates/deployment_cloudcore.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
  pkg/image/image_test.go
Labels: kind/feature, lgtm, approved, size/XXL

#5373 fix the indentation bug of keadm init
  manifests/charts/cloudcore/templates/daemonset_mosquitto.yaml
Labels: kind/bug, lgtm, approved, size/S

#5370 EdgeApplication differential configuration added support for env and …
  cloud/pkg/controllermanager/controllermanager.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/envoverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/resourcesoverrider.go
Labels: kind/feature, lgtm, approved, size/L

#5367 Automated cherry pick of #5196 upstream release 1.15
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5366 Automated cherry pick of #5196 upstream release 1.14
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5365 Automated cherry pick of #5196 upstream release 1.12
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5374 For backward compatibility of the edgecore trigger the upgrade command
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/upgrade.go
Labels: kind/bug, lgtm, approved, size/M

#5364 Automated cherry pick of #5196 upstream release 1.13
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5375 fix the package version in mapper-framework
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
Labels: kind/bug, lgtm, approved, size/S

#5380 Automated cherry pick of #5374: For backward compatibility of the edgecore trigger the
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/upgrade.go
Labels: lgtm, approved, size/M

#5379 Automated cherry pick of #5375: fix the package version in mapper-framework
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
Labels: lgtm, approved, size/S

#5383 fix keadm flag in windows
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
  keadm/cmd/keadm/app/cmd/reset_windows.go
Labels: kind/bug, lgtm, approved, size/S

#5384 Automated cherry pick of #5383: fix keadm flag in windows
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
  keadm/cmd/keadm/app/cmd/reset_windows.go
Labels: lgtm, approved, size/S

#5381 Add patch release note for v1.12.7, 1.13.5, 1.14.5, 1.15.2
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
  CHANGELOG/CHANGELOG-1.15.md
Labels: kind/documentation, lgtm, approved, size/M

#5354 Nominate myself(WillardHu) as a new maintainer
  MAINTAINERS.md
Labels: kind/documentation, lgtm, approved, size/XS

#5348 Nominate myself(Shelley-BaoYue) as a new maintainer
  MAINTAINERS.md
Labels: lgtm, approved, size/XS

#5382 add changelog for release-1.16
  CHANGELOG/CHANGELOG-1.16.md
Labels: kind/documentation, lgtm, approved, size/L

#5168 Remove unused badge build and docs
  README.md
  README_zh.md
Labels: kind/cleanup, lgtm, approved, size/XS
