Repository kubeedge/kubeedge, pull requests merged in 2024-12, with the labels that each got.

#5998 modify kubeedge graduation description in readme
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/XS

#6013 Revert: Fixed the hub client certificate doesn't have any IP address
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/certificate/certs.go
  cloud/pkg/cloudhub/servers/httpserver/pre_server.go
  pkg/security/certs/types.go
  pkg/security/certs/x509_ca_certs_test.go
  pkg/security/certs/x509_certs.go
Labels: lgtm, approved, size/M

#6015 Automated cherry pick of #5960: add metadata uid for crio
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#6014 Automated cherry pick of #5960: add metadata uid for crio
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#6016 Add v1.19.1, v1.18.2, v1.17.4, v1.16.5 changelog
  CHANGELOG/CHANGELOG-1.16.md
  CHANGELOG/CHANGELOG-1.17.md
  CHANGELOG/CHANGELOG-1.18.md
  CHANGELOG/CHANGELOG-1.19.md
Labels: kind/documentation, lgtm, approved, size/M

#5845 adding deployment spec overrides via node label selector
  build/crds/apps/apps_v1alpha1_edgeapplication.yaml
  build/crds/apps/apps_v1alpha1_nodegroup.yaml
  build/crds/devices/devices_v1beta1_device.yaml
  build/crds/devices/devices_v1beta1_devicemodel.yaml
  build/crds/operations/operations_v1alpha1_imageprepulljob.yaml
  build/crds/operations/operations_v1alpha1_nodeupgradejob.yaml
  build/crds/policy/policy_v1alpha1_serviceaccountaccess.yaml
  build/crds/reliablesyncs/cluster_objectsync_v1alpha1.yaml
  build/crds/reliablesyncs/objectsync_v1alpha1.yaml
  cloud/pkg/controllermanager/edgeapplication/edgeapplicationcontroller.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/nameoverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/nodeselectoroverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/overridemanager.go
  cloud/pkg/controllermanager/edgeapplication/utils/utils.go
  cloud/test/integration/controllermanager/controllermanager_test.go
  hack/generate-crds.sh
  manifests/charts/cloudcore/crds/apps_v1alpha1_edgeapplication.yaml
  manifests/charts/cloudcore/crds/apps_v1alpha1_nodegroup.yaml
  manifests/charts/cloudcore/crds/cluster_objectsync_v1alpha1.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_devicemodel.yaml
  manifests/charts/cloudcore/crds/objectsync_v1alpha1.yaml
  manifests/charts/cloudcore/crds/operations_v1alpha1_imageprepulljob.yaml
  manifests/charts/cloudcore/crds/operations_v1alpha1_nodeupgradejob.yaml
  manifests/charts/cloudcore/crds/policy_v1alpha1_serviceaccountaccess.yaml
  staging/src/github.com/kubeedge/api/apis/apps/v1alpha1/edgeapplication_types.go
  staging/src/github.com/kubeedge/api/apis/apps/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, size/XXL

#6002 Dependency update - bump golang version to v1.22.9
  .github/workflows/fossa.yml
  .github/workflows/main-arm64.yaml
  .github/workflows/main-doc.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yml
  .github/workflows/schedule.yml
  build/admission/Dockerfile
  build/cloud/Dockerfile
  build/conformance/Dockerfile
  build/conformance/nodeconformance.Dockerfile
  build/controllermanager/Dockerfile
  build/csidriver/Dockerfile
  build/docker/installation-package/installation-package.dockerfile
  build/edge/Dockerfile
  build/edgemark/Dockerfile
  build/edgesite/agent-build.Dockerfile
  build/edgesite/server-build.Dockerfile
  build/iptablesmanager/Dockerfile
  go.mod
  hack/make-rules/build_with_container.sh
  staging/src/github.com/kubeedge/api/go.mod
  staging/src/github.com/kubeedge/beehive/go.mod
  staging/src/github.com/kubeedge/mapper-framework/go.mod
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
  vendor/github.com/rubenv/sql-migrate/test-migrations/1_initial.sql
  vendor/github.com/rubenv/sql-migrate/test-migrations/2_record.sql
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, size/XL

#6022 fix device desired value type error
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
Labels: kind/bug, lgtm, approved, size/S

#6021 tests for `edge/pkg/eventbus/mqtt/handler.go`
  edge/pkg/eventbus/mqtt/handler_test.go
Labels: kind/test, lgtm, approved, size/M

#5834 Proposal plan for edgeapplication overrides
  docs/proposals/edgeapplication-proposal.md
Labels: lgtm, approved, size/L

#6041 Cleaning up common constants
  cloud/cmd/cloudcore/app/options/options.go
  cloud/cmd/cloudcore/app/options/options_test.go
  common/constants/default.go
  common/constants/default_others.go
  common/constants/default_windows.go
  edge/cmd/edgecore/app/options/options.go
  edge/cmd/edgecore/app/server.go
  edge/pkg/edgehub/task/taskexecutor/node_backup.go
  edge/pkg/metamanager/dao/meta.go
  keadm/cmd/keadm/app/cmd/common/content.go
  keadm/cmd/keadm/app/cmd/debug/collect.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/rollback.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
  staging/src/github.com/kubeedge/api/apis/common/constants/default.go
Labels: kind/cleanup, lgtm, approved, size/L

#6039 CI-Runtime downgrades the `runc` version that depends on isulad.
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS

#6047 Fixed required checks failure in CI
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
  keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go
Labels: kind/bug, lgtm, approved, size/XS
