Repository kubeedge/kubeedge, pull requests merged in 2024-05, with the labels that each got.

#5357 add check if the mandatory command exist.
  build/tools/certgen.sh
Labels: kind/bug, lgtm, approved, size/S

#5592 fix link to technical steering committee chater
  MAINTAINERS.md
Labels: kind/cleanup, lgtm, approved, size/XS

#5610 Clean duplicate code in redis
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/client.go
Labels: kind/cleanup, lgtm, approved, size/S

#5613 add luomengY as reviewer
  cloud/pkg/edgecontroller/OWNERS
  edge/pkg/metamanager/OWNERS
  keadm/OWNERS
  staging/src/github.com/kubeedge/mapper-framework/OWNERS
Labels: lgtm, approved, size/XS

#5574 Proposal:Keadm Tool Enhancement
  docs/images/proposals/keadm tool enhancement.png
  docs/proposals/Keadm Tool Enhancement.md
Labels: kind/feature, lgtm, approved, size/M

#5564 Keadm Tool Enhancement
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
  keadm/cmd/keadm/app/cmd/util/set.go
  keadm/cmd/keadm/app/cmd/util/set_test.go
Labels: kind/feature, lgtm, approved, size/XL

#5632 fix keadm init profile in v1.17.0 for keadm_e2e test.
  tests/scripts/keadm_compatibility_e2e.sh
  tests/scripts/keadm_e2e.sh
Labels: kind/bug, lgtm, approved, size/XS
