Repository kubeedge/kubeedge, pull requests merged in 2024-11, with the labels that each got.

#5034 Add admission to cloud helm charts
  manifests/charts/cloudcore/templates/deployment_admission.yaml
  manifests/charts/cloudcore/templates/deployment_controllermanager.yaml
  manifests/charts/cloudcore/templates/rbac_admission.yaml
  manifests/charts/cloudcore/templates/service_admission.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: kind/feature, lgtm, approved, size/L

#5916 Apply to become maintainers
  MAINTAINERS.md
Labels: lgtm, approved, size/XS

#5945 Upgrade gomonkey version
  LICENSES/vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  cloud/cmd/cloudcore/app/server_test.go
  edge/pkg/edgehub/certificate/certmanager_test.go
  edge/pkg/metamanager/metaserver/handlerfactory/ext_handler_test.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage_test.go
  go.mod
  go.sum
  vendor/github.com/agiledragon/gomonkey/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/patch.go
  vendor/github.com/agiledragon/gomonkey/v2/.gitignore
  vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  vendor/github.com/agiledragon/gomonkey/v2/Makefile
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_loong64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/github.com/agiledragon/gomonkey/v2/ut.sh
  vendor/github.com/agiledragon/gomonkey/v2/write_darwin_amd64.s
  vendor/github.com/agiledragon/gomonkey/v2/write_darwin_arm64.s
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, size/XXL

#5947 Sync OWNER COC and LICENSE file from sub repo
  staging/src/github.com/kubeedge/api/CODE_OF_CONDUCT.md
  staging/src/github.com/kubeedge/api/LICENSE
  staging/src/github.com/kubeedge/api/OWNERS
  staging/src/github.com/kubeedge/mapper-framework/CODE_OF_CONDUCT.md
  staging/src/github.com/kubeedge/mapper-framework/LICENSE
Labels: kind/documentation, lgtm, approved, size/L

#5953 update correponding version and k8s compatibility for v1.19.0
  .github/workflows/schedule.yml
  CHANGELOG/CHANGELOG-1.19.md
  README.md
  README_zh.md
  keadm/cmd/keadm/app/cmd/common/constant.go
  tests/scripts/keadm_compatibility_e2e.sh
Labels: lgtm, approved, size/M

#5949 Rename the docs CI workflow
  .github/workflows/main-doc.yaml
Labels: kind/documentation, lgtm, approved, size/XS

#5946 add prerun and postrun shell hooks for keadm edge commands
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/reset_others.go
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/util/scriptrun.go
  keadm/cmd/keadm/app/cmd/util/scriptrun_test.go
Labels: kind/feature, lgtm, approved, size/L

#5959 Implement batch node access functionality
  go.mod
  keadm/cmd/keadm/app/cmd/cmd_others.go
  keadm/cmd/keadm/app/cmd/edge/batchjoin.go
Labels: kind/feature, lgtm, approved, size/L

#5952 Add a CI workflow to build binaries for linux/arm64
  .github/workflows/main-arm64.yaml
Labels: kind/test, lgtm, approved, size/M

#5950 Git ignore `coverage.out`
  .gitignore
Labels: kind/test, lgtm, approved, size/XS

#5921 Apply to become maintainers
  MAINTAINERS.md
Labels: kind/documentation, lgtm, approved, size/XS

#5970 UT coverage for `cloud/pkg/devicecontroller/controller` pkg
  cloud/pkg/devicecontroller/controller/downstream_test.go
  cloud/pkg/devicecontroller/controller/upstream_test.go
Labels: kind/test, lgtm, approved, size/L

#5981 replace deprecated function
  edge/pkg/metamanager/metaserver/handlerfactory/ext_handler_test.go
  edge/pkg/metamanager/metaserver/handlerfactory/handler.go
  keadm/cmd/keadm/app/cmd/edge/batchjoin.go
Labels: kind/cleanup, lgtm, approved, size/S

#5973 Apply become a reviewer
  cloud/pkg/controllermanager/OWNERS
  keadm/OWNERS
Labels: kind/documentation, lgtm, approved, size/XS

#5977 Fixed the token cannot be refreshed
  cloud/pkg/cloudhub/servers/httpserver/pre_server.go
Labels: kind/bug, lgtm, approved, size/M

#5975 fix device compile error
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
Labels: kind/bug, lgtm, approved, size/XS

#5983 Automated cherry pick of #5977: Fixed the token cannot be refreshed
  cloud/pkg/cloudhub/servers/httpserver/pre_server.go
Labels: lgtm, approved, size/M

#5984 Automated cherry pick of #5977: Fixed the token cannot be refreshed
  cloud/pkg/cloudhub/servers/httpserver/pre_server.go
Labels: lgtm, approved, size/M

#5986 Automated cherry pick of #5975 upstream release 1.19
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
Labels: kind/bug, lgtm, approved, size/XS

#5960 Fix install failed with crio > v1.29.2 for uid missing
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5948 edgepp resource overrider enhancement
  cloud/pkg/controllermanager/edgeapplication/overridemanager/resourcesoverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/resourcesoverrider_test.go
Labels: kind/feature, lgtm, approved, size/L

#5926 Complete tests for `edge/pkg/metamanager/client`
  edge/pkg/metamanager/client/nodestatus_test.go
  edge/pkg/metamanager/client/persistentvolume_test.go
  edge/pkg/metamanager/client/persistentvolumeclaim_test.go
  edge/pkg/metamanager/client/pod_test.go
  edge/pkg/metamanager/client/podstatus_test.go
  edge/pkg/metamanager/client/serviceaccount_test.go
  edge/pkg/metamanager/client/volumeattachment_test.go
Labels: kind/test, lgtm, approved, size/XL

#5991 Automated cherry pick of #5960: add metadata uid for crio
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5990 Automated cherry pick of #5960: add metadata uid for crio
  keadm/cmd/keadm/app/cmd/util/image.go
Labels: lgtm, approved, size/XS

#5994 Fixed the hub client certificate doesn't have any IP address
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/servers/httpserver/certificate/certs.go
  cloud/pkg/cloudhub/servers/httpserver/pre_server.go
  pkg/security/certs/types.go
  pkg/security/certs/x509_ca_certs_test.go
  pkg/security/certs/x509_certs.go
Labels: kind/bug, lgtm, approved, size/M

#5965 Check for duplicate names when joining the node
  cloud/pkg/cloudhub/servers/httpserver/node/checknode.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  common/constants/default.go
  keadm/cmd/keadm/app/cmd/edge/join.go
Labels: kind/feature, lgtm, approved, size/L
