Repository kubeedge/kubeedge, pull requests merged in 2024-07, with the labels that each got.

#5682 Added test coverage for `cloudstream.go`
  cloud/pkg/cloudstream/cloudstream.go
  cloud/pkg/cloudstream/cloudstream_test.go
Labels: kind/test, lgtm, approved, size/L

#5695 Added tests for `keadm beta` and `cloud` packages
  keadm/cmd/keadm/app/cmd/beta/beta_test.go
  keadm/cmd/keadm/app/cmd/cloud/gettoken.go
  keadm/cmd/keadm/app/cmd/cloud/gettoken_test.go
  keadm/cmd/keadm/app/cmd/cloud/init_test.go
  keadm/cmd/keadm/app/cmd/cloud/manifest_test.go
  keadm/cmd/keadm/app/cmd/cloud/reset_test.go
  keadm/cmd/keadm/app/cmd/cloud/upgrade.go
  keadm/cmd/keadm/app/cmd/cloud/upgrade_test.go
Labels: kind/test, lgtm, approved, size/XL

#5684 Test coverage for `cloudstream` package
  cloud/pkg/cloudstream/containerattach_connection_test.go
  cloud/pkg/cloudstream/containerexec_connection.go
  cloud/pkg/cloudstream/containerexec_connection_test.go
  cloud/pkg/cloudstream/containerlog_connection.go
  cloud/pkg/cloudstream/containerlog_connection_test.go
  cloud/pkg/cloudstream/containermetrics_connection.go
  cloud/pkg/cloudstream/containermetrics_connection_test.go
Labels: kind/test, lgtm, approved, size/XL

#5635 Proposal:Add router message high availability.
  docs/images/proposals/ha_router.png
  docs/proposals/ha_router.md
Labels: kind/feature, lgtm, approved, size/M

#5643 Fixed edgecore will not restart when the edge node cannot obtain the IP
  edge/pkg/edgestream/edgestream.go
Labels: kind/bug, lgtm, approved, size/M

#5634 fix: compatible with keadm init/upgrade -- profie
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/helm/cloudcore.go
  keadm/cmd/keadm/app/cmd/helm/helm_helper.go
Labels: lgtm, approved, size/M

#5690 Added test coverage for `pkg/stream` package
  pkg/stream/edgedattachconnection_test.go
  pkg/stream/edgedexecconnection_test.go
  pkg/stream/edgedlogconnection_test.go
  pkg/stream/edgedmetricsconnection.go
  pkg/stream/edgedmetricsconnection_test.go
  pkg/stream/message_test.go
Labels: kind/test, lgtm, approved, size/L

#5715 Automated cherry pick of #5643: Fixed edgecore will not restart when the edge node cannot
  edge/pkg/edgestream/edgestream.go
Labels: lgtm, approved, size/M

#5716 Automated cherry pick of #5643: Fixed edgecore will not restart when the edge node cannot
  edge/pkg/edgestream/edgestream.go
Labels: lgtm, approved, size/M

#5717 Automated cherry pick of #5643: Fixed edgecore will not restart when the edge node cannot
  edge/pkg/edgestream/edgestream.go
Labels: lgtm, approved, size/M

#5719 Automated cherry pick of #5632: fix keadm init profile in v1.17.0 for keadm_e2e test.
  tests/scripts/keadm_compatibility_e2e.sh
  tests/scripts/keadm_e2e.sh
Labels: lgtm, approved, size/XS

#5718 Automated cherry pick of #5634: fix: compatible with keadm init/upgrade -- profie
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/helm/cloudcore.go
  keadm/cmd/keadm/app/cmd/helm/helm_helper.go
Labels: lgtm, approved, size/M

#5720 add v1.17.1/v1.16.3/v1.15.3 patch release changelog
  CHANGELOG/CHANGELOG-1.15.md
  CHANGELOG/CHANGELOG-1.16.md
  CHANGELOG/CHANGELOG-1.17.md
  cloud/pkg/cloudstream/containerattach_connection_test.go
Labels: kind/documentation, lgtm, approved, size/M

#5700 Added tests for `keadm/cmd/keadm/app/cmd/debug/check.go`
  keadm/cmd/keadm/app/cmd/debug/check_test.go
Labels: kind/test, lgtm, approved, size/L

#5502 Encapsulate Token operations
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  edge/cmd/edgecore/app/server.go
  edge/pkg/edgehub/certificate/certmanager.go
  edge/pkg/edgehub/certificate/certmanager_test.go
  pkg/security/token/token.go
  pkg/security/token/token_test.go
Labels: kind/cleanup, lgtm, approved, size/L

#5512 add proposal of cloudhub enhancement
  docs/images/proposals/authorizer-chain.png
  docs/images/proposals/cloudhub-enhancement-design.png
  docs/proposals/cloudhub-enhancement.md
Labels: lgtm, approved, size/M

#5723 Test coverage for `cloud/cmd/admission` module
  cloud/cmd/admission/app/options/options_test.go
  cloud/cmd/admission/app/server_test.go
Labels: kind/test, lgtm, approved, size/L

#5687 Unit tests for `cloud/pkg/cloudhub/common/helper.go`
  cloud/pkg/cloudhub/common/helper_test.go
Labels: kind/test, lgtm, approved, size/L

#5708 Test Coverage for `debug` package
  keadm/cmd/keadm/app/cmd/debug/collect.go
  keadm/cmd/keadm/app/cmd/debug/collect_test.go
  keadm/cmd/keadm/app/cmd/debug/debug_test.go
  keadm/cmd/keadm/app/cmd/debug/diagnose_test.go
  keadm/cmd/keadm/app/cmd/debug/get_flags.go
  keadm/cmd/keadm/app/cmd/debug/get_flags_test.go
  keadm/cmd/keadm/app/cmd/debug/get_test.go
Labels: kind/test, lgtm, approved, size/XL

#5721 fix: func NewErrorMessage
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: kind/bug, lgtm, approved, size/XS

#5730 Fix lint error
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
Labels: kind/test, lgtm, approved, size/XS

#5523 fix device mapper data collecting cycle calculation error
  docs/proposals/device-crd-v1beta1.md
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/influxdb2/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/tdengine/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
Labels: lgtm, approved, size/S

#5663 Add conformance e2e test
  .github/workflows/main.yaml
  Makefile
  build/conformance/e2e-runner/run.go
  build/conformance/kubernetes/edge_skip_case.yaml
  tests/scripts/conformance_e2e.sh
Labels: kind/feature, lgtm, approved, size/L

#5733 Automated cherry pick of #5721: fix func NewErrorMessage
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: lgtm, approved, size/XS

#5735 Automated cherry pick of #5721: fix func NewErrorMessage
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: lgtm, approved, size/XS

#5732 Automated cherry pick of #5523 upstream release 1.17
  docs/proposals/device-crd-v1beta1.md
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/influxdb2/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/tdengine/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
Labels: lgtm, approved, size/S

#5734 Automated cherry pick of #5721: fix func NewErrorMessage
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
Labels: lgtm, approved, size/XS

#5619 Supports high availability of router messages.
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/handler/message_handler.go
  cloud/pkg/edgecontroller/controller/upstream.go
  cloud/pkg/router/listener/http.go
  cloud/pkg/router/provider/eventbus/eventbus.go
  cloud/pkg/router/provider/servicebus/servicebus.go
  common/constants/default.go
Labels: kind/feature, lgtm, approved, size/L

#5556 fix:edge node offline pod‘s status update
  edge/pkg/metamanager/client/pod.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/store.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/util/patch.go
  edge/pkg/metamanager/process.go
  go.mod
Labels: kind/bug, lgtm, approved, size/L

#5535 Proposal: When the edge node goes offline, add pod restart and status query functions for the edge node
  docs/images/proposals/edge-pod-get.png
  docs/images/proposals/keadm-get-pod.png
  docs/images/proposals/keadm-restart-pod.png
  docs/proposals/edgepodgetandrestart.md
Labels: kind/design, lgtm, approved, size/L

#5650 edge support device state
  edge/pkg/devicetwin/dmiserver/event_type.go
  edge/pkg/devicetwin/dmiserver/server.go
  edge/pkg/devicetwin/dtcommon/common.go
  edge/pkg/devicetwin/dtmanager/device.go
  pkg/apis/dmi/services.go
  pkg/apis/dmi/v1beta1/api.pb.go
  pkg/apis/dmi/v1beta1/api.proto
  pkg/apis/dmi/v1beta1/api_grpc.pb.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicestatus.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/driver/driver.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/const.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/register.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/grpcclient/report.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/feature, lgtm, approved, size/XXL

#5544 Encapsulate CA and Certificate operations
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/cloudhub.go
  cloud/pkg/cloudhub/config/config.go
  cloud/pkg/cloudhub/config/config_test.go
  cloud/pkg/cloudhub/servers/httpserver/certificate/certs.go
  cloud/pkg/cloudhub/servers/httpserver/certificate/certs_test.go
  cloud/pkg/cloudhub/servers/httpserver/certutil.go
  cloud/pkg/cloudhub/servers/httpserver/nodetask/report_status.go
  cloud/pkg/cloudhub/servers/httpserver/nodetask/upgrade.go
  cloud/pkg/cloudhub/servers/httpserver/pre_server.go
  cloud/pkg/cloudhub/servers/httpserver/resps/fake.go
  cloud/pkg/cloudhub/servers/httpserver/resps/response.go
  cloud/pkg/cloudhub/servers/httpserver/resps/response_test.go
  cloud/pkg/cloudhub/servers/httpserver/secretsutil.go
  cloud/pkg/cloudhub/servers/httpserver/server.go
  cloud/pkg/cloudhub/servers/httpserver/signcerts.go
  cloud/pkg/cloudhub/servers/httpserver/updateconfig.go
  cloud/pkg/cloudhub/servers/httpserver/updateconfig_test.go
  cloud/pkg/common/client/client.go
  cloud/pkg/common/client/namespace.go
  cloud/pkg/common/client/secret.go
  common/types/http.go
  edge/pkg/edgehub/certificate/certmanager.go
  edge/pkg/edgehub/certificate/certmanager_test.go
  edge/pkg/edgehub/certificate/testdata/server.crt
  edge/pkg/edgehub/certificate/testdata/server.key
  edge/pkg/edgehub/common/certutil/certfile.go
  edge/pkg/edgehub/common/certutil/certfile_test.go
  edge/pkg/edgehub/common/http/fake/http.go
  edge/pkg/edgehub/common/http/http.go
  edge/pkg/metamanager/metaserver/agent/agent_test.go
  go.mod
  pkg/security/certs/factory.go
  pkg/security/certs/io.go
  pkg/security/certs/io_test.go
  pkg/security/certs/types.go
  pkg/security/certs/x509_ca.go
  pkg/security/certs/x509_ca_certs_test.go
  pkg/security/certs/x509_certs.go
  pkg/security/certs/x509_types.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, size/XXL

#5572 Switch the keadm ctl client to client go and add the restful interface for restart pod.
  common/types/types.go
  edge/pkg/metamanager/metaserver/common/types.go
  edge/pkg/metamanager/metaserver/handlerfactory/ext_handler.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/storage.go
  edge/pkg/metamanager/metaserver/server.go
  keadm/cmd/keadm/app/cmd/ctl/client/pod.go
  keadm/cmd/keadm/app/cmd/ctl/client/request.go
  keadm/cmd/keadm/app/cmd/ctl/get/pod.go
  keadm/cmd/keadm/app/cmd/ctl/restart/pod.go
  keadm/cmd/keadm/app/cmd/ctl/restful/pod.go
  keadm/cmd/keadm/app/cmd/ctl/restful/request.go
Labels: kind/feature, lgtm, approved, size/XL

#5740 Automated cherry pick of #5556:fix:edge node offline pod‘s status update
  edge/pkg/metamanager/client/pod.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/store.go
  edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/util/patch.go
  edge/pkg/metamanager/process.go
  go.mod
Labels: lgtm, approved, size/L

#5742 Small misspell
  edge/test/integration/appdeployment/application_test.go
Labels: kind/bug, lgtm, approved, size/XS

#5649 cloud support device state
  build/crds/devices/devices_v1beta1_device.yaml
  cloud/pkg/common/messagelayer/util.go
  cloud/pkg/devicecontroller/constants/service.go
  cloud/pkg/devicecontroller/controller/upstream.go
  cloud/pkg/devicecontroller/types/device.go
  common/constants/default.go
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/devices/v1beta1/device_instance_types.go
Labels: kind/feature, lgtm, approved, size/L

#5743 add v1.17.2 changelog
  CHANGELOG/CHANGELOG-1.17.md
Labels: kind/documentation, lgtm, approved, size/S

#5747 fix edge device state sync error
  edge/pkg/devicetwin/dtmanager/device.go
  edge/pkg/devicetwin/dttype/types.go
  edge/pkg/devicetwin/dttype/types_helper.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
Labels: kind/bug, lgtm, approved, size/M

#5748 Add release 1.18 changelog
  CHANGELOG/CHANGELOG-1.16.md
  CHANGELOG/CHANGELOG-1.17.md
  CHANGELOG/CHANGELOG-1.18.md
Labels: kind/documentation, lgtm, approved, size/M

#5750 Automated cherry pick of #5747: fix edge device state sync error
  edge/pkg/devicetwin/dtmanager/device.go
  edge/pkg/devicetwin/dttype/types.go
  edge/pkg/devicetwin/dttype/types_helper.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
Labels: lgtm, approved, size/M
