Repository kubeedge/kubeedge, pull requests merged in 2024-06, with the labels that each got.

#5646 fix redis client compile error
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/client.go
Labels: kind/bug, lgtm, approved, size/XS

#5602 Adjust some code in Mapper-Framework
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/cmd/main.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/tdengine/client.go
Labels: kind/bug, lgtm, approved, size/S

#5652 update go 1.21 for kubeedge build image
  build/docker/build-tools/build-tools.dockerfile
  build/docker/build-tools/make-build-tools.sh
Labels: kind/feature, lgtm, approved, size/XS

#5648 Fixed the quic protocol handshake timeout when using the service
  manifests/charts/cloudcore/templates/service_cloudcore.yaml
Labels: kind/bug, lgtm, approved, size/XS

#5670 Standardlize some codes in DeviceTwin
  edge/pkg/devicetwin/dmiserver/event_type.go
  edge/pkg/devicetwin/dmiserver/server.go
  edge/pkg/devicetwin/dtmanager/communicate.go
  edge/pkg/devicetwin/dtmanager/membership.go
  edge/pkg/devicetwin/dtmanager/twin.go
Labels: kind/feature, lgtm, approved, size/M

#5668 Tool that supports automatically generating API documentation
  apidoc/generated/openapi/zz_generated.openapi.go
  apidoc/generated/swagger/swagger.json
  apidoc/tools/generate-openapi.sh
  apidoc/tools/generate-swagger.go
  apidoc/tools/lib/render.go
  apidoc/tools/lib/storage.go
  apidoc/tools/update-swagger-docs.sh
  pkg/apis/devices/v1alpha2/doc.go
  pkg/apis/devices/v1beta1/doc.go
  pkg/apis/operations/v1alpha1/doc.go
  pkg/apis/reliablesyncs/v1alpha1/doc.go
  pkg/apis/rules/v1/doc.go
Labels: lgtm, approved, size/XXL

#5547 Add a parent flag --log-level to the keadm and make it hidden for debug.
  keadm/cmd/keadm/app/keadm.go
Labels: kind/feature, lgtm, approved, size/S

#5675 Test coverage for `application.go`
  go.mod
  pkg/metaserver/application_test.go
Labels: kind/test, lgtm, approved, size/L
