Repository kubeedge/kubeedge, pull requests merged in 2024-08, with the labels that each got.

#5778 Added tests for pkgs in `kubernetes` module
  edge/pkg/metamanager/metaserver/kubernetes/scope/scope_test.go
  edge/pkg/metamanager/metaserver/kubernetes/serializer/serializer_test.go
Labels: kind/test, lgtm, approved, size/L

#5763 Tests for `storage/v1` module
  edge/pkg/edged/kubeclientbridge/typed/storage/v1/storage_client_bridge_test.go
  edge/pkg/edged/kubeclientbridge/typed/storage/v1/volumeattachment_bridge_test.go
Labels: kind/test, lgtm, approved, size/L

#5790 Cleanup the kube client tool
  cloud/pkg/common/client/client.go
Labels: kind/cleanup, lgtm, approved, size/S

#5793 typo fixes for github workflow stes names.
  .github/workflows/main.yaml
  .github/workflows/schedule.yml
Labels: kind/cleanup, lgtm, approved, size/S

#5795 Added tests for `cloud/pkg/csidriver` pkg
  cloud/pkg/csidriver/controllerserver_test.go
  cloud/pkg/csidriver/identityserver_test.go
  cloud/pkg/csidriver/uds_test.go
  cloud/pkg/csidriver/utils_test.go
Labels: kind/test, lgtm, approved, size/XL

#5789 Fixed the k8s client impersonation for the authroization
  cloud/pkg/common/client/impersonation.go
  cloud/pkg/common/client/impersonation_test.go
Labels: kind/bug, lgtm, approved, size/L

#5800 Change apt source to fix container runtime CI failures
  hack/local-up-kubeedge.sh
Labels: kind/failing-test, lgtm, approved, size/XS

#5804 Optimize the syncPod startup time for edge nodes.
  edge/pkg/edged/edged.go
Labels: kind/feature, lgtm, approved, size/M

#5806 add luomengY as reviewer
  hack/OWNERS
Labels: lgtm, approved, size/XS

#5808 update to output the information of help
  Makefile
Labels: lgtm, approved, size/S

#5817 Make the timestamps of kubeedge resources support international time
  cloud/pkg/taskmanager/imageprepullcontroller/image_prepull_task.go
  cloud/pkg/taskmanager/nodeupgradecontroller/upgrade_task.go
  cloud/pkg/taskmanager/util/util.go
  common/constants/default.go
  edge/pkg/devicetwin/dtmanager/device.go
  keadm/cmd/keadm/app/cmd/util/common.go
  staging/src/github.com/kubeedge/api/apis/common/constants/default.go
Labels: kind/bug, lgtm, approved, size/S

#5813 Tests for `cloud/pkg/admissioncontroller` package
  cloud/pkg/admissioncontroller/admit_device_test.go
  cloud/pkg/admissioncontroller/admit_devicemodel_test.go
  cloud/pkg/admissioncontroller/admit_nodeupgradejob_test.go
  cloud/pkg/admissioncontroller/common_test.go
Labels: kind/test, lgtm, approved, size/XL

#5821 Automated cherry pick of #5817: Make kubeedge time international
  cloud/pkg/taskmanager/imageprepullcontroller/image_prepull_task.go
  cloud/pkg/taskmanager/nodeupgradecontroller/upgrade_task.go
  cloud/pkg/taskmanager/util/util.go
  edge/pkg/devicetwin/dtmanager/device.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: lgtm, approved, size/S

#5819 Automated cherry pick of #5817: Make kubeedge time international
  cloud/pkg/taskmanager/imageprepullcontroller/image_prepull_task.go
  cloud/pkg/taskmanager/nodeupgradecontroller/upgrade_task.go
  cloud/pkg/taskmanager/util/util.go
  edge/pkg/devicetwin/dtmanager/device.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: lgtm, approved, size/S

#5820 Automated cherry pick of #5817: Make kubeedge time international
  cloud/pkg/taskmanager/imageprepullcontroller/image_prepull_task.go
  cloud/pkg/taskmanager/nodeupgradecontroller/upgrade_task.go
  cloud/pkg/taskmanager/util/util.go
  edge/pkg/devicetwin/dtmanager/device.go
  keadm/cmd/keadm/app/cmd/util/common.go
Labels: lgtm, approved, size/S

#5814 misspell in `schedule.yml`
  .github/workflows/schedule.yml
Labels: kind/cleanup, lgtm, approved, size/XS

#5810 Added tests for `overridemanager` package
  cloud/pkg/controllermanager/edgeapplication/overridemanager/envoverrider_test.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/helper_test.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/imageoverrider_test.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/overridemanager_test.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/replicasoverrider_test.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/resourcesoverrider_test.go
Labels: kind/test, lgtm, approved, size/XXL

#5803 Test coverage for `cloud/pkg/dynamiccontroller` module
  cloud/pkg/dynamiccontroller/application/listener_manager_test.go
  cloud/pkg/dynamiccontroller/application/selector_test.go
  cloud/pkg/dynamiccontroller/filter/defaultmaster/defaultmaster_test.go
  cloud/pkg/dynamiccontroller/filter/endpointresource/endpointresource_test.go
Labels: kind/test, lgtm, approved, size/XL

#5812 `Typed` tests
  edge/pkg/edged/kubeclientbridge/clientset_bridge_test.go
Labels: kind/test, lgtm, approved, size/M

#5829 Sanil affiliation update
  MAINTAINERS.md
Labels: lgtm, approved, size/XS

#5818 feat:upgraded runc version
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/paths.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/validator.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/setns_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/rlimit_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/rlimit_linux_go122.go
  vendor/github.com/opencontainers/runc/libcontainer/system/rlimit_stub.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps.c
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, size/XL, sig/security

#5809 UTs for `commmandoverrider.go`
  cloud/pkg/controllermanager/edgeapplication/overridemanager/commandoverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/commandoverrider_test.go
Labels: kind/test, lgtm, approved, size/XL

#5807 update k8s version in conformance test
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S

#5825 add readme file in apidoc and api
  apidoc/README.md
  pkg/README.md
  staging/src/github.com/kubeedge/api/README.md
Labels: kind/documentation, lgtm, approved, size/S
