Repository kubeedge/kubeedge, pull requests merged in 2024-09, with the labels that each got.

#5780 Test coverage for `edge/pkg/metamanager/client` module - `lease` and `node` files
  edge/pkg/metamanager/client/lease_test.go
  edge/pkg/metamanager/client/node_test.go
Labels: kind/test, lgtm, approved, size/L

#5835 Fix and optimize keadm compatibility test
  .github/workflows/keadm_compatibility.yaml
  .github/workflows/schedule.yml
  tests/scripts/keadm_compatibility_e2e.sh
Labels: lgtm, approved, size/L

#5751 UT coverage for the `cloud/pkg/taskmanager/util` module
  cloud/pkg/taskmanager/util/controller/controller_test.go
  cloud/pkg/taskmanager/util/manager/task_cache_test.go
  cloud/pkg/taskmanager/util/util_test.go
Labels: kind/test, lgtm, approved, size/XL

#5837 Moving from standard lib to `stretchr/testify` for UT
  cloud/pkg/router/messagelayer/util_test.go
  edge/pkg/devicetwin/devicetwin_test.go
  edge/pkg/devicetwin/dttype/types_helper_test.go
  pkg/image/image_test.go
  pkg/metaserver/key_test.go
  pkg/util/pass-through/pass_through_test.go
  pkg/util/util_test.go
  pkg/util/validation/validation_test.go
Labels: kind/feature, lgtm, approved, size/L

#5832 add skip cr install option for local-up-kubeedge.sh
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/S

#5840 fix keadm lack of flag remote-runtime-endpoint
  keadm/cmd/keadm/app/cmd/edge/reset_others.go
  keadm/cmd/keadm/app/cmd/reset_others.go
Labels: kind/bug, lgtm, approved, size/XS

#5842 fix container runtime select error
  keadm/cmd/keadm/app/cmd/reset_others.go
Labels: kind/bug, lgtm, approved, size/S

#5844 Remove some unused constants in api and commons
  common/constants/default.go
  staging/src/github.com/kubeedge/api/apis/common/constants/default.go
Labels: kind/cleanup, lgtm, approved, size/L

#5848 Automated cherry pick of #5840: fix keadm lack of flag remote-runtime-endpoint
  keadm/cmd/keadm/app/cmd/edge/reset_others.go
  keadm/cmd/keadm/app/cmd/reset_others.go
Labels: lgtm, approved, size/XS

#5849 Automated cherry pick of #5840: fix keadm lack of flag remote-runtime-endpoint
  keadm/cmd/keadm/app/cmd/edge/reset_others.go
  keadm/cmd/keadm/app/cmd/reset_others.go
Labels: lgtm, approved, size/XS

#5856 Upgrade github actions to v4
  .github/workflows/build-tools.yml
  .github/workflows/cifuzz.yml
  .github/workflows/fossa.yml
  .github/workflows/main-doc.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yml
  .github/workflows/schedule.yml
Labels: lgtm, approved, size/L

#5831 Add Kubernetes compatibility doc for v1.18
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/S

#5757 Test coverage for `edge/pkg/metamanager/client` module - `CSR` and `CM` files
  edge/pkg/metamanager/client/ceritificatesigningrequest_test.go
  edge/pkg/metamanager/client/configmap_test.go
Labels: kind/test, lgtm, approved, size/XL

#5859 update default kubeedge version in keadm
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/helm/cloudcore.go
Labels: kind/bug, lgtm, approved, size/XS

#5783 Add nodeconformance test
  .github/workflows/main.yaml
  Makefile
  build/conformance/node-e2e-runner/run.go
  tests/scripts/conformance_e2e.sh
Labels: kind/feature, lgtm, approved, size/M

#5855 Fix PersistentVolume data deleted at edge abnormally
  edge/pkg/edged/kubeclientbridge/typed/core/v1/persistentvolume_bridge.go
  edge/pkg/edged/kubeclientbridge/typed/storage/v1/volumeattachment_bridge_test.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/persistentvolume.go
Labels: kind/bug, lgtm, approved, size/M

#5866 Test coverage for `edge/pkg/metamanager/client` module - `lease`, `node` files
  edge/pkg/metamanager/client/lease_test.go
  edge/pkg/metamanager/client/node_test.go
Labels: kind/test, lgtm, approved, size/L

#5877 Automated cherry pick of #5800: Change apt source to fix container runtime CI failures
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS

#5871 Automated cherry pick of #5856: upgrade github actions to v4
  .github/workflows/build-tools.yml
  .github/workflows/cifuzz.yml
  .github/workflows/fossa.yml
  .github/workflows/main-doc.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yml
  .github/workflows/schedule.yml
Labels: lgtm, approved, size/M

#5869 Automated cherry pick of #5856: upgrade github actions to v4
  .github/workflows/build-tools.yml
  .github/workflows/cifuzz.yml
  .github/workflows/fossa.yml
  .github/workflows/main-doc.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yml
  .github/workflows/schedule.yml
Labels: lgtm, approved, size/L

#5868 Automated cherry pick of #5856: upgrade github actions to v4
  .github/workflows/build-tools.yml
  .github/workflows/cifuzz.yml
  .github/workflows/fossa.yml
  .github/workflows/main-doc.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yml
  .github/workflows/schedule.yml
Labels: lgtm, approved, size/L

#5873 chore: remove duplicate error check code
  edge/pkg/metamanager/metaserver/handlerfactory/ext_handler.go
Labels: lgtm, approved, size/XS

#5878 Specify the version for isulad.
  hack/lib/install.sh
Labels: kind/failing-test, lgtm, approved, size/XS

#5884 Automated cherry pick of #5878: Specify the version for isulad. #5800: changing apt source after multiple failures
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/S

#5880 Automated cherry pick of #5878: Specify the version for isulad.
  hack/lib/install.sh
Labels: lgtm, approved, size/XS

#5883 Automated cherry pick of #5878: Specify the version for isulad. #5443: Add a retry mechanism to the container runtime e2e test #5800: changing apt source after multiple failures
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/M

#5860 Change deviceName to deviceID in mapper data panel
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/mysql/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/redis/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/tdengine/client.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/global/global.go
Labels: kind/bug, lgtm, approved, size/M

#5888 Automated cherry pick of #5855: fix pvc deleted abnormally
  edge/pkg/edged/kubeclientbridge/typed/core/v1/persistentvolume_bridge.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/persistentvolume.go
Labels: lgtm, approved, size/S

#5887 Automated cherry pick of #5855: fix pvc deleted abnormally
  edge/pkg/edged/kubeclientbridge/typed/core/v1/persistentvolume_bridge.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/persistentvolume.go
Labels: lgtm, approved, size/S

#5886 Automated cherry pick of #5855: fix pvc deleted abnormally
  edge/pkg/edged/kubeclientbridge/typed/core/v1/persistentvolume_bridge.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/persistentvolume.go
Labels: lgtm, approved, size/S

#5867 Automated cherry pick of #5855: fix pvc deleted abnormally
  edge/pkg/edged/kubeclientbridge/typed/core/v1/persistentvolume_bridge.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/client/persistentvolume.go
Labels: lgtm, approved, size/S

#5891 Add v1.18.1, v1.17.3, v1.16.4 and v1.15.4 patch release changelog
  CHANGELOG/CHANGELOG-1.15.md
  CHANGELOG/CHANGELOG-1.16.md
  CHANGELOG/CHANGELOG-1.17.md
  CHANGELOG/CHANGELOG-1.18.md
Labels: kind/documentation, lgtm, approved, size/M

#5895 fix: fix slice init issue
  cloud/pkg/cloudstream/iptables/iptables.go
  keadm/cmd/keadm/app/cmd/helm/installer.go
Labels: kind/bug, lgtm, approved, size/XS
