Repository kubeedge/kubeedge, pull requests merged in 2024-03, with the labels that each got.

#5443 Add a retry mechanism to the container runtime e2e test
  hack/lib/install.sh
  hack/local-up-kubeedge.sh
Labels: kind/feature, lgtm, approved, size/M

#5392 fixed an issue where env support for edgeapplication was not comprehe…
  cloud/pkg/controllermanager/edgeapplication/overridemanager/envoverrider.go
Labels: kind/bug, lgtm, approved, size/M

#5455 Automated cherry pick of #5392: fixed an issue where env support for edgeapplication was not
  cloud/pkg/controllermanager/edgeapplication/overridemanager/envoverrider.go
Labels: lgtm, approved, size/M

#5424 fix some character error
  build/crds/apps/apps_v1alpha1_edgeapplication.yaml
  cloud/pkg/controllermanager/edgeapplication/overridemanager/envoverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/resourcesoverrider.go
  manifests/charts/cloudcore/crds/apps_v1alpha1_edgeapplication.yaml
  pkg/apis/apps/v1alpha1/edgeapplication_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
Labels: kind/bug, lgtm, approved, size/M

#5409 normalize the hostname in fucntion GetHostname
  go.mod
  pkg/util/util.go
Labels: kind/bug, lgtm, approved, size/XS

#5352 Fix edgecore's metaserver panic due to nil initializers in request scope.
  .golangci.yml
  edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go
Labels: kind/bug, lgtm, approved, size/M

#5460 Automated cherry pick of #5424: fix some character error
  build/crds/apps/apps_v1alpha1_edgeapplication.yaml
  cloud/pkg/controllermanager/edgeapplication/overridemanager/envoverrider.go
  cloud/pkg/controllermanager/edgeapplication/overridemanager/resourcesoverrider.go
  manifests/charts/cloudcore/crds/apps_v1alpha1_edgeapplication.yaml
  pkg/apis/apps/v1alpha1/edgeapplication_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, size/M

#5477 add list/watch abac resources clusterrole for requireAuthorization feature
  manifests/charts/cloudcore/templates/aggregation_rbac_cloudcore.yaml
  manifests/charts/cloudcore/templates/configmap_cloudcore.yaml
  manifests/charts/cloudcore/templates/rbac_cloudcore.yaml
  manifests/charts/cloudcore/templates/rbac_cloudcore_feature.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: kind/bug, lgtm, approved, size/M

#5479 Merge pull request #5352 from Windrow14/bugfix/metaserver_panic_when_…
  .golangci.yml
  edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go
Labels: lgtm, approved, size/M

#5485 update controller-runtime setup-envtest version to handle the CI failure
  cloud/test/integration/scripts/execute.sh
Labels: kind/failing-test, lgtm, approved, size/XS

#5387 Fix keadm upgrade command
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/upgrade.go
Labels: kind/bug, lgtm, approved, size/S

#5484 fix retrytimes in imageprepulljob
  build/crd-samples/operations/imageprepulljob.yaml
  edge/pkg/edgehub/task/taskexecutor/image_prepull.go
Labels: kind/bug, lgtm, approved, size/XS

#5487 Automated cherry pick of #5485: update setup-envtest version
  cloud/test/integration/scripts/execute.sh
Labels: lgtm, approved, size/XS

#5488 Automated cherry pick of #5485: update setup-envtest version
  cloud/test/integration/scripts/execute.sh
Labels: lgtm, approved, size/XS

#5491 Automated cherry pick of #5484: fix retrytimes in imageprepulljob
  build/crd-samples/operations/imageprepulljob.yaml
  edge/pkg/edgehub/task/taskexecutor/image_prepull.go
Labels: lgtm, approved, size/XS

#5492 Automated cherry pick of #5387: Fix keadm upgrade command
  keadm/cmd/keadm/app/cmd/edge/upgrade.go
  keadm/cmd/keadm/app/cmd/upgrade.go
Labels: lgtm, approved, size/S

#5493 upgrade slsa-framework version to v1.10.0
  .github/workflows/release.yml
Labels: kind/bug, lgtm, approved, size/XS

#5494 Automated cherry pick of #5493: upgrade slsa-framework version to v1.10.0
  .github/workflows/release.yml
Labels: lgtm, approved, size/XS

#5495 update CHANGELOG for v1.16.1
  CHANGELOG/CHANGELOG-1.16.md
Labels: kind/documentation, lgtm, approved, size/S
