Repository kubeedge/kubeedge, pull requests merged in 2024-02, with the labels that each got.

#5274 edge node task proposal
  docs/images/edge-node-tasks/node-task-timing-diagram.png
  docs/images/edge-node-tasks/node-tasks-several-controllers.png
  docs/proposals/edge-node-tasks-design.md
Labels: kind/feature, lgtm, approved, size/L

#5310 add images prepull proposal
  docs/images/proposals/image-prepull.png
  docs/proposals/image-prepull.md
Labels: kind/design, lgtm, approved, size/L

#5413 Remove some unused constants in devicecontroller
  cloud/pkg/devicecontroller/constants/device.go
Labels: kind/cleanup, lgtm, approved, size/XS

#5216 remove unused shell in edge/hack
  edge/hack/clean.sh
  edge/hack/install_docker_for_raspbian.sh
  edge/hack/update-gofmt.sh
Labels: kind/cleanup, lgtm, approved, size/M

#5423 remove unused structure in mapper-framework
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/configmaptype.go
Labels: kind/cleanup, lgtm, approved, size/S
