Repository kubeedge/kubeedge, pull requests merged in 2024-04, with the labels that each got.

#5480 servicebus constant optimization
  cloud/pkg/router/provider/servicebus/servicebus.go
Labels: kind/cleanup, lgtm, approved, size/XS

#5530 fix upload codecov failed: update codecov to v4
  .github/workflows/main.yaml
Labels: lgtm, approved, size/XS

#5528 fix: remove short flag in install.sh
  hack/lib/install.sh
Labels: kind/bug, lgtm, approved, size/XS

#5522 update mapper doc
  staging/src/github.com/kubeedge/mapper-framework/README.md
Labels: lgtm, approved

#5519 fix device mapper generate script error
  staging/src/github.com/kubeedge/mapper-framework/hack/make-rules/generate.sh
Labels: kind/bug, lgtm, approved, size/S

#5506 fix device status problem with device's namespace in kubeege v1.16.0
  cloud/pkg/common/messagelayer/util.go
  cloud/pkg/common/messagelayer/util_test.go
  edge/pkg/devicetwin/process.go
  edge/pkg/devicetwin/process_test.go
  edge/pkg/eventbus/mqtt/client.go
  edge/test/integration/utils/helpers/helpers.go
Labels: kind/bug, lgtm, approved, size/M

#5462 Change the print helm chart resources YAML command name keadm generate to keadm manifest.
  keadm/cmd/keadm/app/cmd/cloud/manifest.go
Labels: kind/feature, lgtm, approved, size/M

#5467 Fix the status reporting of device to avoid issues defined by twin.
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
Labels: kind/bug, lgtm, approved, size/M

#5537 Automated cherry pick of #5506: fix device status problem with device's namespace in kubeege v1.16.0
  cloud/pkg/common/messagelayer/util.go
  cloud/pkg/common/messagelayer/util_test.go
  edge/pkg/devicetwin/process.go
  edge/pkg/devicetwin/process_test.go
  edge/pkg/eventbus/mqtt/client.go
  edge/test/integration/utils/helpers/helpers.go
Labels: lgtm, approved, size/M

#5490 fix the error "failed to create serviceaccount access" when metaserver switches to HTTPS.
  manifests/charts/cloudcore/templates/rbac_cloudcore_feature.yaml
Labels: kind/bug, lgtm, approved, size/XS

#5539 Automated cherry pick of #5519: fix device mapper generate script error
  staging/src/github.com/kubeedge/mapper-framework/hack/make-rules/generate.sh
Labels: lgtm, approved, size/S

#5533 fix:fix-validate imageprepull crdexample,now it is use nodeNames not …
  build/crd-samples/operations/imageprepulljob.yaml
Labels: kind/bug, lgtm, approved, size/XS

#5548 Automated cherry pick of #5530: update codecov to v4
  .github/workflows/main.yaml
Labels: lgtm, approved, size/XS

#5550 Automated cherry pick of #5530: update codecov to v4
  .github/workflows/main.yaml
Labels: lgtm, approved, size/XS

#5551 Automated cherry pick of #5530: update codecov to v4
  .github/workflows/main.yaml
Labels: lgtm, approved, size/XS

#5541 Support edge pods using inclusterconfig to access Kube-APIServer
  cloud/cmd/cloudcore/app/server.go
  cloud/pkg/cloudhub/dispatcher/message_dispatcher.go
  cloud/pkg/common/client/client.go
  cloud/pkg/csrapprovercontroller/csrapprover.go
  cloud/pkg/edgecontroller/controller/upstream.go
  common/constants/default.go
  edge/pkg/edgehub/edgehub.go
  edge/pkg/edgehub/edgehub_test.go
  edge/pkg/metamanager/client/ceritificatesigningrequest.go
  edge/pkg/metamanager/client/metaclient.go
  edge/pkg/metamanager/metaserver/certificate/certificates/v1/certificates_client.go
  edge/pkg/metamanager/metaserver/certificate/certificates/v1/certificatesigningrequest.go
  edge/pkg/metamanager/metaserver/certificate/clientset_bridge.go
  edge/pkg/metamanager/metaserver/certificate/manager.go
  edge/pkg/metamanager/metaserver/server.go
  edge/pkg/metamanager/process.go
  go.mod
  manifests/charts/cloudcore/templates/rbac_cloudcore_feature.yaml
  pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  pkg/apis/componentconfig/edgecore/v1alpha2/default.go
  pkg/apis/componentconfig/edgecore/v1alpha2/types.go
  pkg/util/dummy_device.go
  staging/src/github.com/kubeedge/beehive/pkg/core/model/message.go
  vendor/k8s.io/client-go/util/certificate/OWNERS
  vendor/k8s.io/client-go/util/certificate/certificate_manager.go
  vendor/k8s.io/client-go/util/certificate/certificate_store.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, size/XXL

#5538 Automated cherry pick of #5519: fix device mapper generate script error
  staging/src/github.com/kubeedge/mapper-framework/hack/make-rules/generate.sh
Labels: lgtm, approved, size/S

#5461 Refactor the implementation code for the cloud init command
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/helm/cloudcore.go
  tests/scripts/keadm_compatibility_e2e.sh
  tests/scripts/keadm_e2e.sh
Labels: kind/feature, lgtm, approved, size/M

#5376 Add mysql to mapper-framework for enhancing pushmethod db.
  build/crds/devices/devices_v1beta1_device.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  pkg/apis/devices/v1beta1/device_instance_types.go
  pkg/apis/devices/v1beta1/zz_generated.deepcopy.go
  pkg/apis/dmi/v1beta1/api.pb.go
  pkg/apis/dmi/v1beta1/api.proto
  pkg/apis/dmi/v1beta1/api_grpc.pb.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/mysql/client.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/mysql/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
  staging/src/github.com/kubeedge/mapper-framework/go.mod
  staging/src/github.com/kubeedge/mapper-framework/go.sum
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/configmaptype.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/datamodel.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/dmi-api/api.pb.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/dmi-api/api.proto
  staging/src/github.com/kubeedge/mapper-framework/pkg/dmi-api/api_grpc.pb.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/httpserver/callback.go
  staging/src/github.com/kubeedge/mapper-framework/pkg/util/parse/grpc.go
Labels: kind/feature, lgtm, approved, size/XXL

#5540 Add the image-repository address of the container in keadm init/upgrade.
  keadm/cmd/keadm/app/cmd/cloud/init.go
  keadm/cmd/keadm/app/cmd/cloud/upgrade.go
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/helm/cloudcore.go
Labels: kind/feature, lgtm, approved, size/S

#5545 Automated cherry pick of #5467: Fix the status reporting of device to avoid issues defined by twin.
  cloud/pkg/devicecontroller/controller/downstream.go
  cloud/pkg/devicecontroller/controller/upstream.go
Labels: lgtm, approved, size/M

#5463 Refactor the command reset to third-level commands, like: keamd reset
  keadm/cmd/keadm/app/cmd/cloud/reset.go
  keadm/cmd/keadm/app/cmd/edge/reset_other.go
  keadm/cmd/keadm/app/cmd/reset_others.go
  keadm/cmd/keadm/app/cmd/util/common_others.go
  keadm/cmd/keadm/app/cmd/util/reset.go
Labels: kind/feature, lgtm, approved, size/L

#5513 support module restarting feature
  edge/cmd/edgecore/app/server.go
  edge/pkg/edged/edged.go
  edge/pkg/metamanager/process.go
  pkg/features/features.go
  staging/src/github.com/kubeedge/beehive/pkg/core/core.go
  staging/src/github.com/kubeedge/beehive/pkg/core/module.go
Labels: lgtm, approved, size/L

#5504 When the edge node goes offline, add pod restart and status query functions for the edge node
  LICENSES/vendor/github.com/fvbommel/sortorder/LICENSE
  go.mod
  go.sum
  keadm/cmd/keadm/app/cmd/cmd_others.go
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/ctl/ctl.go
  keadm/cmd/keadm/app/cmd/ctl/get/get.go
  keadm/cmd/keadm/app/cmd/ctl/get/pod.go
  keadm/cmd/keadm/app/cmd/ctl/restart/pod.go
  keadm/cmd/keadm/app/cmd/ctl/restart/restart.go
  keadm/cmd/keadm/app/cmd/ctl/restful/pod.go
  keadm/cmd/keadm/app/cmd/ctl/restful/request.go
  keadm/cmd/keadm/app/cmd/ctl/util/pod.go
  vendor/github.com/fvbommel/sortorder/.gitignore
  vendor/github.com/fvbommel/sortorder/LICENSE
  vendor/github.com/fvbommel/sortorder/README.md
  vendor/github.com/fvbommel/sortorder/doc.go
  vendor/github.com/fvbommel/sortorder/natsort.go
  vendor/k8s.io/kubectl/pkg/cmd/get/customcolumn.go
  vendor/k8s.io/kubectl/pkg/cmd/get/customcolumn_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/get/get.go
  vendor/k8s.io/kubectl/pkg/cmd/get/get_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/get/humanreadable_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/get/skip_printer.go
  vendor/k8s.io/kubectl/pkg/cmd/get/sorter.go
  vendor/k8s.io/kubectl/pkg/cmd/get/table_printer.go
  vendor/k8s.io/kubectl/pkg/rawhttp/raw.go
  vendor/k8s.io/kubectl/pkg/util/slice/slice.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, size/XXL

#5514 Mapper supports video streaming data reporting
  build/crds/devices/devices_v1beta1_device.yaml
  build/crds/devices/devices_v1beta1_devicemodel.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_device.yaml
  manifests/charts/cloudcore/crds/devices_v1beta1_devicemodel.yaml
  pkg/apis/devices/v1beta1/device_instance_types.go
  pkg/apis/devices/v1beta1/device_model_types.go
  staging/src/github.com/kubeedge/mapper-framework/README.md
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/Dockerfile_nostream
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/Dockerfile_stream
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/stream/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/stream/handler_nostream.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/stream/img.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/stream/video.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/device.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
  staging/src/github.com/kubeedge/mapper-framework/hack/make-rules/generate.sh
  staging/src/github.com/kubeedge/mapper-framework/pkg/common/const.go
Labels: kind/feature, lgtm, approved, size/XL

#5558 update CHANGELOG for v1.16.2
  CHANGELOG/CHANGELOG-1.16.md
Labels: kind/documentation, lgtm, approved, size/S

#5555 Update the roadmap to 2024
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/XS

#5509 add proposal of module restarting
  docs/images/proposals/module-restarting.png
  docs/proposals/module-restarting.md
Labels: lgtm, approved, size/M

#5568 Automated cherry pick of #5493: upgrade slsa-framework version to v1.10.0
  .github/workflows/release.yml
Labels: lgtm, approved, size/XS

#5575 Fixed failure to run unit-tests on non-Linux
  edge/pkg/metamanager/metaserver/server.go
  edge/pkg/metamanager/metaserver/server_linux.go
  edge/pkg/metamanager/metaserver/server_other.go
  pkg/util/dummy_device_linux.go
Labels: kind/bug, lgtm, approved, size/M

#5448 Add proposal of mapper supporting stream data
  docs/images/mapper/streamData.png
  docs/proposals/mapper-support-video-streaming-data.md
Labels: kind/design, lgtm, approved, size/L

#5576 Automated cherry pick of #5575: Fixed failure to run unit-tests on non Linux
  edge/pkg/metamanager/metaserver/server.go
  edge/pkg/metamanager/metaserver/server_linux.go
  edge/pkg/metamanager/metaserver/server_other.go
  pkg/util/dummy_device_linux.go
Labels: lgtm, approved, size/M

#5578 fix compile failed for some unimplemented function in windows
  keadm/cmd/keadm/app/cmd/edge/reset_others.go
  keadm/cmd/keadm/app/cmd/util/common_windows.go
Labels: kind/bug, lgtm, approved, size/XS

#5579 Automated cherry pick of #5578: fix compile failed in windows
  keadm/cmd/keadm/app/cmd/edge/reset_others.go
  keadm/cmd/keadm/app/cmd/util/common_windows.go
Labels: lgtm, approved, size/XS

#5580 Add release 1.17 changelog
  CHANGELOG/CHANGELOG-1.17.md
Labels: kind/documentation, lgtm, approved, size/M
