Repository kubeedge/kubeedge, pull requests merged in 2025-06, with the labels that each got.

#6285 [test]:improve coverage for edgedattachconnection in pkg/stream/
  pkg/stream/edgedattachconnection_test.go
Labels: kind/test, lgtm, approved, size/L

#6341 [release-1.20] Fixed unit tests failed due to hard-coded certificate expiration
  cloud/pkg/cloudhub/servers/httpserver/certificate/certs_test.go
Labels: kind/bug, lgtm, approved, size/M

#6259 feat: add DisableCSINode feature gate to skip CSI initialization
  edge/pkg/edged/edged.go
  pkg/features/features.go
Labels: lgtm, approved, size/S

#6343 Automated cherry pick of #6341: Fixed unit tests failed due to hard-coded certificate
  cloud/pkg/cloudhub/servers/httpserver/certificate/certs_test.go
Labels: lgtm, approved, size/M

#6342 Automated cherry pick of #6341: Fixed unit tests failed due to hard-coded certificate
  cloud/pkg/cloudhub/servers/httpserver/certificate/certs_test.go
Labels: lgtm, approved, size/M

#6351 test: fix TestGetLocalIP
  pkg/util/util_test.go
Labels: kind/test, lgtm, approved, size/S

#6352 fix nodetask handler register in taskmanager
  cloud/pkg/taskmanager/upstream/config_update.go
  edge/pkg/taskmanager/actions/runner.go
Labels: kind/bug, lgtm, approved, size/XS

#6355 Automated cherry pick of #6352: fix nodetask handler register in taskmanager
  cloud/pkg/taskmanager/upstream/config_update.go
  edge/pkg/taskmanager/actions/runner.go
Labels: lgtm, approved, size/XS

#6354 update manifest version for release 1.21
  README.md
  README_zh.md
  build/cloud/07-deployment.yaml
  keadm/cmd/keadm/app/cmd/common/constant.go
  manifests/charts/cloudcore/Chart.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: kind/documentation, lgtm, approved, size/M

#6357 Automated cherry pick of #6354: update manifest version for release 1.21
  README.md
  README_zh.md
  build/cloud/07-deployment.yaml
  keadm/cmd/keadm/app/cmd/common/constant.go
  manifests/charts/cloudcore/Chart.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/M

#6359 Add v1.21.0 release note
  CHANGELOG/CHANGELOG-1.21.md
Labels: kind/documentation, lgtm, approved, size/L

#6274 [test]:create test for debinstaller in keadm/app/cmd/util
  keadm/cmd/keadm/app/cmd/util/debinstaller_test.go
Labels: kind/test, lgtm, approved, size/L

#6282 [test]:create test for pacmaninstaller in keadm/app/cmd/util
  keadm/cmd/keadm/app/cmd/util/pacmaninstaller_test.go
Labels: kind/test, lgtm, approved, size/L

#6372 Automated cherry pick of #6367 upstream release 1.21 : fix docker e2e test
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS

#6374 Automated cherry pick of #6367 upstream release 1.19: fix docker e2e test
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS

#6383 Automated cherry pick of #6039: debug isulad
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS

#6384 Automated cherry pick of #6039: debug isulad
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS

#6385 Automated cherry pick of #6039: debug isulad
  hack/local-up-kubeedge.sh
Labels: lgtm, approved, size/XS
