Repository kubeedge/kubeedge, pull requests merged in 2025-01, with the labels that each got.

#6063 fix: multiple --set parameters in keadm join command
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
Labels: lgtm, approved, size/S

#6028 Fix iptablesmanager cannot update iptables when delete cloudcore
  build/iptablesmanager/iptablesmanager-ds.yaml
  cloud/pkg/cloudstream/iptables/iptables.go
  manifests/charts/cloudcore/README.md
  manifests/charts/cloudcore/templates/rbac_iptablesmanager.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: kind/bug, lgtm, approved, size/L

#6058 Automated cherry pick of #6038: fix clusterobjectsync can't be deleted
  cloud/pkg/synccontroller/synccontroller.go
Labels: lgtm, approved, size/M

#6059 Automated cherry pick of #6038: fix clusterobjectsync can't be deleted
  cloud/pkg/synccontroller/synccontroller.go
Labels: lgtm, approved, size/M

#6060 Automated cherry pick of #6038: fix clusterobjectsync can't be deleted
  cloud/pkg/synccontroller/synccontroller.go
Labels: lgtm, approved, size/M

#6061 Automated cherry pick of #6038: fix clusterobjectsync can't be deleted
  cloud/pkg/synccontroller/synccontroller.go
Labels: lgtm, approved, size/M

#6054 Fixed recreate secret when etcd error
  cloud/pkg/cloudhub/servers/httpserver/pre_server.go
Labels: kind/bug, lgtm, approved, size/XS

#6065 Automated cherry pick of #6063: fix: multiple --set parameters in keadm join command
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
Labels: lgtm, approved, size/S

#6064 Automated cherry pick of #6063: fix: multiple --set parameters in keadm join command
  keadm/cmd/keadm/app/cmd/common/types.go
  keadm/cmd/keadm/app/cmd/edge/join_others.go
  keadm/cmd/keadm/app/cmd/edge/join_windows.go
Labels: lgtm, approved, size/S

#6062 Make iptablesmanager platform-specific
  cloud/pkg/cloudstream/iptables/iptables.go
  cloud/pkg/cloudstream/iptables/iptables_other.go
Labels: kind/feature, lgtm, approved, size/M

#5799 Get the ConfigMap and Secret from the edge node
  edge/pkg/metamanager/client/configmap.go
  edge/pkg/metamanager/client/configmap_test.go
  edge/pkg/metamanager/client/secret.go
  edge/pkg/metamanager/client/secret_test.go
Labels: kind/feature, lgtm, approved, size/L

#6071 Automated cherry pick of #6028: update configmap when delete cloudcore
  build/iptablesmanager/iptablesmanager-ds.yaml
  cloud/pkg/cloudstream/iptables/iptables.go
  manifests/charts/cloudcore/README.md
  manifests/charts/cloudcore/templates/rbac_iptablesmanager.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/L

#6069 Automated cherry pick of #6054: Fixed recreate secret when etcd error
  cloud/pkg/cloudhub/servers/httpserver/server.go
Labels: lgtm, approved, size/XS

#6067 Automated cherry pick of #6054: Fixed recreate secret when etcd error
  cloud/pkg/cloudhub/servers/httpserver/pre_server.go
Labels: lgtm, approved, size/XS

#6073 Automated cherry pick of #6028: update configmap when delete cloudcore
  build/iptablesmanager/iptablesmanager-ds.yaml
  cloud/pkg/cloudstream/iptables/iptables.go
  manifests/charts/cloudcore/README.md
  manifests/charts/cloudcore/templates/rbac_iptablesmanager.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/L

#6070 Automated cherry pick of #6028: update configmap when delete cloudcore
  build/iptablesmanager/iptablesmanager-ds.yaml
  cloud/pkg/cloudstream/iptables/iptables.go
  manifests/charts/cloudcore/README.md
  manifests/charts/cloudcore/templates/rbac_iptablesmanager.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/L

#6072 Automated cherry pick of #6028: update configmap when delete cloudcore
  build/iptablesmanager/iptablesmanager-ds.yaml
  cloud/pkg/cloudstream/iptables/iptables.go
  manifests/charts/cloudcore/README.md
  manifests/charts/cloudcore/templates/rbac_iptablesmanager.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/L

#6074 Correct community meeting information.
  README.md
  README_zh.md
Labels: kind/documentation, lgtm, approved, size/S

#6085 change `edged.rootDirectory` default to `/var/lib/kubelet`
  staging/src/github.com/kubeedge/api/apis/common/constants/default_others.go
  staging/src/github.com/kubeedge/api/apis/common/constants/default_windows.go
  staging/src/github.com/kubeedge/api/apis/componentconfig/edgecore/v1alpha2/types.go
Labels: kind/feature, lgtm, approved, size/XS

#6086 Add v1.19.2, v1.18.3, v1.17.5, v1.16.6 patch release changelog
  CHANGELOG/CHANGELOG-1.16.md
  CHANGELOG/CHANGELOG-1.17.md
  CHANGELOG/CHANGELOG-1.18.md
  CHANGELOG/CHANGELOG-1.19.md
Labels: kind/documentation, lgtm, approved, size/M

#6090 Fix mapper lint error
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/influxdb2/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
Labels: kind/bug, lgtm, approved, size/S

#6099 Automated cherry pick of #6090: fix mapper lint error
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/data/dbmethod/influxdb2/handler.go
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.mod
  staging/src/github.com/kubeedge/mapper-framework/_template/mapper/go.sum
Labels: lgtm, approved, size/S

#6018 fix `keadm ctl get pod -oyaml` and `keadm ctl get device -oyaml` error: "missing apiVersion or kind" issue.
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/ctl/client/device.go
  keadm/cmd/keadm/app/cmd/ctl/client/pod.go
  keadm/cmd/keadm/app/cmd/ctl/common/print.go
  keadm/cmd/keadm/app/cmd/ctl/get/device.go
  keadm/cmd/keadm/app/cmd/ctl/get/pod.go
Labels: kind/bug, lgtm, approved, size/L

#6100 Automated cherry pick of #6018: fix `keadm ctl get pod -oyaml` and `keadm ctl get device -oyaml` error: "missing apiVersion or kind" issue.
  keadm/cmd/keadm/app/cmd/common/constant.go
  keadm/cmd/keadm/app/cmd/ctl/client/device.go
  keadm/cmd/keadm/app/cmd/ctl/client/pod.go
  keadm/cmd/keadm/app/cmd/ctl/common/print.go
  keadm/cmd/keadm/app/cmd/ctl/get/device.go
  keadm/cmd/keadm/app/cmd/ctl/get/pod.go
Labels: lgtm, approved, size/L

#6093 update default version and compatibility for v1.20.0
  README.md
  README_zh.md
  build/cloud/07-deployment.yaml
  keadm/cmd/keadm/app/cmd/common/constant.go
  manifests/charts/cloudcore/Chart.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: kind/documentation, lgtm, approved, size/M

#6104 Automated cherry pick of #6093: update version for v1.20.0
  README.md
  README_zh.md
  build/cloud/07-deployment.yaml
  keadm/cmd/keadm/app/cmd/common/constant.go
  manifests/charts/cloudcore/Chart.yaml
  manifests/charts/cloudcore/values.yaml
  manifests/profiles/version.yaml
Labels: lgtm, approved, size/M

#6103 Add v1.20 release note
  CHANGELOG/CHANGELOG-1.20.md
Labels: kind/documentation, lgtm, approved, size/M

#6098 Go build using vendors
  hack/make-rules/build.sh
  hack/make-rules/crossbuild.sh
  hack/make-rules/smallbuild.sh
Labels: kind/bug, lgtm, approved, size/XS
